### ISSUE TITLE
Two times 'color' in galaxy wrapper hicPlotTADs.xml

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#100]
In line 57 the color of the track and in line 61 the border color is set. Both times this is done with 'color'. I am wondering if the case could occur that one is overriding the value of the other. If both are set the output file will have two times 'color' in consecutive lines. This behavior can be seen e.g. in the test cases which are failing right now caused by the new pandas version: https://travis-ci.org/maxplanck-ie/HiCExplorer/builds/237228087?utm_source=github_status&utm_medium=notification line 1645 or 1666.

**Comment by bgruening** [comment]
```
#if $track.color and $track.track_input.ext != "h5":
color = $track.color
#end if

#if $track.border_color:
color = $track.border_color
#end if
```
@fidelram is this wrong? Can we rename the cone color to border_color?

**Comment by fidelram** [comment]
I don't understand why there are so many `color` parameters in the file. Is this file generated automatically? The `border_color` only applies to `file_type = bed`

The first section should not have a `color` entry and the file_type must be `hic_matrix` (lines 1618-1627):

``` 
[hic_section_0]
file = /tmp/tmpELcMBp/files/000/dataset_19.dat
title = Kc DpnII (Li et al. 2015)
colormap = RdYlBu_r
depth = 200000
width = 1.5
transform = log1p
boundaries_file = /tmp/tmpELcMBp/files/000/dataset_25.dat
file_type = hic_matrix
```

For the `file_type=bed` sections, the `depth` parameter is not required and the `color` and `border_color` parameters can be set.

The list of valid options is at the end of this page: http://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html#hicplottads
