### ISSUE TITLE
cooler format support

### ISSUE THREAD

**Issue by bgruening** [deeptools/HiCExplorer#109]
It would be nice to support for formats in the long run. Cooler is one of them.

**Comment by joachimwolff** [comment]
@fidelram How important is it that the values for `correction_factor` and `distance_counts` are saved too?  I do not have a complete overview of the code, as far as I can see e.g. `correction_factor` is only saved in `hicCorrectMatrix` and used in `hicExport` if it is already there. Which means I do not see a real usage i.e.  that it is needed for a computation. For `distance_counts` it looks similar but maybe I missed something.

**Comment by bgruening** [comment]
ping @fidelram 
@joachimwolff I guess you could implement this without the correction-factor for now.

**Comment by fidelram** [comment]
@joachimwolff not much important.

The correction factor and distance counts are used to compute enrichment values using lieberman's method which is not part of the HiCExplorer package. The correction factors contain the number used to multiply each bin. Thus, using a unnormalized matrix + the correction factors yields the normalized matrix. I mention this in case the cooler format makes use of this information.

**Comment by joachimwolff** [comment]
I think this is more or less done. If not anyone detects some major bugs.
