### ISSUE TITLE
aggregate plot

### ISSUE THREAD

**Issue by bgruening** [deeptools/HiCExplorer#110]
@fidelram can you push what you have into some branch?

**Comment by fidelram** [comment]
I just added branch submatrix_pool (https://github.com/maxplanck-ie/HiCExplorer/tree/submatrix_pool).

It contains a new file in the bin folder called hicAggregateContacts.

Currently it needs a BED file. The code will compute all vs all combinations of the regions in the BED file. This may not be desired, instead given pairs of regions should be used.

**Comment by joachimwolff** [comment]
Is this something like viewpoint?

**Comment by fidelram** [comment]
This is different than view point. The output are plots like this:

![image](https://user-images.githubusercontent.com/4964309/33950376-85d9834a-e02c-11e7-858e-4b8b881333af.png)

**Comment by joachimwolff** [comment]
Implemented with release 2.1.
