### ISSUE TITLE
Recommendation window size

### ISSUE THREAD

**Issue by mzufferey** [deeptools/HiCExplorer#119]
Dear all,

I have a question regarding the window size parameters. If I am correct, in your article "High-resolution TADs reveal [...]" you use the following parameters: min window length = 10'000, max window length = 40'000 and a step of ~2'000 for a 0.5 kb resolution map.
What would be your recommendation for a Hi-C matrix of 50kb or 100 kb resolution ?
Can I use the following ratio minDepth = 3 x bin size and maxDepth = 6 x bin size as a rule of thumb ? (but how to choose the step size ?)

Thank you in advance and best regards,

Marie

**Comment by joachimwolff** [comment]
ping @fidelram Do you know an answer to this question?

**Comment by DonStephano** [comment]
Hi @mzufferey ,
I used following settings for a 40kb res (HiC-explorer v 1.7.2):
`--minDepth 300000 --maxDepth 3000000 --step 300000`
and `--minBoundaryDistance=400000` for finding TADs. In my eyes, this results in nicely called TADs for 40 and 50kb res.
cheers

**Comment by vivekbhr** [comment]
Hi @mzufferey . Some recommendations regarding mindepth, maxdepth and window sizes at any matrix resolution : 

**mindepth** would affect the TAD results more as it gets closer to the binSize, so you're safer with 4-5x binSize and try increasing it if you get noisy TAD boundaries. 

**maxdepth** the bigger it is the less noisy boundaries you would get. So you can maybe pick 300K as @DonStephano suggested binSize, but after a large value, the maxDepth effect wouldn't be visible.

**stepSize** are the number of points you would take to average between mindepth and maxdepth. The more steps you take the more would be the effect of averaging (decreases noise, but needs a bit more time to compute).

**minBoundaryDistance** was introduced to avoid large regions of flat TAD scores which we saw in mammalian genomes, you can leave it to default at first and try increasing it later if you also see what I mentioned.

At last, you should try using criteria to systematically evaluate the detected TADs, as we used in our paper (Fig 1B-C + scroll the regions in hicbrowser)

Hope this helps.

**Comment by gtrichard** [comment]
We should try to put these information in the documentation.
