### ISSUE TITLE
interaction arc plots

### ISSUE THREAD

**Issue by jsonbl** [deeptools/HiCExplorer#121]
I'm having trouble generating link/arc plots using hicPlotTADs. My link file has the following format (tab delimited):

############
chrX	11470000	11480000	chr2L	160000	170000	4
chrX	11470000	11480000	chr2L	290000	300000	3
chrX	11470000	11480000	chr2L	480000	490000	4
############

I'm getting the attribute error:

Traceback (most recent call last):
  File "//anaconda/envs/snowflakes/bin/hicPlotTADs", line 7, in <module>
    main()
  File "//anaconda/envs/snowflakes/lib/python2.7/site-packages/hicexplorer/hicPlotTADs.py", line 333, in main
    trp.plot(args.outFileName, *region, title=args.title)
  File "//anaconda/envs/snowflakes/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 189, in plot
    track.plot(axis, label_axis, chrom, start, end)
  File "//anaconda/envs/snowflakes/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 1701, in plot
    if interval.start < region_start and interval.end > region_end:
AttributeError: 'Interval' object has no attribute 'start'

###########

Is this a formatting problem in my links file, or a bug in hicPlotTADs.py? If the former, can you post an example links file in the test folder for testing?

**Comment by joachimwolff** [comment]
Dear jsonbl,

can you send me a small example of your files which is failing? I will have a look at it. Additional, which version of HiCExplorer do you use? 

Best,

Joachim

**Comment by jsonbl** [comment]
Hi Joachim,

Files are zipped and attached. README.txt has version and usage details, as well as the error I get when I try to generate the interaction arcs in the plot. I've also included the tracks that I'm trying to plot (HiC and a couple of bigwigs). I'm trying to show interaction links between a genebody and binding sites, plotted as the bottom two bed tracks. The output image is generated by commented out that section, lines 29-38 of the linkplot.ini file. Thanks! -J

[linktest.zip](https://github.com/maxplanck-ie/HiCExplorer/files/1322379/linktest.zip)

**Comment by DonStephano** [comment]
Something new about this issue?! I tried to plot arcs but got the same error, using version 1.8

**Comment by fidelram** [comment]
Can you try https://github.com/deeptools/pyGenomeTracks 

You can plot arcs correctly with that software.

**Comment by DonStephano** [comment]
Thx a bunch!
works perfectly...
