### ISSUE TITLE
hicPlotMatrix: direction of the diagonal

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#125]
What is the reason that the diagonal in hicPlotMatrix goes from the bottom left corner to upper right if the parameter `--region` is used but from the top left corner to bottom right if the parameter `--chromosomeOrder` is set? Is this on purpose? 
![matrix_plot](https://user-images.githubusercontent.com/13435136/30735414-4267cb96-9f7f-11e7-95e3-fd12c2537339.png)
![matrix_plot](https://user-images.githubusercontent.com/13435136/30735408-3bd49ed0-9f7f-11e7-8940-93ee870c4bb9.png)

**Comment by fidelram** [comment]
This is not on purpose. We should use only one direction.

**Comment by joachimwolff** [comment]
I think I fixed this in the pca branch, need to have a look at this code again.
