### ISSUE TITLE
Docker container update to version 1.8

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#144]
The container hosted on quay.io/bgruening/galaxy-hicexplorer is five months old. Therefore I think it is not updated to 1.8 version.

**Comment by bgruening** [comment]
Wait the hicexplorer installation is here: https://quay.io/repository/biocontainers/hicexplorer 
And it is updated. The Galaxy Docker container is not updated.

Update for the Docker integration is here: https://github.com/maxplanck-ie/docker-galaxy-hicexplorer/pull/2
