### ISSUE TITLE
hicPlotViewpoint

### ISSUE THREAD

**Issue by DonStephano** [deeptools/HiCExplorer#154]
Is it possible that hicPlotViewpoint uses a region as reference point instead of a single point?
2nd question: Could hicPlotViewpoint outputs a tsv-file (bedGraph?) with all plotted interactions?

Stephan

**Comment by fidelram** [comment]
I think this is not difficult to do. @joachimwolff can you take a look?

**Comment by joachimwolff** [comment]
I will take care of this.

**Comment by joachimwolff** [comment]
Implemented.
