### ISSUE TITLE
TAD insulation score

### ISSUE THREAD

**Issue by apaytuvi** [deeptools/HiCExplorer#155]
Hi,

I predicted my TADs with your package with a matrix at `80K`. I am wondering why in the `bedgraph` file generated:

```
chr1	120000	320000	-0.1322235
chr1	320000	500000	-1.393757
chr1	500000	660000	-1.6659695
chr1	660000	760000	-1.333263
chr1	760000	880000	-0.7475835
chr1	880000	1100000	-0.661958
chr1	1100000	1340000	-0.337774
chr1	1340000	1480000	-0.6595895
chr1	1480000	1580000	-0.5190255
chr1	1580000	1700000	-0.683183
```
column 3 - column 2 does not yield a size of `80000`.

My aim is to create a plot like the one in Figure 2H of the following paper:
https://www.biorxiv.org/content/biorxiv/early/2017/08/18/177444.full.pdf

**Comment by fidelram** [comment]
if you type `hicInfo -m <your matrix file>` what do you get?

But appart from that, to make the plot that you want, simply convert the bedgraph to bigwig and plot using deepTools2.
