### ISSUE TITLE
hicPCA develop branch: "TypeError: list indices must be integers, not tuple"

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#157]
I launched the new hicPCA tool on a corrected h5 matrix generated with the HiCExplorer with the following command:

```
hicPCA \
-m foo.h5 \
-o bar_pca1.bw bar_pca2.bw \
-noe 2 \
-f bigwig
```
And I get this error:

```
ERROR:HiCMatrix:No self.prev_to_remove defined, defining it now.
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1844, in printchrtoremove
    self.prev_to_remove
AttributeError: hiCMatrix instance has no attribute 'prev_to_remove'
/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/utilities.py:950: RuntimeWarning: divide by zero encountered in double_scalars
  expected_interactions[i] /= pLength_chromosome - (pChromosome_count * i)
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/bin/hicPCA", line 7, in <module>
    main()
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/hicPCA.py", line 138, in main
    assert(len(vecs_list[:, idx]) == len(chrom_list))
TypeError: list indices must be integers, not tuple
```

I installed HiCExplorer with the following command line on Wednesday 13th December:

`pip --upgrade git+https://github.com/deeptools/HiCExplorer.git@develop`

hicInfo from this develop branch fail a bit on this matrix by returning:

`WARNING:HiCMatrix:WARNING: bin size is not homogeneous.`

hicInfo from the master branch on this matrix gives:
```
WARNING: bin size is not homogeneous. Median 29828
File:	foo.h5
Size:	4,231
Sum:	19,231,699.2561
Bin_length:	29828
Chromosomes:	2L, 2R, 3L, 3R, X, 4
Non-zero elements:	4,931,560
Minimum (non zero):	0.413929262678
Maximum:	5075.5781269
NaN bins:	235
```

**Comment by joachimwolff** [comment]
Thanks for reporting this bug. 

For hicPCA: As a hotfix you can use the bedgraph file format as output, this should work. Bigwig support is a bit behind, there is e.g. no support for plotting it with hicPlotMatrix. Maybe I drop bigwig support for this release, let's see if I find time to implement it. 

Concerning hicInfo: I changed the output system yesterday, I have to fine tune it a bit better. 

I will come back to you if I have fixed the mentioned issues.

**Comment by fidelram** [comment]
@joachimwolff check the bigwig generation in deepTools bamCoverage as a template.

**Comment by joachimwolff** [comment]
It should work now. Can you test it @gtrichard? Please let me know if it works as you expect, or we can do any improvements. 

Thanks a lot!

**Comment by gtrichard** [comment]
So I installed the updated develop branch on anaconda2 with:
```pip install --upgrade git+https://github.com/deeptools/HiCExplorer.git@develop 
```

Then I ran hicPCA --version and now I have:
```Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/bin/hicPCA", line 4, in <module>
    from hicexplorer.hicPCA import main
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/__init__.py", line 3, in <module>
    logging.config.fileConfig('logging.ini')
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
```

Running the command line in the first comment gives the same error.

**Comment by joachimwolff** [comment]
@gtrichard Thanks a lot for your feedback and testing. The mentioned bugs should be fixed now, the relevant tests with the python 2 version pass on travis.
My apologies for the instability of the software, if you find more bugs please report them. This helps a lot to create a stable release.

**Comment by gtrichard** [comment]
Thank you @joachimwolff it is now working for both bedgraph and bigwig format with the b2c9971 commit.

Here are some info:

I updated to the b2c9971 commit with:
`pip install --upgrade git+https://github.com/deeptools/HiCExplorer.git@b2c9971`

I ran this command line for multiple matrices (with bigwig or bedgraph format):
```
hicPCA \
-m foo.h5 \
-o foo_pca1.bw foo_pca2.bw \
-noe 2 \
-f bigwig
```

I had this output message:
```
INFO:hicexplorer.HiCMatrix:Number of poor regions to remove: 225 {'2R': 56, '3R': 50, '4': 3, '3L': 49, '2L': 20, 'X': 47}
INFO:hicexplorer.HiCMatrix:found existing 225 nan bins that will be included for masking 
```

And also this one for one matrix:
```
INFO:hicexplorer.HiCMatrix:Number of poor regions to remove: 235 {'2R': 60, '3R': 58, '4': 3, '3L': 49, '2L': 20, 'X': 45}
INFO:hicexplorer.HiCMatrix:found existing 235 nan bins that will be included for masking 
/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/hicexplorer/utilities.py:947: RuntimeWarning: divide by zero encountered in double_scalars
  expected_interactions[i] /= pLength_chromosome - (pChromosome_count * i)
```

If it's ok for you, we can close this issue.

**Comment by joachimwolff** [comment]
Good to know! One small thing: If you run `hicPCA` with `-f datatype` please use the same for the output file `-o foo_pca1.datatype`. In `hicPlotMatrix` I am checking for the file ending to open the file, therefore a bedgraph file with a `bw` aka `bigwig` ending will fail to open.
