### ISSUE TITLE
Control of multicore usage with numpy

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#167]
For computing the PCA we use numpy, and they use openmp in the background. From my experience numpy is using all cores it can get on a machine. We need to have some control variable for this to limit the number of cores to an user defined value. If we don't do this it can happen that e.g. our jobs are killed if they are running on a cluster and they use more resources as granted by the systems scheduler.

**Comment by joachimwolff** [comment]
It seems we have to set:
```
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
```
First one is for numpy versions which have support for Intels math kernel library, second one for numexpr (Fast numerical array expression evaluator for Python, NumPy, PyTables, pandas, bcolz and more, see https://github.com/pydata/numexpr), and the last one is for open mp. 
We have to set all because we never really know which version of numpy an user is using and second, we do not really know (or at least if we don't do research on this) what our used numpy functions really use in the background. 
A possible side effect that I see here: These are system environment variables and as far as I know they are set system wide. E.g. if we run the same bash and just switch the conda environment the value is still set. This can influence other software running in the same bash. Does someone know here a bit more? Especially in the context of Galaxy and using these variables on a cluster.

**Comment by bgruening** [comment]
Galaxy will not be affected and we could `unset` the variables at the end of the execution as well if this helps.
