### ISSUE TITLE
BED file as reference point for hicPlotViewpoint

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#168]
A feature request of @DonStephano.
- A BED file should be used as an input for hicPlotViewpoint instead of a referencePoint. 
- Instead of a fixed region (chrX:1000-2000) a given number of basepairs around a reference point (-x / + y bp) should be used.

**Comment by DonStephano** [comment]
- contains the BED-file  n region(s), n plot(s) are created (one plot per line/region)

**Comment by joachimwolff** [comment]
We moved to chicViewpoint* and the requested features are implemented.
