### ISSUE TITLE
UnicodeDecodeError When running hicPlotMatrix

### ISSUE THREAD

**Issue by ioannisa92** [deeptools/HiCExplorer#174]
Can someone help with this error? I don't understand how to resolve it.

$ hicPlotMatrix --matrix /projects/redser3-notbackedup/projects/yianni_rotation/GreenRotation/HicAnalysis/BO139_10kb_Merged_100bins.h5 --log1p --dpi 300 --clearMaskedBins --chromosomeOrder chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY --colorMap jet --title “BO139_matrix” --outFileName /projects/redser3-notbackedup/projects/yianni_rotation/GreenRotation/HicAnalysis/plots/BO139_AllChr_matrix.png

['chr7', 'chr6', 'chr5', 'chr4', 'chr3', 'chr2', 'chr1', 'chrY', 'chr9', 'chr8', 'chr13', 'chr12', 'chr11', 'chr10', 'chr17', 'chr16', 'chr15', 'chr14', 'chr19', 'chr18', 'chrX']
Number of poor regions to remove: 158
{'chr7': 2, 'chr6': 2, 'chr5': 2, 'chr4': 2, 'chr3': 3, 'chr2': 2, 'chr1': 19, 'chrY': 33, 'chr9': 17, 'chr8': 2, 'chr13': 17, 'chr12': 1, 'chr11': 2, 'chr10': 1, 'chr16': 8, 'chr15': 18, 'chr14': 18, 'chr19': 7, 'chrX': 2}
found existing 158 nan bins that will be included for masking
min: 1, max: 9865
Nan values set to black
Traceback (most recent call last):
  File "/soe/ianastop/virtenv/bin/hicPlotMatrix", line 7, in <module>
    main()
  File "/soe/ianastop/virtenv/lib/python2.7/site-packages/hicexplorer/hicPlotMatrix.py", line 497, in main
    args, fig_width, cmap)
  File "/soe/ianastop/virtenv/lib/python2.7/site-packages/hicexplorer/hicPlotMatrix.py", line 149, in plotHeatmap
    axHeat2.set_title(args.title)
  File "/soe/ianastop/virtenv/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 185, in set_title
    title.set_text(label)
  File "/soe/ianastop/virtenv/lib/python2.7/site-packages/matplotlib/text.py", line 1178, in set_text
    self._text = '%s' % (s,)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by joachimwolff** [comment]
This error is caused by an unknown character in ascii. Given you Hexcode `0xe2` it is an `a` with something on top of it: https://stackoverflow.com/questions/16148356/unicodedecodeerror-utf-8-codec-cant-decode-byte-0xe2-in-position-434852-inv

I am not sure why this error appears. Can you try another title or maybe without any?

**Comment by ioannisa92** [comment]
No title works!
Thanks!
