### ISSUE TITLE
how to build h5 format file from other format data

### ISSUE THREAD

**Issue by shenscore** [deeptools/HiCExplorer#185]
Hi !
I tried cool format, but it only works with HiCExplorer when there is only one resolution matrix inside as well as only one chromosome are required to plot.
So is there someway one can transform other format (like array or matrix) into h5 format?
Thanks for your help!

**Comment by joachimwolff** [comment]
Thanks for using HiCExplorer!

You are right, HiCExplorer is supporting the cooler file format only if there is one resolution stored in the cooler file. I have to get in touch with the developers of cooler to figure out how to support multiple resolutions.
Concerning plotting: Do you want to plot the contact matrix, TADs, viewpoints or PCA? The `hicPlotMatrix` can plot contact matrices and all chromosomes which are given. The issue that sometimes rises is that the resolution of the contact matrix is too high to be plotted and your computer runs out of memory. Try to decrease the resolution of the contact matrix for plotting. You can use `hicMergeMatrixBins` for this task.
`hicPlotTADs` and `hicViewpoint` support only small regions to be plotted, and the PCA track which can be added for `hicPlotMatrix` is computed per chromosome therefore it can only be plotted per chromosome. 

To use other formats than h5 or cooler with existing contact matrices we have support for Lieberman-Aiden, Dekker and npz data, but this is deprecated. It should still work but we do not actively support it anymore. Have a look at `hicExport`. Out of these formats the one which comes closest to your question is the npz format. If you are familiar with python you can maybe adapt how we create npz matrices: https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/HiCMatrix.py#L1400

I hope I could help you. Please don't hesitate to ask for more support.

Best,

Joachim

**Comment by joachimwolff** [comment]
@shenscore I was reading a bit the documentation of cooler, as far as I understand the multiple resolution issue can be solved the following way: Instead of defining only the matrix e.g. `hicPlotMatrix --matrix hic_matrix.cool` try `hicPlotMatrix --matrix hic_matrix.cool::10kb` for a 10kb resolution. 

It would be nice if you can give me feedback if this works. Thanks a lot!

**Comment by joachimwolff** [comment]
@shenscore I did some patching for this issue. You can load mcool matrices by appending which node you want to use e.g. `--matrix matrix.cool::/resolutions/120000`. 
If you like to test it, it is in the 2.0.1-bugfix branch.
