### ISSUE TITLE
hicPCA - bed files for eigenvectors orientation?

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#187]
Would it be possible to implement a function to hicPCA so it can accept a positive bed file and/or a negative bed file to help the orientation of the resulting PCA score?

For the user, it is mandatory to do it by its own means after using the tool, so I think that hicPCA should do it the proper way.

I think that HOMER runHiCpca.pl does it, but since the computation is different, I don't know if it is possible for HiCExplorer to implement such a function.

Best,
Gautier

**Comment by joachimwolff** [comment]
It is already on my TODO list: https://github.com/deeptools/HiCExplorer/issues/166
