### ISSUE TITLE
Error while converting cool format matrix to h5 matrix

### ISSUE THREAD

**Issue by deebhar** [deeptools/HiCExplorer#192]
Hi 

I have matrix in cool format and was using hicexport 2.0 to convert it to h5 format.
I am getting this error 
KeyError: "Unable to open object (object 'weight' doesn't exist)"
Is there anything which I am missing here?

**Comment by joachimwolff** [comment]
Thanks for reporting this issue. I think I made a mistake in the implementation. `Weight` is a field from `bins` and is optional, but I implemented it as mandatory. This will be fixed in the next (bugfix-)release.

**Comment by joachimwolff** [comment]
Fixed with release 2.1.
