### ISSUE TITLE
Should we remove hicLog2Ratio?

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#198]
I think that this tool has been replaced by hicCompareMatrices, do we have to keep / document it?

Are there some tools that rely on hicLog2Ratio.py?

**Comment by fidelram** [comment]
If I remember correctly hicLog2Ratio functionality was superseded by hicCompareMatrices. I don't think that hicLog2Ratio can compare matrices of difference size.. probably it is suppose to mean not different number of bins but different number of total counts. 

I would say that hicLog2Ratio can be safely removed.

**Comment by gtrichard** [comment]
Can it be deleted to close this issue ?

**Comment by joachimwolff** [comment]
We let it open and will close it as soon as we have a new release without it.
