### ISSUE TITLE
hicFindTADs: get boundaries pValue and delta

### ISSUE THREAD

**Issue by samuelCollombet** [deeptools/HiCExplorer#218]
Hi,
It would be great if it was possible to get the pValue and delta of each boundary called with hicFindTads. This way one can make first a loose boundary calling, check the value of each of them and define the value that seems the best.

Thanks for the great tools!

**Comment by gtrichard** [comment]
I think that it is already the case.

hicFindTADs outputs TAD boundaries positions with delta, p-value and TAD separation score as GFF.

The documentation will be updated about this at one point.
