### ISSUE TITLE
findRestSite version 2.0

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#220]
I am getting  standard output error running this function on the last version. It is working on version 1.8 though with python 2.7.14. Here is the error:

 File "/package/anaconda3/envs/HiCExplorer-2.0/lib/python3.5/site-packages/hicexplorer/findRestSite.py", line 118, in main
    find_pattern(args.searchPattern, args.fasta, args.outFile)
  File "/package/anaconda3/envs/HiCExplorer-2.0/lib/python3.5/site-packages/hicexplorer/findRestSite.py", line 110, in find_pattern
    out_file.write(stdout)

**Comment by bgruening** [comment]
Can you try with python2 please, this is probably a python3 bug.

**Comment by fidelram** [comment]
I tried with python3.6 and could not reproduce the problem. Could it be that you don't have write permissions to the file you want to write?

**Comment by vivekbhr** [comment]
It's most probably python issue. We checked with 2.7 and it works

**Comment by gtrichard** [comment]
Is this problem solved?
