### ISSUE TITLE
How to extract TAD boundary coordinates..?

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [deeptools/HiCExplorer#234]
Hello  Team,

We are trying to analysis over Hi-C data with HiCExplorer, we had finished with few steps like(hicBuildMatrix , hicCorrectMatrix , hicPlotMatrix , hicFindTADs , hicPlotTADs )and need some inputs from developers as mentioned below.

We need to extract TAD exact boundaries for extracting the sequence from fasta file. At the moment we can only extract a round off value for the TAD boundary. We need the exact location (start and end) of specific TAD.

Waiting for your response.

Thanks in advance
Vijay N

**Comment by fidelram** [comment]
The resolution of a boundary depends on the size of the bins used. 

When you run hicFindTADs, two files are produced (among others). One is the <prefix>_boundaries.bed and the other is the <prefix>_domains.bed file. The boundaries file contains the start - end position of the bin identified as boundary. This is probably what you are looking for. Instead, the domains file contains the start end of a full TAD.
