### ISSUE TITLE
hicTransform

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#238]
I am using hicTransform to generate the pearson correlation matrix, I get  python runtime warning (RuntimeWarning: invalid value encountered in true_divide) while np.corrcoef is running. I am assuming the issue should be related to the np.corrcoef short come in handling bin size = 0. Here is a part of the matrix:
[[ 29.07633765  28.40623518  28.21770773 ...,   0.           0.           0.        ]
 [ 28.40623518   4.79656871  17.86775506 ...,   0.           0.           0.        ]
 [ 28.21770773  17.86775506   5.32475092 ...,   0.           0.           0.        ]
 ...,

**Comment by joachimwolff** [comment]
Thanks for your feedback, this is a known and tolerated issue. It is caused by divisions with zero. It is faster to compute it with these errors and handle all 'nan' results after the computation.
