### ISSUE TITLE
Clarification on Lieberman format

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#239]
Hi,

Is the Lieberman format described in hicExport.py and elsewhere the .hic format (output of the Lieberman lab's Juicer software)?

Thank you, and thanks for the great software.

-Kris

**Comment by vivekbhr** [comment]
Hello.

The .hic format is not implemented yet. We still refer to the original format from `rao et. al 2014` which we call lieberman format. We are discussing whether we could also add the .hic format to the list of exports.

Best,
Vivek

**Comment by kalavattam** [comment]
Thank you, Vivek. To clarify, the .hic format is currently not a form of input too. Is that correct?

-Kris

**Comment by joachimwolff** [comment]
Hi Kris,

.hic is not supported. We do support the cooler file format and endorse that it becomes the standard file format of Hi-C data. 

I found a tool on github to transform hic to cool format: https://github.com/4dn-dcic/hic2cool
Let us know if it works or if the created cooler matrices cause any issues with HiCExplorer.

Best,
Joachim

**Comment by kalavattam** [comment]
Thank you, Joachim. I will test hic2cool and let you know how it goes.

Thanks again,
Kris

**Comment by kalavattam** [comment]
hic2cool works well and I was able to load .cool maps into HiCExplorer. So far, the matrices look reasonable. I haven't tested multi-resolution .cool maps yet.

Thanks again,
Kris
