### ISSUE TITLE
Missing qc_template.html when installing with pip

### ISSUE THREAD

**Issue by Rmulet** [deeptools/HiCExplorer#241]
Hi,

I have installed hicexplorer via pip, but `qc_template.html` is missing, which results in a complaint from `hicBuildMatrix.py`. However, the file is there -probably unsurprisingly- when I clone the git repository and I install the program with `setup.py`.

Best regards,

Roger

**Comment by joachimwolff** [comment]
Thanks for your feedback Roger.

I strongly recommend to use conda instead of pip. The dependency management is better for us to control using conda and issues like yours should not happen with conda.

**Comment by joachimwolff** [comment]
Updated package 2.2.1.1 doesn't show this behaviour in pip anymore.
