### ISSUE TITLE
proposed improvement for hicPlotTADs

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#256]
Hello,
This tool is really great. It helps to save time with illustrator...
A possible bug:
- It looks like for a bed file when you do not want to print the label, they are printed anyway.
I would add:
- the possibility to plot all annotations from a bed file on one row (even if the label overlap).
- the possibility to plot the normalized count of the matrices (not only log transformed data).
- the possibility to auto-width the matrices in order to have square bins (not diamond).

Many thanks,

Lucille

**Comment by joachimwolff** [comment]
Thanks for your feedback. I will try to add these proposals to the next release.

**Comment by joachimwolff** [comment]
@vivekbhr @fidelram Is one / some / all of the listed features already implemented in pyGenomeTracks?

**Comment by joachimwolff** [comment]
Moved to: https://github.com/deeptools/pyGenomeTracks/issues/49
