### ISSUE TITLE
feature request: hicPlotMatrix

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#274]
Hi all,

Another low-priority, low-importance feature request, but could improve quality of life when making rough figures from output: for `hicPlotMatrix`, an option to set `--bigwig`'s `vMax` and `vMin`.

Even lower importance: an option to run a small number of bigwigs.

As always, thank you for the great work.

-Kris

**Comment by DonStephano** [comment]
Oh yeah, vMax/vMid/vMin for bigwigs would be great in hicPlotMatrix! I definetely support this request :)

**Comment by joachimwolff** [comment]
Option 1 comes with version 2.2, option 2 as soon as the loop detection algorithm is finalized.
