### ISSUE TITLE
HiCTransform is not producing correct output

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/HiCExplorer#276]
The hicTransform with "pearson" is not working correctly, which leads to wrong eigenvalues after PCA, and affects the A/B compartment analysis. 

**Output from HOMER**
![hommer_correlation](https://user-images.githubusercontent.com/8420267/43636147-8e6ba4ec-9711-11e8-8ef6-9cb911ffb419.png)

**Output from hicTransform**
![hictransform](https://user-images.githubusercontent.com/8420267/43636149-909158d4-9711-11e8-8cd8-de861e76a650.png)

**Comment by joachimwolff** [comment]
I am not sure if this is a bug. I have to agree hicTransform is not that good documented. What it does is to compute for any input matrix depending on the mode a) a obs_exp matrix, b) a pearson correlation matrix or c) a covariance matrix. In mode 'all' it is behaving different: It takes the input matrix, transforms it to obs_exp transforms the result of it to a pearson correlation matrix and transforms the result of this to a covariance matrix. 

In hicPCA the mode `all`  is used and than we do the eigenvector decomposition. We correlated the result with HOMER PCA and had a correlation of > 90%.

**Comment by vivekbhr** [comment]
All right thanks for clarification. That would mean hicTransform with "all" (not "pearson") should match the above homer output. I would ask leily to check that on her data and close the issue once it's resolved.

**Comment by joachimwolff** [comment]
Unfortunately I can not agree with your conclusion. I do not know how Homer is computing the Pearson correlation, on which matrix it is based. In their documentation it is written they compute the PCA based on a „background model“ but it is not defined what this background model in detail is. 

If you compare the Pearson matrix of Homer and HiCExplorer, they can be the same or not; if not we only know it is compted somehow different but you can not say it is wrong or correct. 

What we compared were only the values of the eigenvectors. There we had a high correlation, this means not all values are identical, they are just correlated. And sometimes you need to use PC1 from Homer but PC2 from HiCExplorer, sometimes the correlation is negative and you need to flip the sign of the values. For the last case please use the new feature in the dev branch to correlate the values of the pca with the density of the genes.

**Comment by gtrichard** [comment]
Would this difference between `all` and `obs/exp` alone also affect the obs/exp matrices?

**Comment by gtrichard** [comment]
Ok, thank you for your input @joachimwolff .

But then how should I compute a obs/exp matrix to, for example, score long range interactions using HiCExplorer?

I think that we need to update the documentation according to your last message @joachimwolff

**Comment by joachimwolff** [comment]
@gtrichard I have a WIP branch called `longrangecontacts`. In this you can find the script `hicDetectLongRangeContacts`. In combination with `hicPlotMatrix` and the new parameter `--longRangeContacts` it maybe helps you to detect these long range contacts.

If you have any feedback for this tool, please let me know. As I said, it is work in progress and I there is a high chance that the detection method can be improved.

**Comment by LeilyR** [comment]
I have checked the values of hicPCA obsexp_matrix form the pca branch. The values are so small and the matrix has very different values from what I have obtained from homer. In fact it seems the is no region where the obs is larger than exp.

**Comment by LeilyR** [comment]
Thank you so much for the reply. I totally agree with you that homer is not the golden standard, maybe I should have phrased it differently. 
Although obs/exp is an intermediate step,  a common way of looking for compartments is reordering obs/exp matrix based on PCA values, that is why I was looking to the obs/exp matrix and have noticed small values for almost any single bin. It seems to me as if obs. is always significantly smaller than exp. which I assume shouldn't be the case for the regions with long range interaction. That is why I brought the issue up and I hope this is a clearer explanation of what I have exactly meant to say.

**Comment by joachimwolff** [comment]
>Although obs/exp is an intermediate step, a common way of looking for compartments is reordering obs/exp matrix based on PCA values
This is new for me, can you explain me why and how?

In my opinion you should not use the obs/exp matrix we use for the computation, I think a regular obs/exp is better. The reason is I compute expected values in the following way:
`exp(i,j) = f (absolute(i-j)) * n_i * n_j / N` where `f(d)` is the number of interactions observed for this distance, `n_i` the sum of the row i, and N the total number of counts for the matrix summed up. This all together makes expected value really high and therefore obs/exp low, but it helps to get the checked pattern and therefore the PCA values. 
What you should use instead is an obs/exp matrix where expected values are calculated in a 'normal' way e.g. `expected(i.j) = sum of all contacts at distance absolute(i-j) / Number of elements at this distance`. I am not sure HiCExplorer is computing this kind of obs/exp matrix, but I can add it in the next weeks.

**Comment by LeilyR** [comment]
Thanks a lot for the clarification! Regarding to the question you have asked, you might want to check the Figure 1 of this paper http://science.sciencemag.org/content/early/2018/01/17/science.aao6135/tab-pdf . If there is anything unclear just drop me an email for more explanation of how it works.
