### ISSUE TITLE
improvements for hicEx

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/HiCExplorer#278]
I am summarizing what @joachimwolff and I discussed today.

### bugs (?) reported by @leilyR
- [x] HiCplotTADs with full chr throws error, but works with chr:start-end
- [x] hicPCA on drosophila chromosome produces weird results

### capture HiC support
- [ ] **--method** option for hicCorrectmatrix with "ICE" (default) and **localICE** (for chic data)
	- split matrix into multiple matrices, with capture and another with non-capture loci
	- apply ICE seperately --> merge into one
- [x] testing of significant interactions (experimental)

### loop detection
- [x] reuse code from hicFindEnrichedContacts if possible, and deprecate with the release of "hicFindLoops"

### cooler support issues
- [x] keep HDF5 as native format and add cool <-> hdf5 support in hicconvertFileformats
	allow --dividebyFactors option (default = False) to allow storing correction factors as 1/value
- [x] Instead of mcool, hicBuild matrix can write multiple .h5 files at various resolution, then hicConvertFormats can convert it into .mcool

### enhancements on HiCMatrix
- [x] HiCmatrix as a seperate repo, imported by both pyGenometrack and hicEX
- [x] store metadata in the hicMatrix object : 
	- hicQC metadata
	- matrix resolution
	- corrected or not (boolean)
	- other info
- [ ] create multiple matrices by reading a use-specified tag from bam
        - Useful for Allele-specific matrices 
	-  would also be useful for single cell hic, where cells are barcoded
- [x] Try to skip the --reorder requirement
	 - use pre-de-dup matrix (hic option from BWA)

### the war on names
- [x] rename hicConvertFileFormats to **hicConvertFormat**
- [x] rename hicDetectlongRangeContacts to **hicFindLoops**

I would send the references etc. by email later this week.

**Comment by gtrichard** [comment]
What about conversion of GInteractions files back to h5 format with *hicConvertFormat* (I tried with the old and now deprecated hicExport, perhaps I'm not up-to-date on that)?

**Comment by vivekbhr** [comment]
@gtrichard GI/.arcs format may/maynot contain a full HiC matrix info. In fact most Gi input would have missing bins etc. which could create confusion in expanding to a useful matrix, that's why we provided only the export option.

**Comment by LeilyR** [comment]
Is it also possible to get the conversion from .h5 to homer added to hicConvertFormat too? It is very very close to the dekker format just will save me some time not to run couple of lines of a bash script to change dekker to it.

**Comment by joachimwolff** [comment]
@LeilyR See the current master of HiCMatrix, I implemented a write support for homer. Feel free to test it.

**Comment by LeilyR** [comment]
Adding to the improvement list:
- Generating an expected matrix
- Balancing matrices

**Comment by LeilyR** [comment]
> Adding to the improvement list:
> 
> * Generating an expected matrix
> * Balancing matrices

These are done!
