### ISSUE TITLE
Contacts scaling factor in hicPlotMatrix?

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#280]
I have this in the back of my head since forever. 

Basically when you plot a high number of Hi-C matrices with `hicPlotMatrix` and you want to compare them "by eye" (without doing a log2 ratio of 2 matrices with one by one comparisons), the representation is often biased towards the matrix where contacts are the most abundant (the most deeply sequenced).

An option allowing to plot multiple matrices at once and normalise them, or simply an option to multiply the values by a given number just like `--scaleFactorBigwig` but for the Hi-C matrix would be super useful.

Best,
Gautier

**Comment by fidelram** [comment]
There is a parameter called `scale factor` or something like this. I think
this will do what you want

**Comment by gtrichard** [comment]
@fidelram By checking https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicPlotMatrix.py there is `--scaleFactorBigwig` but this is for the bigwig that one can plot below the matrix (pca1 for example).

In https://github.com/deeptools/HiCExplorer/blob/cooler_correction_patch/hicexplorer/hicPlotMatrix.py I see the `--correction_operation` and `--correction_name` parameters, but the documentation is not super clear about them, how should I compute this extra column ? Is it related to my question ? I feel it is more related to cooler compatibility.

**Comment by joachimwolff** [comment]
Hi Gautier,

your discoveries in the branch `cooler_correction_patch` are not related to your question. It is actually a feature which is moved to `hicConvertFormat` at allows to apply correction factors to cooler data which is stored in non-standard named columns like Lieberman-Aidens `hic` format is doing it. The `correction_operation` is to decide if the correction values should be applied by a multiplication or a division. 

I add your request to my features to implement list.

Best,

Joachim

**Comment by joachimwolff** [comment]
Normalization of matrix and bigwig scale factor for hicPlotMatrix is part of release 2.2.
