### ISSUE TITLE
Question about the bin size of the Hi-C matrices when using hicCorrelate

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#283]
Hi
   I tried to use hicCorrelate to compute pairwise correlations between Hi-C matrices data ,but I'm very confused about using which bin size of the Hi-C matrices . I have read some papers , in some papers ,the bin size is 50kb ; in other papers , the bin size is 500kb . I used the two bin sizes , but the results of  hicCorrelate are different , so about how to choose , Can you give me some advice?

Best

**Comment by QianzhaoJ** [comment]
Thanks for your help !

**Comment by vivekbhr** [comment]
Adding to that, you can also take into account that smaller the binsize more the local fluctuations would affect the overall correlation. So you should pick the bin size as per genome-size + how much in detail you would like to see.
