### ISSUE TITLE
hicTransform not producing any output

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#287]
I freshly installed the pca branch to test out the new `hicTransform -me norm` for _Drosophila melanogaster_ genome, sadly enough, no output is created although there are no error messages, only warnings (as usual for hicTransform). 

Here's the log:
```
DEBUG:hicmatrix.HiCMatrix:Load self.matrixFileHandler
DEBUG:hicmatrix.lib.h5:Load in h5 format
INFO:hicexplorer.hicTransform:hic_ma.matrix:   (0, 0)	11166.182259069923
  (0, 1)	4808.3072507347
  (0, 2)	1441.8662331125388
  (0, 3)	571.6018501593607
  (0, 4)	310.2908915975594
  (0, 5)	275.3766000758035
  (0, 6)	158.5374518170839
  (0, 7)	130.81840199920734
  (0, 8)	112.17117944070614
  (0, 9)	89.70415601732218
  (0, 10)	56.15095178681324
  (0, 11)	39.32405736179098
  (0, 12)	53.694404784849795
  (0, 13)	32.60813636435986
  (0, 14)	51.8696248972116
  (0, 15)	39.0592153554476
  (0, 16)	38.29470127039681
  (0, 17)	44.05822972500034
  (0, 18)	51.774171601180996
  (0, 19)	33.50482045672599
  (0, 20)	22.6410455414565
  (0, 21)	25.07537570314107
  (0, 22)	17.775781685321604
  (0, 23)	21.169204961897258
  (0, 24)	17.06077408379608
  :	:
  (4184, 4153)	21.350440208641505
  (4184, 4154)	36.8403542584477
  (4184, 4155)	46.60793039148563
  (4184, 4156)	20.183575840282145
  (4184, 4157)	28.19059124413469
  (4184, 4158)	26.80087721346268
  (4184, 4159)	13.995434902807471
  (4184, 4160)	18.991351992279355
  (4184, 4161)	27.32912066706437
  (4184, 4162)	77.84527885645666
  (4184, 4163)	32.14696571295032
  (4184, 4164)	42.863104514623295
  (4184, 4165)	52.246089812744
  (4184, 4166)	42.18133978118671
  (4184, 4167)	72.15740744635532
  (4184, 4168)	112.46012665592666
  (4184, 4169)	99.21962250730944
  (4184, 4170)	172.72439645585374
  (4184, 4171)	239.65738207827425
  (4184, 4172)	94.89306956448524
  (4184, 4173)	567.9904272409216
  (4184, 4174)	430.77155304102035
  (4184, 4179)	1580.407766783995
  (4184, 4180)	1667.081122077618
  (4184, 4184)	15020.415118301025
DEBUG:hicexplorer.utilities:pLength_chromosome 4187
DEBUG:hicexplorer.utilities:pChromosome_count 5
/data/akhtar/group/richard/Softwares/HiCExplorer/hicexplorer/utilities.py:254: RuntimeWarning: invalid value encountered in true_divide
  expected_interactions /= occurences
/usr/lib64/python2.7/site-packages/numpy-1.15.0.dev0_d233e1f-py2.7-linux-x86_64.egg/numpy/lib/function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/lib64/python2.7/site-packages/numpy-1.15.0.dev0_d233e1f-py2.7-linux-x86_64.egg/numpy/lib/function_base.py:3184: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
DEBUG:hicexplorer.utilities:pLength_chromosome 4187
DEBUG:hicexplorer.utilities:pChromosome_count 5
DEBUG:hicexplorer.utilities:pLength_chromosome 4187
DEBUG:hicexplorer.utilities:pChromosome_count 5
DEBUG:hicexplorer.utilities:pLength_chromosome 4187
DEBUG:hicexplorer.utilities:pChromosome_count 5
DEBUG:hicexplorer.utilities:pLength_chromosome 4187
DEBUG:hicexplorer.utilities:pChromosome_count 5

```

The details from installation to command launching:

```
conda install -c bioconda hicmatrix
conda install -c bioconda hicexplorer
#installation performed in /data/akhtar/group/richard/Softwares/anaconda2/
cd /data/akhtar/group/richard/Softwares/
git clone https://github.com/deeptools/HiCExplorer
cd HiCExplorer
git checkout origin/pca
export PYTHONPATH="/data/akhtar/group/richard/Softwares/HiCExplorer/:/data/akhtar/group/richard/Softwares/anaconda2/lib/python2.7/site-packages/:"${PYTHONPATH}

/data/akhtar/group/richard/Softwares/HiCExplorer/bin/hicTransform --matrix test.h5 -o test_transformed -me norm
```

`test_transformed` files are nowhere to be found.

**Comment by joachimwolff** [comment]
Long story short: You did not add a file ending for `--outFileName foo.h5`. 

-------------------------------------------------------
Long story I wrote before I saw that: 
`/data/akhtar/group/richard/Softwares/HiCExplorer/bin/hicTransform --matrix test.h5 -o **test_transformed** -me norm`

1. `git clone git@github.com:deeptools/HiCExplorer.git`
2. `git checkout pca`
3. `conda create --name hicTransformDebug --file requirements.txt`
4. `source activate hicTransformDebug`
5. `python setup.py install`

6. 
```
whereis hicTransform`
hicTransform: /home/wolffj/miniconda3/envs/hicTransformDebug/bin/hicTransform`
```

7. `hicTransform --matrix mergedSamples_100kbin.corrected.h5 -o hicTransformDebug.h5 -me norm`

8.
 ```
ls -lah | grep hicTransformDebug
-rw-rw-r--  1 wolffj wolffj 2,0M Sep 16 14:26 hicTransformDebug.h5
```

Only thing I see: You missed the file ending of the output matrix:

<pre>/data/akhtar/group/richard/Softwares/HiCExplorer/bin/hicTransform --matrix test.h5 -o <b>test_transformed</b> -me norm</pre>
But it should be:
<pre>/data/akhtar/group/richard/Softwares/HiCExplorer/bin/hicTransform --matrix test.h5 -o test_transformed<b>.h5</b> -me norm </pre>

**Comment by LeilyR** [comment]
step 2.1: (In case channel bioconda is not appended)
conda config --append channels bioconda

**Comment by LeilyR** [comment]
still doesn't work for me. the error is the same. What is this 'obs_norm_pearson.PCA'?

**Comment by LeilyR** [comment]
made it work, The issue was that the code doesn't accept any directory. Basically it means that one has to run it in the directory  that the output is expected to be.

**Comment by gtrichard** [comment]
Actually for me it did solve the issue, I used the -me norm and I'm currently plotting it (I have issues with numpy version on my installation...)

**Comment by joachimwolff** [comment]
Great that it is working now!

I am surprised directory are not accepted, I tested this and it is working on my computer. Maybe this is some Linux / macOS issue, but I can not test for macOS.

**Comment by LeilyR** [comment]
I am using linux.  The program tries to use the arg.out as a name to generate the output, reads the directory as part of the name and throw an error when reaches / . check this:
hic_ma.save('obs_norm_pearson.'+ args.outFileName, pSymmetric=False, pApplyCorrection=False)

**Comment by joachimwolff** [comment]
Actually, this src line is not part of the most recent version. Please get the latest changes.
