### ISSUE TITLE
converting matrices into h5 format

### ISSUE THREAD

**Issue by ahorvath** [deeptools/HiCExplorer#291]
I would like to convert matrices in GInteractions format into h5 format. 
I tried hicExport with an example file:
 
hicExport --inFile matrix.GInteractions.tsv --outFileName test.h5 --inputFormat GInteractions --outputFormat h5 

But I got this error:

matrix format not known.

Can you me help with that?

Thanks in advance.

**Comment by joachimwolff** [comment]
Hi,

This functionality is not supported, there is only write support but no read support for ginteractions files.

Best,

Joachim

**Comment by gtrichard** [comment]
It is not officially supported by HiCExplorer currently, but there's a way for it to work, but it is untested so be sure to check that your matrix is fine in the end...

What you need is `cooler` and the `develop` branch of HiCExplorer. Let's consider you have a GInteractions file called `foo.1000.GInteractions.tsv` at the resolution of 1000bp bins in _Drosophila melanogaster_ (dm6 genome assembly).

Run the following:
```
mv foo.1000.GInteractions.tsv foo.1000.bg2
gzip foo.1000.bg2 # in order to relate better to the cooler documentation
cooler cload pairs --assembly dm6 --tril-action drop --zero-based dmel.chrom.size:1000 foo.1000.bg2.gz foo.1000.cool -c1 1 -p1 2 -c2 4 -p2 5
hicConvertFormat -m foo.1000.cool -o foo.1000.h5 --inputFormat cool --outputFormat h5
```
