### ISSUE TITLE
TADplot problems

### ISSUE THREAD

**Issue by MackZhang** [deeptools/HiCExplorer#294]
when I run hicPlotTADs, I got this message, I don't know how to fix it 

INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
/usr/local/lib/python2.7/dist-packages/unidecode/__init__.py:46: RuntimeWarning: Argument <type 'type'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  _warn_if_not_unicode(str)
/home/wulab/.local/lib/python2.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
WARNING:hicexplorer.HiCMatrix:Bin size is not homogeneous.                                       Median 10000

Traceback (most recent call last):
  File "/usr/local/bin/hicPlotTADs", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/hicPlotTADs.py", line 357, in main
    track_label_width=args.trackLabelFraction, p_region=args.region)
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/trackPlot.py", line 120, in __init__
    if properties["file_type"] == 'bedgraph':
KeyError: 'file_type'

**Comment by joachimwolff** [comment]
It looks for me that you have a wrong defined tracks.ini file. See https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html#configuration-file-template for an example file. 

If this can not solve your issue, please create a small reproducible example and send it to me.

**Comment by hzaumsq** [comment]
I have the same mistake,when I follow the example to analyze my own data

**Comment by joachimwolff** [comment]
Please write the command you used and the error message and post the tracks.ini file.

**Comment by MackZhang** [comment]
I use new tracks.ini template in https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html#hicplottads and set the "depth = 400000", solve the problem.
