### ISSUE TITLE
hicPlotMatrix PCA 

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#295]
I got a mistake,when a use hicPlotMatrix to draw PCA picture,but  the example show we can use it to do.
hicPlotMatrix -m ./correct_martix/correct_10kb.h5 --outFileName pca1_10k.png --perChr --pca ./hic_PCA/10kb_pca1.bedgraph 
usage: hicPlotMatrix --matrix MATRIX --outFileName OUTFILENAME [--title TITLE]
                     [--scoreName SCORENAME] [--perChromosome]
                     [--clearMaskedBins]
                     [--chromosomeOrder CHROMOSOMEORDER [CHROMOSOMEORDER ...]]
                     [--region REGION] [--region2 REGION2] [--log1p] [--log]
                     [--colorMap COLORMAP] [--vMin VMIN] [--vMax VMAX]
                     [--dpi DPI] [--bigwig BIGWIG] [--flipBigwigSign]
                     [--scaleFactorBigwig SCALEFACTORBIGWIG] [--help]
                     [--version]
hicPlotMatrix: error: unrecognized arguments: --pca ./hic_PCA/10kb_pca1.bedgraph

https://hicexplorer.readthedocs.io/en/latest/content/example_usage.html

**Comment by joachimwolff** [comment]
Hi,

I have to apologize, the documentation was not updated in this specific point. `--pca` was the name of the parameter in version 2.0, but we changed it in 2.1 to `--bigwig` to make it clear that every bigwig file can be used and not only a pca track.

To get it run you need to run:
```
hicPCA -m hic_corrected.h5 --outFileName pca1.bw pca2.bw --format bigwig
```

and 

```
hicPlotMatrix -m pearson_all.h5 --outFileName pca1.png --perChr --bigwig pca1.bw
```

Unfortunately we dropped the support of bedgraph files for hicPlotMatrix.
