### ISSUE TITLE
mapping pipeline

### ISSUE THREAD

**Issue by mictadlo** [deeptools/HiCExplorer#296]
Hi,
Do you recommend to use this [mapping pipeline](https://github.com/ArimaGenomics/mapping_pipeline/blob/master/01_mapping_arima.sh) ?

Or what is the best practice for mapping?

Thank you in advance,

Michal

**Comment by bgruening** [comment]
Hi @mictadlo.

Have a look at our tutorial to learn more about mapping.
http://galaxyproject.github.io/training-material/topics/epigenetics/tutorials/hicexplorer/tutorial.html#reads-mapping

Cheers,
Bjoern

**Comment by gtrichard** [comment]
In terms of pipelines, I want to drag your attention to the snakepipes:
https://github.com/maxplanck-ie/snakepipes

the Hi-C pipeline is based on HiCExplorer and has been developed alongside HiCExplorer at the MPI-IE.
