### ISSUE TITLE
Excluding regions from hicPCA analysis

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#297]
Could it be possible to provide a bed file for hicPCA to calculate PCA only for the regions in that bed file?

**Comment by joachimwolff** [comment]
Hi Leily,

If you only care about the filter step, than I could add a filter in the end to output only the specified regions.
To change the computation I would need to verify first if the results are still correct. My ToDO list is very long atm, I don't know when I would find time for this.

**Comment by LeilyR** [comment]
Hi Joachim,
Thanks a lot for the respond, to be honest I rather go for the second case. I would like to remove some regions before running PCA since I suspect they have a big affect in compartmentalization and may bias the computation. But even if you could only go for the first one atm I can give that a try and see how it performs.

**Comment by gtrichard** [comment]
@LeilyR I think it is simpler to just `hicExport` your matrices with regions you want per chromosome and then merge all the matrices into one h5 file that you analyse with hicPCA (if it's removing beginning / end of chromosomes you are talking about).

**Comment by LeilyR** [comment]
Thank you @gtrichard , although I couldn't see any 'region' option in hicExport. It seems that only chromosomes can be set.

**Comment by LeilyR** [comment]
In fact I think the best way of doing that would be adding two features to hicBuildMatrix that user be able to provide a bed file of regions which he wishes to include or to provide a bed file of regions which he wishes to exclude

**Comment by joachimwolff** [comment]
@LeilyR Please have a look at the branch `adjustMatrix` and the tool `hicAdjustMatrix`. Make sure the current `development` branch of hicmatrix is installed.

The tool `hicAdjustMatrix` gives the option to keep, remove or mask a list of chromosomes (as parameter in the bash) or regions (one per line in a bed file with `chr start end` ).

**Comment by LeilyR** [comment]
Hi Joachim, Did you already merge the changes from `adjustMatrix` to some other branches? I cannot find the branch.

**Comment by joachimwolff** [comment]
It is merged to the `develop` branch.

**Comment by LeilyR** [comment]
thanks a million!
