### ISSUE TITLE
hicbuildMatrix --region

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#298]
HicBuildMatrix with --region extends the last bin all the way to the end of the chromosome if the set region started somewhere after beginning of the chromosome and ended somewhere before the end.
example: I have asked for 3L:2000000-22700000 but the last bin went all the way to 24543557 which is the end of the arm.

**Comment by joachimwolff** [comment]
I am not sure if we need to fix this. @LeilyR is it still an issue or could you work around it?

**Comment by LeilyR** [comment]
I suppose the issue is still there, i have not checked it recently.however in my case hicadjustmatrix does the job .
