### ISSUE TITLE
hicConvertFormat to ginteractions: no output

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#301]
For example when I use:

```
hicConvertFormat -m $1.cool -o $1.GI --inputFormat cool --outputFormat ginteractions
```

I receive the following messages but no output is created.
```
DEBUG:hicexplorer.hicConvertFormat:Namespace(bedFileHicpro=None, chromosome=None, correction_division=False, correction_name='weight', inputFormat='cool', matrices=['../HiC_matrices_corrected/control_2.5kb_cor.cool'], outFileName=['../HiC_matrices_corrected/c
ontrol_2.5kb_cor.GI'], outputFormat='ginteractions', resolutions=None, store_applied_correction=False)
DEBUG:hicmatrix.lib.cool:Load in cool format
DEBUG:hicmatrix.lib.cool:self.chrnameList None
DEBUG:hicexplorer.hicConvertFormat:Setting done
```

This is using the latest develop branch

`hicExport` is currently the only way to export to GInteractions format it seems.

**Comment by joachimwolff** [comment]
I need more information, I cannot reproduce this behaviour. I tried the `small_test_matrix.h5` and converted it to cool and both,  h5 and cool matrix, to ginteractions. With both I get an output and the files are identical.

**Comment by LeilyR** [comment]
hicConvertFormat is not working for me while converting from h5 to any possible format.

`  pApplyCorrectionCoolerLoad=applyCorrectionCoolerLoad)
TypeError: __init__() got an unexpected keyword argument 'pApplyCorrectionCoolerLoad'`

Also, is it possible to bring the dekker format back?

**Comment by LeilyR** [comment]
The error I have reported is resolved if hicmatrix version 2 instead of version 4

**Comment by LeilyR** [comment]
works with version 5 thanks! May I ask for the dekker output to be back as well

**Comment by joachimwolff** [comment]
@gtrichard @LeilyR Is this bug still existing?

**Comment by LeilyR** [comment]
works for me.
