### ISSUE TITLE
Issue with hicExport cool to hicexplorer

### ISSUE THREAD

**Issue by IttaiEres** [deeptools/HiCExplorer#302]
Hello,

I'm trying to use HiCExplorer to visualize some data, so attempting to export some of what I have to hicexplorer format from cool files with the following command:

hicExport --inFile /HiC/EXAMPLE/human.full.multi.cool --outFileName Human.5.hicexpl --inputFormat cool --outputFormat hicexplorer --chromosomeOrder chr5

But keep getting the following set of errors:
INFO:hicexplorer.HiCMatrix:Could not open cooler file. Maybe the path is wrong or the given node is not available.
INFO:hicexplorer.HiCMatrix:The following file was tried to open: /HiC/EXAMPLE/human.full.multi.cool
INFO:hicexplorer.HiCMatrix:The following nodes are available: [u'/resolutions/10000', u'/resolutions/100000', u'/resolutions/1000000', u'/resolutions/25000', u'/resolutions/250000', u'/resolutions/2500000', u'/resolutions/5000', u'/resolutions/50000', u'/resolutions/500000']

I have double-checked the paths and the permissions; not sure what else could be the problem here but I find it odd it seems to not be able to access the file, but know what resolutions are available in it. Any guidance would be greatly appreciated!

Thanks,
Ittai

**Comment by gtrichard** [comment]
I recommend using the develop branch `hicConverFormat`

For cool to h5, you need to specify a node that want to convert since h5 format can only contain one matrix (unlike cool or mcool).

I think you need to: 

```
hicConvertFormat -m  /HiC/EXAMPLE/human.full.multi.cool::/resolutions/10000 -o  /HiC/EXAMPLE/human.full.10kb.h5 --inputFormat cool --outputFormat h5
```

**Comment by IttaiEres** [comment]
Thanks for your helpful suggestions.

I am having a bit of trouble just getting a hicexplorer install from the develop branch, if you have any suggestions:

When trying to install from the develop branch using git with the following command:
pip install git+git://github.com/deeptools/HiCExplorer@develop

I keep getting an error:
"Collecting hicmatrix==2.2 (from HiCExplorer==2.2.dev0)
  Could not find a version that satisfies the requirement hicmatrix==2.2 (from HiCExplorer==2.2.dev0) (from versions: )
No matching distribution found for hicmatrix==2.2 (from HiCExplorer==2.2.dev0)"

I also tried to install by simply cloning the repo and then switching to the develop branch, then running python setup.py install, but received the following error:
"error in HiCExplorer setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers"

Thanks!
-Ittai

**Comment by joachimwolff** [comment]
Hi,

my apologies that you have troubles installing the development branch. However, it is 'in development' and errors are to be expected. 

To get it run:
Install the dependencies listed in the requirements.txt file in it's own conda environment with python 3.X. 
Get than the current development branch of HiCMatrix: https://github.com/deeptools/HiCMatrix and install the dependencies via requirements.txt file in this new environment,  install it via `python setup.py install`. Install now the development branch of HiCExplorer. 

Concerning your error: I cannot reproduce it, please write again if still exists after you followed my installation steps.

Best,

Joachim

**Comment by IttaiEres** [comment]
Thank you so much Joachim! This fixed everything up for me.
