### ISSUE TITLE
hicPlotTAD ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by pkubgmlixs** [deeptools/HiCExplorer#305]
I have no idea how to handle this kind of error. Could anyone help me, many thanks. Attached is my cfg file and err file.

[hicPlotTADs.err.txt](https://github.com/deeptools/HiCExplorer/files/2560208/hicPlotTADs.err.txt)
[hicPlotTADS.ini.txt](https://github.com/deeptools/HiCExplorer/files/2560209/hicPlotTADS.ini.txt)

**Comment by joachimwolff** [comment]
Hi,

I found [this](https://github.com/matplotlib/matplotlib/issues/12003) bug report with your error. Seems to be some numpy and matplotlib issue. 

They report it is working with numpy 1.14 but not 1.15.1 anymore. There is a bug fix, can you try the newest version 1.15.4 of numpy? 

Best,

Joachim

**Comment by joachimwolff** [comment]
Could you solve this issue?

**Comment by pkubgmlixs** [comment]
Yes, I have solved this issue! Many thanks!

**Comment by pkubgmlixs** [comment]
Yes, I have solved this issue! Many thanks!

2018-11-27 

李向上 



发件人：Joachim Wolff <notifications@github.com>
发送时间：2018-11-26 18:44
主题：Re: [deeptools/HiCExplorer] hicPlotTAD ValueError: negative dimensions are not allowed (#305)
收件人："deeptools/HiCExplorer"<HiCExplorer@noreply.github.com>
抄送："upleee"<17854201145@163.com>,"Author"<author@noreply.github.com>

Could you solve this issue?
