### ISSUE TITLE
hicAggregateContacts Bam file requirements

### ISSUE THREAD

**Issue by C-L-Wike** [deeptools/HiCExplorer#308]
Could I get a bit more detail on how the bed file for the ChiP-seq data was generated for the hicAggregateContacts. 

I'm confused by what this means 
"The regions specified in the BED file will be centered between half number of bins and the other half number of bins." 

Could you provide an example of the Bed file that was being used in the usage example 

thank you!

**Comment by joachimwolff** [comment]
@gtrichard Can you answer this? Unfortunately I don't have detailed knowledge of this specific script.

**Comment by gtrichard** [comment]
Dear C-L-Wike,

`hicAggregateContacts` uses regular bed files (chr start end). If the regions are more than 1bp long, then the bin at the center of these regions will be used. For example you can give peak files from MACS2 as input, then the bin overlapping the center of the peaks regions will be used, so sometimes it might be better to give the peaks summits coordinates.

Best,
Gautier
