### ISSUE TITLE
How to install development version of HiCExplorer

### ISSUE THREAD

**Issue by vanhzh** [deeptools/HiCExplorer#311]
Hi,

Thanks very much for the excellent package!  May I ask a question that might sound stupid on how to install development version?  I did the following steps:
1 > make a folder called "/data/vanhzh/f.hicExplorer"
2> Download and unzip "HiCExplorer-develop.zip" file, generating folder:
                     "/data/vanhzh/f.hicExplorer/HiCExplorer-develop"
3> Go to folder "/data/vanhzh/f.hicExplorer/HiCExplorer-develop"
4> install by "python setup.py install --prefix  /data/vanhzh/f.hicExplorer/HiCExplorer-develop"
5> Go to folder  "/data/vanhzh/f.hicExplorer/HiCExplorer-develop/bin"
6> When typing in the command "./hicConvertFormat", I get the following error message:
             Traceback (most recent call last):
             File "./hicConvertFormat", line 4, in <module>
             from hicexplorer.hicConvertFormat import main
             ImportError: No module named 'hicexplorer'
My python version is "Python 3.5.2".

In addition, I have created a environment  using conda with python 3.6.7, and installed HiCExplorer using conda way. However,  hicConverFormat command is not included in this installation.

Any helps are greatly appreciated!

Thanks very much again for the excellent package!

**Comment by joachimwolff** [comment]
Hi,

my apologies that you have troubles installing the development branch. However, it is 'in development' and errors are to be expected.

To get it run:
Install the dependencies listed in the requirements.txt file (but you have to remove pyGenomeTracks first from this list, yesterday I realized that this package is broken on conda) in it's own conda environment with python 3.X.
Swithch this new environment, install pyGenomeTracks via python setup.py install and install now the development branch of HiCExplorer.

hicConvertFormat is not included in the current 2.1.4 release, it will be in the upcoming 2.2 release.

Best,

Joachim

**Comment by vanhzh** [comment]
Hi Joachim,

Thanks very much for the detailed explanation! Now it works.

Thanks!

Zhenhua
