### ISSUE TITLE
QC only returns "same fragment" and "duplicated pairs"

### ISSUE THREAD

**Issue by GinaRe** [deeptools/HiCExplorer#315]
The discarded read pairs during hicBuildMatrix are only classified as "same fragment" and "duplicated pairs" but none of the other categories as "dangling ends" are used. This used to work in older versions of HiCExplorer.

**Comment by gtrichard** [comment]
Weirdly enough, the proportion of removed contacts is not so different:
```
                                   New           Old
Pairs used                         27,023,101    26,891,468
One mate not close to rest site    0             46,391
dangling end                       0             1,778,174
duplicated pairs                   4,004,534     4,004,534
same fragment                      5,858,286     2,440,325
self circle                        0             98,487
self ligation (removed)            0             1,626,542
Total removed                      9,862,820     9,994,453
Total pairs                        36,885,921    36,885,921
```

**Comment by joachimwolff** [comment]
What is 'current' and what is 'old' version? 2.2beta and 2.1.4?

**Comment by GinaRe** [comment]
So what we figured out is that you need to give all the following options:
--restrictionCutFile ../DpnII.bed (required argument)
-seq GATC --danglingSequence GATC (both optional arguments)
The QC for restriction fragment resolution works like this (I tested version 1.8.1 and 2.1.4). 
We need to adjust the QC for fixed bin size matrices because usually you would not provide information about the restriction enzyme and thus one does not get all the QC about e.g. dangling ends.

**Comment by joachimwolff** [comment]
We change the output of QC report with the last release. Please check if it still an issue and if yes, reopen with a description.
