### ISSUE TITLE
plot TAD tracks

### ISSUE THREAD

**Issue by zhixuqiu** [deeptools/HiCExplorer#318]
I found  a function in the script "trackPlot.py" , which can add links track and be imported  by "hicPlotTADs.py". But I don't know how to use. Could you share  a Configuration file template with me?
The function 'PlotArcs' was located in "trackPlot.py" .
```python
elif properties['file_type'] == 'hic_matrix':
	self.track_obj_list.append(PlotHiCMatrix(properties, p_region=p_region))
elif properties['file_type'] == 'bed':
	self.track_obj_list.append(PlotBed(properties))
elif properties['file_type'] == 'links':
	self.track_obj_list.append(PlotArcs(properties))
```

**Comment by gtrichard** [comment]
Dear @zhixuqiu ,

What you are looking for is this portion of the documentation : 
```
# You can also show the interactions as arcs between start and end bins.
# for this simply write the interactions in the Ginteraction format (HiCExport)
# and add the file here

[interactions]
file = Ginteractions.tsv
file_type = links
width =  10
color = black
title = HAS manual interactions
line width = 1
```

The ` Ginteractions.tsv` file should look like:
```
chr2   1500  3000   chr2    15000   16500   78.24
chr2   1500  3000   chr2    16500   18000   23.45
```

For more detailled information, please check pyGenomeTracks, which is the standalone version of hicPlotTADs (which is a bit more complete also and not only orientated towards Hi-C) :
https://github.com/deeptools/pyGenomeTracks

**Comment by gtrichard** [comment]
Might be weird, but can you try this:

rename ` testloop.tsv` in ` testloop.arcs` and try:
```
[test arcs]
file = testloop.arcs
line width = 3
title = HAS manual interactions
height = 3
```

For a quick fix, using pyGenomeTracks with these parameters will fix your issue for sure, now we need to check what is happening with hicPlotTADs.

**Comment by zhixuqiu** [comment]
> Dear @zhixuqiu ,
> 
> What you are looking for is this portion of the documentation :
> 
> ```
> # You can also show the interactions as arcs between start and end bins.
> # for this simply write the interactions in the Ginteraction format (HiCExport)
> # and add the file here
> 
> [interactions]
> file = Ginteractions.tsv
> file_type = links
> width =  10
> color = black
> title = HAS manual interactions
> line width = 1
> ```
> The ` Ginteractions.tsv` file should look like (the score is needed, even though it will not be used by the plotting tool if I remember well, you can put a mock score if needed):
> 
> ```
> chr2   1500  3000   chr2    15000   16500   78.24
> chr2   1500  3000   chr2    16500   18000   23.45
> ```
> For more detailled information, please check pyGenomeTracks, which is the standalone version of hicPlotTADs (which is a bit more complete also and not only orientated towards Hi-C) :
> https://github.com/deeptools/pyGenomeTracks



> Dear @zhixuqiu ,
> 
> What you are looking for is this portion of the documentation :
> 
> ```
> # You can also show the interactions as arcs between start and end bins.
> # for this simply write the interactions in the Ginteraction format (HiCExport)
> # and add the file here
> 
> [interactions]
> file = Ginteractions.tsv
> file_type = links
> width =  10
> color = black
> title = HAS manual interactions
> line width = 1
> ```
> The ` Ginteractions.tsv` file should look like (the score is needed, even though it will not be used by the plotting tool if I remember well, you can put a mock score if needed):
> 
> ```
> chr2   1500  3000   chr2    15000   16500   78.24
> chr2   1500  3000   chr2    16500   18000   23.45
> ```
> For more detailled information, please check pyGenomeTracks, which is the standalone version of hicPlotTADs (which is a bit more complete also and not only orientated towards Hi-C) :
> https://github.com/deeptools/pyGenomeTracks



> Might be weird, but can you try this:
> 
> rename ` testloop.tsv` in ` testloop.arcs` and try:
> 
> ```
> [test arcs]
> file = testloop.arcs
> line width = 3
> title = HAS manual interactions
> height = 3
> ```
> For a quick fix, using pyGenomeTracks with these parameters will fix your issue for sure, now we need to check what is happening with hicPlotTADs.
> 
> Which version of HiCExplorer are you using?

My HiCExplorer's version is  2.1.1.  Thanks for your suggestion! I have tried to run pyGenomeTracks, which can plot arc track. But I want to display arc track in HiCBrowser which generated the track by importing module "trackPlot.py" from HiCExplorer.  The module "trackPlot.py" was also imported by hicPlotTADs. So I think  I should plot arc track by uing HiCExplorer.

**Comment by joachimwolff** [comment]
I apologize for the confusion. We reorganize the source code of HiCExplorer and it's 'spin-offs' pyGenomeTracks, HiCMatrix and HiCBrowser at the moment. trackPlot.py will be no longer part of HiCExplorer, we moved it to pyGenomeTracks. But this change was not applied so far on HiCBrowser. At the same time bug fixes and further development of trackPlot is only done now in pyGenomeTracks. Therefore it happens that features don't work in HiCBrowser but they do in pyGenomeTracks.

**Comment by joachimwolff** [comment]
Hi,

thanks for your contribution. To add these changes to our 2.1 release, could you fork HiCExplorer, create a new branch based on current master and create a pull request? In this way we can keep better track of changes and who contributed what.

Thanks a lot,

Joachim

**Comment by zhixuqiu** [comment]
> Hi,
> 
> thanks for your contribution. To add these changes to our 2.1 release, could you fork HiCExplorer, create a new branch based on current master and create a pull request? In this way we can keep better track of changes and who contributed what.
> 
> Thanks a lot,
> 
> Joachim
Hi,
Joachim, I am happy to give it a try, after the follow-up of my project is OK. This may take some time.
