### ISSUE TITLE
Invalid: 'type = lines' When I want to plot the result of TAD.

### ISSUE THREAD

**Issue by TXM1230** [deeptools/HiCExplorer#319]
I just follow the "Hi-C analysis of mouse ESCs using HiCExplorer" but when I try to use
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/30117630/49536549-c3cbd880-f901-11e8-8e36-70815f36c836.png">
I just get this.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/30117630/49536579-db0ac600-f901-11e8-9b17-316cb0af7d71.png">

so I delete the "type = lines", then try again, this time I got a pdf, but there is not TAD, it's just like this
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/30117630/49536669-0db4be80-f902-11e8-86bc-56794022500d.png">
So how can I get a right pdf?

**Comment by TXM1230** [comment]
My track.ini is 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/30117630/49536769-4359a780-f902-11e8-9270-d91bb115027e.png">

I think there is no mistake.

**Comment by joachimwolff** [comment]
Hi,

you use the beta version of release 2.2, but the documentation is for the stable version 2.1.4 and not updated to 2.2 so far.

Things you can do: 

- Downgrade to stable version 2.1.4
- Stay at 2.2beta version and change in the init file the [hic] section to:

```
[hic]
file = hicMatrix/replicateMerged.Corrected_20kb.h5
title = your title
colormap = RdYlBu_r
depth = 2000000
transform = log1p
x labels = yes
file_type = hic_matrix
height = 5

[tads]
file = domains.bed
file_type = domains
border color = black
color = none
height = 5
line width = 1.5
overlay previous = share-y
show data range = no
```
Please replace `width` with `height` in all your tracks.

**Comment by joachimwolff** [comment]
Hi Xinming,

to install it via conda use: `conda install hicexplorer=2.1.4`

The documentation is for 2.1.4 only, we work atm on the updated version for 2.2.

Best,

Joachim

**Comment by TXM1230** [comment]
Thank you so much!!
Looking forward the new documentation!
