### ISSUE TITLE
proposed improvement for HiCplotTADs

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#320]
Hi,
I put back my comments which were related to HiCExplorer:
the possibility to plot the normalized count of the matrices (not only log transformed data).
the possibility to auto-width the matrices in order to have square bins (not diamond).
Thanks,

Lucille

**Comment by gtrichard** [comment]
Hi Lucille,

I think what you are looking for is 
```
hicNormalize --normalize smallest -m mat1.h5 mat2.h5
hicPlotMatrix -m mat1.h5
hicPlotMatrix -m mat2.h5
```

**Comment by lldelisle** [comment]
Hi,
My goal is to plot matrices **not in log scale** above multiple tracks like ChIP or annotations. So I need to use hicPlotTADs but when I use this function:
1) I cannot plot values which are not log
2) I need to do a lot of tries before finding the good height of the Hi-C tracks to obtain square bins. I think it would be nice if we could specify in the height of the track "adaptable to make square bins" or something like this.

**Comment by lldelisle** [comment]
You can close this issue.
Thanks
