### ISSUE TITLE
hicPlotTADs outputs multiple plots in the same file

### ISSUE THREAD

**Issue by benxiahu** [deeptools/HiCExplorer#325]
I have four Hi-C datasets, and I want to make four plots of TADs in the same file. So hicPlotTADs could do that?

**Comment by LeilyR** [comment]
Yes, it can generate figures with several tracks.

**Comment by benxiahu** [comment]
Hi Leily, 
 Thanks for your immediate reply. What I want to do is to make multiple plots in the same PDF file lik this one 
![default](https://user-images.githubusercontent.com/12387462/50478982-0cf9de80-0a0f-11e9-9116-a593a02f7110.png).
Thanks in advance!
Best,
.

**Comment by joachimwolff** [comment]
Hi,

See https://hicexplorer.readthedocs.io/en/latest/content/tools/hicFindTADs.html#hicfindtads

Please use the current master version of HiCExplorer 2.1.4.

Best,

Joachim

**Comment by benxiahu** [comment]
Thanks a lot. Another question, How could I get this bed file? 
![default](https://user-images.githubusercontent.com/12387462/50481532-14c07f80-0a1d-11e9-95ca-1a7654a59c8c.png)
Is the bed file from UCSC suitable for the hicplotTADs?

**Comment by joachimwolff** [comment]
It depends on your used reference genome. If you mapped against UCSC than you have to use a genome tracks file from UCSC, the same is valid for ensembl.

**Comment by benxiahu** [comment]
koay. Thanks for your help. Recently, we want to use HiCExplorer to analyze FIREs. Do you think that it is fine? Best,

**Comment by gtrichard** [comment]
@benxiahu you need to make a bed file with the gene names using biomart instead of the gene ID.

https://www.ensembl.org/biomart/martview/fcaaadf8eb69b00e495b7e7d94eeb259

**Comment by benxiahu** [comment]
![default](https://user-images.githubusercontent.com/12387462/51043042-acff5c80-15f8-11e9-8b0b-f66ff1151b28.png)
here is the gene bed file. It is super odd that several gene symbols were printed in the plots for TADs, while other gene symbols were not. like this one 
![default](https://user-images.githubusercontent.com/12387462/51043157-f64fac00-15f8-11e9-9dea-ba88d1afd473.png)

**Comment by gtrichard** [comment]
This corresponds to isoforms.

For simpler representations, you can keep the longest isoform.

**Comment by benxiahu** [comment]
yes, I did zoom the PDF file, but I got the same problem. 
![default](https://user-images.githubusercontent.com/12387462/51044367-eb4a4b00-15fb-11e9-87ca-04673d4f48ce.png)
Is it right?

**Comment by gtrichard** [comment]
font_size should be higher I guess? Like, 10?

You can find examples here:
https://github.com/deeptools/pyGenomeTracks

**Comment by benxiahu** [comment]
I modified the font_size to be 20, but I got the same result.
![default](https://user-images.githubusercontent.com/12387462/51066548-d1cdf100-1645-11e9-9d0f-35a91a8b9ac8.png)
