### ISSUE TITLE
which matrix (raw or iced) when covert hicpro to hicexplorer

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#326]
Hi :
   I want to convert hicpro to hicexplorer , but  there are two matrix (raw matrix and iced matrix) in the results of hicpro , but I'm not sure which matrix I should use . Could you give me some advice ?
   Thanks a lot !
Best !

**Comment by MzwaneleN** [comment]
Hi @QianzhaoJ did you find answer to this?

**Comment by QianzhaoJ** [comment]
When  convert hicpro to hicexplorer , hicexplorer will not change the Original data. You can use "raw" matrix ,and then run "hicCorrectMatrix" or You can Directly use "iced" matrix .

**Comment by MzwaneleN** [comment]
Thanks
