### ISSUE TITLE
when I want to use hicFindEnrichedContacts to find the enrich  interaction ,I can't fiand which parameter for input? 

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#327]
hicFindEnrichedContacts --outFileName OUTFILENAME --method
                               {z-score,obs/exp} [--perchr] [--skipDiagonal]
                               [--depth DEPTH] [--help] [--version]
can you give me an example to show use this function?

**Comment by gtrichard** [comment]
Dear @hzaumsq , thanks for using HiCExplorer.

hicFindEnrichedContacts can be used to convert a matrix to z-score or obs/exp matrix using the following:
```
hicFindEnrichedContacts --matrix data.h5 --outFileName data_z-score.h5 --method z-score --depth 20000000
```

will output a z-score matrix with bins separated at most by 20 million nucleotides.

**Comment by hzaumsq** [comment]
hicFindEnrichedContacts --matrix egg_vs_J2_10k.h5 --outFileName enrich.h5 --method z-score --depth 20000000
usage: hicFindEnrichedContacts --outFileName OUTFILENAME --method
                               {z-score,obs/exp} [--perchr] [--skipDiagonal]
                               [--depth DEPTH] [--help] [--version]
hicFindEnrichedContacts: error: unrecognized arguments: --matrix egg_vs_J2_10k.h5

**Comment by hzaumsq** [comment]
The same error as follow： hicFindEnrichedContacts --matrix egg_vs_J2_10k.h5 --outFileName enrich.h5 --method z-score --depth 20000000
usage: hicFindEnrichedContacts --outFileName OUTFILENAME --method
                               {z-score,obs/exp} [--perchr] [--skipDiagonal]
                               [--depth DEPTH] [--help] [--version]
hicFindEnrichedContacts: error: unrecognized arguments: --matrix egg_vs_J2_10k.h5

**Comment by gtrichard** [comment]
Are you on the master branch? I tried with the release22beta branch and it was working. With this branch executing `hicFindEnrichedContacts` gives:
```
usage: hicFindEnrichedContacts --matrix MATRIX --outFileName OUTFILENAME
                               --method {z-score,obs/exp} [--perchr]
                               [--skipDiagonal] [--maxDepth MAXDEPTH] [--help]
                               [--version]
```

Where `--matrix` is required.
