### ISSUE TITLE
hicAverageRegions input bed file 

### ISSUE THREAD

**Issue by GinaRe** [deeptools/HiCExplorer#334]
hicAverageRegions does not work using a regular bed file format (chr start end) but only in the format (chr start). The runtime using more than 100 regions is more than 10 min.

**Comment by joachimwolff** [comment]
@GinaRe Can you check if it is better now with a) the regular bed file issue and b) the performance? Thanks a lot!

**Comment by GinaRe** [comment]
In which branch?

**Comment by joachimwolff** [comment]
hicAverageRegions_fix

**Comment by joachimwolff** [comment]
Should be fixed with release 3.3.
