### ISSUE TITLE
Question about hicAggregateContacts

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#338]
Hi  
I want to plot enriched contacts (or loops) in hicexplorer , just like **Aggregate Peak Analysis** in [juicer](https://github.com/aidenlab/juicer/wiki/APA) . I think the function **hicAggregateContacts** is similar with  **Aggregate Peak Analysis** . Can I use the tool  **hicAggregateContacts** to get it ?
Could you give some advice?
Thanks for your time !

Best
Qianzhao

**Comment by gtrichard** [comment]
Dear @QianzhaoJ ,

Yes `hicAggregateContacts` is the same analysis as "APA" of Juicer. Currently the tool is only working per chromosome, a `--genome` option is available in the `aggregateGenome` branch and should be available in the master branch soon.

**Comment by QianzhaoJ** [comment]
Thanks for so quick reply ! 
But Could you tell me more about the format of necessary **bed** file?
Maybe it's like `chr  start  end  chr  start  end  value` ?
Thanks again !
Qianzhao

**Comment by Kurotakid** [comment]
Hi gtrichard,
How can I use "aggregateGenome" branch in the hicexplorer? I want to use "hicAggregateContacts" in a whole genome but not each chromosome. 
Thank you!
Daisuke

**Comment by gtrichard** [comment]
Dear @Kurotakid 

The best way is to have the HiCExplorer installed by conda.

Then you can:

```
git clone https://github.com/deeptools/HiCExplorer/
cd HiCExplorer
git checkout aggregateGenome
hicex_git_dir=$(pwd)
export PATH=$hicex_git_dir/bin:$PATH
export PYTHONPATH=$hicex_git_dir:$PYTHONPATH
```

Verify that the right `hicAggregateContacts` is called by:
```
which hicAggregateContacts
```

It should be the one for the newly cloned git repository where you loaded the `aggregateGenome` branch.
