### ISSUE TITLE
hicAdjustMatrix new mode: `keepByMasking`

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#341]
`hicAdjustMatrix` is currently removing bins when `--action keep` is specified. If someone uses a BED file of many regions within a chromosome, the adjusted matrix plotting is broken.

Therefore, `hicAdjustMatrix` should have 4 modes:

```
keepByMasking
keepByDeleting
removeByMasking
removeByDeleting
```

Although I'm not sure that `keepByDeleting` has many interest.

**Comment by LeilyR** [comment]
@gtrichard why cannot you use --action mask for that matter?
