### ISSUE TITLE
hicPCA should ignore masked bins

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#342]
Currently `hicPCA` is defining maskedBins as 0 I guess, maskedBins should be instead removed of the PCA computation as the resulting scores can be influenced by maskedBins, while we don't have any information for those.

The bedgraph would have "holes" but this is not an issue.

**Comment by joachimwolff** [comment]
Hi,

I implemented in the same way the masked bins are handled in hicPlotMatrix. Does this work for you?

Best,

Joachim
