### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by hwick** [deeptools/HiCExplorer#344]
Hello,
I am getting a unicode error similar to the one that appears in issue #174 when trying to run hicBuildMatrix. None of my file names have non-ASCII/non-standard characters as far as I am aware, though, so I'm unsure what the origin of the error is (the author of #174 got around it by omitting a title, which does not seem relevant in this case):

```
hicBuildMatrix --samFiles /path/to/Ctrl_R1_hg19.bwt2merged.bam /path/to/Ctrl_R2_hg19.bwt2merged.bam \
                 --binSize 10000 \
                 --restrictionSequence AAGCTT \
                 --threads 4 \
                 --inputBufferSize 100000 \
                 --outBam /path/to/Ctrl.bam \
                 -o /path/to/Ctrl_matrix.h5 \
                 --QCfolder /path/to/hicQC
```
error:
```
Traceback (most recent call last):
  File "/cm/shared/jhmi/apps/HiCExplorer/python2.7.6/64/2.0/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/cm/shared/jhmi/apps/python/gcc/64/2.7.6/lib/python2.7/site-packages/hicexplorer/hicBuildMatrix.py", line 1465, in main
    QC.main("-l {} -o {}".format(log_file_name, args.QCfolder).split())
  File "/cm/shared/jhmi/apps/python/gcc/64/2.7.6/lib/python2.7/site-packages/hicexplorer/hicPrepareQCreport.py", line 284, in main
    read_orientation_table, table)
  File "/cm/shared/jhmi/apps/python/gcc/64/2.7.6/lib/python2.7/site-packages/hicexplorer/hicPrepareQCreport.py", line 65, in save_html
    .format(lambda x: '{:,}'.format(x) if x > 1 else '{:.2%}'.format(x)).render())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1241: ordinal not in range(128)
```

I saw that a related ascii error was fixed for a different HiCExplorer function in #175, but perhaps not for this/other functions? Please advise how to resolve this error. Thanks,
~ Heather

**Comment by joachimwolff** [comment]
Hi Heather,

Two remarks:
- Which version of HiCExplorer do you use? Please check if you use the up-to-date 2.2 version.
- Can you try the Python 3 version of HiCExplorer to see if the works here? We will drop Python 2 support with the next release, and bugs appearing only in Python 2 won't be fixed anymore.

Best,

Joachim

**Comment by hwick** [comment]
I am using version 2.1. I will try to update to version 2.2 using python 3 and rerun.

**Comment by joachimwolff** [comment]
Could you solve the issue?

**Comment by hwick** [comment]
Hi,
We could not get pip to install version 2.2, so we installed 2.1.1 on python 3 and reran. We ran into this error:
```
Traceback (most recent call last):
  File "/cm/shared/jhmi/apps/HiCExplorer/python3.5.6/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/cm/shared/jhmi/apps/python3.5.6/lib/python3.5/site-packages/hicexplorer/hicBuildMatrix.py", line 1465, in main
    QC.main("-l {} -o {}".format(log_file_name, args.QCfolder).split())
  File "/cm/shared/jhmi/apps/python3.5.6/lib/python3.5/site-packages/hicexplorer/hicPrepareQCreport.py", line 284, in main
    read_orientation_table, table)
  File "/cm/shared/jhmi/apps/python3.5.6/lib/python3.5/site-packages/hicexplorer/hicPrepareQCreport.py", line 61, in save_html
    html = open(os.path.join(root, "qc_template.html"), "r")
FileNotFoundError: [Errno 2] No such file or directory: '/cm/shared/jhmi/apps/python3.5.6/lib/python3.5/site-packages/hicexplorer/qc_template.html'
```

We had gotten this same error before switching to python 3, and worked around it by manually downloading qc_template.html and moving it to the proper folder, so we have done that and are currently rerunning with the hopes that both this and the ascii error goes away with this run (if not, we will have to figure out some way to install 2.2)

**Comment by joachimwolff** [comment]
Hi,

I have to apologize, the pip version is not that well updated from our side. I will try to update this soon. However, we prefer to use `conda` and in the `bioconda` channel the newest HiCExplorer version is always available. See http://bioconda.github.io/#using-bioconda 

Best,

Joachim

**Comment by joachimwolff** [comment]
Hi,

I updated the Python 2 version in pip to 2.2.1. Please let me know if it works and solves your issues.

Best,

Joachim
