### ISSUE TITLE
PCR duplicates identification

### ISSUE THREAD

**Issue by abhisheksinghnl** [deeptools/HiCExplorer#355]
Hi,

My senior really wants to know, how PCR duplicates are computed in Hi-C explorer. Could someone please, explain this. 

Roughly, I tried to put it through that hic explorer uses picard tools (MarkDuplicates or MarkDuplicatesWithMateCigar) to mark these and then samtools to remove.

The thing is bench scientist is worried to see soo many duplicates ;)

Could some please confirm or explain bit.

Thanks in advance.

**Comment by joachimwolff** [comment]
Hi,

we store a set of tuples (chromname, position) and if we detect an identical position it is considered as a PCR duplicate.

See: 
https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicBuildMatrix.py#L56
https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicBuildMatrix.py#L73
https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicBuildMatrix.py#L733

I hope I could help.

Best,

Joachim

**Comment by abhisheksinghnl** [comment]
Hi Joachim,

I will try to convince him :)

Thanks
