### ISSUE TITLE
diagnostic_plot

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#357]
Hi,
I'm a second year phd student in NYU in Ercan lab. We are trying to analyze published data using hicexplorer. 

We are currently using **hicexplorer/2.2b**. We generated .h5 matrix using the following:
hicBuildMatrix --samFiles N2B1T1_X_X_R1_X.bam N2B1T1_X_X_R2_X.bam \
	--binSize 10000 \
	--restrictionSequence GATC \
	--threads 4 \
	--inputBufferSize 100000 \
	--outBam hic_2017B1T1.bam \
	-o 2017B1T1.h5 \
	--QCfolder ./hicQC_2017B1T1

When we try to get the diagnostic plot using:
hicCorrectMatrix diagnostic_plot --matrix 2017B1T1.h5 -o diagnostic_2017B1T1.png

I get the following error:
 File "/share/apps/hicexplorer/2.2b/lib/python3.6/site-packages/hicexplorer/utilities.py", line 489, in check_cooler
    if pFileName.endswith('.cool') or cooler.io.is_cooler(pFileName) or'.mcool' in pFileName:
AttributeError: module 'cooler.create' has no attribute 'is_cooler'

I tried converting .h5 into .cool using hicConvertFormat, and then using the .cool file to get the diagnostic plot. It gives me the following error:
  File "/share/apps/hicexplorer/2.2b/lib/python3.6/site-packages/hicmatrix/lib/cool.py", line 61, in load
    data[start_pos:start_pos + len(_data)] = _data
ValueError: could not broadcast input array from shape (319163) into shape (249163)

But, if we take 2017B1T1.h5 file and bring it to hicexplorer.usegalaxy.eu, diagnostic_plot works. We would like to be able to do everything on command line. Could you help us out? Thanks! - Jun Kim

**Comment by joachimwolff** [comment]
Hi,

from your comment I guess you use the 2.2 beta version of HiCExplorer. In the meantime the cooler lib had some changes and I guess your error is created somehow by a mixture of different versions. 

Please try the installation with conda and bioconda, use HiCExplorer in its own environment:

`conda create --name hicexplorer2.2.1 python=3.6 hicexplorer=2.2.1`

and activate the environment with `source activate hicexplorer2.2.1`.

I hope this will resolve your issues.

Best,

Joachim

**Comment by joachimwolff** [comment]
However, you can create a coole file with hicBuildMatrix too.

**Comment by kimj50** [comment]
thank you !
