### ISSUE TITLE
hiChIP data suitable for HiCExplorer?

### ISSUE THREAD

**Issue by simjbaum** [deeptools/HiCExplorer#358]
Dear all,
great tool. I already loved deeptools2. We have some hiChIP data (method: https://www.ncbi.nlm.nih.gov/pubmed/27643841) and I was wondering if you would see some reasons we should not try to analyze our data with the HiCExplorer? Are there some limitations/ problems/ issues when I would analyze the hiChIP data?
Best,
Simon

**Comment by joachimwolff** [comment]
Hi,

Given details in the link I would say it is worth a try. It seems you still have chimeric reads therefore it could work. You have to be careful with the parameters, maybe you need to adjust them.

Any thought on this @bgruening?

Best,

Joachim

**Comment by bgruening** [comment]
This should be possible, but we haven't yet any specific documentation about it.
Afaik @rgilsbach has already analyzed this kind of data with hicexplorer.

**Comment by DonStephano** [comment]
Should work, depending a little bit which modification/protein you HiChIPed. I used published HiChIP-data from the Mumbach-paper (27ac-HiChIP) but only to build a Matrix and to plot a few regions. I think it really depends on the question and kind of HiChIP. And of course on the seq-depth

**Comment by DonStephano** [comment]
@joachimwolff: depending on the HiChIPed modification, i.e. 27ac/4me3/CTCF it's more or less similar to Promotor Capture Hi-C data and analysis...
