### ISSUE TITLE
hicMergeTADbins is missing

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#363]
Hi :
I installed HiCExplorer using `conda` and the version is 2.2 .
I want to use the function `hicMergeTADbins` ,But I found the command is missing . When I typed `hicexplorer -h`  , I looked 

> The following is the list of tools:
   findRestSites            Identifies the genomic locations of restriction sites
   hicBuildMatrix           Creates a Hi-C matrix using the aligned BAM files of the Hi-C sequencing reads
   hicQC                    Plots QC measures from the output of hicBuildMatrix
   hicCorrectMatrix         Uses iterative correction to remove biases from a Hi-C matrix
   hicFindEnrichedContacts  Identifies enriched Hi-C contacts
   hicCorrelate             Computes and visualizes the correlation of Hi-C matrices
   hicFindTADs	            Identifies Topologically Associating Domains (TADs)
   hicMergeMatrixBins	    Merges consecutive bins on a Hi-C matrix to reduce resolution
   hicPCA                   Computes the principal components (eigenvectors) for A/B compartment analysis
   hicTransform             Computes obs_exp (like Lieberman-Aiden), pearson and covariance matrix for A/B compartment analysis
   hicPlotDistVsCounts	    Plot the decay in interaction frequency with distance
   hicPlotMatrix	        Plots a Hi-C matrix as a heatmap and can add a pca track to it
   hicPlotTADs	            Plots TADs as a track that can be combined with other tracks (genes, signal, interactions)
   hicPlotViewpoint         Plots the number of interactions around a reference point
   hicSumMatrices	        Adds Hi-C matrices of the same size
   hicPlotDistVsCounts	    Plots distance vs. Hi-C counts of corrected data
   hicInfo                  Shows information about a Hi-C matrix (no. of bins, bin length, sum, max, min, etc)
   hicCompareMatrices       Computes difference or ratio between two matrices
   hicAdjustMatrix          Remove, keep or mask specific regions in a matrix
   hicAverageRegions        Sum up defined reference points and a range up/downstream of it. Useful for TAD analysis
   hicPlotAverageRegions    Plot tool for hicAverageRegions
   hicNormalize             Normalizes matrices to 0 1 range or to lowest read coverage
   hicConvertFormat         Converter for different interaction matrix file formats.

`hicMergeTADbins` doesn't exist .
It is so confusing because I find `hicMergeTADbins` in github , may be I should install it from github ?
Many thanks !

**Comment by joachimwolff** [comment]
Hi,

this script is from the previous main developers of HiCExplorer, it was created back in November 16 but was never added to 'setup.py' and is therefore missing. There are no test cases for this tool too, which means I cannot tell you if this is some working script and it was simply not added to setup.py or it was accidentally merged to master. Could be there are some issues with Python 3 too.

I think it is the best to use it from github and test it on your own if it works, any feedback is welcome.

Best,

Joachim
