### ISSUE TITLE
Question about hicBuildMatrix

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#367]
Hello,

When I run the function hicBuildMatrix, it works fine and generates the interaction matrices and the qc reports. However, when I look the the output log file, it has the following error in the last line 'INFO:hicmatrix.HiCMatrix:Only init object, no matrix given.'  While I am getting the correct output files, this error makes me wonder if the command ran successfully or not? Would appreciate any ideas on what might be going on.

Looking at some previous questions it seems that this problem can arise if the output file name does not have the correct extension but I have tried it with both .h5 and .cool but have the same problem. I am not running the commands on my own data but on sample data exactly as described in the example on the tutorial website (https://hicexplorer.readthedocs.io/en/latest/content/mES-HiC_analysis.html# ) so the problem is probably not in the data. 

The command I am using is:

hicBuildMatrix --samFiles SRR1956527_1.bam SRR1956527_2.bam --binSize 10000 --restrictionSequence GATC --outBam SRR1956527_ref.bam --outFileName hicMatrix/SRR1956527_10kb.h5 --QCfolder hicMatrix/SRR1956527_10kb_QC --threads 8 --inputBufferSize 400000

So should I just ignore the error or is it a problem?

Thanks

**Comment by joachimwolff** [comment]
Hi, 

Don‘t worry, you can ignore this message.

It simply means the HiCMatrix library, which handels all I/O, did not get any matrix to open (read). This is how it should be with hicBuildMatrix, you create an interaction matrix and write it to disk.

Maybe I will mute this output in the future, it causes more confusion than actual usage for the most users.

Best,

Joachim

**Comment by re2srm** [comment]
Great. 

Thanks!
