### ISSUE TITLE
Analyzing library cut with two restriction enzymes

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#372]
Hello,

The data I am analyzing was processed with two restriction enzymes which cut at: ^GATC and G^ANTC. Since the HicBuildMatrix command only accepts one restriction site how do I go about this? 

Also as both restriction sequence and restrictioncutfile are optional arguments for building the matrix, I was also curious how the results would be different if I dont supply the either of these arguments? 

Thanks

**Comment by LeilyR** [comment]
you could merge the two bed files you get after running `findResSite` twice on each of your restriction enzymes.

**Comment by re2srm** [comment]
Thanks, I will try that.  However, if I provide the merged bed file using the --restrictionCutFile option, do I build the matrix without specifying the --restrictionSequence (since this option does not accept two restriction sites)?

**Comment by LeilyR** [comment]
It should work without providing the --restrictionSequence.

**Comment by re2srm** [comment]
Thanks I merged the bed files and it seems to be working but I am still confused if the way I am merging the files is the right way to do this. I am merging the two bed files produced by the findResSite command like this:

cat file1.bed file2.bed | uniq > merged.bed
bedtools sort -i merged.bed

Do you think this is the correct way to merge the files? My understanding is that the bed file produced by  findResSite contains the coordinates of all restriction sites so simply concatenating the files and taking the unique value should work.

Thanks

**Comment by re2srm** [comment]
Also issue #315 seems to imply that not providing the restrictionSequence and danglingends would affect QC results output but the actual matrix would still be produced correctly? 

Since the restrictionSequence and danglindends aruments wont accept two inputs for two enzymes I cannot include them in the command.

**Comment by LeilyR** [comment]
If your enzymes are having non overlapping cut sites, which I assume they are, your approach should work and you shouldn't need to look for the unique sites since they are already unique. However, if your cut sites are overlapped you might need to properly merge your bed file but I am afraid it would affect your analysis. Please check if your cut sites are not overlapping with each other. 
Also, about the QC question that you have asked, you are right. It only affects your QC reports.

**Comment by re2srm** [comment]
Thanks a lot for the clarification. I have checked that my restriction sites are non-overlapping and was able to build the matrices using the merged bed file.

Also one last question I have is that can the buildmatrix function correctly generate a fixed bin matrix for my data? In other words if construct a fixed bin matrix without providing the bed file or optional arguments, the matrix would still be constructed correctly irrespective of whether is was cut with one or two restriction enzymes and only the QC reports would be affected?

**Comment by LeilyR** [comment]
Glad it helped.
yes, you are right.

**Comment by re2srm** [comment]
Great. Thanks!
