### ISSUE TITLE
what makes  TAD and TAD boundary so different？

### ISSUE THREAD

**Issue by Epigenetics-Wang** [deeptools/HiCExplorer#374]
Hi，team
Thanks for the HiCExplorer，so powerful tools for HiC data！
Recently I download the HiC data from NCBI which has been published for practicing analysis TAD，i get the result by using hicFindTADs（parameters：hicFindTADs --matrix HiC_matrix_20k_corrected.h5 --minDepth 60000 --maxDepth 200000 --numberOfProcessors 64 --step 20000 --outPrefix TAD-rice-20k-Bins --minBoundaryDistance 150000 --correctForMultipleTesting fdr --threshold 0.05 --delta 0.001). 
![rice-chr1-TADs20](https://user-images.githubusercontent.com/48174571/56287167-3c636100-614e-11e9-8404-6d10449945bd.png)

But i found my result is so different with the result from the published paper. especially the position of the TAD boundary.
This is the result from the published paper:

![published](https://user-images.githubusercontent.com/48174571/56287414-d5927780-614e-11e9-9ab1-697f5cde52a3.png)

So, can you give me some advice about how to solve this problem  or which parameter led to this result. Thank you very much.

Sincerely!

**Comment by LeilyR** [comment]
Really difficult to say based on the info you have provided. Did they call TADs on the same resolution matrix as you did (20kb matrix)? Do you know the parameters they have used? Can you send the link to the published paper?
