### ISSUE TITLE
hicAggregateContacts question

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#376]
Hello,
I am having some trouble understanding the  the hicAggregateContacts function and if it is supposed to be used for the type of anlaysis I am trying to do or not. I have a list of genes in a bed file and I am interested in finding out if area around these genes is enriched for interactions in my treatment sample vs my control sample. 

When I run the following command I get an error:

hicAggregateContacts --matrix WT_Merged_rest.h5 --BED genes.bed
--outFileName aggregate_Contacts \
--range 300000:1000000 --numberOfBins 30 \
--avgType mean --transform obs/exp

Error:
hicAggregateContacts:No valid submatrices were found for chrom: chr6
Traceback (most recent call last):
  File "/scratch/gencore/software/hicexplorer/bin/hicAggregateContacts", line 7, in <module>
    main()
  File "/scratch/gencore/software/hicexplorer/lib/python2.7/site-packages/hicexplorer/hicAggregateContacts.py", line 638, in main
    format(over_1_5, float(over_1_5) / len(chrom_matrix[chrom])))
KeyError: 'chr6'

I have tried running the command using different bin sizes but i get similar errors where no valid matrix is detected for a  chromosome and I was wondering what that means? Is it because my data is not deep enough and can I get around this by changing any parameters like bin size, range or no of bins? My understanding is that even if there are no contacts for a given gene region, the function  should still be able to plot the average of other regions.  

Also just to make sure I understand this command correctly, if I use a 5kb matrix and specify the no of bins as 10, this will average contacts in a 25kb window on each side of my target region only using contacts that fall within the distance specified by the range. 

Thanks

**Comment by gtrichard** [comment]
Hello @re2srm  and thank you for using HiCExplorer,

You can try the same command but limiting it to something else than chr6 with `--chromosomes chr2` for instance?

Currently, hicAggregateContacts crashes when regions in a given chromosome do not produce valid submatrices. In a future patch it will just throw a warning and the problematic chromosomes will be removed for the analysis.

It might happen if you only have very few regions on the chr6, or if they are too close or too far away from each other given your range.

For your understanding of the method, you are right, although contacts between genes might or might not aggregate... TAD boundaries is a nice starter to get a hang on the hicAggregateContacts analysis (setting up the range and the bins size, although is might need to be adjusted for other regions sets).

**Comment by re2srm** [comment]
Thanks for the clarification. However, I still don't think I am using the function and especially the range parameter correctly. 

For example, lets say I am interested in the enrichment of contacts around a gene that is located on chr1. In this case the majority of contacts are expected to be intrachromosomal so most probably there will be few or no contacts with chr6 or with most other chromosomes other than the one on which the gene is located. And even if there are contacts with other chromosomes they will most likely be beyond the distance specified by the range parameter so wouldnt they be excluded anyway before the error arises?  

Thanks

**Comment by gtrichard** [comment]
`hicAggregateContacts` is only analysing intrachromosomal contacts, interchromosomal contacts are not part of the analysis.

As for your usage of the tool to answer your question:  

> if area around these genes is enriched for interactions in my treatment sample vs my control sample.
> lets say I am interested in the enrichment of contacts around a gene that is located on chr1.

`hicAggregateContacts` is used to look at long range interactions, to see if a group of regions are in proximity or not (forming spatial clusters). It looks at the contacts enrichment between all these sites within a given range.

So if you give a list of Transcription Start Sites to `hicAggregateContacts`, the outcome will be the aggregation of contacts between the TSS and with the bins next to the TSS. So within a given range, the tool will collect submatrices whose center correspond to TSS - TSS interaction points, then it computes the average or median of all these submatrices per chromosome.

 If you suspect increased contacts of genes TSS with other TSS surroundings, you should look at the enrichment in the corner of the plot produced by `hicAggregateContacts`. Please, avoid using entire genes in your bed file as the outcome will not be meaningful (you will then cluster the contacts between the left of all genes).

If you want to see if a given gene TSS / promoter has more interactions with its surroundings, you must use `hicViewpoint`.

**Comment by re2srm** [comment]
Thanks, I understand it much more clearly now. I should have been using hicPlotViewpoint all along because enrichment of interactions at promoters was actually what I was trying to investigate.
