### ISSUE TITLE
Error while plotting in hicPlotTADs

### ISSUE THREAD

**Issue by CornelisB** [deeptools/HiCExplorer#381]
Hi I'm playing around with the mouse data from the [example](https://hicexplorer.readthedocs.io/en/latest/content/mES-HiC_analysis.html) analysis.

Everything looks fine so far and is going really well, however when I try to plot the hicPlotTADs I get an error. Any ideas how to solve this?

```
hicPlotTADs --tracks track.ini --region chrX:98000000-105000000 \
> --dpi 300 --outFileName plots/marks_et-al_TADs.png \
> --title "Marks et. al. TADs on X"
INFO:hicmatrix.HiCMatrix:Number of poor regions to remove: 9109 {'chr1': 172, 'chr2': 272, 'chr3': 189, 'chr4': 324, 'chr5': 291, 'chr6': 182, 'chr7': 413, 'chr8': 198, 'chr9': 166, 'chr10': 186, 'chr11': 168, 'chr12': 211, 'chr13': 173, 'chr14': 349, 'chr15': 166, 'chr16': 162, 'chr17': 163, 'chr18': 161, 'chr19': 165, 'chrX': 724, 'chrY': 4274}
INFO:hicmatrix.HiCMatrix:found existing 9109 nan bins that will be included for masking 
Invalid: 'type = lines' in section: 4. [tad score]
```

This is the HiCinfo and I'm using the provided track.ini file with as only change the filename used.

```
hicInfo -m hicMatrix/SRR1956527_20kb_corrected.h5
# Matrix information file. Created with HiCExplorer's hicInfo version 3.0
File:	hicMatrix/SRR1956527_20kb_corrected.h5
Size:	136,288
Bin_length:	20000
Sum of matrix:	15784703.181441043
Chromosomes:	chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chrX, chrY
Non-zero elements:	15,527,350
Minimum (non zero):	1.7266308086222907e-11
Maximum:	327.3049875169182
NaN bins:	9109
```

**Comment by gtrichard** [comment]
Hello @CornelisB, thank you for using HiCExplorer.

I think it is a small mistake on our end, pyGenomeTracks on which hicPlotTADs is based has been updated and is not using `type = lines` anymore. Please, use the following in the `.ini` file:

```
[tad score]
file = TADs/marks_et-al_TADs_20kb-Bins_score.bm
title = "TAD separation score"
height = 2
file_type = bedgraph_matrix
```

We need to update the example analysis I think.

**Comment by CornelisB** [comment]
Yes that worked! Thank you very much! and indeed an updated example analysis would be amazing for beginners like me.

**Comment by gtrichard** [comment]
fixed with https://github.com/deeptools/HiCExplorer/commit/3b7abc349a8f2aa31a10d4d79ac4ed100b3b7aa1
