### ISSUE TITLE
Question about hicnormalize

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#382]
Hello,

I had a basic question about when to use hicnormalize. I am currently using hicnormalize on all my matrices before any further analysis. I build matrices, and merge, correct and normalize them before doing TAD calling, PCA and comparison of different conditions. Is this the correct way to do this or is hicnormalize only supposed to be used for plotting functions like hiccompare and TAD calling/PCA etc should be performed before normalization?

Thanks

**Comment by gtrichard** [comment]
I think it makes sense to use before any analysis, especially if you want to compare TADs insulation score, which is dependent on the sequencing depth.

Although, some analyses are already implementing a scaling like `hicCompareMatrices` and `hicPlotDistVsCounts` and thus hicNormalize is not required there.

**Comment by re2srm** [comment]
Thank you for the quick reply. That is how I am doing it right now. Also even though hicComapareMatrices is doing its own scaling, would it be ok if I also use normalized matrices with hicCompareMatrices just so that all my analysis is consistent?

**Comment by gtrichard** [comment]
Yes it should work properly.

**Comment by re2srm** [comment]
Thanks

**Comment by MzwaneleN** [comment]
I am trying to normalize two matrices with hicNormalize. I thought I was supposed to get two output files of normalized matrices but I get one file with 0 bytes size. I dont quite get it
