### ISSUE TITLE
Correct matrix using suggested thresholds?

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#383]
I am working with a large number of samples and was wondering if it is somehow possible to pass on the suggested thresholds from the hicCorrectMatrix diagnostic_plot to the hicCorrectMatrix correct command?  

Thanks

**Comment by LeilyR** [comment]
is `--filterThreshold` what you need?

**Comment by re2srm** [comment]
Maybe this is more of a suggestion. 
What I meant was it would be nice to have a way of directly passing the threshold suggested in the diagnostic plot to the --filterThreshold parameter instead of manually specifying it for each sample. I have around 15 samples in triplicate and looking at the diagnostic plot, writing down the suggested thresholds and inputting them in the hiccorrect command for fifty samples is not very efficient.

**Comment by LeilyR** [comment]
The reason for manually setting a threshold was giving a chance to user to be able to set their own threshold value after seeing the generated plot. However, we have a HiC pipeline which does that for you. If you have several samples you might want to try this pipeline (https://github.com/maxplanck-ie/snakepipes)  which runs hicexplorer in the background.

**Comment by re2srm** [comment]
Thanks!

**Comment by gtrichard** [comment]
To give the direct answer here without having to install SnakePipes, here is the code to run to directly get the corrected matrices with the suggested thresholds:

```
hicCorrectMatrix diagnostic_plot -m matrix.h5 -o QC/matrix.pdf &> QC/matrix_mad_threshold.out
madscore=$(grep "mad threshold" QC/matrix_mad_threshold.out | sed 's/INFO:hicexplorer.hicCorrectMatrix:mad threshold //g');
upper=$(echo -3*$madscore | bc);
echo $madscore " " $upper > QC/matrix_mad_threshold.values
thresholds=$(cat QC/matrix_mad_threshold.values);
hicCorrectMatrix correct --filterThreshold $thresholds -m matrix.h5 -o matrix_cor.h5
```
