### ISSUE TITLE
HicNormalize implementation

### ISSUE THREAD

**Issue by CMylonas** [deeptools/HiCExplorer#385]
Hello,

I've been using HiCExplorer recently and I have to admit it's a great tool for HiC/ HiChIP analysis.
I was wondering whether in the future it would be possible to implement HicNormalize so it can normalize matrix files by a given value specified by the user (in case we have spike-in controls). 

Best wishes,
Constantine

**Comment by joachimwolff** [comment]
Hi Constantine,

Sure, we can add this feature in a future release.

Best,

Joachim

**Comment by joachimwolff** [comment]
Implemented in 3.3 release.
