### ISSUE TITLE
Importing matrices produced by other pipelines?

### ISSUE THREAD

**Issue by re2srm** [deeptools/HiCExplorer#388]
Is it possible to somehow import hi-c marices produced by other pipelines like HOMER or HiCUP and use them with hi-c explorer? 

I have a dataset that was processed with the arima hi-c kit which uses a combination of 2 restriction enzymes. As far as I know there is no way to do the initial qc for such data using hicexplorer because we can only provide one restriction site when making fixed bin matrices (I dont want to make restriction fragment resolution matrices). I have now done the initial qc and processing of the data using the HiCUP pipeline which works well with the arima kit. The HiCUP pipeline allows conversion to formats compatible with HOMER, GOTHiC and CHiCAGO but I was wondering if there is a way to import these matrices into hicexplorer for downstream analysis?

Thanks

**Comment by gtrichard** [comment]
The HOMER format can be converted into h5, and then used for further analyses in HiCExplorer using `hicConvertFormat`

https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html`

**Comment by re2srm** [comment]
Thank you. Dont know how I missed this.

**Comment by re2srm** [comment]
Quick question about importing HOMER matrices for TAD calling.

HOMER can make interaction matrices using different normalization options (default is interactions per hundred square kilobases per billion) or  with raw interaction counts. I was wondering if I should import normalized matrices into HiCexlporer and use them directly for TAD calling or should I import raw matrices, correct them with HiCexplorer and then do TAD calling?

Also as I am trying to compare different TAD callers I was wondering if I can use HiCexplorer matrices with TopDom? 

Thanks

**Comment by LeilyR** [comment]
if you want to compare the TAD calling between homer and hicexplorer you need to ue the same normalised matrix in both (either normalised by hixplorer or homer). 

We don't specifically have TopDom format but check the text formats we support in `hicConvertFormat` . `ginteractions ` might be the closest to what you need I suspect.
