### ISSUE TITLE
Question about calculating expected

### ISSUE THREAD

**Issue by zhqu1148980644** [deeptools/HiCExplorer#389]
Why the distance calculated in `expected_interactions_in_distance` and  `obs_exp_matrix_lieberman` are different.
https://github.com/deeptools/HiCExplorer/blob/3b7abc349a8f2aa31a10d4d79ac4ed100b3b7aa1/hicexplorer/utilities.py#L311-L312
https://github.com/deeptools/HiCExplorer/blob/3b7abc349a8f2aa31a10d4d79ac4ed100b3b7aa1/hicexplorer/utilities.py#L223-L224

**Comment by joachimwolff** [comment]
That could be an implementation error, but I need to validate it.

Thanks for reporting.

Joachim

**Comment by LeilyR** [comment]
obs/exp calculation is now updated in more recent versions. I will close this issue but feel free to reopen it if there was any unclear matter.
