### ISSUE TITLE
hicAggregateContacts option request

### ISSUE THREAD

**Issue by zhanyinx** [deeptools/HiCExplorer#390]
Hi,

I was wondering if you could provide an option where we can specify exactly the list of interactions we want to aggregate. 

In the current version, if I provide one or two BED files, the algorithm will aggregate all the interactions between ALL the regions in the bed files given that they satisfy the --range option.

It would be great if it would be possible to give specific regions to aggregate:
for instance, consider the case we have region 1,2,3,4. 
If I am interested only in the interactions between 1 and 2; 3 and 4; but not 2 and 3; and I want to aggregate 1-2 and 3-4 interactions. This would not be possible if 2-3 satisfies the --range condition

Not sure if I managed to explain

Zhan

**Comment by joachimwolff** [comment]
Thanks for opening this issue Zhan. We try to implement this soon.

**Comment by joachimwolff** [comment]
@LeilyR Have you implemented this already?

**Comment by LeilyR** [comment]
Sorry for delay. I put it in my todo list.

**Comment by LeilyR** [comment]
2 bed files can be give to hicAggregateContacts. If you use 2 bed files, it will check for the contact between bed1 and bed2 but not within bed1 or bed2. This should solve your issue.

**Comment by LeilyR** [comment]
I will add a row-wise option to exclude more combination, I think that is what you wanted

**Comment by joachimwolff** [comment]
Implemented with version 3.5.
