### ISSUE TITLE
BWA example mapping (docs)

### ISSUE THREAD

**Issue by keiranmraine** [deeptools/HiCExplorer#391]
It looks like there may be a typo in the doc page section:

https://hicexplorer.readthedocs.io/en/latest/content/example_usage.html#reads-mapping

```
$ bwa mem -A1 -B4  -E50 -L0  index_path \
    -U mate_R1.fastq.gz 2>>mate_R1.log | samtools view -Shb - > mate_R1.bam
```

It appears that `-U` should be removed from the BWA command.  It's not valid to have an option between index and inputs, plus `-U` is only relevant for paired data (and it's intentionally run as unpaired here).

**Comment by joachimwolff** [comment]
I think you are right, thanks for reporting.
