### ISSUE TITLE
pip/eigen question

### ISSUE THREAD

**Issue by keiranmraine** [deeptools/HiCExplorer#392]
The docs indicate that from v3 pip installation is no longer supported due to a dependency on the c++ eigen library.

1. Which tools require eigen?
2. When the library is required and not found is this obvious from the error message?

**Comment by dpryan79** [comment]
It requires this: https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm

Yes, it will likely be obvious, since a dependency will be missing. Just use conda.

**Comment by keiranmraine** [comment]
Guess one more 🐢 in our shared dependency management will have to do 😉
