### ISSUE TITLE
hicCorrectMatrix example docs

### ISSUE THREAD

**Issue by keiranmraine** [deeptools/HiCExplorer#394]
The example for performing the actual correction after generating the plot is missing the subcommand `correct` here:

https://github.com/deeptools/HiCExplorer/blob/3b7abc349a8f2aa31a10d4d79ac4ed100b3b7aa1/docs/content/example_usage.rst#correction-of-hi-c-matrix

**Comment by joachimwolff** [comment]
Thanks for reporting.
