### ISSUE TITLE
Docs: Image missing

### ISSUE THREAD

**Issue by keiranmraine** [deeptools/HiCExplorer#395]
Last item to display in [this page](https://hicexplorer.readthedocs.io/en/latest/content/example_usage.html#a-b-compartment-analysis):

```
//.. figure:: ../images/eigenvector1_lieberman.png // :scale: 90 % // :align: center
```

Doesn't appear to exist in `docs/images`

**Comment by joachimwolff** [comment]
Fixed with release 3.1
