### ISSUE TITLE
hello,how can  I get the TAD boundary sequence for the boundary?

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#396]

**Comment by hzaumsq** [comment]
such  as ctcf or other? How can l to make sure which protein to determine my doundary? i am confused

**Comment by gtrichard** [comment]
`bedtools getfasta`. You can ask this kind of questions on Biostars since it is much broader than HiCExplorer itself (i.e. how to get a fasta sequences from a bed file).
