### ISSUE TITLE
hicCorrectMatrix diagnostic_plot?

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#398]
I found the picture is different from you example? How did I to correct my Hi-c matrix?
![image](https://user-images.githubusercontent.com/34264027/59551854-3fde6180-8fb2-11e9-85f5-2281bb555a2a.png)

**Comment by joachimwolff** [comment]
Hi,

Unfortunately there is not that much information provided. To help you we need:

- Which organism you work with?
- What is the resolution of the matrix?
- What is your read coverage? Please use hicInfo for this.

Thanks a lot,

Joachim

**Comment by francicco** [comment]
Apparently I have the same problem

![hic_matrix](https://user-images.githubusercontent.com/9006870/60708901-0b9df700-9f07-11e9-828d-cc938bd3c7d6.png)

```
# Matrix information file. Created with HiCExplorer's hicInfo version 2.2.1.1
File:   hic_matrix.h5
Size:   13,270
Sum:    54,755,762.5
Bin_length:     0
Chromosomes:    Scf0000001_pilon_pilon_pilon_pilon_pilon, Scf0000002_pilon_pilon_pilon_pilon_pilon, Scf0000003_pilon_pilon_pilon_pilon_pilon, Scf0000004_pilon_pilon_pilon_pilon_pilon, Scf0000005_pilon_pilon_pilon_pilon_pilon, Scf0000006_pilon_pilon_pilon_pilon_pilon, Scf0000007_pilon_pilon_pilon_pilon_pilon, Scf00000 [...]
Non-zero elements:      17,320,102
Minimum (non zero):     1
Maximum:        18837
NaN bins:       0
```

How do I correct this?
Thanks a lot
F

**Comment by francicco** [comment]
Hi @joachimwolff,

I now reduce the bin size to 10k and I got this:

![hic_matrix bz10k](https://user-images.githubusercontent.com/9006870/60727275-6d755580-9f35-11e9-955f-9cd922f89474.png)

Better?
Shell I use `--filterThreshold -0.4 4` for the correction?

Thanks
F

**Comment by LeilyR** [comment]
the shape of the frequency depends on your data. Not all data produce the same plot. However it can easily give you an idea about the sparsity of your matrix. From what you have sent it is clear that your matrix is quite sparse. Your data seems to be so shallow too return interaction between  small bins. by reducing resolution, you have generated larger bins so lee sparsity and got a more decent plot. You might even need to increase it a bit further or consider sequencing deeper replicates and merge them to your current data to obtain a more clear 3D view of your data.

**Comment by francicco** [comment]
Unfortunately I can't sequence more. Reads are also quite short 37bp for each end.

So the idea is trying to get a better shape then correct as much as possible then using HiCAssembler to scaffold the assembly, is that right?

Thanks
F

**Comment by GinaRe** [comment]
Dear Francicco,

do you know the length distribution of you scaffolds? I am asking this because if you choose a bin size that is big, many of your scaffolds might be smaller than the bin size you choose for your matrix. 
If your scaffolds are small, you could try to generate a restriction fragment resolution matrix, so you get more bins per scaffold.

**Comment by joachimwolff** [comment]
No more feedback, please reopen if topic still needs to be solved.
