### ISSUE TITLE
Calculating intra/inter-TAD interactions

### ISSUE THREAD

**Issue by ywiwasaki** [deeptools/HiCExplorer#404]
I want to calculate density of intra-TAD interactions and inter-TAD interactions for each of the TADs defined by HiCExplorer. Is there any way to do this using HiCExplorer? (Or do I need to calculate it by using the matrix file converted in ginteractions format?)

**Comment by joachimwolff** [comment]
Hi,

Sorry, this feature we do not have currently in HiCExplorer.

Best,

Joachim

**Comment by Drosophilid** [comment]
Hi,

I also got stuck with a similar situation to calculate the Inter vs Intra TAD interactions. Would it be possible to do it now in the recent release?

Any kind of help or suggestion will be appreciated.

Thanks

**Comment by joachimwolff** [comment]
Implemented with PR #733.
