### ISSUE TITLE
hicAggregateContacts chromosomes

### ISSUE THREAD

**Issue by Phlya** [deeptools/HiCExplorer#405]
Hi, I was trying hicAggregateContacts, and seems like it gives me an error because I have chromosomes in the cooler file that are not in the bed file? I would understand if it was the opposite, chromosome from a bed file absent in the cooler, but this doesn't make sense in my opinion. Is this expected?

```
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/dotfinder/bin/hicAggregateContacts", line 7, in <module>
    main()
  File "/exports/igmm/eddie/wendy-lab/ilia/condaenvs/dotfinder/lib/python3.6/site-packages/hicexplorer/hicAggregateContacts.py", line 654, in main
    cluster_ids[chrom] = [range(len(chrom_matrix[chrom]))]
KeyError: 'chrY'
```

**Comment by joachimwolff** [comment]
I guess it is the same as #397.

**Comment by LeilyR** [comment]
I have the same issue with hicAggreagate and it is not about throwing a warning as has been mentioned #397. I totally agree with Phyla. It is a bug to be fixed.

**Comment by joachimwolff** [comment]
Hi,

I tried to fix it, but I cannot reproduce the error. It would be great if you could checkout the concerning branch and test if it is fixed.

Best,

Joachim

**Comment by LeilyR** [comment]
Which branch? I can test it.

**Comment by joachimwolff** [comment]
hicAggregateFix

**Comment by LeilyR** [comment]
I have tested it with a bed file that doesn't have all the chromosomes of the input matrix, this is the case I had issue with it before, and it worked fine. 
I have also tested the case where both bed file and matrix have the exact same set of chromosomes and the case where the bed file has a chromosome that doesn't exist on the matrix and it worked in all cases. Thanks!
