### ISSUE TITLE
How to determine Z-score threshold in HiC Explorer?

### ISSUE THREAD

**Issue by anupambh** [deeptools/HiCExplorer#407]
![plot_1Mb_matrix](https://user-images.githubusercontent.com/47624012/60716415-f8a61980-9f3c-11e9-98fd-bab52e7a2fe9.png)
![diagnostics_plot](https://user-images.githubusercontent.com/47624012/60716436-0196eb00-9f3d-11e9-95d2-489e95930d8b.png)

Hi,
We have used your Hic Explorer for the analysis of the Human datasets. The commands and plots are generated successfully though we are having problem to select the Z value threshold. We run the following command get this error:

Command:
 
/opt/miniconda2/bin/hicCorrectMatrix correct --chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY --matrix hicMatrix/replicateMerged.matrix_20kb.h5 --filterThreshold -2 3  --perchr --outFileName hicMatrix/replicateMerged.Corrected_20kb.h5

Error:

ERROR:
hicexplorer.iterativeCorrection:*Error* matrix correction produced extremely large values. This is often caused by bins of low counts. Use a more stringent filtering of bins.

While we have randomly selected the Z-value threshold to -1.5 to 3, and remove Chromosome Y, the program run successfully. 

Command:
/opt/miniconda2/bin/hicCorrectMatrix correct --chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX --matrix hicMatrix/replicateMerged.matrix_20kb.h5 --filterThreshold -1.5 3 --perchr --outFileName hicMatrix/replicateMerged.Corrected_20kb.h5

**My question is that what is relevance to remove Chromosome Y and how do we determine the Z score threshold.**
 

The figures are attached herewith. 

Thank you for your time.

Regards.
Anupam

**Comment by joachimwolff** [comment]
Hi Anupam,

Thank you for using HiCExplorer. 

Which version of HiCExplorer do you use? The command does not look like the current version 3.0. In version 3.0 we have added the parameter `--correctionMethod` and set it by default to `KR`, however you don't use this parameter and run `ICE`. I recommend to update your HiCExplorer version to 3.0 and try to correct the data also with KR.

Concerning your question, chromosome Y is really small and does not contribute many interactions. As you can see in your plot there are many intra- and inter-chromosomal interactions and the chromosome territories are big. However, for chromosome Y this is not the case and there are more or less no interactions recorded. This is causing the observed errors in the data correction. The best you can do, and as you already did, is to remove the Y chromosome.

The z-score values should be determined with the help of the plot. The distribution should follow a Gaussian bell and the thresholds can be determined by the regions in the curve where the tails starts, i.e. in your data around the value 2.6 and on the negative side -1.6 to -1.8. Please try to set the values as big (positive threshold) and as small (negative threshold) as possible.

Best,

Joachim

**Comment by anupambh** [comment]
Hi,
Thank you very much for detailed explanation. I will update the HiC Explorer and use the parameter that you have mentioned. 

Thank you for your time.

Regards.
Anupam
