### ISSUE TITLE
hicPlotMatrix cannot plot a region of matrix from yesterday

### ISSUE THREAD

**Issue by brainfo** [deeptools/HiCExplorer#413]
When I used hicPlotMatrix to plot a region of Matrix say from chr1:30000000-40000000, I got a plot from 0-40000000, with 0-30000000 squares are colored by the max value's corresponding color.
This just happened from yesterday afternoon. I did not encounter this before yesterday.
Is there anyone having the same problem or Does anyone know where I got wrong?
I used 5k and 25k resolution cool files to test, no one can work.

**Comment by bgruening** [comment]
@brainfo you resolved this?

**Comment by brainfo** [comment]
> @brainfo you resolved this?

I have resolved this, using version 3.1, hicPlotMatrix with --clearMaskedBins will lead to this issue.
cancel this option will work.
But using version 3.0, it works fine with --clearMaskedBins

**Comment by bgruening** [comment]
Maybe we reopen this issue and let @joachimwolff look at it if he has time.

**Comment by joachimwolff** [comment]
Hi,

can you post the commands you used and attach the output? We did not apply changes in hicPlotMatrix for version 3.0 to 3.1; maybe a log of which dependecies you have installed will help too. You can get this via `conda list >> dependecies.log`

Thanks a lot for reporting this issue.

Best,

Joachim

**Comment by joachimwolff** [comment]
No more feedback. Closing this issue.
