### ISSUE TITLE
what confused me about hicFindTADs ?

### ISSUE THREAD

**Issue by hzaumsq** [deeptools/HiCExplorer#414]
when I used hicFindTADs to detecte TADs，The following parameters that I couldn't understand . minDepth and maxDepth, The software's suggestion just a range.so when I try different parameters, the result will also different, like this .....
so what's the best  parameters for me to choose or it has some standards for this ? someone can help me ? 
Best wishes

**Comment by hzaumsq** [comment]
![O5Q`R~02L`7)O5I$}HJWD@W](https://user-images.githubusercontent.com/34264027/62007618-68957180-b182-11e9-8b50-6fb4f4c23667.png)
![1S)`Z 9PYPOLY4}71V4M A](https://user-images.githubusercontent.com/34264027/62007622-6df2bc00-b182-11e9-9e14-77f197ed73d1.png)

**Comment by wzhjlau2009** [comment]
@joachimwolff，@hzaumsq ，
Hi，i have the same problem that i don't know how to fix the parameters for this,  also the --minBoundaryDistance , can you explain how to set these parameters ? Thank you very much !

**Comment by LeilyR** [comment]
Unfortunately there is no standard for tad calling and all depends on your data and its depth. 
In the images you have sent I cannot really see any TADs, it might be because of the scale though if it is a bit too zoomed out. Also, your TAD separation score don't seem to be matched to your boundaries.  A good practice could be calling TADs once with all the default parameters and then try to modify them and each time check how they look by eyes to get the best result. Also bear in mind, if your data is shallow and the resolution is too high you might want merge some of your bins prior to TAD calling. You can find more information about the parameters here:
https://hicexplorer.readthedocs.io/en/latest/content/tools/hicFindTADs.html#hicfindtads

**Comment by gtrichard** [comment]
A good way to check if your TAD boundaries are correctly called in regard to the TAD insulation score (or separation score) is to plot the average insulation score signal at TAD boundaries using deepTools `computeMatrix` and `plotProfile`. 

By using different TAD calling parameters, you should keep the one with the lowest average... up to a certain number of TADs (you don't want to call only 700 strong TADs).

Another way, is to check the enrichment of TAD boundaries predictive features, i.e. CTCF binding motifs or ChIP-seq enrichment for mammals, or Beaf-32, CP190, etc motifs for Drosophila for instance.

**Comment by hzaumsq** [comment]
@gtrichard  there is another question,I had read your team published paper. you identified a new insulator protein of Drosophila melanogaster, for my project ,It lost CTCF and other insulator protein ,I want to use your method to find the new elements in boundary , the first step ,I must to know where is boundary and then to do next step, so what result I had analyzed is not dependable,because of the boundary is varied.

**Comment by gtrichard** [comment]
Hum so I guess it is in mammals? Well you can try different parameters until you call the "correct" number of TADs (i.e., a number of TADs equivalent to recent publications).

If you fear that the TAD structure might be overall affected, you can inspect the log2ratio matrix to see if there's a collapse of TADs in the genome. In that case you can expect less TADs to be called overall.

But again, there's no standard and little expectations you can have on what to call as TADs in a KO sample... Call TADs, check the average insulation score at the boundaries, and scan the genome to see if the Hi-C matrix is matching the TADs called (be sure to use the same matrix resolution for both plotting and TAD calling).

Also, if you compare Control (/WT) vs KO, be sure to call TADs in both of them, overall the number and the structure of the called TADs is usually matching different samples if there's no difference in the TAD structure. If you consistently call less TADs in the KO, perhaps the TAD structure or the overall insulation score are affected...

**Comment by hzaumsq** [comment]
That's very kind of you ! @gtrichard @LeilyR
