### ISSUE TITLE
H5 & cool file - spike in normalization

### ISSUE THREAD

**Issue by CMylonas** [deeptools/HiCExplorer#424]
Hello,

I suggested a few months ago an implementation for HicNormalize for spike-in controls. I see that it has been added as a future request so thank you for that.
In the interim, is there another quick way (either a bash script or any changes I can make to hicNormalize.py) to multiply either .h5 or .cool files by a specific value calculated from my spike-in controls? 

Thanks for the great software

Best,

Constantine

**Comment by joachimwolff** [comment]
Hi,

I implemented it, see branch `spike_in`. 

Usage example:

`hicNormalize --matrices gm12878_10kb_chr1.cool imr90_10kb_chr1.cool --normalize multiplicative --multiplicativeValue 2 -o gm12878_double.cool imr90_double.cool`

Let me know if you need help to install HiCExplorer from a branch.

Best,

Joachim
