### ISSUE TITLE
P(s) between and within TADs

### ISSUE THREAD

**Issue by apaytuvi** [deeptools/HiCExplorer#438]
Dear all,

I am trying to generate P(s) plots. It is easy to get these plots genome-wide. However, I would like to generate them considering interactions within TADs on one hand, and interactions between TADs on the other.

What I did is the following: I created 2 matrices:

* 1 matrix with TADs filled with 0s.
* 1 matrix with all bins being 0 but TADs with normal counts.

Could I use these matrices as input to `hicPlotDistVsCounts` to obtain these plots? Is it a valid approach?

Thanks,
Andreu

**Comment by gtrichard** [comment]
Thank you for using HiCExplorer.

Yes you can do it, I have for instance recently extracted A comp. or B comp. interactions using `hicAdjustMatrix` and `hicPlotDistVsCounts` was giving the expected results.

**Comment by apaytuvi** [comment]
But doing my approach I obtain something like this: @gtrichard 

![image](https://user-images.githubusercontent.com/11228225/67783433-84066600-fa6a-11e9-9007-5787d79b7fa7.png)

How is it possible that at 1Mb resolution the "between-TAD" interactions is higher than the "within-TAD" interactions? Something might be wrong...

**Comment by apaytuvi** [comment]
@LeilyR Thanks for answering. The resolution is 50K. TAD size:
```
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
  150000   300000   450000   779937   900000 36050000
```

**Comment by LeilyR** [comment]
I have a bit of problem understanding the scales on the x axis of the plots you sent, it seems to me that the distance between 0.1 and 0.3 is the same as 0.3 and 1, so i dunno where exactly between lines cross within lines. However, based on the values you have sent, it doesn't seem to be so wrong if they have just before 1mb since your 3rd quantile is 900k.
