### ISSUE TITLE
Zscore in HiCFindTads

### ISSUE THREAD

**Issue by samuelCollombet** [deeptools/HiCExplorer#442]
Hi,
I was wondering if there was not a bug in HicFindTADs usinf the Z-score. In the code of HicFindTADs.py, lines 1065 you have:

```
        if self.use_zscore:
            # use zscore matrix
            log.info("Computing z-score matrix...\n")
            self.hic_ma.convert_to_zscore_matrix(maxdepth=self.max_depth * 2.5, perchr=perchr)
```
However in HiCMatrix.py it looks liek the zscore argument is FALSE by default, so convert_to_zscore_matrix in HicFindTADs will only report the obs/exp matrix, isn't it?

**Comment by joachimwolff** [comment]
Hi Samuel,

Thanks for your question.

In line 346 of HiCMatrix the mentioned function is implemented. https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/HiCMatrix.py#L346

As you can see we set the z-score argument explicitly to True:

<pre>
def convert_to_zscore_matrix(self, maxdepth=None, perchr=False):
        return self.convert_to_obs_exp_matrix(maxdepth=maxdepth, <b>zscore=True</b>, perchr=perchr)
</pre>

I hope this answers your question.

Best,

Joachim

**Comment by samuelCollombet** [comment]
oops sorry Missed that one ! thanks
