### ISSUE TITLE
hicConvertFormat convert homer to .cool file issue

### ISSUE THREAD

**Issue by pqyNUS** [deeptools/HiCExplorer#444]
hi, 

I have HiC data processed by HiCUP and i did a bam file conversion using hicup2homer to obtain the .homer files. 
But when i run the hicConvertFormat, 
hicConvertFormat --matrices P1_d1_L2_1_2.hicup.bam.homer --outFileName P1_d1_L2_1_2.cool --inputFormat homer --outputFormat cool --resolutions 10000

or,

hicConvertFormat --matrices P1_d1_L2_1_2.hicup.bam.homer --outFileName P1_d1_L2_1_2.cool --inputFormat homer --outputFormat cool 

i get the following error for both commands:
    start_first = int(values[2].strip().split('-')[1])
IndexError: list index out of range

is there a way to fix this?

**Comment by joachimwolff** [comment]
Hi,

can you please post the full error message? It is difficult without any context to figure out what is wrong.

Thanks,

Joachim

**Comment by pqyNUS** [comment]
hi,

as attached. Thanks

Traceback (most recent call last):
  File "/hpctmp2/a0123882/hicexplorer/bin/hicConvertFormat", line 7, in <module>
    main()
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicConvertFormat.py", line 165, in main
    distance_counts, correction_factors = matrixFileHandlerInput.load()
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicmatrix/lib/matrixFileHandler.py", line 45, in load
    return self.matrixFile.load()
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicmatrix/lib/homer.py", line 23, in load
    start_first = int(values[2].strip().split('-')[1])
IndexError: list index out of range

Ed

**Comment by joachimwolff** [comment]
It seems your Homer file does not follow the Homer matrix format. Can you check if it follows this format: http://homer.ucsd.edu/homer/interactions/HiCoutput.png

And yes, that screenshot is the documentation of Homers matrix. :unamused:

**Comment by pqyNUS** [comment]
i ran the command to get the first 10 lines of the hicup converted homer file

head -n 10 P1_d1_L2_1_2.hicup.bam.homer
1       chr14   100133449       -       chr14   98996259        -
2       chr14   106321998       +       chr14   105840423       +
3       chr14   106590738       +       chr19   23075466        +
4       chr14   102484770       +       chr20   4210869 -
5       chr14   100645890       +       chr14   100602344       -
6       chr14   102871230       +       chr14   102976416       -
7       chr14   100444844       +       chr14   100658079       +
8       chr14   101137306       -       chr19   31510494        -
9       chr14   103193955       -       chr14   54568786        -
10      chr14   96273531        -       chr14   100235882       -

**Comment by pqyNUS** [comment]
i got what u mean by the homer matrix. Ok thanks,
I will generate the appropiate matrix file.

Thank you for the help :)

**Comment by pqyNUS** [comment]
can i ask if i generate the matrix from homer, should i do any normalization?

they have several normalization options like -simpleNorm, norm, logp, corr, etc

**Comment by joachimwolff** [comment]
It is the best to import raw matrices and to use our correction and normalization algorithms. The only exception are corrected files from Lieberman-Aidens Juicer, they follow the same standards. What most HiCExplorer algorithms can not handle is if the values are normalized to a 0 -1 range, and some tools do this e.g. cooltools.

I think what hiccup2homer creates are these internal used files from Homer which are created if you run 'makeTagDirectory'. 
We have a different terminology in HiCExplorer than HOMER. To correct the data we use 'correction' and this can be done with 'hicCorrectMatrix' with ICE or KR algorithm. A normalization is to either normalize different matrices to the same read coverage or to the range of 0 -1. But this is only needed if you have multiple matrices you want to compare. Correlation or logp is not a normalization.

I hope this clarifies it a bit. 

Best,

Joachim

**Comment by pqyNUS** [comment]
Thank you for the explanation. yes it helped me alot.

Best regards,
Eddy
