### ISSUE TITLE
If you want matplotlib to be able to compare pdf

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#450]
Hi,
I saw that travis is skipping all pdf comparison in HiCExplorer.
I found the solution to make them evaluated (add ghostscript to the travis conda environment):
https://github.com/deeptools/pyGenomeTracks/blob/301ba29d01d86f4dfdfb145e36f2634f681e8f35/.travis.yml#L64

**Comment by joachimwolff** [comment]
Hi Lucille, 

Thanks a lot for the suggestion! I really appreciate your work on pyGenomeTracks!

Best,

Joachim
