### ISSUE TITLE
multiple restriction enzymes used

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#453]
Hi, 
If multiple restriction enzymes are used, blunt and sticky. What is the correct way to use the function hicBuildMatrix?
I used findRestSite function to find restirction site for all enzymes, individually. And then simply combined all bed file output --> rs.bed

hicBuildMatrix --samFiles ./BAM/"$i"_1.bam ./BAM/"$i"_2.bam \
        --binSize 250 \
        --minDistance 50 \
        -rs rs.bed \
        --threads 8 \
        --inputBufferSize 400000 \
        -o ./matrix_uncorrected/"$i"_250b.h5 \
        --QCfolder ./matrix_uncorrected/hicQC/250b/"$i"

Q: If I do this, how does it distinguish which of the restriction sites are sticky/blunt? or is this information not that important?
Thank you! - Jun

**Comment by GinaRe** [comment]
Dear Jun,
could you first clarify/explain how using a blunt end restriction enzyme allows you to incorporate the biotinylated nucleotides that you need for the pull down of ligated fragments during the Hi-C protocol?

**Comment by kimj50** [comment]
Hi Gina,
Sorry, I misunderstood. No blunt ends. 
We started using arima kit, but previously we had been using hicexplorer to analyze the data. And the kit makes more than one enzyme. Can we use hicexplorer to process arima-kit protocol?
The Arima-HiC chemistry uses restriction enzymes that digest chromatin at ^GATC and G^ANTC, where N can be any of the 4 genomic bases. Our multiple restriction enzyme chemistry produces the following possible ligation junction motifs: GATCGATC, GANTGATC, GANTANTC, GATCANTC.
Thank you, Jun

**Comment by kimj50** [comment]
Hi Joachim,
I don't think I understood the function hicbuildmatrix properly.
the options -bs and -rs are not allowed together. So, if I want binned data, there is no place to input which restriction enzymes were used in the protocol. And to generate the bam files, I used the default reference genome (bowtie2 with -local option). I did successfully visualized arima-kit data without ever providing which restriction enzymes were used.
Question: for building a binned matrix, is the information of which restriction enzymes were used in the protocol not important?
Thank you,
Jun

**Comment by LeilyR** [comment]
You are right, you can not set both -bs and -rs at the same time because you either are interested in making a matrix with restriction site resolution or a fixed bin size. However you could provide the information about the cut sites via `--restrictionSequence `

I close this issue, but feel free to reopen it if there is still any question left.
