### ISSUE TITLE
hicInfo

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#456]
It would be nice to have the coordinates of chromosomes which were used to build a matrix in hicinfo. For example: 

File:matrix.h5
Size:	437
Bin_length:	50000
Sum of matrix:	7599.096216851063
Chromosomes:	2L (0-2250000), 2R (0-10000000)
Non-zero elements:	190,969
Minimum (non zero):	-0.3425034355295254
Maximum:	1.0
NaN bins:	0

the ` (0-2250000)` is not there at the moment.

Also in case of cool although it says: 
`The following columns are available: ['chrom' 'start' 'end']` 
but it doesn't even show the list of chromosomes. It'd be quite handy having chr, start and end be printed after that message

**Comment by joachimwolff** [comment]
Cool shows whatever is in the metadata. If the desired information is not written to the metadata, you can set the parameter `--no_metadata`.
