### ISSUE TITLE
pearson matrix shape

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#457]
Pearson matrix which has been made by hicPCA has different shape from the input matrix, what does cause this behavior?

**Comment by LeilyR** [comment]
I have some guess, it removes/merges the nan bins and that is why it happens. Is there a way to avoid that? Can they be kept as they are and only be masked during the correlation computation?

**Comment by joachimwolff** [comment]
Can you tell me how large the difference is?

**Comment by LeilyR** [comment]
The difference is the number on nan bins. In my case was 6

**Comment by LeilyR** [comment]
solved now
