### ISSUE TITLE
KR or ICE of hicNormalize; And the order of hicNormalize and hicCorrectMatrix

### ISSUE THREAD

**Issue by Linhua-Sun** [deeptools/HiCExplorer#459]
Hi:
1. I'm curious about the order of `hicNormalize` and `hicCorrectMatrix`. Should I do `hicNormalize` firstly to make the sequencing depth of two samples are equal, than use `hicCorrectMatrix` to correct the matrix?
2. Another questions is the difference of ICE and KR. Based on the help of `hicCorrectMatrix`, if we use ICE, there are a lot of threshold to control. While there are noting for KR normalization. I am kind of confused.
Thank you!

**Comment by LeilyR** [comment]
Hi, 
1. It is recommended to do the normalization prior to matrix balancing. 
2. You are right, KR doesn't need any threshold. The algorithm guaranties the convergence even in the presence of low quality regions.

**Comment by Linhua-Sun** [comment]
Thanks!
