### ISSUE TITLE
hicPlotMatrix --bigwig not at correct position

### ISSUE THREAD

**Issue by GinaRe** [deeptools/HiCExplorer#462]
When I use `hicPlotMatrix --bigwig PC1.bw` without `--clearMaskedBins` to plot a Hi-C matrix and its A/B compartment track, the position of the bw track is not correct. This only happens when the start of a chromosome is removed (using hicAdjustMatrix). The bw track in the following plot should start at the start of the matrix.
[Dmel_m50_pearsonMatrix_v10.pdf](https://github.com/deeptools/HiCExplorer/files/3864664/Dmel_m50_pearsonMatrix_v10.pdf)

**Comment by joachimwolff** [comment]
Implemented with version 3.5.

**Comment by GinaRe** [comment]
I have tested version 3.5. The same problem persists. Here are the examples:
1) hicPlotMatrix -m Dmel_m50_pearsonMatrix.h5 -o Dmel_m50_pearsonMatrix_v11.pdf --bigwig Dmel_A840_Rep1_Rep2_merge_m50_corrected_adjusted_PCA.bw --chromosomeOrder 2R
2) hicPlotMatrix -m Dmel_m50_pearsonMatrix.h5 -o Dmel_m50_pearsonMatrix_v12.pdf --bigwig Dmel_A840_Rep1_Rep2_merge_m50_corrected_adjusted_PCA.bw --chromosomeOrder 2R  --clearMaskedBins

The second version using `--clearMaskedBins` shows the correct position of the bw track. I have removed 0-7Mb from the matrix using hicAdjustMatrix.
[Dmel_m50_pearsonMatrix_v11.pdf](https://github.com/deeptools/HiCExplorer/files/4988483/Dmel_m50_pearsonMatrix_v11.pdf)
[Dmel_m50_pearsonMatrix_v12.pdf](https://github.com/deeptools/HiCExplorer/files/4988484/Dmel_m50_pearsonMatrix_v12.pdf)

**Comment by LeilyR** [comment]
I have tested this, and I generated another error. 
`envs/HiCExplorer-3.5/lib/python3.7/site-packages/hicexplorer/hicPlotMatrix.py", line 962, in plotBigwig
    num_bins = int(bigwig_end - region_start) // pResolution
ZeroDivisionError: integer division or modulo by zero`
