### ISSUE TITLE
how to comvert .h5 matrix into .txt file

### ISSUE THREAD

**Issue by benxiahu** [deeptools/HiCExplorer#471]
I used hicCorrectMatrix to get the correct matrix. Would you tell me how to get the normalized matrix from the correct matrix generated by hicCorrectMatrix?
best

**Comment by gtrichard** [comment]
Hello,

Thank you for using HiCExplorer. 

Please define "normalized".

**Comment by benxiahu** [comment]
I have changed it.

**Comment by gtrichard** [comment]
If you mean hicNormalize, it is better to use it before hicCorrectMatrix

**Comment by benxiahu** [comment]
thanks. 
how to convert. h5 file to. txt file if I use hicNormalize?
