### ISSUE TITLE
saddle plot feature

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#472]
Hi,
Thank you for the user-friendly hic analysis tool. 
I was wondering if you guys are implementing the saddle plot feature present in cooltools:
https://github.com/mirnylab/cooltools/blob/master/cooltools/saddle.py
If I understand correctly, it's just hicPlotMatrix of obs/exp matrix with genomic positions ordered and averaged in the ranking of an arbitrary bedgraph-like file.
I ask because I want to do the analysis on only a subset of a chromosome, but hicAdjustmatrix breaks compatibility with cooltools.
Thank you! - Jun

**Comment by LeilyR** [comment]
Hi, We have a module called `hicCompartmentsPolarization` which designs to study the separation of compartment. It saves a matrix  if `--outputMatrix` which can then be plotted as a heatmap. This is comparable with the saddle plot from the mirny's lab. However, I have recently fixed some bugs in it which are not available in the current release, though it is accessible via our github on a branch called  `fix_polarization`. I have also fixed a bug in `hicAdjustMatrix --keep` available in that same branch which might help you. Hopefully these changes will be out in the next release, but for now please feel free to use `fix_polarization` branch

**Comment by kimj50** [comment]
Hi,
Thank you for the quick reply.
I haven't tried plotting the matrices in npz file but...
I tried the following with your recommendation. We've been using version 3.2. We updated to 3.3+the branch. Here is what I see. 
AdjustMatrix(3.2 OR the 3.3+branch, same region) -> hicPCA(3.3) -> plotmatrix(3.3).
The two bigwigs are pca1 and pca2. The 3.3 seems to keep contacts that contain the requested region even when the bin of the region only on one end of the pair. This also seems to result in weird hicPCA output.
[test_3.3.pdf](https://github.com/deeptools/HiCExplorer/files/3958219/test_3.3.pdf)
[test_3.2.pdf](https://github.com/deeptools/HiCExplorer/files/3958220/test_3.2.pdf)

Despite the weird matrix of 3.3 adjusted... I tried converting it to cool and tried cooltools and gave me the following error:
(base) [kimj50@c40-03 analysis]$ cooltools call-compartments regions_3.3.cool -o test                                                                                                        Traceback (most recent call last):
  File "/share/apps/hicexplorer/3.2/bin/cooltools", line 10, in <module>
    sys.exit(cli())
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/cooltools/cli/call_compartments.py", line 65, in call_compartments
    clr = cooler.Cooler(cool_path)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/cooler/api.py", line 80, in __init__
    self._refresh()
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/cooler/api.py", line 84, in _refresh
    with open_hdf5(self.store, **self.open_kws) as h5:
  File "/share/apps/python3/3.6.3/intel/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/cooler/util.py", line 576, in open_hdf5
    fh = h5py.File(fp, mode, *args, **kwargs)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/share/apps/hicexplorer/3.2/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'regions_3.3.cool', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I know that if I don't use adjustmatrix, and simply convert h5 to cool the entire matrix, the cooltools is compatible.

Thank you! - Jun

**Comment by LeilyR** [comment]
did you use hicadjust matrix with --keep from the fix_polarization branch , not the released version? The figure you have sent doesn't seem to be right. I have tested it here and it seems fine. 
You should do something like this:
1. git clone -b fix_polarization git@https://github.com/deeptools/HiCExplorer.git
2. make a frash conda env and activate it
3. python setup.py 
We will check for you second question about h5 to cool format and will get back to you

**Comment by kimj50** [comment]
Sorry I was using 3.3 without the branch. 
AdjustMatrix works well with the fix_polarization branch, although compartmentpolarization function seems to give me no graph. cooltools is still incompatible with adjustmatrix. Thanks! - Jun

[test_3.2.pdf](https://github.com/deeptools/HiCExplorer/files/3962772/test_3.2.pdf)
[test_branch.pdf](https://github.com/deeptools/HiCExplorer/files/3962773/test_branch.pdf)

**Comment by LeilyR** [comment]
compartmentPolarization generates an npz matrix (--outputMatrix) which you need to use something like matplotlib imshow to plot it as a heatmap.

We will work on the hicadjustmatrix compatibility with cool format, thanks for the report!

**Comment by kimj50** [comment]
i plotted --outputMatrix file using imshow and it works. Thanks! - Jun
![plot](https://user-images.githubusercontent.com/47995646/71265162-a2bf0580-2313-11ea-8f1c-a486b4ee3ce9.png)

**Comment by kimj50** [comment]
it seems that if I use a bedfile containing regions A and B using hicadjustmatrix, then the outputmatrix contains all interactions withinA, withinB, and A-B, including all intra and inter chromosomal. I was wondering if you considered making an option for keeping only withinA and withinB (ie matrix along the main diagonal). It might be useful for computing distVScontact for TADs and such...But obviously this can be done manually using the current hicadjustmatrix. 
Anyways, amazing tool. Thanks!

**Comment by gtrichard** [comment]
Yes you can use hicAdjustMatrix to keep only A or B interactions and subsequently compute hicPlotDistVsCounts, it works pretty well.
