### ISSUE TITLE
hicSumMatrices not Generating output file

### ISSUE THREAD

**Issue by adamxmiranda** [deeptools/HiCExplorer#476]
I've been trying to use the hicSumMatrices function to combine 3 replicate matrices, but there is no output file being created. I'm not receiving any error messages, there is just no output file. Any help will be greatly appreciated. My input is copied below.

hicSumMatrices -m WT_rep1_10000bp_matrix.h5 WT_rep2_10000bp_matrix.h5 WT_rep3_10000bp_matrix.h5 --outFileName WT_10kb_pooled

**Comment by LeilyR** [comment]
Add `.h5` for the output, that might do the job

**Comment by adamxmiranda** [comment]
Thanks so much for your help! That solved my issue.

You may need to amend the documentation because on the documentation it says explicitly **not** to add the .h5 for the output.

**Comment by LeilyR** [comment]
Sure, thanks for brining it up. We will fix it in the next release.
