### ISSUE TITLE
question about QC read pair type discrepancy with HiCPro

### ISSUE THREAD

**Issue by hwick** [deeptools/HiCExplorer#477]
Hello,
The HiC Explorer QC outputs the following percentages for read pair types for one of my samples:
Read pair type: inward pairs	10156839	(7.82)
Read pair type: outward pairs	28998981	(22.33)
Read pair type: left pairs	10991141	(8.46)
Read pair type: right pairs	11073298	(8.53)

Which is odd because the HiC-Pro mRSstat file on  the same data says that they are roughly even:
Valid_interaction_pairs	374332424
Valid_interaction_pairs_FF	91926271
Valid_interaction_pairs_RR	93050991
Valid_interaction_pairs_RF	96727094
Valid_interaction_pairs_FR	92628068

I used the same bam files for both HiC-Pro and HiC Explorer, aligned with bowtie2. Using hicexplorer 3.3 and hicpro 2.11.1
I'm curious what might lead to such a discrepancy, and if there is any way of filtering out the extraneous outward pairs detected by HiC Explorer?
Thank you

**Comment by joachimwolff** [comment]
Hi,

thanks for asking this question. 

To have a chance to understand what is going on we need more information.

1. Which HiCExplorer tool did you use? hicBuildMatrix or hicQuickQC?
2. Can you give us the full QC reports?
3. You write, this happens for one of your samples. How is the situation for other samples of yours?
4. Have you used any specific bowtie2 settings?

Best,

Joachim

**Comment by hwick** [comment]
Hi Joachim, thanks for getting back to me.
To answer your questions:
1. I used hicBuildMatrix

2. I've attached the QC.log as well as all the text files produced for one of the samples; let me know if you'd like the rest of the samples
[discarded_table.txt](https://github.com/deeptools/HiCExplorer/files/4036277/discarded_table.txt)
[distance_table.txt](https://github.com/deeptools/HiCExplorer/files/4036278/distance_table.txt)
[QC_table.txt](https://github.com/deeptools/HiCExplorer/files/4036279/QC_table.txt)
[read_orientation_table.txt](https://github.com/deeptools/HiCExplorer/files/4036280/read_orientation_table.txt)
[unmapable_table.txt](https://github.com/deeptools/HiCExplorer/files/4036281/unmapable_table.txt)
[QC.log](https://github.com/deeptools/HiCExplorer/files/4036282/QC.log)
3. I got similar stats on all 3 of the samples I ran so far; in HiC-Pro I get a pretty even ratio for all of them, but in HiC Explorer the outward pairs are quite elevated

4. Bowtie was run as a part of HiC-Pro, with the following options set in the config file; bowtie2-2.2.4 was used:
```
BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder
BOWTIE2_LOCAL_OPTIONS =  --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder
```
HiC-Pro then combines these bowtie results, and the resulting bam file is what I fed into HiC Explorer.

Best,
~ Heather

**Comment by YuZhang337** [comment]
Hi Heather, 
  I used the same merged bam files from HiC-Pro and fed into HiC Explorer like you , but I got an error like 
AssertionError: FATAL ERROR CL100150972L1C001R001_345/1 CL100150972L1C001R001_345/2 Be sure that the sam files have the same read order If using Bowtie2 or Hisat2 add the --reorder option.
 I also used bowtie2 to mapping my raw data then fed into HiC Explorer, and I got the same error, so I want to ask have you encountered the same error or could you show me your commond in hicBuildMatrix?
Thank you!
