### ISSUE TITLE
hicPCA. inter-chromosomal information

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#483]
Hi,
I noticed that cooltools call-compartments have --conact-type trans option.
I was wondering if hicPCA uses any information from inter-chromosomal portion of the matrix.
Or if there will ever be an option to just use inter-chromosomal interaction to compartmentalize.
Thanks for the great tool! - Jun

**Comment by LeilyR** [comment]
At the moment it only takes the contact on each chromosome (intra-chromosomal interaction) into account to compute the pca values for each chromosome independently.

**Comment by kimj50** [comment]
thank you - Jun
