### ISSUE TITLE
Chromosome length problem

### ISSUE THREAD

**Issue by wzhjlau2009** [deeptools/HiCExplorer#484]
Hi，
When I used hisexplorer to do the compartment analysis ，I found the chromosome length seem not correct in the output picture， for exampleexample ，the real length of chr 1 is about 169M ，but in the picture is above 175M in horizontal direction. When i used the hicPlotTAD, i also get an error about the chr length mistake ,the real Hic_asm_4 is about 145M , but it turns out the size of Hic_asm_4 is only about 129.88 M , I don't know how to solve this problem , Thanks very much !
![image](https://user-images.githubusercontent.com/6326115/72705420-5d058f00-3b96-11ea-9b0d-6a93660701f1.png)
![image](https://user-images.githubusercontent.com/6326115/72705810-617e7780-3b97-11ea-91c7-9e127a2be65b.png)

**Comment by gtrichard** [comment]
Hello,
What is `hicInfo` giving you for that matrix?

**Comment by LeilyR** [comment]
the reason for the error is that you try to plot a region out of chromosome length boundary.  Check your data and the reference genome you use . Also be sure that you didnt mask or remove any part of a chromosome before plotting using tools such as hicAdjustMatrix. Those blue strips look like that to me.

**Comment by wzhjlau2009** [comment]
@gtrichard , @LeilyR 
Hi, this is the size of the chromosomes from the genome fasta file
![image](https://user-images.githubusercontent.com/6326115/73259764-6f6d7180-4203-11ea-92d3-39e5afc94cc7.png)
and also the hicInfo output for the pca matrix, thanks! 
![image](https://user-images.githubusercontent.com/6326115/73259833-99bf2f00-4203-11ea-8874-628fdbb6a7af.png)
By the way , I only used the hicCorrectMatrix  correct tools with the --filterThreshold -2 2. this is the diagnostic_plot ,  I didnt mask or remove any part of a chromosome before plotting using tools such as hicAdjustMatrix. 
![diagnostic_100k](https://user-images.githubusercontent.com/6326115/73260151-4ac5c980-4204-11ea-808d-8aee566425a1.png)

**Comment by gtrichard** [comment]
thanks for the details @wzhjlau2009 . I have one small request, could you use the develop branch from HiCExplorer (clone the repo and manipulate your PYTHONPATH so it's pointing to the cloned repo dir) and test `hicInfo` on your matrix?

It should give you the size of the matrix for each chromosome.

**Comment by wzhjlau2009** [comment]
@gtrichard ,
Thanks for your help! yes , i have check the PCA score of the Hi-C matrix, this is the beginning 
![image](https://user-images.githubusercontent.com/6326115/73268665-56ba8700-4216-11ea-96bf-256167bf187c.png)
and this is the end 
![image](https://user-images.githubusercontent.com/6326115/73268717-6d60de00-4216-11ea-909c-27750a4c8753.png)
I think NA value is the empty loci,  But i still have one question about what makes this happen，because of no reads map at the beginning and the end of the chromosome？or because the Hi-C sequencing library ？ or because I have used the hicCorrectMatrix correct tools with the --filterThreshold -2 2 and Some data was artificially discarded ？Such as these data in the red circus.
![image](https://user-images.githubusercontent.com/6326115/73269766-62a74880-4218-11ea-8375-e6b18569d865.png)

**Comment by wzhjlau2009** [comment]
@gtrichard 
When I used the correct Matrix to plot, I also found some area missing in the output picture. and I don't know why. 

![Uploading chr3.png…]()
![Uploading chr10.png…]()
![Uploading chr11.png…]()
![Uploading chr12.png…]()






![Uploading chr3.png…]()
![Uploading chr10.png…]()
![Uploading chr11.png…]()
![Uploading chr12.png…]()

**Comment by wzhjlau2009** [comment]
@gtrichard
When I used the correct Matrix to plot, I also found some area missing in the output picture. and I don't know why.
![image](https://user-images.githubusercontent.com/6326115/73270634-034a3800-421a-11ea-98ea-c834a4df8ab8.png)
![image](https://user-images.githubusercontent.com/6326115/73270674-152bdb00-421a-11ea-850c-43af594ddb98.png)
![image](https://user-images.githubusercontent.com/6326115/73270690-2248ca00-421a-11ea-8efa-8da1e148b05f.png)

**Comment by gtrichard** [comment]
These huge blocks must correspond to centromeres / repetitive regions. No reads map there, hence you don't have Hi-C contacts in these regions.

You can plot uncorrected matrices, you will have the same profile I guess.

For the bigwigs, it would help you to check the actual bins coordinates to know if there's an issue with the chromosome size in your contact matrix.

Also, I think you have assembly issues on Hic_asm_11 :smile:

**Comment by wzhjlau2009** [comment]
@gtrichard 
Hi，I have plotted the uncorrected matrices.
![image](https://user-images.githubusercontent.com/6326115/73355847-fdb12880-42d3-11ea-8443-5b3c22cf1757.png)
![image](https://user-images.githubusercontent.com/6326115/73355874-09045400-42d4-11ea-9a1b-5b64fff02b68.png)
![image](https://user-images.githubusercontent.com/6326115/73355889-11f52580-42d4-11ea-950c-8c5ac39d6b5b.png)
And i also check the last bins of the Hic_asm_0, it is indeed different with the total length of the genome fasta file. 
![image](https://user-images.githubusercontent.com/6326115/73357105-aceeff00-42d6-11ea-820b-6998c653a9e5.png)
I also analysis the gene density of each chromosome, such as the pic below. But I found these missing region looked like gene-rich region. And I don't know why. Thanks.
![image](https://user-images.githubusercontent.com/6326115/73357133-bc6e4800-42d6-11ea-9169-97d7c435201a.png)

**Comment by gtrichard** [comment]
Can you detail the way you obtained your matrices?

The chromosome plots you made are representing the genes density along each chromosome (I would like to know which tool you used to represent that, I like this last plot a lot eheh)? It is indeed weird you don't have contacts over the beginning of the chromosomes. How .bam files that you used to build the matrix are looking under IGV for these regions (beginning and end of the first chromosome for instance)?

**Comment by wzhjlau2009** [comment]
@gtrichard 
Hi, I used HiC-Pro to get the iced matrix and abs.bed, then I used hicConvertFormat -m sample1_100000_iced.matrix --bedFileHicpro sample1_100000_abs.bed --inputFormat hicpro --outputFormat h5 -o 100000_matrix.h5 to get the h5 format matrix.
The last plot I used a R package called RIdeogram to draw the pic.
This is the total plot of the uncorrected matrix
![image](https://user-images.githubusercontent.com/6326115/73452544-0f163580-43a5-11ea-80ce-b89e228cd63f.png)

**Comment by gtrichard** [comment]
I'm not sure your problem is related to HiCExplorer per se. We never get such issues using HiCExplorer based pipelines.

Please check snakePipes HiC pipeline, it works really well.
https://snakepipes.readthedocs.io/en/latest/content/workflows/HiC.html

**Comment by LeilyR** [comment]
@wzhjlau2009 Since we have not heard of you again, we assume your problem is solved. I close this issue for now but feel free to reopen it if there is still any question left.
