### ISSUE TITLE
hicAdjustMatrix- Index Error

### ISSUE THREAD

**Issue by pqyNUS** [deeptools/HiCExplorer#487]
Hi,

I tried to run hicAdjustMatrix with the following command:
hicAdjustMatrix -m matrix.cool --action mask --regions badRegions.bed -o matrix_masked.cool

however, i get this error:
ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/hpctmp2/a0123882/hicexplorer/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 262, in getRegionBinRange
    endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
IndexError: list index out of range

my badRegions.bed file contains regions of from the ucsc (hg38) database: 
1. http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/gap.txt.gz
2. http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz

subsequently, I split the badRegions.bed file into windows of 5000bp for those which are higher than my matrix bin size (as i read in #322 that the hicAdjustMatrix crashes when dealing with bed regions bigger than matrix bin size)

Please advise if I had done something wrong in executing the adjust matrix command

Thanks!

**Comment by gtrichard** [comment]
Hello,

>  I split the badRegions.bed file into windows of 5000bp for those which are higher than my matrix bin size

This I don't really get.

If you try to reduce the range of the last bin of your bed file so that it's less than the matrix size for a given chromosome, I think it should fix the issue, here's an example:

In your Hi-C matrix Chr1 is 19,000,000bp long, in your bed file, the last region for Chr1 should be strictly inferior to 19,000,000 (i.e. 18,999,999).

Your matrix should anyways have a bin size > 1000bp, so it is pointless to have bed files with exact coordinates (18,999,999 vs 18,999,000 would give the exact same output from hicAdjustMatrix). As long as the bed file coordinates are overlapping with the corresponding matrix bins, those bins will be masked/removed by hicAdjustMatrix.

**Comment by pqyNUS** [comment]
Hi,

what i meant was the badRegions.bed file had region sizes above 10,000bp. 
> head badRegions.bed
#chrom  start   end     range
1       1       87112   " 87,111 "
1       87114   297956  " 210,842 "
1       297969  817292  " 519,323 "
1       817368  821400  " 4,032 "
1       823660  867135  " 43,475 "
1       867193  872507  " 5,314 "
1       872880  898701  " 25,821 "
1       955922  960557  " 4,635 "
1       1075857 1079032 " 3,175 "

thus, i split those regions sizes > 10,000bp to regions of 5000bp long (using bedtools makewindows)

>head badRegions_5k.bed
#chrom  start   end     range
1       1       5000    " 4,999 "
1       5001    10000   " 4,999 "
1       10001   15000   " 4,999 "
1       15001   20000   " 4,999 "
1       20001   25000   " 4,999 "
1       25001   30000   " 4,999 "
1       30001   35000   " 4,999 "
1       35001   40000   " 4,999 "
1       40001   45000   " 4,999 "

my matrix bin size is 25,000bp. I checked my badRegions.bed, and saw that there are regions on Chr1 that is more than 19,000,000. for example:

#chrom  start   end     range
1       25,412,423	25,417,422	   " 4,999 "

Is it ok to leave these regions in the badRegions.bed? As you mentioned that the bins will be masked/removed for those bed file coordinates that overlaps the corresponding matrix bins. 

If not, how could I remove these regions that exceed the matrix bins' coordinates, as I am not sure what is the start & end coordinates of the matrix for each chromosome. So far, I only checked if my bed file coordinates are within the chrom sizes of hg38

thanks

**Comment by LeilyR** [comment]
Please remove those regions which are exceeding the length of chromosome and try again, that may solve the issue.

**Comment by pqyNUS** [comment]
I checked my regions against the chrom.sizes file from UCSC (hg38), and the regions are within the chromosome sizes. How should i check against the actual length in the HiC matrix instead?

**Comment by LeilyR** [comment]
hicInfo will give you the chr length of chromosomes you have used to generate your matrix.

**Comment by gtrichard** [comment]
> what i meant was the badRegions.bed file had region sizes above 10,000bp.

This is not an issue, you can have regions as large as you want in the bed file (for instance whole centromeres in only 1 line in your bed file). However the bed file features must be STRICTLY (i.e. <, not <=) below the size of the chromosomes indicated by `hicInfo` as Leily pointed out.

**Comment by pqyNUS** [comment]
yes. Thank you for the advice. 
btw, i tried to hicInfo as suggested. but i do not get any info on the sizes of the chromosomes. The output i get is the same as the one in the documentation.

Example:
File:        hic_matrix.h5
WARNING: bin size is not homogeneous. Median 434
Size:        339,684
Sum: 243,779,407
Bin length:  434
Chromosomes: 2L, 2R, 3L, 3R, 4, X
Non-zero elements:   229,122,848
Minimum:     0
Maximum:     2116
NaN bins:    0

**Comment by LeilyR** [comment]
which version are you using? I have just tested and it looks like this: 
Size:	3,383
Bin_length:	50000
Sum of matrix:	19490384.234475713
Chromosomes:length: 2L: 23011544 bp; 2LHet: 368872 bp; 2R: 21146708 bp; 2RHet: 3288761 bp; 3L: 24543557 bp; 3LHet: 2555491 bp; 3R: 27905053 bp; 3RHet: 2517507 bp; 4: 1351857 bp; U: 10049037 bp; Uextra: 29004656 bp; X: 22422827 bp; XHet: 204112 bp; YHet: 347038 bp; dmel_mitochondrion_genome: 19517 bp; 
Non-zero elements:	2,714,341
Minimum (non zero):	0.26503369708639324
Maximum:	12608.682781602649
NaN bins:	752

We might need to update the documentation though.

**Comment by pqyNUS** [comment]
I am using Hicexplorer 3.3

**Comment by pqyNUS** [comment]
sorry, does it make a difference if i run hicInfo on cool format versus .h5 format?
as i ran it on cool format

**Comment by LeilyR** [comment]
yeah the output can look different, in cool format it depends what you have saved as metadata.

**Comment by pqyNUS** [comment]
yes i tried running on h5 format but i get the following for chromosome

Chromosomes:    M, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y

i do not get the "chromosomes:length" output

**Comment by LeilyR** [comment]
did you use hicBuildMatrix to generate a .cool matrix and then converted it to h5? That could be the reason and if so we have to fix it on our side. For now, could you please try building a .h5 matrix from scratch and see if you still miss the chr length?

**Comment by pqyNUS** [comment]
i used homer to generate .hic files from the homer TagDirectories. ok i will try building the h5 matrix using the hicexplorer pipeline

**Comment by LeilyR** [comment]
actually we have just checked and the length feature is not in the current released version. We tag a new release today and you can hopefully have it from tomorrow.

**Comment by gtrichard** [comment]
Alternatively you can use the current "develop" branch if you are impatient :smiley:

**Comment by LeilyR** [comment]
Our new release is out and is already available as a conda package. please try version 3.4

**Comment by cjy8709** [comment]
Hello hicexplorer developers

Sorry to hijack this thread but I had a similar problem with hicPCA.
Let me show the error first

 
> $ hicPCA -m DpnII_Osat_Osativa.matrix.50bins.corrected.cool -o pca1.50bins.bw pca2.50bins.bw --format bigwig --extraTrack Osativa_IRGSP-1.0.locus.gene.sorted.bed 
> ERROR:hicmatrix.HiCMatrix:Index error
> Traceback (most recent call last):
>   File "/home/jyc387/miniconda2/envs/hicexplorer3.4/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 262, in getRegionBinRange
>     endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
> IndexError: list index out of range
> Traceback (most recent call last):
>   File "/home/jyc387/miniconda2/envs/hicexplorer3.4/bin/hicPCA", line 7, in <module>
>     main()
>   File "/home/jyc387/miniconda2/envs/hicexplorer3.4/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 334, in main
>     vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
>   File "/home/jyc387/miniconda2/envs/hicexplorer3.4/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 158, in correlateEigenvectorWithGeneTrack
>     gene_occurrence[bin_id[1]] += 1
> TypeError: 'NoneType' object is not subscriptable

I think the error I have is very similar to the original posters error as well. 
Note I use hicexplorer 3.4 and a .cool file for the hi-c matrix. But the matrix was generated using an experimental long-read based hi-c protocol so I use our in-house long-read based hi-c caller. Without too much detail it basically generates a pairs file which then I converted to a .cool file with the cooler tools. Note that I used hicexplorer (although using the old v2.2) for calling TADs comparment etc and had no problems. Its just using the --extraTrack on hiPCA that i have a problem.

I don't think my bed file is bigger then the chromosome size since when I tail my bed its looks like:

> $ tail Osativa_IRGSP-1.0.locus.gene.sorted.bed 
> chr01	637962	639060	Os01g0112201	0	+
> chr01	640698	644217	Os01g0112300	0	+
> chr01	645598	646722	Os01g0112400	0	+
> chr01	648288	651869	Os01g0112500	0	+
> chr01	677029	677602	Os01g0112600	0	+
> chr01	689788	693923	Os01g0112800	0	+
> chr01	700533	706399	Os01g0113000	0	+
> chr01	710956	714232	Os01g0113150	0	+
> chr01	720673	723317	Os01g0113200	0	+
> chr01	723693	726099	Os01g0113300	0	+

And that last line "chr01	723693	726099	Os01g0113300	0	+" is the problem since if I delete it hiPCA runs fine. If I don't then hiPCA breaks with the above error message.
When I do hicInfo it looks like:

> $ hicInfo -m DpnII_Osat_Osativa.matrix.50bins.cool
> Matrix information file. Created with HiCExplorer's hicInfo version 3.4
> File:	DpnII_Osat_Osativa.matrix.50bins.cool
> Date:	2020-02-01T17:32:19.535534
> Genome assembly:	unknown
> Size:	7,252
> Chromosomes:length: chr01: 43258000 bp; chr02: 35937000 bp; chr03: 36413819 bp; chr04: 35502694 bp; chr05: 29958000 bp; chr06: 31248787 bp; chr07: 29696000 bp; chr08: 28442000 bp; chr09: 22991000 bp; chr10: 23207000 bp; chr11: 29009000 bp; chr12: 27531000 bp; 
> Number of chromosomes:	12
> Non-zero elements:	21,534,500
> The following columns are available: ['chrom' 'start' 'end']
> 
> 
> Generated by:	HiCMatrix-11
> Cooler library version:	cooler-0.8.5
> HiCMatrix url:	https://github.com/deeptools/HiCMatrix
> 

Any suggestions on the error?

**Comment by pqyNUS** [comment]
Hi LeilyR and gtrichard,
i got the hicInfo to show the chromosome length for each chromosome, after processing according to the hicexplorer documentation. 

 'Chromosome:length' output for hicInfo on my matrix file:
"Chromosomes:length: chr1: 248950000 bp; chr2: 242193529 bp; chr3: 198295559 bp; chr4: 190200000 bp; chr5: 181538259 bp; chr6: 170800000 bp; chr7: 159345973 bp; chr8: 145138636 bp; chr9: 138394717 bp; chr10: 133797422 bp; chr11: 135086622 bp; chr12: 133275309 bp; chr13: 114350000 bp; chr14: 107043718 bp; chr15: 101991189 bp; chr16: 90338345 bp; chr17: 83250000 bp; chr18: 80373285 bp; chr19: 58600000 bp; chr20: 64444167 bp; chr21: 46700000 bp; chr22: 50800000 bp; chrX: 156040895 bp; chrY: 57227415 bp;"

before i ran the hicAdjustMatrix:
1. I updated the hicexplorer to the newest version (v 3.4)
2. I applied hicCorrectMatrix with correction method set to 'KR'
2. I removed the regions from the bedfile (badRegions.bed) that were outside(>=) of the max chromosome length, based on hicInfo output. 

for example (badRegions.bed)
#chrom---start---end---chrom_max_length(hicInfo)
chr1---248946422---248956400---248950000---discard
chrY---57217415---57227415---57227415---discard

hicAdjustMatrix command:
hicAdjustMatrix -m matrix_50k.h5 --action mask --regions badRegions.bed -o matrix_50k_masked.h5

the hicAdjustMatrix ran without any errors.

thanks so much again for identifying the issues and solving it.

**Comment by LeilyR** [comment]
Happy to hear that.

**Comment by gtrichard** [comment]
@cjy8709  I think it is better if you post your error in a new issue.
