### ISSUE TITLE
hicAverageRegions fails when too close to the borders

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#493]
Hi,
I got an error when I launched `hicAverageRegions` on a matrix with multiple chromosome and I was close to the border (but I think you could reproduce the but with a matrix with only one chromosome if you are close to the border):
```
Traceback (most recent call last):
  File "/home/ldelisle/.local/bin/hicAverageRegions", line 7, in <module>
    main()
  File "/home/ldelisle/.local/lib/python3.7/site-packages/hicexplorer/hicAverageRegions.py", line 129, in main
    summed_matrix[_start:_end, _start:_end] += hic_ma.matrix[start:end, start:end]
  File "/home/ldelisle/.local/lib/python3.7/site-packages/scipy/sparse/base.py", line 415, in __add__
    raise ValueError("inconsistent shapes")
```
I found the bug:
https://github.com/deeptools/HiCExplorer/blob/4acc900f4800a9e8dd0150d3318fc657e5084215/hicexplorer/hicAverageRegions.py#L152-L157
You check if `start < 0` or `end >= hic_ma.matrix.shape[1]`.
I think start will never be negative and end will never be equal to the shape.
What I used is:
```
    start_bins = [ hic_ma.chrBinBoundaries[chrom][0] for chrom in hic_ma.getChrNames() ]
    end_bins = [ hic_ma.chrBinBoundaries[chrom][1] - 1 for chrom in hic_ma.getChrNames() ]
    for start, end in indices_values:
        _start = 0
        _end = summed_matrix.shape[1]
        if (end - start) < summed_matrix.shape[1]:
            print(start, end)
            if start in start_bins and end in end_bins:
              # I cannot use because I do not know the center
              print("What")
              pass
            elif start in start_bins:
              _start = summed_matrix.shape[1] - (end - start)
            elif end in end_bins:
              _end = end - start
            else:
              print("WhatWhat")
        if (end - start) == (_end - _start):
            summed_matrix[_start:_end, _start:_end] += hic_ma.matrix[start:end, start:end]
        else:
            print("Impossible to determine start or end for {}, {}".format(start, end))
```
This is an ugly fix but it is to help you to see how to solve the issue.
Also my bugfix is incorrect because this will divide all values of the summed_matrix by the length of indices_values whereas in some cases there were no data...

**Comment by lldelisle** [comment]
Oups, version hicAverageRegions 2.2.1.1
But I think it is still the case.

**Comment by LeilyR** [comment]
how do you mean by `close to a border`? you region excess the end of chr?

**Comment by lldelisle** [comment]
My "viewpoint" is 100kb from the border and I put "range" 200kb each size.

**Comment by joachimwolff** [comment]
Please try version 3.4, version 2.2.1.1 is quite old and I am sure I applied changes to hicAverageRegions in the meantime.

**Comment by gtrichard** [comment]
Sorry misclicked "close issue"

I think you can install miniconda on any machine by the way, being root or not.

**Comment by lldelisle** [comment]
I am sorry, but I just tested with the last version available on conda, I took the files in https://github.com/deeptools/HiCExplorer/tree/master/hicexplorer/test/test_data/hicAverageRegions:
```
(hicexplorer) [ldelisle@SV-49-002 hicex]$ hicAverageRegions --version
hicAverageRegions 3.4
(hicexplorer) [ldelisle@SV-49-002 hicex]$ hicAverageRegions --matrix small_test_matrix.cool --region regions.bed -o test --range 3000000 3000000
Traceback (most recent call last):
  File "/home/ldelisle/.conda/envs/hicexplorer/bin/hicAverageRegions", line 7, in <module>
    main()
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicAverageRegions.py", line 159, in main
    summed_matrix[_start:_end, _start:_end] += hic_ma.matrix[start:end, start:end]
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/lil.py", line 135, in __iadd__
    self[:,:] = self + other
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/base.py", line 418, in __add__
    raise ValueError("inconsistent shapes")
ValueError: inconsistent shapes
```
Also:
```
(hicexplorer) [ldelisle@SV-49-002 hicex]$ echo -e "chr2L\t10000" > test_close_beginning.bed
(hicexplorer) [ldelisle@SV-49-002 hicex]$ hicAverageRegions --matrix small_test_matrix.cool --region test_close_beginning.bed -o test --range 100000 100000
Traceback (most recent call last):
  File "/home/ldelisle/.conda/envs/hicexplorer/bin/hicAverageRegions", line 7, in <module>
    main()
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicAverageRegions.py", line 159, in main
    summed_matrix[_start:_end, _start:_end] += hic_ma.matrix[start:end, start:end]
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/lil.py", line 135, in __iadd__
    self[:,:] = self + other
  File "/home/ldelisle/.conda/envs/hicexplorer/lib/python3.6/site-packages/scipy/sparse/base.py", line 418, in __add__
    raise ValueError("inconsistent shapes")
ValueError: inconsistent shapes
```

**Comment by LeilyR** [comment]
so if I understood you correctly, your upstream regions pass the end of chromosome, right? I will check the tool's behavior for such a case and will get back to you.

**Comment by lldelisle** [comment]
It is the case in both directions:
If the region - range is below 0 or if region + range is above the chromosome size. It fails because `getBinIndices` adapt to the size of the chromosome to the start,end range is smaller than the _start,_end range.

**Comment by LeilyR** [comment]
what makes sense is that although the regions on either sides are going over a chromosome boundaries, it only takes the regions all the way to start of chromosome and/or to the end of it and returns the average for this window. I was assuming that is what  the line of code you have posted takes care of. I will have a look and see how it is

**Comment by LeilyR** [comment]
I started fixing this bug in #495 feel free to try it. So far I only fixed it for --range.

**Comment by LeilyR** [comment]
One thing that i am still not sure about it is, if this makes any sense to take the regions near to boundaries into count at all. Alternatively one can remove those regions and not use them at all.

**Comment by lldelisle** [comment]
This is also an alternative. This is what I am doing now but I think, you should add a warning when you are skipping a region.

**Comment by LeilyR** [comment]
Indeed

**Comment by LeilyR** [comment]
please check develop now, it should work for regions next to the chromosomes edges. Don't hesitate to contact us again if there was any other question.
