### ISSUE TITLE
Conda update?

### ISSUE THREAD

**Issue by adamxmiranda** [deeptools/HiCExplorer#494]
Is it possible to use conda update to update hicexplorer to the newest release. I've tried a few ways, but haven't had any success. Is there a specific way to update the hicexplorer version without totally reinstalling?

**Comment by joachimwolff** [comment]
I am not sure if I get your question. You can update an existing HiCExplorer installation via conda with `conda update hicexplorer --update-all`, as an alternative `conda install hicexplorer` or `conda install hicexplorer=3.4.1`. These commands all update an existing HiCExplorer installation. If this all doesn't help it make sense to create a new environment via `conda create --name hicexplorer3.4.1 hicexplorer=3.4.1 python=3.6`

I hope I could help,

Joachim

**Comment by adamxmiranda** [comment]
Sorry for the confusion. I was trying to update from 3.3 to 3.4 and when I tried to "conda update hicexplorer" it would not update to 3.4 and only reloaded 3.3. I ended up just creating a new conda environment and installing 3.4.1 within the new environment
