### ISSUE TITLE
expected_interactions does not give the expected output

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#496]
Hi,
I think there is an issue in:
https://github.com/deeptools/HiCExplorer/blob/ea19824e5e69d0b2a9595238b2f0cb3592cb81a7/hicexplorer/utilities.py#L282
Especially, here:
https://github.com/deeptools/HiCExplorer/blob/ea19824e5e69d0b2a9595238b2f0cb3592cb81a7/hicexplorer/utilities.py#L290
If you consider a full matrix (both upper corner and lower corner are full), then the occurence should be: shape for distance = 0 and then 2*(shape - distance) (each side of the diagonal), so: 
```
occurences = np.concatenate((np.asarray([pSubmatrix.shape[0]]), 2 * np.arange(pSubmatrix.shape[0] - 1, 0, -1)))
```
Then if you only consider the upper triangle, you should have:
```
occurrences = np.arange(pSubmatrix.shape[0], 0, -1)
for i, distance_ in enumerate(distance):
  if row[i] <= col[i]:
    expected_interactions[distance_] += pSubmatrix.data[i]
```

Here is a small test which shows the issue:
```
mat_test = csr_matrix((np.ones(100, 'int'), (np.repeat(np.arange(10), 10),np.tile(np.arange(10), 10))), shape=(10, 10))
mat_test.toarray()
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

e = expected_interactions(mat_test)
print(e)

[0.90909091 1.8        1.77777778 1.75       1.71428571 1.66666667
 1.6        1.5        1.33333333 1.        ]
```

**Comment by LeilyR** [comment]
this is an old function, we already dropped it from hicPCA. I just checked and saw it is still in hicTransform, we may even delete it from there for the next version too. Please you HiCPCA to generate obs/exp matrices. That is up to date.

**Comment by lldelisle** [comment]
OK many thanks

**Comment by lldelisle** [comment]
(but how can I get the matrix file ? I only see bedgraph or bigwig output)

**Comment by lldelisle** [comment]
Sorry `--obsexpMatrix`

**Comment by LeilyR** [comment]
there 2 different method provided
