### ISSUE TITLE
plotTads output does not line up

### ISSUE THREAD

**Issue by nt365** [deeptools/HiCExplorer#501]
I have attached my .ini file and the output, and the command is here:
hicPlotTADs --tracks dmel_dup1.ini -o dmel_dup1.png --region dmel_muller_A:5500000-6500000 , and the output. The 

This was run using HiCexplorer 3.4.1. The score minima line up with the TAD boundaries but the outlined domains look shifted from where the domains are evident on the contact map. This is not happening for other species. Any advice on what might be causing this and how to fix it would be greatly appreciated.

[dmel_dup1.ini.txt](https://github.com/deeptools/HiCExplorer/files/4183615/dmel_dup1.ini.txt)

![dmel_dup1](https://user-images.githubusercontent.com/55988255/74201805-b6faf100-4c38-11ea-9412-d2fa380b90fb.png)

**Comment by joachimwolff** [comment]
Hi,

can you add vertical lines based on the boundaries? It would make it easier for us to see if this is a problem of TAD calling or with the visualization.

Best,

Joachim

**Comment by joachimwolff** [comment]
@lldelisle Maybe a pyGenomeTracks issue?

**Comment by lldelisle** [comment]
Hi,
I think, you could replace `overlay previous = yes` by `overlay previous = share-y` to have the height of the TAD triangles to fit with the matrix. 
Could you tell me if this is your issue and if this solve it?

**Comment by nt365** [comment]
Thank you so much for the suggestions. I attached the plots with the vertical lines and "share-y". These look much better but I think the domain triangle outlines still look slightly offset?

Nicole

![dmel_dup1_sharey_vlines](https://user-images.githubusercontent.com/55988255/74248936-61fdc000-4cb6-11ea-98df-320a66941569.png)
![dmel_dup1_sharey](https://user-images.githubusercontent.com/55988255/74248938-62965680-4cb6-11ea-8374-c6451399e7ae.png)

**Comment by joachimwolff** [comment]
The TADs look good for me, but the TAD score value doesn't really match. @nt365 can you plot this with hicPlotTads in version 2.2? That is a version from a year ago, just as a test if we have this behaviour since a long time or it is a more recent bug.

**Comment by nt365** [comment]
Hi Joachim,

I did try using version 2.2 before upgrading. Here is the plot:
![dmel_dup1](https://user-images.githubusercontent.com/55988255/74251161-b6566f00-4cb9-11ea-8ae2-95f106184703.png)

**Comment by joachimwolff** [comment]
I think the problem is you use the wrong file, it should be the bedgraph matrix file. This one ends to `bm` and the filetype is `bedgraph_matrix`. Moreover, we usually set the type to 'lines':

```
[score]
file=TAD_information_in _bm_file.bm
file_type=bedgraph_matrix
type = lines
height = 3.5
```

Best,

Joachim

**Comment by lldelisle** [comment]
Hi,
I think the TAD calling is not so bad and aligned but just after 6Mb you can see that you had 2 consecutive bins with very close insulation index. Apprently, the second one is the minimum that's why the boundary is called on the second bin. I think you should play with the parameters of hicFindTADs.

**Comment by LeilyR** [comment]
changing tad parameters may change the quality of your tad calling but will not change the shift you see. Please follow what Joachim have suggested. You were using a wrong file to see the tad scores. Using `.bm` file should solve your issue.
