### ISSUE TITLE
Can't  found Requirements 

### ISSUE THREAD

**Issue by shiyi-pan** [deeptools/HiCExplorer#512]
hi, there are two Requirements -fit-nbinom and krbalancing that I can't found , is anybody give me an download RUL? Thank you very much

**Comment by dpryan79** [comment]
You are encouraged to use conda rather than installing with pip.

`krbalancing` is available here: https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm

`fit-nbinom` is available here: https://github.com/joachimwolff/fit_nbinom
