### ISSUE TITLE
PC plots irreproducible

### ISSUE THREAD

**Issue by MzwaneleN** [deeptools/HiCExplorer#514]
PC1 and PC2 tracks in the TADs plot look different from the PC1 and PC2 tracks in the TADs plot of the HiCExplorer tutorial figure. However, my PC plots underneath the pearson matrix are the same as the one in the HiCExplorer tutorial figure. I have used the same eigenvector files. 

I am not quite sure what could be the reason for the differences in the PC plots, is there something else I missed. Please help.

![TADs Plot](https://user-images.githubusercontent.com/61521905/76898949-0dc59d00-686d-11ea-9629-31db869afafa.png)
![pearson_matrix_from_PCA_Plot1](https://user-images.githubusercontent.com/61521905/76898963-1322e780-686d-11ea-88b4-e0ef64a29b7b.png)
![pearson_matrix_from_PCA_plot2](https://user-images.githubusercontent.com/61521905/76898972-17e79b80-686d-11ea-8007-195dbfb1e08c.png)

**Comment by AdrijaK** [comment]
I would also like to hear the reply on this question. 

Also, to me the PC1.bw  plot under the 'Pearson matrix and PC1' looks strange with half the chromosome being above and half - being below zero. Is this an indication that we have to look for PC2.bw instead to identify the compartments? 

Maybe somewhat related to https://github.com/deeptools/HiCExplorer/issues/277 where Joachim wrote: 

> I have to add here some information: In the most cases you look for PC1 and positive values correlate to open chromatin and negative to closed.
> All rules come with exceptions: some times it is PC2 and not PC1. For details on this please see Lieberman-Aiden 2009, in this paper the issues with principal component analysis are well explained. 

Is that correct?

**Comment by joachimwolff** [comment]
Hi,

the plots are not different. Please have in mind that the Pearson plot is for the full chromosome chr2L and the TAD plot only for a region of it: chr2L:14.5MB-16.5MB. 

![Galaxy7- hicPlotMatrix_on_hicPCA_on_data_1_ data_2_and_data_4 __Plot](https://user-images.githubusercontent.com/13435136/77046189-ca7d4280-69c2-11ea-8305-4c7f046c55f5.png)
![Galaxy8- hicPlotMatrix_on_hicPCA_on_data_1_ data_3_and_data_4 __Plot](https://user-images.githubusercontent.com/13435136/77046191-cc470600-69c2-11ea-8a37-283e6b8a38bc.png)
![Galaxy11- pyGenomeTracks_on_ data_3,_data_2,_and_data_1 __Plot](https://user-images.githubusercontent.com/13435136/77046197-cd783300-69c2-11ea-81e8-2d409be24a73.png)
![Galaxy14- hicPlotMatrix_on_hicPCA_on_data_1_ data_2_and_data_4 __Plot](https://user-images.githubusercontent.com/13435136/77046203-cea96000-69c2-11ea-9264-df619be13f05.png)
![Galaxy15- hicPlotMatrix_on_hicPCA_on_data_1_ data_3_and_data_4 __Plot](https://user-images.githubusercontent.com/13435136/77046208-cf41f680-69c2-11ea-8fe7-5109d507e158.png)


@AdrijaK This is not strange, it is to be expected and represents the chromosome arms and not the compartments. It is high likely that either PC1 or PC2 (in very rare cases PC3) are the chromosome arms or the compartments. Please have also in mind that different organism and different experiments may require different normalization methods to get the desired result.

Best,

Joachim


Best,

Joachim
