### ISSUE TITLE
hicDetectLoops dataset error

### ISSUE THREAD

**Issue by MzwaneleN** [deeptools/HiCExplorer#515]
I get data set error when I try to compute loops, even if I change -pit and the p-values.

Command line:
ln -s '/data/dnb02/galaxy_db/files/014/320/dataset_14320954.dat' 'matrix.h5' && hicDetectLoops  --matrix  'matrix.h5'  --peakWidth 6  --windowSize 10  --pValuePreselection 0.01  --peakInteractionsThreshold 5  --maximumInteractionPercentageThreshold 0.1 --pValue 0.01 --maxLoopDistance 2000000   --chromosomes 'chr1'  --statisticalTest wilcoxon-rank-sum  --outFileName output_loop.bedgraph  --threads ${GALAXY_SLOTS:-4} -tpc ${GALAXY_SLOTS:-4}

Error:
An error occurred with this dataset: INFO:hicexplorer.hicDetectLoops:peak interactions threshold set to 5.0

**Comment by joachimwolff** [comment]
You need to share your history with me, this error here can mean all and everything.

**Comment by MzwaneleN** [comment]
I have shared my history with you. Thanks

**Comment by joachimwolff** [comment]
Your command seems alright for and the error is a bit meaningless. As I wrote, for me it was running successful, maybe it helps to download the data from the ftp server directly to your histroy (via Paste/Fetch data option) instead of importing it from the Shared Data. It could be that this file is also effected by our data loss.

**Comment by bgruening** [comment]
> galaxy@sn04:~$ ll /data/dnb02/galaxy_db/files/014/320/dataset_14320954.dat
-rw-r--r--. 1 galaxy galaxy 1581838731 Mar 22 02:24 /data/dnb02/galaxy_db/files/014/320/dataset_14320954.dat

The dataset seems to contain data.

**Comment by joachimwolff** [comment]
As far as I remember this was clarified via e-mail. Please reopen if this is not correct and the issue is unsolved.
