### ISSUE TITLE
Binsize and Restriction enzyme file

### ISSUE THREAD

**Issue by wyim-pgl** [deeptools/HiCExplorer#520]
Hi!
 I am using Arima Hi-C as input. I am trying to use  --restrictionCutFile and --binSize together to build but I faced below error
```bash
--restrictionCutFile/-rs: not allowed with argument --binSize/-bs
```
Is it okay to use it without binsize?
Regards,
Won

**Comment by joachimwolff** [comment]
These two options are mutually exclusive. Bin size is for a fixed bin size, while restriction cut file is for restriction fragment resolution.

If you use binSize for a fixed resolution it will still work, only the QC report is a bit misleading.

**Comment by LeilyR** [comment]
This discussion is not valid anymore from hicexplorer 3.5 where both`-- bs` and `--rs` can be provided to result in a more detailed QC report.
