### ISSUE TITLE
HiCExplorer v3.4 for linux 64

### ISSUE THREAD

**Issue by zyqfrog10** [deeptools/HiCExplorer#521]
Hi there,

I trying to use install hicexplorer on our cluster. 
But I found I can only install v2.2 through bioconda. 
Will you provide updates for linux 64 user in near future? 
Thank you.

-YZ

**Comment by bgruening** [comment]
@zyqfrog10 how do you install hicexplorer?

Can you please try: `conda create -n hicex hicexplorer=3.4.3`

**Comment by zyqfrog10** [comment]
I followed the installation instruction:
```
conda install hicexplorer -c bioconda -c conda-forge
```

I tried what you suggested and got the following:
``` 
PackagesNotFoundError: The following packages are not available from current channels:
  - hicexplorer=3.4.3
```

I believe it is said on bioconda page, v3.4.3 is not available for linux 64
<img width="258" alt="Untitled" src="https://user-images.githubusercontent.com/9779738/77815461-a4763300-7091-11ea-9e56-4e5d9723b43c.png">

**Comment by joachimwolff** [comment]
I am running a 64 bit Linux and noarch is working fine. Please follow what was posted here already. Or  add to your command `conda install hicexplorer=3.4.3 -c bioconda -c conda-forge`.

However, it is a question to answer for @bgruening or @dpryan79 why there are these outdated versions available and how we can fix this.

**Comment by zyqfrog10** [comment]
Thanks @joachimwolff . Your suggestion worked. 

Maybe I wasn't very clear, but I **DID** follow everything on the hicexplorer documentation and later what @bgruening suggested. The former one installed v2.2 by default. And @bgruening 's suggestion gave me an error message posted above, i.e. ```PackagesNotFoundError:```. 

If I didn't check on bioconda, I wouldn't even know the latest version is v3.4.3, which is not indicated in the hicexplorer documentation. 

It would be helpful if the documentation can tell the latest version number, or explicitly write ```conda install hicexplorer=3.4.3 -c bioconda -c conda-forge``` in the installation session. And yes, of course, it'd be better to remove lower version in bioconda to avoid confusion. 

Thank you for your help.
