### ISSUE TITLE
How to convert matrix generated by HiCExplorer to N x N matrix

### ISSUE THREAD

**Issue by benxiahu** [deeptools/HiCExplorer#523]
Hi,
   I have run HiCExplorer to make Hi-C matrix. Now I want to convert that matrix into N x N format.
Do you know how to do that?
Best,

**Comment by joachimwolff** [comment]
Hi,

Not quite clear what do you by NxN matrix. It is highly recommended to use either the cool for the h5 format to process Hi-C data, text files are a really bad choice.

**Comment by LeilyR** [comment]
Although, we really discourage you to use text formats for HiC matrices, there is a possibility of converting your .h5 or .cool matrix to it using hicConvertFormat (homer, ginteractions) .
