### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by evaristplanet** [deeptools/HiCExplorer#525]
Dear developers,

As you very well describe in the documentation, the best way to install this piece of software is via conda. The current version of conda uses python3.7. If you want to install HiCExplorer you need python3.6. This line installs python3.6 and HiCExplorer:

conda create -n hicexplorer_3.4.3 python=3.6 hicexplorer=3.4.3 anaconda -c bioconda -c conda-forge

I think it would be useful to add this to the documentation

Thank you very much,

Evarist

**Comment by brainfo** [comment]
> Dear developers,
> 
> As you very well describe in the documentation, the best way to install this piece of software is via conda. The current version of conda uses python3.7. If you want to install HiCExplorer you need python3.6. This line installs python3.6 and HiCExplorer:
> 
> conda create -n hicexplorer_3.4.3 python=3.6 hicexplorer=3.4.3 anaconda -c bioconda -c conda-forge
> 
> I think it would be useful to add this to the documentation
> 
> Thank you very much,
> 
> Evarist

You Really helped me! (I thought before python is downward compatible.)

**Comment by LeilyR** [comment]
please check our latest conda version (v3.4.3) with python 3.7 support.
