### ISSUE TITLE
bash: hicDetectLoops: command not found

### ISSUE THREAD

**Issue by amv33576** [deeptools/HiCExplorer#530]
Hello,
I am working with HiCExplorer. Used conda for the installation, so far, I was able to use the commands: hicConvertFormat, hicPlotMatrix, hicCorrectMatrix, hicFindTADs, hicPlotTADs and hicPCA without any problem, but when trying to use hicDetectLoops it responds with the error:
bash: hicDetectLoops: command not found

Using: hicexplorer 2.2 and python 3.6

Any ideas?

Thanks,

Anyi

**Comment by amv33576** [comment]
I can not get the lastest hicexplorer version using conda installer. I have the last version of conda, all updated. I used conda install hicexplorer -c bioconda -c conda-forge but it is installing 
hicexplorer        bioconda/linux-64::hicexplorer-2.2-py36_0

Thanks

**Comment by joachimwolff** [comment]
conda install hicexplorer=3.4.3 -c bioconda -c conda-forge

I don’t know why conda uses a wrong version for default.
