### ISSUE TITLE
hicCompartmentsPolarization running error

### ISSUE THREAD

**Issue by lubna290** [deeptools/HiCExplorer#531]
I have submitted command:
hicCompartmentsPolarization -m obsExp.h5 --pca pca1.bedgraph -o test.png

getting error:

Traceback (most recent call last):
  File "/apps/python3/3.7.0/bin/hicCompartmentsPolarization", line 7, in <module>
    main()
  File "/apps/python3/3.7.0/lib/python3.7/site-packages/hicexplorer/hicCompartmentsPolarization.py", line 156, in main
    args.quantile)
  File "/apps/python3/3.7.0/lib/python3.7/site-packages/hicexplorer/hicCompartmentsPolarization.py", line 80, in count_interactions
    data = chr_submatrix[row_indices, :][:, col_indices]
  File "/apps/python3/3.7.0/lib/python3.7/site-packages/numpy/matrixlib/defmatrix.py", line 195, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 4795 is out of bounds for axis 0 with size 4709

could you please explain this error to me.
Thanks

**Comment by LeilyR** [comment]
The error seems to be a result of having different numbers of bins on you matrix and pc1 bed graph. In one of them (I assume pc1) you reached 4795th bin while the other (I suppose the matrix) has only 4709 bins. You should consider giving the pc1 and matrix which were generated which the bins of the same size. Please take of that and let us know if you still have an issue.

**Comment by lubna290** [comment]
Thanks for the reply, same matrix worked in cool format.
could you please guide how we can explain such analysis? How it explains the segregation of active vs inactive comaprtments and the regions they covered?

**Comment by LeilyR** [comment]
strange, was the cool matrix the one you used to make pc1? Which version are you using? This tool has been renamed to compartmentalisation while ago. Please use the updated one. 
I have explained its concept once int  #473 you might want to have a look at it. Please don't hesitate to get back to use, f there was anything unclear

**Comment by LeilyR** [comment]
@lubna290 we assume that the version update has solved your issue , please feel free to reopen this issue if there was any further question.
