### ISSUE TITLE
the summation of col

### ISSUE THREAD

**Issue by benxiahu** [deeptools/HiCExplorer#533]
Hi,
   I used hicexplore (v2.2.1.1) to build and correct matrix, 
```
hicCorrectMatrix correct \
--chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX \
--matrix sample_100kb.h5 --filterThreshold -2 3 --perchr --outFileName sample.100kb.h5
```
then converted .h5 into NxN format.  
   When I calculated the summations in different columns, I found that the summation in different columns is not the same. 
`cat nor.chr14 | awk '{s+=$1000}END{print s}`' :**1797**
`cat nor.chr14 | awk '{s+=$500}END{print s}'` : **1778**
`cat nor.chr14 | awk '{s+=$400}END{print s}'` : **1883**
Do you know what's wrong?

**Comment by joachimwolff** [comment]
Please update to the current version 3.4.3 of HiCExplorer.

**Comment by LeilyR** [comment]
they are not supposed to be the same but are supposed to be close to 1 after KR (https://doi.org/10.1093/imanum/drs019). However, our correction method rescale them after KR algorithm by taking the total sum of matrix into account.

**Comment by benxiahu** [comment]
> Please update to the current version 3.4.3 of HiCExplorer.

do you mean 3.4.3 version will output the sane summation in different columns?

**Comment by benxiahu** [comment]
> they are not supposed to be the same but are supposed to be close to 1 after KR (https://doi.org/10.1093/imanum/drs019). However, our correction method rescale them after KR algorithm by taking the total sum of matrix into account.

I calculate the summation of one column of a NxN matrix, not .h5 matrix.

**Comment by joachimwolff** [comment]
Version 3.4.3 makes sure no already fixed bugs can influence your results. Therefore you should always use the up-to-date version and never a version which was released more than a year ago. In the meantime there was the release of multiple versions.

What @LeilyR wrote is true. The KR algorithm tries to make the sum close to one, however, not guaranteeing it is exact one for all. After applying rescaling to the original data range the differences you observe seem reasonable to us.

**Comment by benxiahu** [comment]
> Version 3.4.3 makes sure no already fixed bugs can influence your results. Therefore you should always use the up-to-date version and never a version which was released more than a year ago. In the meantime there was the release of multiple versions.
> 
> What @LeilyR wrote is true. The KR algorithm tries to make the sum close to one, however, not guaranteeing it is exact one for all. After applying rescaling to the original data range the differences you observe seem reasonable to us.

Do you mean v2.2.1.1 applied KR to correct the raw matrix? Also how about ICE? Does it do not output the same summation in different columns?

**Comment by joachimwolff** [comment]
Sorry, I don't get it. KR and ICE are two different correction algorithms, if you care about their details, please read their publications: Knight&Ruiz 2013 (https://academic.oup.com/imajna/article-abstract/33/3/1029/659457?redirectedFrom=fulltext) and ICE: Imakaev 2011 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3816492/)

**Comment by benxiahu** [comment]
I meant that v2.2.1.1 just applied **KR** to correct the raw matrix, right?
I found that v3.4.3 contained **KR** and **ICE** methods to correct the raw matrix. Does **ICE** do not output the same summation in different columns?

**Comment by LeilyR** [comment]
1. We don't output the sum of normalised contacts pre row or column for any of the matrices. You can use out api or any other way that you feel comfortable with to compute them .

2. The older versions of HiCExplorer supports only ICE correction method to balance the matrices however the more recent ones support KR too. So you could decide which one to use.  If you want the details about their algorithms , we recommend you read their publications which has been mentioned above in the previous comment. 

3. The reason that we asked you to use the most recent version is that we are dynamically working on the tools and we improve them by making them more efficient and by fixing the bugs.

**Comment by LeilyR** [comment]
@benxiahu We hope that we could have answered your question and that is why we have not heard of you anymore. I close this issue but please feel free to reopen it if there was any further question.
