### ISSUE TITLE
py3.7 support

### ISSUE THREAD

**Issue by nservant** [deeptools/HiCExplorer#539]
Hi there,
I was just wondering if you plan to soon support python 3.7 ? because I start to have some conda issue between hicExplorer and other tools. Thanks
Nicolas

**Comment by LeilyR** [comment]
Hi Nicolas, It is indeed in our todo list and hopefully be added very soon.

**Comment by nservant** [comment]
great. Can I ask you if this is a matter of weeks or months ?
Sorry, just to know if I jave to downgrade all my conda environment or if I can wait for it :)
Thanks again

**Comment by joachimwolff** [comment]
Just merged the update to bioconda, should be available soon.

Best,

Joachim
