### ISSUE TITLE
can't find krbalancing module in correct matrix

### ISSUE THREAD

**Issue by mtegtmey** [deeptools/HiCExplorer#540]
Hi, I'm getting this error when running hicCorrectMatrix:

wm06b-74e:~ mtegtmey$ hicCorrectMatrix correct --matrix ~/Desktop/0514d28_10000_norm.cool --correctionMethod KR --outFileName ~/Desktop/0514d28_corrected.cool
Traceback (most recent call last):
  File "/Users/mtegtmey/miniconda3/bin/hicCorrectMatrix", line 4, in <module>
    from hicexplorer.hicCorrectMatrix import main
  File "/Users/mtegtmey/miniconda3/lib/python3.7/site-packages/hicexplorer/hicCorrectMatrix.py", line 17, in <module>
    from krbalancing import *
ModuleNotFoundError: No module named 'krbalancing'

I'm using HiCExplore version 3.4.3

Thanks!

Matt

**Comment by LeilyR** [comment]
How did you install hicexplorer? it seems like a missing dependencies

**Comment by mtegtmey** [comment]
That was fast. I installed through cloning the git repo. I updated my dependencies and it seems to be working now.
