### ISSUE TITLE
HiC

### ISSUE THREAD

**Issue by dominik-handler** [deeptools/HiCExplorer#541]
Hi,

with my newest dataset I am getting the following error when I try to build the matrix. 
```
Traceback (most recent call last):
  File "/usr/local/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/hicBuildMatrix.py", line 1366, in main
    hic_ma.setMatrix(hic_matrix, cut_intervals=bin_intervals)
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/HiCMatrix.py", line 375, in setMatrix
    self.intervalListToIntervalTree(self.cut_intervals)
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/HiCMatrix.py", line 1968, in intervalListToIntervalTree
    cut_int_tree[chrom].add(Interval(start, end, intval_id))
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 313, in add
    " {0}".format(interval)
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(1676848, 162381, 44220)
correctMatrix-plot
```

I mapped my data using BWA, created the digest-file using:
`hicFindRestSite --fasta ${assemblyFASTA} --searchPattern GATC -o ${locTMP}rest_site_positions.bed`
and try to build the matrix using this command:
```
hicBuildMatrix --samFiles ${locTMP}mate_R1.bam ${locTMP}mate_R2.bam \
                 --restrictionCutFile ${locTMP}rest_site_positions.bed \
                 --restrictionSequence GATC \
                 --maxLibraryInsertSize 1500 \
                 --threads $SLURM_CPUS_PER_TASK \
                 --inputBufferSize 1000000 \
                 -o ${locTMP}hic_matrix.h5 \
                 --QCfolder ${OPENdir}hicQC

```

Thank you,
Dominik

**Comment by joachimwolff** [comment]
Hi,

you are using Python 2 and therefore a version which was released more than a year ago. Please try again with the last release 3.4.3.

Best,

Joachim

**Comment by dominik-handler** [comment]
Hi, sorry this was my bad. I did not change the build file for my container and assumed a re-build updated HiCExplorer. 

I was also able to fix the problem which still persisted in the updated version. A upstream tool generated contigs with identical identifiers in my genome assembly. After renaming the duplicates all works nicely.

Thank you and cheers,
Dominik
