### ISSUE TITLE
hicPlotMatrix and square heatmap

### ISSUE THREAD

**Issue by Linhua-Sun** [deeptools/HiCExplorer#545]
Hi: 
    I have a small question. When I used hicPlotMatrix to generated Hi-C heatmap with multiple bigwig files (>=3). I found the Hi-C heatmap became flatten (oblong shape, not 1:1). Can I control the heatmap to be square? 
Thanks.
Linhua Sun

**Comment by joachimwolff** [comment]
Hi,

I need to test this, but I think it sound more like a bug.

Best,

Joachim

**Comment by Linhua-Sun** [comment]
Thank you so much! I have tested it in different environment and versions. All with the same problem.

**Comment by joachimwolff** [comment]
Hi Linhua Sun,

it is now improved and will be released with the next main release of HiCExplorer. I hope it suits your needs.

![bar4](https://user-images.githubusercontent.com/13435136/86533044-a7719280-bece-11ea-9303-e4061dccf0f4.png)
![bar5](https://user-images.githubusercontent.com/13435136/86533048-aa6c8300-bece-11ea-9d4f-2e8e6cda754d.png)
![bar6](https://user-images.githubusercontent.com/13435136/86533050-ac364680-bece-11ea-915e-f0255330dfc7.png)
![bar10](https://user-images.githubusercontent.com/13435136/86533051-ae000a00-bece-11ea-9bea-d832c3cf9988.png)


Best,

Joachim

**Comment by MzwaneleN** [comment]
Hi,

Quick question: what are/causes the blue horizontal and vertical lines?

Thanks,
Mzwanele
