### ISSUE TITLE
hicDetectLoops: raw or corrected matrix.cool to be use as input

### ISSUE THREAD

**Issue by shuaibm33** [deeptools/HiCExplorer#547]
Hello,

I am trying to use hicDetectloop on hic cool hic matrix that are convereted from h5 format. But I am not sure whether I have to use corrected (like ICE or KR) or just the raw matrix.cool as input?
Thank you.
Muhammad

**Comment by joachimwolff** [comment]
Hi,

for all data processing the usage of a corrected matrix is recommended. Both mentioned algorithms are good and it depends on your data which of these should be used.

Best,

Joachim

**Comment by shuaibm33** [comment]
Hi Joachim,

Thank you very much for this clarification!
Best
Muhammad
