### ISSUE TITLE
hicBuildMatrix needs to specify the format of the output

### ISSUE THREAD

**Issue by LaureTomas** [deeptools/HiCExplorer#550]
Hi!

First, thanks for this useful tool.

But I've been reading the documentation to create the hic matrix and I couldn't generate the matrix. While running the command the output file was generated but when it finishes running the file disappears. So I've been trying several things until I realise that you need to specify the format of the output file (i.e. output.h5).

I'm writing this issue for you to know that in the documentation that is not specified and I think it should be, so more people don't get it wrong.

Thanks again!

**Comment by LeilyR** [comment]
Thanks @LaureTomas ! We will add that to the documentation asap
