### ISSUE TITLE
Compare changes within TADs between two biological samples

### ISSUE THREAD

**Issue by dot-kom** [deeptools/HiCExplorer#551]
Hi,
I am a biologist trying to analyze Hi-C data (it's a warning meaning I am stupid). I have Hi-C data and histone mark data of control and treated sample and I would like to see if observed changes in histone marks happen predominantly in TADs that were gained after te treatment. What would be best approach? If I do hicCompareMatrices can I call TADs from this calculation? Or should I perform TADs calling separately and then compare somehow their coordinates in bed?

I need to add that I am using galaxy for this analysis, so I am limited to the tools available on the server.

Thanking you in advance for your help,
D.

**Comment by LeilyR** [comment]
If I understood you correctly, you are looking for the TADs which were formed in your treated sample. for that you need to call tads separately on both of them and compare. To set the best parameters for tad calling use your wild type sample only. Also considering comparing their insulation scores at the boundaries of your interest.
On how to check for the ChIP signal on the boundaries, you might need to consider using` igv`, `pygenometracks` or `deeptools plotProfile`
