### ISSUE TITLE
Some shortcut scripts use hardcoded interpreter path

### ISSUE THREAD

**Issue by ScottNortonPhD** [deeptools/HiCExplorer#552]
Version affected: hicexplorer 2.2.1.1 (pip)

Steps to reproduce:

    $ hicDetectLoops

Expectation: usage string

Observation:

    bash: /path/where/hicexplorer/was/installed/hicDetectLoops: 
    /home/wolffj/miniconda2/envs/hic_py3/bin/python: bad interpreter: No such file or directory

Other scripts affected: chicAggregateStatistic, chicDifferentialTest, chicPlotViewpoint, chicViewpoint, chicViewpointBackgroundModel, hicDifferentiaAnalysis, hicLog2Ratio

**Comment by joachimwolff** [comment]
Hi,

Version 2.2 and also pip are no longer supported and will not get any bug fixes or updates.

Please use conda instead of pip and use the current version of HiCExplorer 3.4.3.

Best,

Joachim
