### ISSUE TITLE
chicPlotViewpoint and pyGenomeTracks  

### ISSUE THREAD

**Issue by amv33576** [deeptools/HiCExplorer#553]
This is more a suggestion, I am wondering if you can add a feature to use the data from chicPlotViewpoint as another track for pyGenomeTracks. Imagine you have a Matrix with its TADs, some Chip-seq data, and the viewpoint computation for a possible CRE.

Thanks

**Comment by joachimwolff** [comment]
Hi,

Thanks for your idea, it is already on our todo list: https://github.com/deeptools/pyGenomeTracks/issues/234

Best,

Joachim
