### ISSUE TITLE
hicFindTADs - "all the input arrays must have the same number of dimensions"

### ISSUE THREAD

**Issue by conchoecia** [deeptools/HiCExplorer#555]
Hi, I'm using hicFindTADs version 3.4.1 and am using the following commands to try to call TADs. The input data is a cooler with a resolution of 500bp.

```
cooler balance --cis-only thirteen_scafs_balanced.500.cool
hicConvertFormat --inputFormat cool -m thirteen_scafs_balanced.500.cool --outputFormat h5 -o matrix500.h5
hicCorrectMatrix diagnostic_plot -m matrix500.h5 -o diag2.png --chromosomes sca1 sca2 sca3 sca4 sca5 sca6 sca7 sca8 sca9 sca10 sca11 sca12 sca13
hicCorrectMatrix correct -m matrix500.h5 -o matrix500_corr.h5  -t -2 5 --chromosomes sca1 sca2 sca3 sca4 sca5 sca6 sca7 sca8 sca9 sca10 sca11 sca12 sca13
hicFindTADs -m matrix500_corr.h5  --outPrefix out500 --correctForMultipleTesting fdr --thresholdComparisons .01 --delta .01 --chromosomes sca1 sca2 sca3 sca4 sca5 sca6 sca7 sca8 sca9 sca10 sca11 sca12 sca13
```

When I run the hicFindTADs step I get the following output and error:

```
INFO:hicexplorer.hicFindTADs:removing diagonal values

INFO:hicexplorer.hicFindTADs:Computing z-score matrix...

INFO:hicexplorer.hicFindTADs:Computing TAD-separation scores...

INFO:hicexplorer.hicFindTADs:computing spectrum for window sizes between 30 (15000 bp)and 60 (30000 bp) at the following window sizes 4 [15000, 17000, 20656, 25392]

Traceback (most recent call last):
  File "/home/user/miniconda3/bin/hicFindTADs", line 7, in <module>
    main()
  File "/home/user/miniconda3/lib/python3.7/site-packages/hicexplorer/hicFindTADs.py", line 1378, in main
cooler balance --cis-only thirteen_scafs_balanced.500.cool
    ft.hic_ma.save(args.outPrefix + "_zscore_matrix.h5")
  File "/home/user/miniconda3/lib/python3.7/site-packages/hicmatrix/HiCMatrix.py", line 93, in save
    self.restoreMaskedBins()
  File "/home/user/miniconda3/lib/python3.7/site-packages/hicmatrix/HiCMatrix.py", line 873, in restoreMaskedBins
    np.repeat(np.nan, N)])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

Any idea what might be going wrong? Thank you-

**Comment by LeilyR** [comment]
it could be `cooler balance --cis-only`. I am afraid the output for `cis_only` generates a matrix of a shape which does not match the hicexplorer criteria . Why don't you use the hicexplorer balancing ? It is called `hicCorrectMatrix`

**Comment by joachimwolff** [comment]
Maybe as a first question from my side: Why do you convert the cool to h5? We support cool natively.

**Comment by conchoecia** [comment]
Hi All. I'm new to hicCorrectMatrix, so that explains why I'm doing strange things, like converting cool to h5 ! :)

I've been using `cooler balance --cis-only`, because I often make multiple Hi-C libraries, each with a different restriction enzymes. I map all of these to the genome and generate a single cool file. `cooler balance` doesn't appear to like this, as the correction never converges. It only works if I add the `--cis-only` flag. Balancing cool files from a single restriction enzyme works fine though.

I'll try to come up with a new workflow using `hicCorrectMatrix` and see how it goes. Thanks.

**Comment by LeilyR** [comment]
from what you explained you may also find `hicSumMatrices` useful.

**Comment by conchoecia** [comment]
Thanks, @LeilyR - that is great news. Btw, I was successfully able to use `hicCorrectMatrix diagnostic_plot`, `hicCorrectMatrix correct`, then `hicFindTADs`. I will close this issue as I have figured out the issues that were troubling me before.
