### ISSUE TITLE
hicMergeLoops: Is merged loop file correspond to high or low resolution loop-file?

### ISSUE THREAD

**Issue by shuaibm33** [deeptools/HiCExplorer#558]
Hello,
I am using the hicMergeLoops tool to merged the loop files generated at 10kb and 25kb. I was expecting to get the merged loop at 25kb, but after checking the loop file it is 10kb? I used this command : 
hicMergeLoops -i loop_10kb.bedgraph loop_25kb.bedgraph -o Merged.loop,bedgraph -r 25000

The output merged file looks like this
tail Merged.loop,bedgraph
chrX	147090000	147100000	chrX	148120000	148130000	0.001
chrX	147130000	147140000	chrX	147230000	147240000	0.001
chrX	147200000	147210000	chrX	148120000	148130000	0.001

Could please check if I am doing some mistake in merging the loop files?
Thank you!
Best regards
Muhammad

**Comment by joachimwolff** [comment]
Hi,

As stated in our documentation `If two or more locations are to be merged, the loop at the lowest resolution is taken as the merged loop.`

https://hicexplorer.readthedocs.io/en/latest/content/tools/hicMergeLoops.html#hicmergeloops

Best,

Joachim

**Comment by shuaibm33** [comment]
Hi Joachim,

First, thanks a lot for your response!
As you said and also mentioned in your documentation that after merging the
lowest resolution is taken as the merged loop. In my case, I am merging
loop of 10kb and 25kb, so I am expecting to get the merged loop at 25kb bin
size, right? But I am getting the merged loop at 10kb not at 25kb. You can
see the head of the megred loop in my early request.
Thanks
Muhammad

**Comment by joachimwolff** [comment]
The lower resolution is only taken if and only if two loops are merged e.g. from the same region a loop is detected in 10kb and 25 kb file. However, if a loop is unique and only detect at one resolution, it is accepted and part of the merged file as it is. No adjustment to a certain resolution is done.
