### ISSUE TITLE
HiC File Format (Normalized Hi-C contact matrix file)

### ISSUE THREAD

**Issue by anupambh** [deeptools/HiCExplorer#559]
Hi,
I have successfully run HiCExplorer for my datasets. The output of the matrix file is in .h5 format and I have converted in different formats by hicconvert program.

**I am looking for a Normalized Hi-C contact matrix file in the following format**. Is that possible to do so by using HiCExplorer argument or any other parameter?

The first three columns correspond to chromosome, from.coord, and to.coord. The last N columns should contain normalized contact counts.

  chr19       0   40000       0 0 0 0 ...
  chr19   40000   80000     0 0 0 0 ...
  chr19   80000  120000    0 0 0 0 ...
  chr19  120000  160000   0 0 0 0 ...

Any help would be highly appreciated. 

Regards;
Anupam Bhattacharya
Research Scholar
Bioinformatics Department
IASST,India

**Comment by LeilyR** [comment]
Hi, 
We are not really supporting any text format for HiC matrices and we believe that that they are not the most suitable way to present gigantic HiC matrices. However, If you really look for a text format `ginteractions ` is the closest you can convert your matrix to.  Just a small note on the presentation you are interested in, you need to have 2 coordinates to show the interaction between two regions on a contact matrix and a bed file format as you have asked does not give you that.
