### ISSUE TITLE
HiCBuildMatrix Assertion Error despite reordering

### ISSUE THREAD

**Issue by sjquon** [deeptools/HiCExplorer#562]
Hi,

I keep on encountering the following error when trying to run HiCBuildMatrix despite using the reorder function. I have also tried repairing with bbtools and leaving out the samtools conversion to bam.

Traceback (most recent call last):
  File "/home/sjquon/anaconda3/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/home/sjquon/anaconda3/lib/python3.7/site-packages/hicexplorer/hicBuildMatrix.py", line 1229, in main
    pMinMappingQuality=args.minMappingQuality
  File "/home/sjquon/anaconda3/lib/python3.7/site-packages/hicexplorer/hicBuildMatrix.py", line 692, in readBamFiles
    "the --reorder option".format(mate1.qname, mate2.qname)
AssertionError: FATAL ERROR V300039379L3C001R0030002787/1 V300039379L3C001R0030002787/2 Be sure that the sam files have the same read order If using Bowtie2 or Hisat2 add the --reorder option
Unloading compiler-dependent module openmpi_ib/3.1.4
~

My alignment code:
for f in ./DN1*R[12]_001.fastq.gz; do fname=$(basename $f _001.fastq.gz); \
hisat2 -x mm10/genome  --threads 16 -U $f --reorder -S Aligned/$fname.sam 2> Aligned/$fname.er ; done

My HiCBuildMatrix code: 
for f in ../Fastq/Aligned/*_R1.repaired.sam; do fname=$(basename $f _R1.repaired.sam);\
hicBuildMatrix --samFiles $f ../Fastq/Aligned/${fname}_R2.repaired.sam --outFileName $fname --QCfolder QC --restrictionCutFile MboI_mm10_RestSitePostions.bed --maxLibraryInsertSize 1500 --restrictionSequence GATC --danglingSequence GATC --threads 16 --doTestRun ; done

Any ideas on how to fix this?

**Comment by joachimwolff** [comment]
Hi,

you could try to use a different mapper. What about bowtie2 or bwa mem?

Best,

Joachim

**Comment by sjquon** [comment]
Using bwa instead of hisat2 solved the problem! Thanks!
