### ISSUE TITLE
convert to homer

### ISSUE THREAD

**Issue by kdl44** [deeptools/HiCExplorer#564]
I am having a problem with converting matrix files to the file format homer using hicConvertFormat. I tried using the native .h5 and .cool as input files. First I thought it may not be working because the bin sizes are not equal but it also has not worked for equally sized 5kb bins. 

$ hicConvertFormat -m matrix.cool --inputFormat cool --outputFormat homer -o matrix.homer 

I'm getting something like this in the output files:
Í9bƒ#
ÈÔeàÍªG∑’U8ÌdˆÌ[≥‰ˇ˚ø¸oˇ˛?¸˜˝óˇ˚ﬂ˛OˇÈ_˛ı?ˇ«ˇ˛_ˇıˇ˘_ˇóˇ˘ﬂ¸ˇ˘ø¸À˝ø˛€ø˘èˇÁø˛˚w˝ˇ∏ØÎ|5◊ü/ˇˇ´ÛÔ˛«?˛\¯Î_õ˝ØÂœ’¸π⁄?W˚ÁÍ˘sı¸πzˇπzˇπ˙¸π˙¸π˙˛π˙˛π˙˚sı˜ÁÍ˜ÁÍ˜∑U¸ıı∫æó∑÷7kÅ≥V8kâ≥÷8kë≥V9˜ﬁæu}-t÷Jg-u÷Zg-v÷jg-wæø˝˜˘ÎÎu}≠7˚øÁ˛∫÷õµﬁ¨ıf≠7kΩπ˜åu}≠7kΩYÎÕZo÷z≥÷õµﬁ|˚ì˜◊◊Î˙Zo◊zª÷€˝'xˇ^ÎÌZo◊z{Ô? 

I haven't seen the file extension ".homer" anywhere else either. I am expecting formats of a HicSummaryFile or the matrix files of homer, which outputs simple tab delimited .txt files for both formats. My end goal is to use the normalized/corrected matrices produced by HicExplorer, convert them to Homer formats, then use some of the downstream analysis of Homer, which requires (for those familiar) a tag directory.

Am I completely missing something here? Any help is appreciated!

**Comment by joachimwolff** [comment]
Hi,

what we understand as 'homer' format is the tab-delimited file as it would be created be analyseHiC from Homer. See http://homer.ucsd.edu/homer/interactions/HiCmatrices.html section 'Visualizing the Interaction Matrix'. Unfortunately their documentation is very limited. We do not create tag directories, but you can use this text file and transform it to the alternative input file as it is described here: http://homer.ucsd.edu/homer/interactions/HiCtagDirectory.html

However, to write out such a file can take multiple hours to days, and the Homer software itself is really slow and is consuming very large amounts of memory. I can only recommend to use ANY other software for Hi-C data.

To your error: Have you considered that we gzip the output? 

Best,

Joachim

**Comment by LeilyR** [comment]
on top of what Joachim has already said, you might want to consider using hicexplorer for its downstream analysis modules. I believe it supports almost all you would need for a usual hic study and you don't need to be worried about change of the format to a very large text file.
