### ISSUE TITLE
no output of hicFindEnrichedContacts

### ISSUE THREAD

**Issue by hosseinsalari65** [deeptools/HiCExplorer#566]
Hi,
I am using hicFindEnrichedContacts to find loops, the script is:
hicFindEnrichedContacts -m ES_stage_chr1_2000000_25000000bp.cool -o loop.bed --method obs/exp
I got this:
INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicmatrix.HiCMatrix:Number of poor regions to remove: 270418 {'chr7': 14545, 'chr6': 14974, 'chr5': 15184, 'chr4': 15651, 'chr3': 16004, 'chr2': 18212, 'chr1': 17402, 'chrY': 9175, 'chr9': 12460, 'chr8': 12941, 'chr13': 12043, 'chr12': 12013, 'chr11': 12209, 'chr10': 13070, 'chr17': 9499, 'chr16': 9821, 'chr15': 10405, 'chr14': 12491, 'chr19': 6144, 'chr18': 9071, 'chrX': 17104}
INFO:hicmatrix.HiCMatrix:found existing 270418 nan bins that will be included for masking 
INFO:hicmatrix.HiCMatrix:processing chromosome all

INFO:hicmatrix.HiCMatrix:masked bins were restored

but the output is empty!
Any help is appreciated!

**Comment by joachimwolff** [comment]
Hi,

to find loops we provide 'hicDetectLoops'. hicFidEnrichedContacts was dropped with version 3.0 and is no longer supported or maintained. Please update to a current version of HiCExplorer which is 3.4.3.
Best,

Joachim
