### ISSUE TITLE
hicCorrelate with mcool files

### ISSUE THREAD

**Issue by ChristopherBarrington** [deeptools/HiCExplorer#567]
I have used `distiller` to preprocess my data and have `mcool` files with resolutions starting at 1kb. I would like to use one of the aggregated resolutions in the `mcool` as input matrices. However the following does not work:

`hicCorrelate --matrices 'results/coolers_library/lib1.genome.mapq_30.1000.mcool::resolutions/10000' 'results/coolers_library/lib2.genome.mapq_30.1000.mcool::resolutions/10000' --outFileNameHeatmap foo --outFileNameScatter bar`

If I use the regular 1kb `cool` instead it does work. Have I specified the `matrices` incorrectly with the `mcools`? Do I have to extract the resolution from the `mcool` into a `cool` and use that instead?

Also, the man page suggests using uncorrected counts rather than normalised. I believe these are in the cooler but I am not sure whether they are accessed by default or need to be speicified?

Thank you.

**Comment by joachimwolff** [comment]
Hi Christopher,

can you specify 'does not work' a bit? Is the data not loaded, do you get an error, are the results weird?

Best,

Joachim

**Comment by ChristopherBarrington** [comment]
Sorry, of course that would have been helpful of me! Please see below

```
Traceback (most recent call last):
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/bin/hicCorrelate", line 7, in <module>
    main()
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicexplorer/hicCorrelate.py", line 389, in main
    results[row, col] = correlation_opts[args.method](vector1, vector2)[0]
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/stats/stats.py", line 3838, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```

**Comment by joachimwolff** [comment]
Sorry for the delay, a lot going on at the moment.

This error has nothing to do with mcool or cool, it complains that the matrix is empty. The question now is, why it is doing this. Can you verify if there is content in the matrices? For example with `hicInfo -m foo.mcool::/path/to/cool`? And maybe also with a tool like hdfview. 

From what I see also is that I think the correct path is `lib2.genome.mapq_30.1000.mcool::/resolutions/10000`; i.e. one more `/` in front of `resolution`.

Normalized vs non-normalized: We follow the cool file format, which means the correction factors (!= normalization!!!) are stored in the `weights` column of bins. However, to get it uncorrected we enforce to write this out to its own cool file via `hicConvertFormat`, please have a look at the docs for the correct parameter setting.

**Comment by ChristopherBarrington** [comment]
Thanks for the ideas. I am still getting used to using cool files, but the `/resolutions/10000` typo didnt seem to resolve the problem.

I checked that there are matrices are in the mutlicooler:

```
hicInfo -m results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/10000
# Matrix information file. Created with HiCExplorer's hicInfo version 3.4.3
File:   results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/10000
Date:   2020-07-01T08:12:59.527524
Genome assembly:        unknown
Size:   1,179
Bin_length:     10000
Chromosomes:length: chr1: 5563398 bp; chr2: 3682552 bp; chr3: 2524083 bp;
Number of chromosomes:  3
Non-zero elements:      681,797
The following columns are available: ['chrom' 'start' 'end' 'weight']


Generated by:   cooler-0.8.8
```
```
hicInfo -m results/coolers_library/G1_C_AD_B2.sy12.mapq_30.1000.mcool::/resolutions/10000
# Matrix information file. Created with HiCExplorer's hicInfo version 3.4.3
File:   results/coolers_library/G1_C_AD_B2.sy12.mapq_30.1000.mcool::/resolutions/10000
Date:   2020-07-01T08:20:47.655857
Genome assembly:        unknown
Size:   1,179
Bin_length:     10000
Chromosomes:length: chr1: 5563398 bp; chr2: 3682552 bp; chr3: 2524083 bp;
Number of chromosomes:  3
Non-zero elements:      690,809
The following columns are available: ['chrom' 'start' 'end' 'weight']


Generated by:   cooler-0.8.8
```

If I use the base 1kb or the 2kb resolutions from the `mcool` then `hicCorrelate` works but if I use the 5kb resolution map or above from the same `mcool` then `hicCorrelate` fails:

```
hicCorrelate --matrices results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/1000 results/coolers_library/G1_C_AD_B2.sy12.mapq_30.1000.mcool::/resolutions/1000 --outFileNameHeatmap foo --outFileNameScatter bar
```
```
hicCorrelate --matrices results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/5000 results/coolers_library/G1_C_AD_B2.sy12.mapq_30.1000.mcool::/resolutions/5000 --outFileNameHeatmap foo --outFileNameScatter bar
Traceback (most recent call last):
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/bin/hicCorrelate", line 7, in <module>
    main()
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicexplorer/hicCorrelate.py", line 389, in main
    results[row, col] = correlation_opts[args.method](vector1, vector2)[0]
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/stats/stats.py", line 3838, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```

I tried extracting the 10kb map from the `mcool` into a `cool`, checked them with `hicInfo`, and `hicCorrelate` was still unhappy:

```
hicConvertFormat -m results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/10000 -o A.10kb.col --inputFormat cool --outputFormat cool
```
```
hicConvertFormat -m results/coolers_library/G1_C_AD_B2.sy12.mapq_30.1000.mcool::/resolutions/10000 -o B.10kb.col --inputFormat cool --outputFormat cool
```
```
hicCorrelate --matrices A.10kb.col B.10kb.col --outFileNameHeatmap foo --outFileNameScatter bar
Traceback (most recent call last):
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/bin/hicCorrelate", line 7, in <module>
    main()
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/hicexplorer/hicCorrelate.py", line 389, in main
    results[row, col] = correlation_opts[args.method](vector1, vector2)[0]
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/stats/stats.py", line 3838, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```

I then checked whether the 10kb map could be used at all with the following (which produced the number of rows expected from the output of `hicInfo`):

```
hicConvertFormat -m results/coolers_library/G1_C_AD_B1.sy12.mapq_30.1000.mcool::/resolutions/10000 -o 10kb --inputFormat cool --outputFormat ginteractions --load_raw_values
```

Is there anything else I can do to help diagnose?

Thank you for your time, Chris

**Comment by LeilyR** [comment]
1. please consider giving your output matrices a right extension: col -> cool also for the 10kb one. 
2. are you sure that your mcool contains 500kb resolution at all?

**Comment by brainfo** [comment]
Today I need to regenerate the hicCorrelate results with different colerMap. 
![image](https://user-images.githubusercontent.com/11832080/105630122-1cfc7a80-5e82-11eb-80da-5587f068d900.png) This is my normal results generating in September.
But this time when I do it with two cool files, for example `hicCorrelate -m A.cool B.cool -oh AB_heatmap.pdf -os AB_scatter.pdf`; and `hicCorrelate -m C.cool D.cool -oh CD_heatmap.pdf -os CD_scatter.pdf`; it worked fine. When I input all four files, it errored: 
ValueError: x and y must have length at least 2.

cooler info messages are listed below:
A:
```
{
    "bin-size": 100000,
    "bin-type": "fixed",
    "creation-date": "2020-09-05T12:03:08.000256",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.9",
    "genome-assembly": "unknown",
    "nbins": 27269,
    "nchroms": 22,
    "nnz": 58607062,
    "storage-mode": "symmetric-upper",
    "sum": 191222352
}
```
B:
```
{
    "bin-size": 100000,
    "bin-type": "fixed",
    "creation-date": "2020-09-05T12:30:51.069656",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.9",
    "genome-assembly": "unknown",
    "nbins": 27269,
    "nchroms": 22,
    "nnz": 35620467,
    "storage-mode": "symmetric-upper",
    "sum": 111571026
}
```
C:
```
{
    "bin-size": 100000,
    "bin-type": "fixed",
    "creation-date": "2020-09-05T13:01:59.923631",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.9",
    "genome-assembly": "unknown",
    "nbins": 27269,
    "nchroms": 22,
    "nnz": 83788434,
    "storage-mode": "symmetric-upper",
    "sum": 237680042
}
```
D:
```
{
    "bin-size": 100000,
    "bin-type": "fixed",
    "creation-date": "2020-09-05T13:26:37.584076",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.9",
    "genome-assembly": "unknown",
    "nbins": 27269,
    "nchroms": 22,
    "nnz": 45952959,
    "storage-mode": "symmetric-upper",
    "sum": 238232306
}
```

Any help? Thank you for your attention!

**Comment by joachimwolff** [comment]
Hi,

`hicCorrelate` does a pairwise correlation. This is described in the documentation, however, we could intercept this already at the time we parse the arguments. I put it on my to-do list for the feature requests.

[General comment] Please open always a new issue, the one you posted in has a very different error than yours. If you think that something is related, a link to the other issue in your new one is fine.

Best,

Joachim

**Comment by jakevc** [comment]
Hi I have noticed that I get  this error described above by @ChristopherBarrington :

```
    results[row, col] = correlation_opts[args.method](vector1, vector2)[0]
  File "/camp/stp/babs/working/barrinc/.conda/envs/hicexplorer/lib/python3.7/site-packages/scipy/stats/stats.py", line 3838, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```

occurs when the matrix is balanced. I was able to no get this error by recalculating the zoom level without matrix balancing. `cooler zoomify original.cool -r 100000` generates a zoom level without matrix balancing by default, when I run it without balancing the correlation completes.

Hope this helps.
