### ISSUE TITLE
hicQuickQC and hicQC 'same fragment' classification

### ISSUE THREAD

**Issue by ChristopherBarrington** [deeptools/HiCExplorer#568]
The above programs report a high proportion of "Same fragment: These are read mates, facing inward, separated by up to 800 bp that do not have a restriction enzyme in between. These read pairs are not valid Hi-C pairs"

I am a bit confused about how the restriction site can be determined to be between reads? I don't supply a genome anywhere  and have only provided the `--restrictionSequence` and `--danglingSequence` parameters. Does it use the sites identified in the sam file and assume that every restriction site is reported at least once?

Apologies for the confusion on this point, I have tried to read the source but could not find the answer.

**Comment by joachimwolff** [comment]
Hi Christopher,

we check if the given dangling ends are part of the read: https://github.com/deeptools/HiCExplorer/blob/3.4.3/hicexplorer/hicBuildMatrix.py#L956 https://github.com/deeptools/HiCExplorer/blob/3.4.3/hicexplorer/hicBuildMatrix.py#L482

If there is no, and the distance between the two reads is not more than the user given `maxLibraryInsertSize` we consider the two reads to be from the same fragment.

I hope this helps you, please ask again if it is still not clear.

Best,

Joachim

**Comment by ChristopherBarrington** [comment]
OK, thank you for the explanation. I understand the logic now. So to change the `maxLibraryInsertSize` parameter I would have to generate the QC log via `hicBuildMatrix` - the parameter isn't listed in the docs for `hicQuickQC`?

**Comment by joachimwolff** [comment]
`hicQuickQC` is just a wrapper for `hicBuildMatrix`, if you call `hicBuildMatrix` with `--doTestRun` and `--doTestRunLines 1000000` and add the parameters for `--restrictionSequence` and `--danglingSequence` it behaves identical to `hicBuildMatrix`.

**Comment by ChristopherBarrington** [comment]
That's great, thank you for the help.
