### ISSUE TITLE
hicConvertFormat: how to convert h5 to hicpro

### ISSUE THREAD

**Issue by zhanzhan90** [deeptools/HiCExplorer#569]
Hi,

Matrices generated by HiC-Pro can be converted to h5 by hicConvertFormat. I wonder can I do it reversely? I noticed hicpro format is not supported as output in current release. If not, can any other supported formats be used as input of HiC-Pro?

Best

**Comment by LeilyR** [comment]
Hi, Supported formats for the output of hicConvertMatrix are `cool, h5, homer, ginteractions, mcool`.

**Comment by zhanzhan90** [comment]
Thanks
