### ISSUE TITLE
hicFindTADs with input files different from h5...

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCExplorer#571]
Hi,
I just noticed that if you use hicFindTADs with a cool matrix, then the zscore_matrix is ending with `h5` but it is a `cool` file:
https://github.com/deeptools/HiCExplorer/blob/22b731cfd537a38e870883e523ab0847ca3fa895/hicexplorer/hicFindTADs.py#L1378
Then I realized that if the input matrix would be hicpro it would raise an error...
I don't know how you want to deal with that but if you have an idea I can write a PR.

**Comment by joachimwolff** [comment]
This is already fixed in develop branch, will be released with the next version.
