### ISSUE TITLE
Different results by hicPCA and hicTransform

### ISSUE THREAD

**Issue by zhanzhan90** [deeptools/HiCExplorer#580]
Hi,

Recently I found obs/exp matrices calculated by hicPCA and hicTransform are different. This is contact matrix:

![chr8_contactMatrix](https://user-images.githubusercontent.com/66302892/87139047-f144e900-c2d1-11ea-9cc2-3e89df7a819a.png)

When hicPCA was used, the result looked like this:

`hicPCA -m matrix_iced.h5 -o pca1.bdg pca2.bdg -f bedgraph -oem matrix_oem.h5`

![oem_PCA](https://user-images.githubusercontent.com/66302892/87137737-fb65e800-c2cf-11ea-9d44-7427ba46afcb.png)

But when hicTransform was used, the result was more "clean":

`hicTransform -m matrix_iced.h5 -me obs_exp -o matrix_troem.h5`

![troem_PCA](https://user-images.githubusercontent.com/66302892/87137683-e2f5cd80-c2cf-11ea-9775-1f51a10e40b6.png)

It seems hicTransform masked more interaction pairs especially at the diagonal. I wonder what makes them different and which method is more reasonable. 

Thanks

**Comment by LeilyR** [comment]
In hicTransform : `obs_exp computes the expected matrix as the sum per genomic distance j divided by maximal possible contacts: sum(diagonal(j) / number of elements in diagonal(j) ` and it is going to be genome wide unless you ask for it to be done per chromosme. 
In hicPCA it is computed per chromosome and by default (`dist_norm`) uses a method which is  equivalent of hicTransform `obs_exp_non_zero` method. (`computes the expected matrix as the sum per genomic distance j divided by sum of non-zero contacts: sum(diagonal(j) / number of non-zero elements in diagonal(j)`)

**Comment by zhanzhan90** [comment]
Thank you for quick reply.

One following question is that these two methods also generate very different pearson matrices. Is that also caused by genome range (whole genome vs per chromosome) and contacts (all vs non_zero)

**Comment by zhanzhan90** [comment]
I saw similar question was asked in #578. It seems that difference in genome range is the key.

**Comment by joachimwolff** [comment]
Hi,

Yes, the different obs_exp methods create different results and therefore all subsequent steps will create a different output.

Best,

Joachim

**Comment by HengkuanLi** [comment]
Hi! When using hicTransform to generate the O/E matrix, is it more appropriate to perform the analysis genome-wide or per chromosome?
