### ISSUE TITLE
hicConvertFormat do nothing with the not chr start chromosome name

### ISSUE THREAD

**Issue by seqyuan** [deeptools/HiCExplorer#583]
hicConvertFormat do nothing with my .hic format file, my be not compatible with the chromosome name not start with 'chr'

**Comment by joachimwolff** [comment]
Hi,

Would you be so kind and post the used version, the command and maybe the bash output? Without this information it is difficult to determine where the problem is located.

Best,

Joachim

**Comment by seqyuan** [comment]
> Hi,
> 
> Would you be so kind and post the used version, the command and maybe the bash output? Without this information it is difficult to determine where the problem is located.
> 
> Best,
> 
> Joachim

Thank you very much, I used the latest version, here is my command: 
`hicConvertFormat -m FT0126.Pp01.hic --inputFormat hic --outputFormat ginteractions -o FT0126.Pp01.ginteractions --resolutions 5000`

there is none bash  output, so  I wonder whether `hicConvertFormat` compatible with the chromosome name not start with 'chr', because the chromosome name is like this: `Pp01`.

The following is my  .hic format file (31M).
https://drive.google.com/file/d/1tEOWwbZi7ECsHLbfO_zxdUITMOt5Sx-5/view?usp=sharing

Best,

seqyuan

**Comment by joachimwolff** [comment]
Hi,

As stated in our documentation, a direct converting from hic files is only possible to cooler files. To get your desired output you have to first convert hic to cool, then cool to cool and apply your desired correction factors, and finally, cool to ginteractions. 

Please consider especially this section in our docs: https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#hic2cool
And for the second step: https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#cool-to-cool

Best,

Joachim
