### ISSUE TITLE
hicCorrelate does not plot the right colormap in the correlation heatmap

### ISSUE THREAD

**Issue by dmalzl** [deeptools/HiCExplorer#585]
I recently used hicCorrelate to get a correlation between my Hi-C replicates and sequencing runs. After the first plot did not look decent in terms of the colormap I decided to redo them with a different one. Unfortunately, this also looked quite odd and did not change for an array of other named colormaps. Having a look at the code, I quickly identified the line causing this.
The `plotCorrelation` gets passed the `args.colorMap` variable and uses it to fetch the respective `colormap` object from `matplotlib`. Subsequently, the script tries to clip the colormap to avoid colors that are too dark for plotting numbers with:

```python
cmap = cmap.from_list(colormap + "clipped", cmap([0.0, 0.8]))
```

But `cmap([0.0, 0.8])` does not return colors in the range from 0.0 to 0.8, but only two colors corresponding to 0.0 and 0.8 and `cmap.from_list` then generates a colormap by interpolation between the two returned colors effectively making a very different colormap than intended by the user. I would suggest doing it the same way as in deeptools plotCorrelation:

```python
if plot_numbers:
        cmap = pltcolors.LinearSegmentedColormap.from_list(colormap + "clipped",
                                                           cmap(np.linspace(0, 0.9, 10)))
```

This way the transformation is also avoided when --plotNumbers is not specified.

**Comment by dmalzl** [comment]
Additionally, it would be nice to also make the text importable as actual text in Adobe Illustrator.

**Comment by joachimwolff** [comment]
Text: Don't know if that is possible. I don't have Adobe Illustrator, and matplotlib is responsible for this. However, I know that it should work with Inkscape, maybe that is some alternative for you.

**Comment by dmalzl** [comment]
@joachimwolff I think it's just a matter of setting the matplotlib rcparams right like:
```python
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
```

Thanks, for taking care of the issue

**Comment by joachimwolff** [comment]
Ok, I actually never dug that deep in the settings of matplotlib. But this setting is only for pdfs, what about svg, eps? Or is there the issue of importing to Illustrator not existent?

**Comment by dmalzl** [comment]
It is actually out of pure convenience of sharing results with collaborators such that they can view it and make figures as needed. That's why I said it would be nice to have it. But there is no obligation, just a suggestion :). I actually never thought about svg or eps but I might consider it in the future.

**Comment by joachimwolff** [comment]
I added it to the development branch. Would be great if you can test it and give me feedback if it works as expected.

**Comment by dmalzl** [comment]
Works perfectly now and the text is also editable in Illustrator. Thank you very much for taking care
