### ISSUE TITLE
saddle plot contains value "0"

### ISSUE THREAD

**Issue by zhanzhan90** [deeptools/HiCExplorer#589]
Hi,

Thank you a lot for this user-friendly tool to process Hi-C data. Recently I found my saddle plot looked strange because it contained "0" columns and rows in the middle.  
![saddle_0h](https://user-images.githubusercontent.com/66302892/87846697-5f0d9800-c904-11ea-9b63-e16e76f23713.png)

Compartment strength seems normal.
![compStrength_0h](https://user-images.githubusercontent.com/66302892/87846874-ec052100-c905-11ea-8992-995cfc4a58c2.png)

Saddle plot is created by matplotlib from npz matrix, which is an output of hicCompartmentalization. Use `--offset 0` or `--offset 0 1` didn't make any difference in output matrix. I'm confused why "0" values occur in the middle of matrix.

Thank you again.

**Comment by LeilyR** [comment]
This could be because of the bins values on your obs/exp matrix(0 or nan). My suggestions are:
1. cut some of the outlier bins out ( `--outliers` ~5%)
2. try with the smaller number on bins for compartmentalization matrix (`q` ~20)

**Comment by zhanzhan90** [comment]
Thank you for suggestions. I tried to cut 1% outlier bins out and plot looks much better. 
![saddle_0h_q30](https://user-images.githubusercontent.com/66302892/89255423-44e9ee80-d654-11ea-89db-f8ba103d5bd3.png)

**Comment by 14stutzmanav** [comment]
Hi all,

Could someone please share how they used imshow to plot the .npz file?

Thanks a lot!

**Comment by LeilyR** [comment]
something like this should do the job:
```
import matplotlib.pyplot as plt
import numpy as np
with np.load(out_path+"saddle_matrix.npz") as data:
    a = data['arr_0'][0]
    plt.imshow(np.log10(a), cmap='RdBu_r', vmin = -0.5, vmax = 0.5)
plt.savefig(out_path+"saddle_matrix.png", format="png")
```
