### ISSUE TITLE
Apply weights to cool files

### ISSUE THREAD

**Issue by brainfo** [deeptools/HiCExplorer#595]
Just need clarification:
in hicPlotMatrix, by default, it applies correction (* weight) on the matrix? And in hicCorrelate, by default, it doesn't apply such correction?
And I think maybe some times we wanna see the matrix correlation after this weight applied? Can you help or give some hint on how to do this? Or in a professional view, the correlation after applying weights cannot serve as any reference?

for hicCorrelate on cooler balance output matrix, I tried setting pApplyCorrectionCoolerLoad==True when calling matrixFileHandler but it turns out such error that  (hicCorrelate.py line 396) results[row, col] = correlation_opts[args.method](vector1, vector2)[0], the vector length is less than 2.
My matrix when ICE normalized is like this (40kb bin):
![image](https://user-images.githubusercontent.com/11832080/89914394-89aef000-dc27-11ea-88d1-42c2077c0046.png)
And if ICE to column sum 1 is like this (40kb bin):
![image](https://user-images.githubusercontent.com/11832080/89914570-c549ba00-dc27-11ea-987c-44205453220a.png)
This sample in the correlation scatter plot (Y axis) (40 kb bin, 40kb-200kb range, all autosomes):
![image](https://user-images.githubusercontent.com/11832080/89915251-b31c4b80-dc28-11ea-9f4d-0fe42af851c7.png)

Thank you!

**Comment by joachimwolff** [comment]
Sorry, I cannot follow your argumentation. The correction factors are always applied if present. There is no way for a user to define this in the mentioned tools.

**Comment by brainfo** [comment]
> Sorry, I cannot follow your argumentation. The correction factors are always applied if present. There is no way for a user to define this in the mentioned tools.

For example, the default usage of hicPlotMatrix (v 3.5) (--log, --region chr1:1M-165M, others default) on my 'KK_merge_40000.cool' (cooler balance --check, is balanced) is like this:
![image](https://user-images.githubusercontent.com/11832080/89976160-48a3f380-dc9a-11ea-9486-dd3c4ac6ca44.png)
in hicmatrx package (v 14), HiCMatrix.py line 54, it said 'self.matrixFileHandler = MatrixFileHandler(pFileType=fileType, pApplyCorrectionCoolerLoad=False, pMatrixFile=pMatrixFile, pChrnameList=pChrnameList, pDistance=pDistance, pMatrixFormat=pMatrixFormat, pLoadMatrixOnly=pLoadMatrixOnly)'
for example, here, setting the pApplyCorrectionCoolerLoad=True, the hicPlotmatrix (--log, --region chr1:1M-165M, others default)  on that 'KK_merge_40000.cool' is this:
![image](https://user-images.githubusercontent.com/11832080/89976355-cb2cb300-dc9a-11ea-8f37-5a4b4076a888.png)
Same happens for tad plot from pygenometracks (v3.5).
But no change for hicCorrelate (v 3.5).

Oh, while writing this I just noticed that the required version of hicmatrix is 11 for hicexplorer, but I have v 14.

I'll check for v 11 to continue my work.
Thank you very much for your help!

**Comment by lldelisle** [comment]
Indeed it changed between v13 to v14.

**Comment by joachimwolff** [comment]
I confirm this bug and apologize because this is really an avoidable mistake. Unfortunately the test cases did not cover this case, and it actually is a bug with major influence! Thanks @brainfo and @lldelisle for making me aware of it. Will fix it asap!
