### ISSUE TITLE
hicPlotMatrix --chromosomeOrder

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#596]
`chromosomeOrder` generates incorrect matrices. The output is showing this issue if comparing the rows and columns values also if compare the figures obtained from two different orders. example:
![test_3 4 3_1](https://user-images.githubusercontent.com/25766687/91717641-31b63a00-eb92-11ea-9ccc-55afac0974ec.png)
![test_3 4 3](https://user-images.githubusercontent.com/25766687/91717646-34189400-eb92-11ea-997b-75a21e03af80.png)

**Comment by joachimwolff** [comment]
Should be fixed with release 3.5.2. Please reopen if the issue still exists in this release.
