### ISSUE TITLE
hicBuildMatrix error: --restrictionCutFile required while --restrictionSequence is provided

### ISSUE THREAD

**Issue by mdozmorov** [deeptools/HiCExplorer#598]
Hi,
I try to build a matrix with a fixed bin size. The command is:
``` bash
hicBuildMatrix -s $BAMR1 $BAMR2 \
               --binSize 10000 \
               --restrictionSequence GATC \
               --danglingSequence GATC \
               --QCfolder binSizeQCs \
               --threads 8 \
               --outBam binSize.bam \
               --outFileName binSize.h5 \
               --inputBufferSize 400000
```

From the documentation and this issue #520 it is obvious `--restrictionSequence` and `--restrictionCutFile` are mutually exclusive. I'm getting an error:
``` bash
hicBuildMatrix: error: the following arguments are required: --restrictionCutFile/-rs
```
What may be wrong?

Thanks,
Mikhail

**Comment by LeilyR** [comment]
This has been updated in the more recent versions to result in a more accurate QC report. The documentation has been updated for our [develop](https://hicexplorer.readthedocs.io/en/develop/content/tools/hicBuildMatrix.html) branch but indeed has not been merged to the master yet. I will write a comment on #520 to avoid any confusion in the future too.

**Comment by mdozmorov** [comment]
Updating HiCExplorer didn't help. I did the following:
``` bash
# Remove old version
conda remove --name HiCExplorer --all
# Install the latest
conda create --name HiCExplorer hicexplorer=3.5 python=3.6 -c conda-forge -c bioconda
# Test it is updated
source activate HiCExplorer
hicexplorer --version
hicexplorer 3.5.1
```
Trying the above hicBuildMatrix command results in the same error:
```
hicBuildMatrix: error: the following arguments are required: --restrictionCutFile/-rs
```
I see changes in the documentation, nothing unusual, just clarifications. Any other ideas how to solve this error?

**Comment by LeilyR** [comment]
I am afraid I was not clear enough. I meant now you need to provide both of them at the same time, if you are interested in bin size matrices. In this case `-rs` is used to provide you with a more accurate QC report. Documentation is updated under the [develop branch.](https://hicexplorer.readthedocs.io/en/develop/content/tools/hicBuildMatrix.html#hicbuildmatrix)

**Comment by mdozmorov** [comment]
Thank you, yes, it makes sense. And, the command runs with `-rs` along with `--binSize` and `-seq` settings. Looks like the issue is solved.

**Comment by LeilyR** [comment]
@mdozmorov Just to let you, I have updated our [readthedoc](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicBuildMatrix.html).
