### ISSUE TITLE
DNAse Hi-C

### ISSUE THREAD

**Issue by dabitz** [deeptools/HiCExplorer#599]
Hello,

I have recently performed an Omni-C library, which is actually a DNAse-based Hi-C protocol. I want to know if HiCExplorer can handle these libraries and how to set up in that case?

Best,
André

**Comment by joachimwolff** [comment]
Hi André,

I had a quick scan at the protocol, and could not detect a difference to Hi-C at the output. However, I just spend a minute on this and maybe I have missed something.

For HiCExplorer we expect either two mapped (forward and reverse strand) BAM files (representing the chimeric reads), the cut sequence, the dangling end sequence and the locations of the cut sites. Or an already created cooler / h5 file containing the interaction matrix. If these requirements are met, I don't see why it should not work. 

Please check if these requirements are met,

Joachim

**Comment by dabitz** [comment]
Thanks for the quick reply. In fact DNASE hic there is no specific restriction site, as the enzyme is supposed to cut the genome randomly. that is the only difference. So I cannot tell the restriction site for hicexplorer.

**Comment by joachimwolff** [comment]
In this case the only workaround is to specify random sequences and to accept the quality report is for the restriction cut site and dangling ends non-sense.

**Comment by dabitz** [comment]
Can I provide a fasta file with all the random cut sites? I just figured out that if I generate random sites for a 4-nucleotide sequence I will have 135 sites!

**Comment by joachimwolff** [comment]
You need to provide a space separated list, a fasta file support is not implemented so far.

This is an example for two restriction sites, you need to extend this for all of your 135. I hope this works we have tested this for max 2 sequences so far. 
`hicBuildMatrix -s foo.bam foo1.bam --restrictionSequence acgt acgg --danglingSequence acgt acgg --restrictionCutFile cutsitesACGT.bed cutsitesACGG.bed`

**Comment by LeilyR** [comment]
I am afraid it is going to be more than that, your mapped reads need to be validated to be a valid pair for building hic matrix. I am not sure the checks we have there are enough in this case. I am not familiar with Dnase HiC though I should say.

**Comment by dabitz** [comment]
Yes, I have already filtered the bam files for chimeric reads... just need to combine the pairs and build the matrix. I have tried with different software and to check how hicexplorer perform on this data as well.

**Comment by LeilyR** [comment]
ah ok I see then i think it should be fine

**Comment by dabitz** [comment]
Funny... I got the hicFindRestSite running only with one site. When I try two or more it produces an empty bed file. I tried separating the sites with space and comma, but both didn't work. Any idea?

**Comment by joachimwolff** [comment]
You can run hicFindRestSite only with one site.
