### ISSUE TITLE
hicConvertFormat : .hic file to .h5 conversion

### ISSUE THREAD

**Issue by CDL-HongwooLee** [deeptools/HiCExplorer#601]
Hi,

I wanted to generate a fragment resolution matrix (.h5) file from a '.hic. file (including fragment resolution).

I tried to convert a '.hic' file to a '.h5' file by hicConvertFormat & hic2cool, however, there is no option for supporting fragment resolution matrices.

Could you give me a solution for the conversion or should I generate the fragment resolution matrix from the raw sequencing file?

Best,
Lee

**Comment by LeilyR** [comment]
hicConverFormat, only convert the formats as the name says. It does not change your matrix resolution. the output has the same resolution as your input.

**Comment by CDL-HongwooLee** [comment]
Thanks,


You mean hicConvertFormat can convert not only the fixed-interval matrices but also the fragment-delimited matrices, if my input .hic file includes the fragment-delimited matrices?

Another question is, can hicConverFormat convert the .hic file to .h5 format directly? Or should go through .cool file?
________________________________
보낸 사람: LeilyR <notifications@github.com>
보낸 날짜: 2020년 9월 15일 화요일 오후 9:17
받는 사람: deeptools/HiCExplorer <HiCExplorer@noreply.github.com>
참조: 이홍우 <miso5103@snu.ac.kr>; Author <author@noreply.github.com>
제목: Re: [deeptools/HiCExplorer] hicConvertFormat : .hic file to .h5 conversion (#601)


hicConverFormat, only convert the formats as the name says. It does not change your matrix resolution. the output has the same resolution as your input.

**Comment by LeilyR** [comment]
This part of our documentation may help you:

```
The following example will convert a hic file which contains the resolution of 1000 to a cool file with 10kb resolution. The desired resolution needs to be existing in the hic file. If no resolution parameter is defined, a mcool file with all available resolutions is created.
$ hicConvertFormat -m matrix.hic --inputFormat hic --outputFormat cool -o matrix.cool --resolutions 10000
It is only possible to convert from hic to cool format, no other formats are supported
```

you can find this, and more about this tool [here](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#hicconvertformat).

**Comment by CDL-HongwooLee** [comment]
Thanks for your response.


Maybe I recognized the problem that hic2cool cannot convert the fragment-matrix from a hic file to the cool file.
And I could get the fragment-matrix h5 file by cooler load and hicConvertFormat.

Now I'm trying to find TAD using hicFindTAD with my fragment-matrix.
Is there any recommendable --minDepth value for fragment-delimited matrices?


Thanks
________________________________
보낸 사람: LeilyR <notifications@github.com>
보낸 날짜: 2020년 9월 16일 수요일 오후 4:45
받는 사람: deeptools/HiCExplorer <HiCExplorer@noreply.github.com>
참조: 이홍우 <miso5103@snu.ac.kr>; Author <author@noreply.github.com>
제목: Re: [deeptools/HiCExplorer] hicConvertFormat : .hic file to .h5 conversion (#601)


This part of our documentation may help you:

The following example will convert a hic file which contains the resolution of 1000 to a cool file with 10kb resolution. The desired resolution needs to be existing in the hic file. If no resolution parameter is defined, a mcool file with all available resolutions is created.
$ hicConvertFormat -m matrix.hic --inputFormat hic --outputFormat cool -o matrix.cool --resolutions 10000
It is only possible to convert from hic to cool format, no other formats are supported


you can find this, and more about this tool here<https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#hicconvertformat>.

**Comment by LeilyR** [comment]
As stated in our doc it should be at least 3 times bigger than the bin size, but  if your matrices are RS with no bin merging then you can consider it even more than that, something like 5k should be fine, I'd say.
