### ISSUE TITLE
how to distinguish loop TADs and not loop TADs by using hicFindTADs 

### ISSUE THREAD

**Issue by Nuturetree** [deeptools/HiCExplorer#608]
Hi
  i statistics the length of TADs that be identified by hicFindTADs in genome， the proportion of TADs in genome always close 100%。 i guess this TADs that be identified by hicFindTADs include loop TADs and not loop TADs。i want to know how to get loop TAD by hicexplorer？

**Comment by joachimwolff** [comment]
Can you clarify your understanding of a loop TAD and a non-loop TAD? Unfortunately there is no clear definition of these terms and it would be helpful to help you if I know your definition of it.

**Comment by Nuturetree** [comment]
> Can you clarify your understanding of a loop TAD and a non-loop TAD? Unfortunately there is no clear definition of these terms and it would be helpful to help you if I know your definition of it.

As we know that TAD is composed of many loops，not the entire gene region can form TAD。just like euchromatin is easier to form TAD than heterochromatin，but the  analysis result by using hicFindTADs is all gene region can form TAD。i want to find loop TAD that formed by loop。so how i can do to find this TADs.

**Comment by joachimwolff** [comment]
If I do understand you in the correct way, we can offer hicFindTADs and hicDetectLoops, however we do not have something which can identify if a loop is a loop for its own or loop-TAD.  Moreover, to identify euchromatin/hetrochromatin regions you can use hicPCA to compute the A/B compartments. I recommend to plot the results with hicPlotTADs to get the insight you like to have.

**Comment by Nuturetree** [comment]
OK，thanks





发自网易邮箱大师
On 10/09/2020 18:06, Joachim Wolff wrote:

If I do understand you in the correct way, we can offer hicFindTADs and hicDetectLoops, however we do not have something which can identify if a loop is a loop for its own or loop-TAD. Moreover, to identify euchromatin/hetrochromatin regions you can use hicPCA to compute the A/B compartments. I recommend to plot the results with hicPlotTADs to get the insight you like to have.
