### ISSUE TITLE
Abnormal diagnostic plot result in hicCorrectMatrix

### ISSUE THREAD

**Issue by yanchunzhang** [deeptools/HiCExplorer#611]
Hi, thank you for developing these great tools.
I got some abnormal distribution in diagnostic plots by hicCorrectMatrix which were not a regular shape of Gaussian curve. I guess these may because of technical problems? Could you please comment or interprete a little on these distribution?  And any suggestions on further analysis on these data?

The following two figures showed a second small peak at left end:
![22RV1_Scr_10000_normalized h5 correct_histo](https://user-images.githubusercontent.com/19245352/95135183-a9dfc480-0729-11eb-9e58-d823ec588d57.png)
![PrEC_10000_normalized h5 correct_histo](https://user-images.githubusercontent.com/19245352/95135211-b19f6900-0729-11eb-8ef4-8ef2ce220eb4.png)

The following two figures showed leftward shift:
![H660_10000_normalized h5 correct_histo](https://user-images.githubusercontent.com/19245352/95135254-bc59fe00-0729-11eb-8f3b-8ed575fe91da.png)
![RWPE1_10000_normalized h5 correct_histo](https://user-images.githubusercontent.com/19245352/95135262-c11eb200-0729-11eb-84c2-eea8106f0aab.png)

This figure showed straight decline instead of smooth-curve:
![BPH1_10000_normalized h5 correct_histo](https://user-images.githubusercontent.com/19245352/95135269-c54acf80-0729-11eb-8d71-d5cf8a6ffd5d.png)

Thanks!

**Comment by LeilyR** [comment]
Your plots look how usually a hic count distribution should be, I see nothing abnormal in it.  The small peak on the left shows the (almost) empty bins.

**Comment by yanchunzhang** [comment]
> Your plots look how usually a hic count distribution should be, I see nothing abnormal in it. The small peak on the left shows the (almost) empty bins.

Thanks for your reply! The small peak I mentioned is the peak around x=1000, do you have any interpretation on that?

**Comment by yanchunzhang** [comment]
Hi @LeilyR, I also come across another issue that I tried to do VC correction after normalization on a cool file converted from hic format. But I found that the correction attributes heritated from hic file (KR, VC, VC_SQRT) were all lost after the normalization of cool file. Do you think is it possible that I want to do both VC correction and normalization with a cool file.
Thanks!

**Comment by joachimwolff** [comment]
This approach is problematic. Your VC correction values are computed for the values as they are stored in the matrix. If you now change them by normalizing, the correction factors are quite likely not mathematical correct anymore and your interaction matrix values will become wrong.

**Comment by yanchunzhang** [comment]
> This approach is problematic. Your VC correction values are computed for the values as they are stored in the matrix. If you now change them by normalizing, the correction factors are quite likely not mathematical correct anymore and your interaction matrix values will become wrong.

Thanks for your reply, @joachimwolff ! In my understanding, the normalization on cool file will operate on the raw values stored in cool file, not the corrected values because I just converted the file from hic and didn't add the correction_name parameter. And when after normalization, the normalized cool file just discard those correction attributes heritated from hic file, so we just cannot do the VC correction anymore but should expect get a right normalized value. Is my understanding right?

**Comment by yanchunzhang** [comment]
I still have another two more questions... 
The first is I understand that the p-value in hicFindTADs is mainly calculated on the region in minDepth length around candidate boundary bin,

> The probability of a local minima to be a boundary is estimated by comparing the distribution (Wilcoxon ranksum) of the z-scores between the left and right regions (diamond) at the local minimum with the matrix z-scores for a diamond at –minDepth to the left and a diamond –minDepth to the right. quote from [https://hicexplorer.readthedocs.io/en/latest/content/tools/hicFindTADs.html#hicfindtads](url)
so what's the meaning of the larger window size up to the maxDepth?

The second is have you come across this phenomenon that hicPlotTADs generated an uneven scale? Please see the following figure.
![NLGN1 copy](https://user-images.githubusercontent.com/19245352/95293535-35944680-0839-11eb-9d22-34bd12d60663.png)

Thanks for your patience :)

**Comment by joachimwolff** [comment]
> > This approach is problematic. Your VC correction values are computed for the values as they are stored in the matrix. If you now change them by normalizing, the correction factors are quite likely not mathematical correct anymore and your interaction matrix values will become wrong.
> 
> Thanks for your reply, @joachimwolff ! In my understanding, the normalization on cool file will operate on the raw values stored in cool file, not the corrected values because I just converted the file from hic and didn't add the correction_name parameter. And when after normalization, the normalized cool file just discard those correction attributes heritated from hic file, 
Yes so far it is correct
> so we just cannot do the VC correction anymore but should expect get a right normalized value. Is my understanding right?
Well, you could save the VR correction factors (a bit complicated but I think it is possible), however, to apply them will lead to a mathematical wrong interaction matrix.

The main problem is that your correction factors are computed on the raw values. To normalize the raw values to your desired range, will cause that the previous calculated correction factors are wrong.
In your special case: You have to apply the normalization and do on these values a new correction that we support e.g. ICE or KR.

**Comment by joachimwolff** [comment]
> I still have another two more questions...
> The first is I understand that the p-value in hicFindTADs is mainly calculated on the region in minDepth length around candidate boundary bin,
> 
> > The probability of a local minima to be a boundary is estimated by comparing the distribution (Wilcoxon ranksum) of the z-scores between the left and right regions (diamond) at the local minimum with the matrix z-scores for a diamond at –minDepth to the left and a diamond –minDepth to the right. quote from [https://hicexplorer.readthedocs.io/en/latest/content/tools/hicFindTADs.html#hicfindtads](url)
> > so what's the meaning of the larger window size up to the maxDepth?
> 

A larger window size will include more values for the calculation: https://hicexplorer.readthedocs.io/en/latest/content/tools/hicFindTADs.html?highlight=step#Optional%20arguments
Please consider: https://www.nature.com/articles/s41467-017-02525-w 'identification of boundaries'

> The second is have you come across this phenomenon that hicPlotTADs generated an uneven scale? Please see the following figure.
> ![NLGN1 copy](https://user-images.githubusercontent.com/19245352/95293535-35944680-0839-11eb-9d22-34bd12d60663.png)
> 


We use pyGenomeTracks in the background to plot this, please check if you have installed the latest version. If so, I kindly ask you to report this issue in the pyGenomeTracks repository: https://github.com/deeptools/pyGenomeTracks

However, can you define 'uneven scale'? There parameters like min/max values to control the scale, and if no scale is given, the min/max values are used as they are given in the data. For example: https://pygenometracks.readthedocs.io/en/latest/content/tracks/bigwig.html?highlight=min

> Thanks for your patience :)
