### ISSUE TITLE
hicBuildMatrix 3.5

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#613]
It seems to be a newly introduced bug in hicBuildMatrix which causes [this](https://github.com/maxplanck-ie/snakepipes/issues/697)

**Comment by joachimwolff** [comment]
Confirming this bug, if you are affected by it, please use HiCExplorer version 3.4.3 until this bug is resolved.

**Comment by LeilyR** [comment]
This is related to the used restriction enzyme, only happens if the enzyme is wrong and no valid pair found or very little valid pair found. I do not know what is the right error message here though.

**Comment by joachimwolff** [comment]
Fixed with 3.5.3 release. Please reopen if it is still existing.

**Comment by joachimwolff** [comment]
Should be fixed with release 3.6. Please reopen if it is still existing.
