### ISSUE TITLE
hicDifferentialTAD

### ISSUE THREAD

**Issue by biohubx** [deeptools/HiCExplorer#614]
Hi,

     Can I use hicDifferentialTAD to analyze differential TADs based on the TADs generated by rGMAP, and normalized contatc matrix generated by HiC-Pro?

Best,

**Comment by joachimwolff** [comment]
Hi,

you can do this if the computed TAD domains file has at least six columns and the first three are chromosome, start, end e.g. https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/test/test_data/hicDifferentialTAD/untreated_R1_domains.bed

HiC-Pro: possible, but you have to convert the format with hicConvertFormat from hicpro to cooler or h5 https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicConvertFormat.py
https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#hic-pro

Best,

Joachim
