### ISSUE TITLE
Create a matrix of an specific region(s)

### ISSUE THREAD

**Issue by luciaalvarez95** [deeptools/HiCExplorer#616]
Hi!

I have been working with HiCExplorer for a while and I wonder if there is a possibility to create a matrix of an specific region(s) somehow. I am aware that you can plot whatever region you want to plot but it would like to know if there is a way to create a matrix of that specific plotted regions too.

Many thanks

Lucía

**Comment by LeilyR** [comment]
Hi Lucia, 

You can use hicAdjustMatrix or run hicBuildMatrix with  --region, if only one region is of your interest.

**Comment by luciaalvarez95** [comment]
Amazing! I will try it. 

Many thanks for you quick response!

Lucía
