### ISSUE TITLE
hicPCA and NaN bins

### ISSUE THREAD

**Issue by PerrineLacour** [deeptools/HiCExplorer#618]
Hello,
I used hicPCA (version 3.4.3) on two HiC corrected matrices 
` hicPCA --matrix 'matrix.h5'     --outputFileName pca1.bigwig pca2.bigwig --format bigwig     --pearsonMatrix pearson.h5 `
and wanted to compare the Pearson matrices obtained by using hicCompareMatrices 
` hicCompareMatrices --matrices 'matrix1.h5' 'matrix2.h5' --operation diff --outFileName 'matrix.h5' `
but I get this error
Fatal error: Exit code 1 ()
The two matrices have different size. Use matrices having the same resolution and created usingthe same parameters. Check the matrix values using the tool `hicInfo`.

When checking the infos, I saw that the two Pearson matrices have different sizes (2666 vs 2645), even though the input matrices were of the same size (2678). The only difference is the number of NaN bins in the input matrices (12 vs 33).

I thought that all bins were kept in the Pearson matrix with the options I used. Is this a bug or should I use other options?
Thanks for your help!

**Comment by joachimwolff** [comment]
Hi,

sorry for the late reply. Is this issue still open for you, concerning your other issue with the person matrices for version 3.5.3?

If yes please reply, I will have a look into this, otherwise please close this issue.

Best,

Joachim

**Comment by PerrineLacour** [comment]
Hi, 

Thank you for your answer! Yes I still have this problem, and it is also the case with version 3.5.3. 

Best, 

Perrine

**Comment by joachimwolff** [comment]
@PerrineLacour  Will be fixed in version 3.7.
