### ISSUE TITLE
hicPCA gene track format

### ISSUE THREAD

**Issue by PerrineLacour** [deeptools/HiCExplorer#621]
Hello, 

I used hicPCA `version 3.5.3` with a gene track (bed6 format)
`hicPCA --matrix "matrix.h5" -o "PC1-flip.bw" "PC2-flip.bw" "PC3-flip.bw" -noe 3 --extraTrack "dmel-all-r6.genes.chrfiltered.bed"`
and I get this error
`ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
 File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicmatrix/HiCMatrix.py", line 269, in getRegionBinRange
    startbin = sorted(self.interval_trees[chrname][startpos:startpos + 1])[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/bin/hicPCA", line 7, in <module>
    main()
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 334, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/g/funcgen/gbcs/public/software/conda/envs/hicexplorer-3.5.3/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 158, in correlateEigenvectorWithGeneTrack
    gene_occurrence[bin_id[1]] += 1
TypeError: 'NoneType' object is not subscriptable`

I don't understand where it comes from. Which format should I use for the gene track?
Thank you for your help,

Best,

**Comment by LeilyR** [comment]
gene track should be a bed file. check our test gene track [here](https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/test/test_data/dm3_genes.bed.gz)

Here is a few lines of it:
```
chrX	22409507	22411288	CR45009	0	+	22411288	22411288	0	2	127,532,	0,1249,
chrX	22410601	22413139	FucTC	0	-	22410757	22412570	0	2	592,1409,	0,1129,
chrX	22412807	22413129	CR45010	0	+	22413129	22413129	0	1	322,	0,
chrX	22413975	22415052	Rab21	0	-	22414212	22414782	0	1	1077,	0,
chrX	22415330	22416102	CG13865	0	+	22415417	22415995	0	2	187,448,	0,324,

```
The error you posted suggests that one of the intervals in your bed file might have exceeded a chromosome range . We have add a check for that in our code to return more clear error message.

**Comment by Jwindler** [comment]
> gene track should be a bed file. check our test gene track [here](https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/test/test_data/dm3_genes.bed.gz)
> 
> Here is a few lines of it:
> 
> ```
> chrX	22409507	22411288	CR45009	0	+	22411288	22411288	0	2	127,532,	0,1249,
> chrX	22410601	22413139	FucTC	0	-	22410757	22412570	0	2	592,1409,	0,1129,
> chrX	22412807	22413129	CR45010	0	+	22413129	22413129	0	1	322,	0,
> chrX	22413975	22415052	Rab21	0	-	22414212	22414782	0	1	1077,	0,
> chrX	22415330	22416102	CG13865	0	+	22415417	22415995	0	2	187,448,	0,324,
> ```
> 
> The error you posted suggests that one of the intervals in your bed file might have exceeded a chromosome range . We have add a check for that in our code to return more clear error message.

could you tell me how to get this file or each col meaning for ? @LeilyR
