### ISSUE TITLE
difference in contact matrices

### ISSUE THREAD

**Issue by benxiahu** [deeptools/HiCExplorer#622]
Hi,
   I want to analyze the difference of 2 normalized contact matrices generated by HiC-Pro. However, the sequencing depth of two Hi-C libraries is different.

  Can I just use hicCompareMatrices to compare those 2 normalized contact matrices?

Best,

**Comment by joachimwolff** [comment]
Hi,

it would be the best to normalize for the read coverage first using hicNormalize with the mode 'smallest'.

Best,

Joachim

**Comment by benxiahu** [comment]
thanks
