### ISSUE TITLE
Converting npz files from DeepHiC pipeline to hic files

### ISSUE THREAD

**Issue by smurthy55** [deeptools/HiCExplorer#623]
Hi!

Hope you are doing well. I am trying to convert npz files from the DeepHiC pipeline (https://github.com/omegahh/DeepHiC ) to a hic file to visualize using the hicExport command in hicexplorer/2.0. However, the element names in these generated npz files are different:

>>> z = np.load('deephic_10kb40kb_c40_s40_b201_nonpool_valid.npz', mmap_mode='r')
>>> for k in z.files:
...     print(k)
... 
data
target
inds
compacts
sizes

Do you have suggestions on how I can convert this file to a .hic file, or a valid pairs type of file that can then be converted into a .hic file?

**Comment by joachimwolff** [comment]
Hi,

we support only to read .hic files but not to write. I asked for some API implementation similar to hic2cool (https://groups.google.com/forum/embed/?place=forum/3d-genomics&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Faidenlab.org%2Fforum.html#!topic/3d-genomics/jCSQk4oEl5w) but Aiden's lab did not even reply a 'no'. 

Moreover, hicExport is no longer available and is removed from HiCExplorer, please use hicConvertFormat and update to the latest HiCExplorer release 3.5.3.

If visualizations are important to you, we offer with hicPlotMatrix and hicPlotTads/pyGenomeTracks two powerful tools to do this. There is no need to use Aiden's Juicer software.

Best,

Joachim

**Comment by smurthy55** [comment]
Hi! Thanks for your response. I don't need to necessarily use the Juicer software to visualize, but I do need to be able to convert the npz files generated from this DeepHiC software to a format that can then be visualized. 

The hicConvertFormat does not have the option to read npz files, so I cannot use this for this purpose. I was using an older version of hicexplorer containing hicExport as it still has the option of taking npz files as input. The problem I am having is that the files or keys differ from what is expected for this method. Could you let me know what files or keys this method expects the npz file to contain so I could see if I can still convert it?
