### ISSUE TITLE
hicPlotTADs not overlapping calculated TADs with Hi-C

### ISSUE THREAD

**Issue by dhall1995** [deeptools/HiCExplorer#625]
Hi there,

I recently calculated TADs from Hi-C generated in both WT and a KO system. TADs were calculated using hicexplorer's hicFindTADS function and regions with differing TAD structure were identified using hicexplorer's hicDifferentialTAD fucntion - both of which functioned without any hitches. Similar to the plot displayed on hicDifferentialTAD's webpage (https://hicexplorer.readthedocs.io/en/latest/content/tools/hicDifferentialTAD.html) I wanted to display regions with differing TAD structure using hicexplorer's hicPlotTADs function. 

Despite copying the code almost verbatim into my WTvsMbd3KO_differential_TAD_tracks.ini file I can't seem to get the calculated TADs to actually overlay the Hi-C maps though. I've attached WTvsMbd3KO_differential_TAD_tracks.ini as well as the output of running: 

`~/anaconda3/bin/hicPlotTADs --dpi 50 --tracks WTvsMbd3KO_differential_TAD_tracks.ini --region 2:15,000,000-18,000,000 -t 'WT vs Mbd3KO differential TAD structure, Chromosome 2 15-18Mb' -o Chr2_15_18Mb_differential_TADs_WTvsMbd3KO.pdf`

terminal output is:

`title not set for 'section 3. [tads]'

title not set for 'section 6. [tads]'
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:128.08293294906616
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 14.0. Dpi is set to 50

INFO:pygenometracks.tracksClass:plotting 1. [spacer]
INFO:pygenometracks.tracksClass:plotting 2. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 2. [hic matrix] to: 2.0, 320.6

INFO:pygenometracks.tracksClass:plotting 3. [tads]
INFO:pygenometracks.tracksClass:plotting 4. [spacer]
INFO:pygenometracks.tracksClass:plotting 5. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 5. [hic matrix] to: 2.0, 320.6

INFO:pygenometracks.tracksClass:plotting 6. [tads]
INFO:pygenometracks.tracksClass:plotting 7. [spacer]
INFO:pygenometracks.tracksClass:plotting 8. [x-axis]`

any help would be appreciated!

all the best,

Dom

[Chr2_15_18Mb_differential_TADs_WTvsMbd3KO.pdf](https://github.com/deeptools/HiCExplorer/files/5488583/Chr2_15_18Mb_differential_TADs_WTvsMbd3KO.pdf)
[WTvsMbd3KO_differential_TAD_tracks.ini.txt](https://github.com/deeptools/HiCExplorer/files/5488608/WTvsMbd3KO_differential_TAD_tracks.ini.txt)

**Comment by lldelisle** [comment]
Hi,
I see 2 things:
First, it looks like you are using an old version of hicPlotTADs also named pyGenomeTracks. Could you try:
```
hicPlotTADs --version
```
If it gives you something lower than 3.2 this is it. Just update to the last version by:
```
conda install pygenometracks=3.5.1
```
Then, if you find your plot is compressed vertically, just remove the lines `height = 5` in your ini file.
I hope it solves your problem.

**Comment by dhall1995** [comment]
Thanks for the tips - I’ll give it a go now!

**Comment by LeilyR** [comment]
please add `display = triangles` to your ini file for domain tracks.
