### ISSUE TITLE
Converting HiCUP output for HiCExplorer

### ISSUE THREAD

**Issue by zqzneptune** [deeptools/HiCExplorer#626]
Hi,

I have pre-processed HiC data using [HiCUP](https://www.bioinformatics.babraham.ac.uk/projects/hicup/read_the_docs/html/index.html) pipeline, which produced only one aligned bam file in the finalized results. Any suggestions in converting into HiCExplorer compatible format?

I have checked current functions:
**hicBuildMatrix** takes R1 and R2 files separately, while **hicConvertFormat** doesn't accept the HiCUP output files.

Thanks,
Johnson

**Comment by lldelisle** [comment]
Hi,
I personally first convert the bam to a pair list in juicer format and then cooler to go from valid pair to matrix. For the first part, I use a personnal python script but since version 0.7.3 of HiCUP, they propose one. Here is the code I would use:

```
# Require hicup >=0.7.3 samtools bgzip tabix cooler

inputBAM=# Put here the name of the output of HiCUP
pairs=# Put here the name you want for you pairs sorted indexed (ending with csort.gz)
pathForSizes=# Put here the path for a tabulated file with name of chromosome and size
bin=# Put here the size of bin you want in kb
genome=# Put here the name of your genome
coolFile=# Put here the output file name (ending with .cool and optionally containing the bin size in the name)

# Deduce the path to the converter
pathForHiCUPToJuicer=$(dirname $(which hicup))/Conversion/hicup2juicer

# First convert bam to juicer file:
$pathForHiCUPToJuicer --zip ${inputBAM}

# The inputValidPairs is created from the name of inputBAM:
inputValidPairs=${inputBAM}.prejuicer.gz

# Then prepare the pairs and index with tabix using cooler
cooler csort -i tabix -c1 3 -c2 7 -p1 4 -p2 8 -o $pairs $inputValidPairs $pathForSizes

# Create a bed with bin coordinates:
cooler makebins $pathForSizes "${bin}000" > ${genome}.${bin}kb.bins

# Create a cool file (a matrix) with the pairs and the bins:
cooler cload tabix -p 1 -c2 7 -p2 8 --assembly $genome ${genome}.${bin}kb.bins $pairs ${coolFile}
```

Good luck

**Comment by zqzneptune** [comment]
Thanks! Really appreciate your input!
