### ISSUE TITLE
hicAggregateContacts - strand frame

### ISSUE THREAD

**Issue by fgualdr** [deeptools/HiCExplorer#630]
Hi,

I am quite new to HiC explorer.
I cannot figure out if there is a way to put in frame (e.g. flip strand to have + and - with same directions ) in hicAggregateContacts.
How are treated the strands of the BED provided?
Thanks a lot

Francesco

**Comment by LeilyR** [comment]
Hi, 
hicAggregateContacts does not look for the strands. If you ask for `first` it check for the locations on the second column in the given bed file, if you ask for `last` it takes the 3 column  and if `centre`, it will look for the coordinates in the middle of the second and third columns.
