### ISSUE TITLE
suggestion for hicAggregate and hicAverage

### ISSUE THREAD

**Issue by fgualdr** [deeptools/HiCExplorer#633]
Hi,

for both functions would be really useful if strand informations stored in BED could be taken into account in order to make the aggregation and average strand aware. This would be extremely useful when for example plotting TSS to TES regions.

**Comment by LeilyR** [comment]
for know I would suggest you to generate a TSS or TES bed file from your original bed file. (one base length files)

**Comment by fgualdr** [comment]
thanks for the quick reply.
My point is to make the mean/median or sum aggregation in order to have all on the "+" strand by transposing the sub matrix of features in the BED which are on the minus strand... don't know if my point is clearer.

**Comment by LeilyR** [comment]
I am not sure I understand you but why don't you make two bed files then , one with positive and other with negative strands, then run hicAggregate twice, once on each of them.

**Comment by fgualdr** [comment]
Thanks again,
yes that I could do. The point is if I then want to combine the two separate aggregations into one only by transposing the one obtained with "-" strand BED.
Thanks

**Comment by joachimwolff** [comment]
Hi @fgualdr,

sorry for the delayed reply. I have finally some time atm to fix bugs and implement new features. Can you explain to me what you mean with `transposing the one obtained with "-" strand BED.`? 

Thanks a lot,

Joachim

**Comment by joachimwolff** [comment]
Ah, I think I get what feature you want.

**Comment by joachimwolff** [comment]
I implemented it the following: 
- hicAggreagateContacts:
   - Strand + / +: as it used to be
   - Strand + / - : flip values left to right: [[1,2,3], [4,5,6]] becomes [[3,2,1],[6,5,4]]
   - Strand - / + : flip values up/down: [[1,2,3], [4,5,6]] becomes [[4,5,6],[1,2,3]]
   - Strand - / - : compute transpose: [[1,2,3], [4,5,6]] becomes  [[6,5,4],[3,2,1]]
   
- hicAverageRegions:
    - Strand + : as it used to be
    - Strand - : transpose

The changes are in the branch `aggregate_average_strand_information`. Would be great if you can give me feedback if it works as you intended.

Best,

Joachim
