### ISSUE TITLE
Visualizing TADs without Hi-C data, and only .bed files?

### ISSUE THREAD

**Issue by cshoben** [deeptools/HiCExplorer#634]
Hello!

I'm trying to figure out a way to visualize TADs without the Hi-C data in hand. The TADs were called by our collaborators, and I was sent BED files for both the domains and boundaries. I was eyeing the hicPlotTADs function, but notice the configuration file seems to require both [hic matrix] and [tad] for the first track to be produced. Can I create this track without defining the [hic matrix]? Or maybe there is another way I can utilize HiCExplorer to visualize TAD BED files? Thanks for your help!

**Comment by LeilyR** [comment]
Check pygenometracks documentation on how to visualise bed files. 
https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-bed-and-gtf

**Comment by cshoben** [comment]
Thank you! This is a huge help!
