### ISSUE TITLE
Extracting mean normalized counts of a set of sub-matrices (loops)

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#636]
Question. I have a bedpe file containing loop coordinates, and I would like to extract the read count (total|mean|median) for a given matrix file (H5/cool) across each of these regions in the bedpe file (which are essentially sub-matrices). The idea is to compare the "score" of these loop regions across multiple hic files (different samples, conditions,etc) 
is there a way to do this with HiCexplorer or any other tool that support H5 files?

**Comment by joachimwolff** [comment]
Hi,

hicAggregateContacts could be something for you: https://hicexplorer.readthedocs.io/en/latest/content/tools/hicAggregateContacts.html

However, you have to transform your bedpe file to bed format.

Best,

Joachim

**Comment by rikrdo89** [comment]
I thought hicAggregateContacts would mainly plot. Is it possible to get the scores of each of the regions in the bed file using this tool?

**Comment by LeilyR** [comment]
does `--outFileContactPairs`  help?

**Comment by rikrdo89** [comment]
I tried the option `--outFileContactPairs` but I did not get any table output.  My exact code was:
```
hicAggregateContacts -m myMatrix.h5 -out myPlot.png --mode intra-chr --BED loop_1.bed --BED2 loop_2.bed --row_wise --range 10000:1000000 --outFilePrefixMatrix OUTmatrix --outFileContactPairs OUTcontacts
```
I am using version 3.6. Is this a bug? I tried with one bed and without row-wise and still didnt work. Maybe I should open a new issue.

**Comment by LeilyR** [comment]
I will have a look at it, this is an old argument I will check if it needs any update.

**Comment by LeilyR** [comment]
I have checked for it, this has not been updated for the more recent capabilities of hicAggregate, thus only handles the old way which is equivalent of --perChr in the recent version. For now you can try --perChr and it should work, but I will update it as soon as possible and make it work for all the other cases.

**Comment by rikrdo89** [comment]
Thanks a lot for looking into this @LeilyR 
I added --perChr and I still don't see any files from the --outFileContactPairs... I see my png file with all the chromosomes  so the --perChr flag is working .

**Comment by LeilyR** [comment]
I cannot reproduce your issue. Here is what I do: 
`hicAggregateContacts -m hicexplorer/test/test_data/Li_et_al_2015.h5 --BED hicexplorer/test/test_data/hicAggregateContacts/test_regions.bed --mode intra-chr --perChr -o test.png --outFileContactPairs tsv_file --range 50000:900000`
output:
`head tsv_file_X_cluster_1.tab 
X	1268823	1268824	X	1356647	1356648	24.85811715426542
X	1588015	1588016	X	1679121	1679122	18.38930207884974
X	548547	548548	X	656427	656428	14.08509664172546
X	818016	818017	X	937135	937136	12.578931941344102
X	1268823	1268824	X	1375009	1375010	12.553550742832504
X	2340287	2340288	X	2493295	2493296	11.096257978628518
X	548547	548548	X	692287	692288	9.831224634547928
X	2072937	2072938	X	2162302	2162303	8.996637719420477
X	692287	692288	X	818016	818017	8.927080260521397
X	2340287	2340288	X	2503119	2503120	8.865702219307966
`

**Comment by rikrdo89** [comment]
Hi @LeilyR , I troubleshot this a bit more. Yes, you are correct, adding the `--perChr` flag in addition to the `--outFileContactPairs` will generate the table. This works with  one or two beds `--BED loop_1.bed --BED2 loop2_2`. However, no table is generated as soon as I add the `--row-wise` flag  (which I think is needed if the goal is to plot all the loops listed in a bedpe file in aggregate). I think the  `--row-wise` flag  is needed to prevent plotting  all he possible combinations between the two beds (which  in my case are the proximal and distal anchors of the loops that came from a bedpe file).
I don't know if there is a way to circumvent this at the moment.

**Comment by LeilyR** [comment]
Hi @rikrdo89 , I quickly updated the code upon your request. It should be able to handle your case now. Feel free to try the code from aggregate_fix branch and let us know if it works as you expect it. It still needs to be polished, so we can add it to the next release.

**Comment by LeilyR** [comment]
#643
