### ISSUE TITLE
--outFileContactPairs not working

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#638]
--outFileContactPairs in hicAggregateContacts 3.6 does not generate any table for me. --outFilePrefixMatrix works fine. Is this a bug in this version?

**Comment by LeilyR** [comment]
Is the output matrix what you need for the question you asked in #636 ?

**Comment by rikrdo89** [comment]
I don't think so, what I needed was the mean values per each of the regions indicated in my bed file... the --outFilePrefixMatri just gives you all the values for the final aggregated matrix, not for each individual region that makes up the final matrix. Do you know if there is a way to extract this information from within HiCExplorer?

**Comment by LeilyR** [comment]
#636

**Comment by LeilyR** [comment]
#643
