### ISSUE TITLE
hicMergeMatrixBins --runningWindow 

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#639]
Could you please elaborate how the --runningWindow parameter works? 
If I have a matrix of 5Kb resolution, and I merge the matrix by 3 bins (--runBins 3); How does adding the --runningWindow flag changes the matrix? Is this some sort of "smoothing"?

**Comment by joachimwolff** [comment]
It creates a 'running window' merge without changing the original resolution of the matrix. The window size is defined by the num_bins that are merged. Num bins had to be an odd number such that equal amounts of left and right bins can be merged.

``` 
a | b | c
---------
d | e | f
---------
g | h | i
  ``` 
 In this matrix, using a merge of num_bins 3, the merge is done as follows, `a = a + b + d + e` , ` e = a + b + c + d + e + f ` etc.
