### ISSUE TITLE
hicPlotMatrix --loop with regions spanning more than one bin.

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#640]
When using the --loops parameter containing regions that span more than one bin, hicPlotMatrix will only consider the fist bin in a given region, resulting in off-set red squares on the hic map. Could I suggest adding a parameter such as --largeRegionsOperation from the hicAggregateContacts to deal with regions bigger than the HiC bins?

**Comment by joachimwolff** [comment]
@rikrdo89 Are you reachable? I have some questions regarding this request.
