### ISSUE TITLE
After hic to cool convertion, sum of matrix is different at different resolutions

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#641]
When I convert a .hic file to .cool at different resolutions using:
```
hicConvertFormat -m tx4h_2.filteredPairs.hic --inputFormat hic --outputFormat cool -o tx4h_2.filteredPairs.cool -r 5000 10000 50000

```
I notice  that the "Sum of matrix" ( total number of reads in all the bins?) is slightly different at different resolutions. You can see the info below that in these two files at 10Kb and 50Kb bins, the sum of matrix goes from ~105M to ~96M respectively. is this a bug or is there a reason for this during the format conversion? 

```
$ hicInfo -m  H5_raw/tx4h_2.filteredPairs_10000.h5
# Matrix information file. Created with HiCExplorer's hicInfo version 3.6
File:	H5_raw/tx4h_2.filteredPairs_10000.h5
Size:	272,566
Bin_length:	10000
Sum of matrix:	105160981.5
Chromosomes:length: 1: 195471971 bp; 2: 182113224 bp; 3: 160039680 bp; 4: 156508116 bp; 5: 151834684 bp; 6: 149736546 bp; 7: 145441459 bp; 8: 129401213 bp; 9: 124595110 bp; 10: 130694993 bp; 11: 122082543 bp; 12: 120129022 bp; 13: 120421639 bp; 14: 124902244 bp; 15: 104043685 bp; 16: 98207768 bp; 17: 94987271 bp; 18: 90702639 bp; 19: 61431566 bp; M: 16299 bp; X: 171031299 bp; Y: 91744698 bp; 
Non-zero elements:	81,422,513
Minimum (non zero):	1
Maximum:	2887
NaN bins:	15421

$ hicInfo -m  H5_raw/tx4h_2.filteredPairs_50000.h5
# Matrix information file. Created with HiCExplorer's hicInfo version 3.6
File:	H5_raw/tx4h_2.filteredPairs_50000.h5
Size:	54,521
Bin_length:	50000
Sum of matrix:	96781257.0
Chromosomes:length: 1: 195471971 bp; 2: 182113224 bp; 3: 160039680 bp; 4: 156508116 bp; 5: 151834684 bp; 6: 149736546 bp; 7: 145441459 bp; 8: 129401213 bp; 9: 124595110 bp; 10: 130694993 bp; 11: 122082543 bp; 12: 120129022 bp; 13: 120421639 bp; 14: 124902244 bp; 15: 104043685 bp; 16: 98207768 bp; 17: 94987271 bp; 18: 90702639 bp; 19: 61431566 bp; M: 16299 bp; X: 171031299 bp; Y: 91744698 bp; 
Non-zero elements:	32,519,836
Minimum (non zero):	1
Maximum:	6640
NaN bins:	2414


```

**Comment by joachimwolff** [comment]
Can you check how it behaves for raw .hic files?

**Comment by joachimwolff** [comment]
Besides this, I would expect behavior like this. On a higher resolution, there is more specificity for e.g. nan bins given. I.e. assume three bins `NaN, 1, 3` and we merge these three together to one bin, it will become NaN, and the two other interactions are lost.
Moreover, the correction factors for different resolutions are different too; and this might lead to a difference in the observed number of reads.

**Comment by rikrdo89** [comment]
What do you mean by using raw .hic files? I thought the raw values (as well any correction vector) are already in the .hic files that used for the initial conversion from `.hic --> .cool` , and after that I convert `.cool --> .h5`, and then merge the .h5 files at different resolutions.

Also, when you merge to larger bins, wouldn't there be less NaNs because the bigger bin will take all the other bin values even when there is a NaN bin in it? Otherwise it seems to me that as you increase bin size, you will end up with lots of NaNs. 

Thanks for your help clarifying this!

**Comment by joachimwolff** [comment]
I mean `raw hic` in the sense of 'open the hic file in the way it was intended by the people who wrote .hic format; and do not use any hic to something-file format for this.' If you open a .hic and do the same lookup as you did with the created cool files, what is the output?

NaN issue: `1 2 3 4 Nan` -> will become one `Nan`-bin. But `NaN NaN NaN 1` will also become one `NaN` bin. The number of NaN bins can decrease or increase if the resolution is lowered, it depends on their appearance in the original data.

**Comment by rikrdo89** [comment]
`HiCExplorer  hicInfo` doesnt read .hic files, and unfortunately,  I am not super familiar with the .hic file structure to get the summary stats. I tried using the  ptyhon script (https://github.com/aidenlab/straw/blob/master/python/read_hic_header.py) from straw to read the file  but it doesn't give me any meaningful measure of the total number of reads. Do you know of any tool I could use to quickly check this?

**Comment by joachimwolff** [comment]
Maybe Lieberman-Aiden's Juicer? They have designed .hic for this software, but I don't know the usage details.
