### ISSUE TITLE
hicMergeMatrixBins warning in uncorrected H5 matrix

### ISSUE THREAD

**Issue by rikrdo89** [deeptools/HiCExplorer#642]
When trying to merge a raw h5  matrix  ( generated from a .hic file by converting .hic --> .cool --> .h5) , I get the following warning. 
```
WARNING:hicexplorer.hicMergeMatrixBins:*WARNING*: The matrix is probably a corrected matrix that contains NaN bins. This bins can not be merged and are removed. It is preferable to first merge bins in a uncorrected  matrix and then correct the matrix. Correction factors, if present, are removed as well.
```
I am not sure if this is a standard warning since I never applied any corrections to my matrix during my file conversion approach, or whether hicConvertFormat is applying some corrections (despite not being specified) during the file conversion.

**Comment by joachimwolff** [comment]
That is a standard warning, nothing to worry about. As soon as you merge matrices their correction values are obviously no longer valid and are removed.

**Comment by rikrdo89** [comment]
Ok great!. Thanks Joachim!
