### ISSUE TITLE
hicBuildMatrix - redundant memory usage

### ISSUE THREAD

**Issue by StephenRicher** [deeptools/HiCExplorer#646]
Hi,

Thanks for developing this great tool!

When using `--region` with hicBuildMatrix I have noticed that memory usage is still high even for small matrix regions. This seems to be related to `--restrictionCutFile` from `hicFindRestSite` as the rest site file still corresponds to the full genome. 

I tried sub-setting the restrictionCutFile to include only regions within my desired region (+/- a buffer of a few regions) and reran hicBuildMatrix. Memory usage was significantly reduced but the matrix appeared to produce identical results.

I guess somewhere in the hicBuildMatrix code the full restrictionCutFile is processed regardless of the `--region` argument?  Would it be possible to consider only the appropriate restriction sites when `--region` is specified to significantly reduce memory usage.

Thanks,
Stephen

**Comment by joachimwolff** [comment]
Hi Stephen,

Thank you for your feedback.

> I guess somewhere in the hicBuildMatrix code the full restrictionCutFile is processed regardless of the `--region` argument? Would it be possible to consider only the appropriate restriction sites when `--region` is specified to significantly reduce memory usage.

Yes, it is just read as it was given by the user and the region parameter is not considered. I will add it to my TODO list to improve this in a future version.

Best,

Joachim

**Comment by joachimwolff** [comment]
Implemented with PR #731.
