### ISSUE TITLE
No module named 'hicexplorer'

### ISSUE THREAD

**Issue by shiyi-pan** [deeptools/HiCExplorer#648]
Hi，I installed the HiCExplorer with the following command:

python setup.py install --prefix /ds3512/home/panyp/ruanjian/HiCExplorer/

and the logs are here:

running install
running build
running build_py
running egg_info
writing HiCExplorer.egg-info/PKG-INFO
writing dependency_links to HiCExplorer.egg-info/dependency_links.txt
writing requirements to HiCExplorer.egg-info/requires.txt
writing top-level names to HiCExplorer.egg-info/top_level.txt
reading manifest file 'HiCExplorer.egg-info/SOURCES.txt'
writing manifest file 'HiCExplorer.egg-info/SOURCES.txt'
running build_scripts
running install_lib
running install_egg_info
removing '/ds3512/home/panyp/ruanjian/HiCExplorer//lib/python3.6/site-packages/HiCExplorer-3.4.1-py3.6.egg-info' (and everything under it)
Copying HiCExplorer.egg-info to /ds3512/home/panyp/ruanjian/HiCExplorer//lib/python3.6/site-packages/HiCExplorer-3.4.1-py3.6.egg-info
running install_scripts
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicCompartmentalization to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotSVL to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicConvertFormat to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicViewpointBackgroundModel to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicQuickQC to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicAggregateStatistic to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotMatrix to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicQC to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotViewpoint to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicFindTADs to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotAverageRegions to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicTransform to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicFindRestSite to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicQualityControl to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicCorrectMatrix to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicValidateLocations to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicDifferentialTest to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicPlotViewpoint to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotDistVsCounts to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicMergeMatrixBins to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicInfo to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicBuildMatrix to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicAdjustMatrix to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPCA to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicPlotTADs to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicMergeLoops to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicAverageRegions to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicSumMatrices to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicDetectLoops to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicAggregateContacts to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicSignificantInteractions to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicexplorer to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicCompareMatrices to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicCorrelate to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/chicViewpoint to 775
changing mode of /ds3512/home/panyp/ruanjian/HiCExplorer//bin/hicNormalize to 775

I thought I installed the HiCExplorer correctly but when I used it  as following command :

hicBuildMatrix --samFiles soybean_R1.bam soybean_R2.bam --binSize 10000 --restrictionSequence GATC --danglingSequence GATC --restrictionCutFile cut_sites.bed --threads 4 --inputBufferSize 100000 --outBam hic.bam -o hic_matrix.h5 --QCfolder ./hicQC

I got an error :

Traceback (most recent call last):
  File "/ds3512/home/panyp/ruanjian/HiCExplorer/bin/hicBuildMatrix", line 4, in <module>
    from hicexplorer.hicBuildMatrix import main
ModuleNotFoundError: No module named 'hicexplorer'

could you help me fix this problem ,thank you very much

**Comment by joachimwolff** [comment]
Hi,

Sorry, with the given information it is not possible for me to make any statement why your installation fails. However, I can recommend our official way to install HiCExplorer via conda:

`conda install hicexplorer=3.6 -c bioconda -c conda-forge`

You can install conda with user permissions: https://docs.conda.io/projects/conda/en/latest/user-guide/install/

It is also possible to install different HiCExplorer versions to different conda environments:

`conda create --name hicexplorer3.4 hicexplorer=3.4.1 -c bioconda -c conda-forge`

Also, I notice you want to use HiCExplorer version 3.4.1, maybe you have your good reasons for this but there is a 3.4.3 version of the 3.4 release and the latest major release is 3.6.

Best,

Joachim

**Comment by shiyi-pan** [comment]
Thank you for your reply. I fix it by not using the --prefix option. But I met an new error :

usage: hicBuildMatrix --samFiles two sam files two sam files --outFileName
                      FILENAME --QCfolder FOLDER [--outBam bam file]
                      (--binSize BINSIZE [BINSIZE ...] | --restrictionCutFile BED file)
                      [--minDistance MINDISTANCE] [--maxDistance MAXDISTANCE]
                      [--maxLibraryInsertSize MAXLIBRARYINSERTSIZE]
                      [--restrictionSequence RESTRICTIONSEQUENCE]
                      [--genomeAssembly GENOMEASSEMBLY]
                      [--danglingSequence DANGLINGSEQUENCE]
                      [--region CHR:START-END] [--keepSelfCircles]
                      [--minMappingQuality MINMAPPINGQUALITY]
                      [--threads THREADS] [--inputBufferSize INPUTBUFFERSIZE]
                      [--doTestRun] [--doTestRunLines DOTESTRUNLINES]
                      [--skipDuplicationCheck] [--help] [--version]
hicBuildMatrix: error: argument --restrictionCutFile/-rs: can't open 'cut_sites.bed': [Errno 2] No such file or directory: 'cut_sites.bed'

could you tell me what the format of the cut_sites.bed file and how to generate it ? thank you very much.

**Comment by shiyi-pan** [comment]
forget it ,I think I can generate the cut_sites.bed file by hicFindRestSite tools.
