### ISSUE TITLE
hicTransform  invalid argument 

### ISSUE THREAD

**Issue by shiyi-pan** [deeptools/HiCExplorer#649]
Hi, I want to use hicTransform  module to analysis the A / B compartments as you described in documentation ,but when I run hicTransform as following command :

hicTransform -m hic_corrected.h5 --outFileName all.h5 --method all

I meet an error that  the method argument has no option 'all' ,here is my log :

usage: hicTransform --matrix MATRIX --outFileName OUTFILENAME
                    [--method {obs_exp,obs_exp_lieberman,obs_exp_non_zero,pearson,covariance}]
                    [--ligation_factor]
                    [--chromosomes CHROMOSOMES [CHROMOSOMES ...]]
                    [--perChromosome] [--help] [--version]
hicTransform: error: argument --method/-me: invalid choice: 'obs_exp,obs_exp_lieberman,obs_exp_non_zero,pearson,covariance' (choose from 'obs_exp', 'obs_exp_
lieberman', 'obs_exp_non_zero', 'pearson', 'covariance')

could you help me fix this problem , thank you very much.

**Comment by joachimwolff** [comment]
Hi,

It seems we have not updated this particular command in our documentation (https://hicexplorer.readthedocs.io/en/latest/content/example_usage.html?highlight=hicTransform#a-b-compartment-analysis). As the error message states, the option `all` for methods was removed. You have with the current HiCExplorer version 3.6 two options: Either you specify for hicPCA that the intermediate pearson matrix is saved via 

`hicPCA -m hic_corrected.h5 --outFileName pca1.bw pca2.bw --format bigwig --pearsonMatrix pearson.h5` 

or you use hicTransform

 `hicTransform -m hic_corrected.h5 --outFileName all.h5 --method pearson`.

Best,

Joachim

**Comment by shiyi-pan** [comment]
thank you for your reply, Joachim .I will try.

**Comment by shiyi-pan** [comment]
Hi,Joachim. I tried to hicTransform -m hic_corrected.h5 --outFileName all.h5 --method pearson and met an error :

Traceback (most recent call last):
  File "/ds3512/home/panyp/ruanjian/python36/bin/hicTransform", line 7, in <module>
    main()
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/hicTransform.py", line 188, in main
    trasf_matrix = csr_matrix(_pearson(hic_ma.matrix.todense()))
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/hicTransform.py", line 101, in _pearson
    pearson_correlation_matrix = np.corrcoef(pSubmatrix)
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2522, in corrcoef
    c = cov(x, y, rowvar)
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2377, in cov
    X = array(m, ndmin=2, dtype=dtype)
MemoryError

could you help me fix this problem ? My input file is 443Mb and I think it not too big in HiC data. My python is 64bit already. Thank you very much.

**Comment by joachimwolff** [comment]
Well, your system has too less memory, that‘s it. 

The matrix we store and work with is a sparse one, however a pearson matrix is dense.

**Comment by shiyi-pan** [comment]
Thank you for your reply . so this is the linux system problem? is there a method to fix it ?

**Comment by joachimwolff** [comment]
This is not a Linux issue, why should it?! https://en.wikipedia.org/wiki/Random-access_memory

What helps is to upgrade your system to 64, or better to 128 GB of RAM. However, it seems to be that a webserver usage where you don't need to care about all this is the better solution for you: https://hicexplorer.usegalaxy.eu
