### ISSUE TITLE
hicBuildMatrix-TypeError: save() got an unexpected keyword argument 'pHiCInfo'

### ISSUE THREAD

**Issue by Yang-Haoyan** [deeptools/HiCExplorer#650]
Hi,

When I used hicBuildMatrix , there is an error.

My **command** is “/home/bioSoft/Common/Anaconda3/bin/hicBuildMatrix --samFiles ADL215.R1.bam ADL215.R2.bam --binSize 10000 --restrictionSequence GATC --danglingSequence GATC --restrictionCutFile rest_site_positions.bed --outBam ADL215_ref.bam --outFileName hicMatrix/ADL215_10kb.h5 --QCfolder hicMatrix/ADL215_10kb_QC --threads 10 --inputBufferSize 400000”.

The **error code** is as follow:

INFO:hicexplorer.hicBuildMatrix:reading ADL215.R1.bam and ADL215.R2.bam to build hic_matrix

[E::idx_find_and_load] Could not retrieve index file for 'ADL215.R1.bam'
[E::idx_find_and_load] Could not retrieve index file for 'ADL215.R2.bam'
INFO:hicexplorer.hicBuildMatrix:dangling sequences to check are {'GATC': {'pat_forw': 'GATC', 'pat_rev': 'GATC'}}

INFO:hicexplorer.hicBuildMatrix:processing 2062074 lines took 92.71 secs (22242.3 lines per second)

INFO:hicexplorer.hicBuildMatrix:344928 (16.73%) valid pairs added to matrix

……

INFO:hicexplorer.hicBuildMatrix:processing 311073102 lines took 12311.92 secs (25266.0 lines per second)

INFO:hicexplorer.hicBuildMatrix:164821964 (52.98%) valid pairs added to matrix

INFO:hicexplorer.hicBuildMatrix:processing 313073102 lines took 12380.84 secs (25286.9 lines per second)

INFO:hicexplorer.hicBuildMatrix:166560396 (53.20%) valid pairs added to matrix

Traceback (most recent call last):
  File "/home/bioSoft/Common/Anaconda3/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/home/bioSoft/Common/Anaconda3/lib/python3.8/site-packages/hicexplorer/hicBuildMatrix.py", line 1619, in main
    hic_ma.save(args.outFileName.name, pHiCInfo=hic_metadata)
TypeError: save() got an unexpected keyword argument 'pHiCInfo'

I don't  understand where the problem is.

Could you give me some suggestions?

Thanks in advance

**Comment by LeilyR** [comment]
what is your hicmatrix and hicexplorer version ? Did you use conda to install them?

**Comment by joachimwolff** [comment]
As Leily already said: Please check the versions of hicmatrix and hicexplorer. The error message occurs because your HiCMatrix is an outdated version.
