### ISSUE TITLE
TAD score normalization in hicFindTADs

### ISSUE THREAD

**Issue by YichaoOU** [deeptools/HiCExplorer#651]
Hello,

Is the TAD score (`tad_score.bedgraph`) from `hicFindTADs` comparable for data from different conditions?

Should we do some normalization?

Thanks,
Yichao

**Comment by gtrichard** [comment]
Yes they are, I did it in that paper for instance (Figure 4):
https://www.cell.com/cell/pdf/S0092-8674(20)30621-8.pdf

No Normalisation is required. Be sure to take random sites in the genome and compare the insulation score, they shouldn't be different.
