### ISSUE TITLE
UnicodeDecodeError When running hicPCA

### ISSUE THREAD

**Issue by shiyi-pan** [deeptools/HiCExplorer#652]
Hi, I run hicPCA with following command :

hicPCA -m hic_corrected.h5 --outputFileName pca1.bw pca2.bw --format bigwig --pearsonMatrix pearson.h5 --method dist_norm --extraTrack NN1138-2.100k.bins.gene.density.bigWig

and met an error :

Traceback (most recent call last):
  File "/ds3512/home/panyp/ruanjian/python36/bin/hicPCA", line 7, in <module>
    main()
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 334, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/hicPCA.py", line 142, in correlateEigenvectorWithGeneTrack
    bed = ReadBed(file_h)
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/readBed.py", line 35, in __init__
    fields = self.get_no_comment_line()
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/readBed.py", line 69, in get_no_comment_line
    line = toString(line)
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/hicexplorer/utilities.py", line 408, in toString
    return s.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 1: ordinal not in range(128)

Could you help me fix this problem, Thank you very much. Here is my bigWig file.
[NN1138-2.100k.bins.gene.density.zip](https://github.com/deeptools/HiCExplorer/files/5768999/NN1138-2.100k.bins.gene.density.zip)

**Comment by joachimwolff** [comment]
Hi,

you are using a character which is not in the ASCII encoding: https://en.wikipedia.org/wiki/ASCII

Remove this character and it will work.

Best,

Joachim

**Comment by shiyi-pan** [comment]
Thank you for your reply. I used the bedGraphToBigWig to generate the bigWig file , there is no error in my code and the file is binary , So I don't know how this character generated. Could you help me remove this character.

here is my code to generate the bigWig file:

bedGraphToBigWig NN1138-2.100kb.bins.gene.density.bedGraph NN1138-2.v1.0.chrom.sizes NN1138-2.100k.bins.gene.density.bigWig

and here is part of my input file:

NN1138-2.v1.0.chrom.sizes:
Chr01   57180813
Chr02   49974985
Chr03   47135343
Chr04   50772388
Chr05   40763724
Chr06   49765926
Chr07   44477389
Chr08   47918604
Chr09   48783406
Chr10   52870952

NN1138-2.100kb.bins.gene.density.bedGraph:
Chr01   0       100000  0
Chr01   100000  200000  6
Chr01   200000  300000  70
Chr01   300000  400000  207
Chr01   400000  500000  145
Chr01   500000  600000  206
Chr01   600000  700000  104
Chr01   700000  800000  256
Chr01   800000  900000  154
Chr01   900000  1000000 210

**Comment by joachimwolff** [comment]
File ending of a bigwig should be either `.bw` or `.bigwig` but not `.bigWig`. In this case it is interpreted as a bed file and that could lead to the error you presented.

**Comment by joachimwolff** [comment]
No more reply. Closing.
