### ISSUE TITLE
hicPlotTADs can not show Hic map

### ISSUE THREAD

**Issue by yancychy** [deeptools/HiCExplorer#653]
Hi,
I tired to view the hic data using hicPlotTADs. My track.ini is referring the link of
https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-hi-c-data.
The plot is like a line. The hic data is viewed as a line. The figure is shown in (please paste it to the web browser)
https://drive.google.com/file/d/1g47R3nvGyssyH4g9dnPbRnwxR9B966il/view?usp=sharing

track.ini content is as follows. I am not sure what's wrong with my configuration. Could you help me to solve it? Thanks very much.

[hic matrix]
file = Biotin_1000_norm.h5
title = Hi-C Biotin
depth = 1000
file_type = hic_matrix
show_masked_bins = false
[tads]
file = Biotin_1000_norm_domains.bed
display = triangles
border_color = black
color = none
overlay_previous = share-y

**Comment by lldelisle** [comment]
Hi,
There is a misunderstanding of the `depth` parameter. The `depth` is the maximum distance that should be plotted. You put 1000 which means that you will only be able to see interactions below 1kb. I am not sure this is what you wanted. I think if you increase it to `400000`. It should be closer to what you were expecting.

**Comment by yancychy** [comment]
Thanks very much. It works now.
