### ISSUE TITLE
how to run hicCompartmentalization 

### ISSUE THREAD

**Issue by biohubx** [deeptools/HiCExplorer#654]
Hi,
   I just checked out `hicCompartmentalization`, which looks good to analyze compartment. Now I am a little confused about the difference between `hicPCA` and `hicCompartmentalization`.  Another question about the hicCompartmentalization input arguments: **--obsexp_matrices** and **--pca**. **--obsexp_matrices** requires the normalized contact matrix, right? Does **--pca** just represent pc1.bedgraph?
  Thanks in advance.
   best,

**Comment by LeilyR** [comment]
Hey @biohubx , 
hicCompartmentalization is a downstream analysis after computing the pca vectors and the obs/exp matrices. This is to see the strength of compartments separation. However, compartments themselves can be achieved by running hicPCA. 
It is indeed highly recommended to use the balanced matrices, to discard the interaction bias.

**Comment by biohubx** [comment]
Thanks @LeilyR.
