### ISSUE TITLE
how to choose correct PC

### ISSUE THREAD

**Issue by biohubx** [deeptools/HiCExplorer#656]
Hi,
    I am runnung HicPCA to analyze compartment analysis. Would you have any good suggestions to choose the coorect PC for each HiC?
Thanks in advance.
Best,

**Comment by joachimwolff** [comment]
The correct PC is usually PC1 or 2, in rare cases it is PC3. A simple way is to see if it matches the checkerboard pattern of the Pearson matrix.

**Comment by gtrichard** [comment]
To complement Joachim's answer, be sure to check that the PCs are correctly oriented, i.e. that positive values are corresponding to active regions and negative values to inactive regions. You can determine that by calculating genes density, GC content, average binned genes transcription, active histone marks or open chromatin.
