### ISSUE TITLE
metadata missing after .cool to .cool conversion

### ISSUE THREAD

**Issue by mj-mage** [deeptools/HiCExplorer#657]
Hi,

I have to convert some .hic files into the .cool format for downstream applications using hicConvertFormat. To obtain a single resolution file with one data column (weight) for normalization I have followed @joachimwolff 's suggestions in the following post:

_Originally posted by @joachimwolff in https://github.com/deeptools/HiCExplorer/issues/347#issuecomment-463097095_
"...
I recommend the following:
1. run hicConvertFormat for each resolution you like to use:ˋhicConvertFormats -m your.hic —inputFormat hic —outputFormat cool -o your-cool-file-10kb.cool -r 10000ˋ.
2. run hicInfo to see which correction factors are available: ˋhicInfo -m your-cool-file-10kb.coolˋ
3. Apply the correction factors e.g. ˋhicConvertFormat -m your-cool-file-10kb.cool —inputFormat cool —outputFormat cool -o your-cool-file-10kb-KR.cool —correction_name KRˋ
....."

The first conversion is working fine (hic to cool), but during the second conversion (cool to cool) some of the metadata is lost, in my case the path to the chromsize info/genome assembly. This is a problem for the downstream analysis when normalizing to genome size is required. Can I restore the metadata in the .cool file somehow? Or remove the additional correction factors from the first .cool file that still has the correct metadata?

Thanks in advance!
Maja

**Comment by joachimwolff** [comment]
It might be that we missed this metadata to write out, I need to check this and will come back to you.

As far as I know, the missing metadata is not an issue in the downstream analysis with HiCExplorer.
