### ISSUE TITLE
HicConvertFormat

### ISSUE THREAD

**Issue by paolabc** [deeptools/HiCExplorer#658]
Hi

I tried to use hicexplorer, but i know that i need to convert my hic file in cool to use it. When i tried it, this message appears. I'm new in hic evaluation and bioinformatics also. Can someone say what is wrong? I downloaded my file from GeoDatabase. 

my screen:
  File "/home/paola/anaconda3/lib/python3.7/site-packages/hic2cool/hic2cool_utils.py", line 59, in readcstr
    return buf.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1: invalid start byte

**Comment by joachimwolff** [comment]
Hi,

you use a character that is not part of the UTF-8 encoding. Why this happens I can't tell you, please post the full error message.

Best,

Joachim

**Comment by AssumeAssume** [comment]
> Hi
> 
> I tried to use hicexplorer, but i know that i need to convert my hic file in cool to use it. When i tried it, this message appears. I'm new in hic evaluation and bioinformatics also. Can someone say what is wrong? I downloaded my file from GeoDatabase.
> 
> my screen: File "/home/paola/anaconda3/lib/python3.7/site-packages/hic2cool/hic2cool_utils.py", line 59, in readcstr return buf.decode("utf-8") UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1: invalid start byte

Hello, @paolabc , have you addressed your problem? I met the same error when converting ENCODE .hic file to .cool format

**Comment by paolabc** [comment]
Hi
 I had this problem and I needed to reinstall the samtools or bedtools ( I do not remember which one of these software). I did this and it worked. I do not know if this could solve your problem.

**Comment by theshowmustgolangon** [comment]
I have the same issue, and it doesn't work to install samtools or bedtools.

**Comment by paolabc** [comment]
Hi 

What is the output error? Maybe if you print it here, I or another GitHub user can help you.

**Comment by malbassam** [comment]
I get this error too: 
icConvertFormat -m ~/Downloads/inter_30.hic -o inter_30_rep1.cool --inputFormat hic --outputFormat cool
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicexplorer.hicConvertFormat:Converting with hic2cool.
Traceback (most recent call last):
  File "/Users/mahmoudal-bassam/opt/anaconda3/bin/hicConvertFormat", line 7, in <module>
    main()
  File "/Users/mahmoudal-bassam/opt/anaconda3/lib/python3.9/site-packages/hicexplorer/hicConvertFormat.py", line 118, in main
    hic2cool_convert(matrix, args.outFileName[i], 0)
  File "/Users/mahmoudal-bassam/opt/anaconda3/lib/python3.9/site-packages/hic2cool/hic2cool_utils.py", line 871, in hic2cool_convert
    used_chrs, resolutions, masteridx, genome, metadata = read_header(req)
  File "/Users/mahmoudal-bassam/opt/anaconda3/lib/python3.9/site-packages/hic2cool/hic2cool_utils.py", line 102, in read_header
    key = readcstr(req)
  File "/Users/mahmoudal-bassam/opt/anaconda3/lib/python3.9/site-packages/hic2cool/hic2cool_utils.py", line 65, in readcstr
    return buf.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte

**Comment by malbassam** [comment]
This error is from a test hit file that I downloaded from ENCODE.  
downloaded test hic file from here: https://github.com/ENCODE-DCC/hic-pipeline/blob/dev/tests/data/inter_30.hic

**Comment by umarov90** [comment]
I have same issue with 30 .hic files I downloaded from ENCODE:
  File "hic2cool/hic2cool_utils.py", line 59, in readcstr
    return buf.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 1: invalid start byte

**Comment by ToruOkadaOi** [comment]
Hello is there a fix for this? Encountering the same problem

**Comment by Yihuki** [comment]
This is due to hic2cool not able to work with .hic v9 file. [VonAlphaBisZulu/hic2cool](https://github.com/VonAlphaBisZulu/hic2cool)  This hic2cool works, but the commit haven't merged to upstream hic2cool yet. You can use this hic2cool to convert hic v9 to cool.

**Comment by solo7773** [comment]
[hictk](https://github.com/paulsengroup/hictk) helps
