### ISSUE TITLE
Multiple enzyme hicFindRestSites support?

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#659]
Hi @joachimwolff  and @LeilyR , best wishes for 2021.

I'm using Arima Genomics Hi-C kit which uses DpnII and HinfI enzymes. Currently, I need to perform two hicFindRestSites run (one for each enzyme) and concatenate the resulting .bed files to use in hicBuildMatrix for RF resolution matrices.

Do you plan multiple enzyme support for hicFindRestSites? I'm asking because I'm working on modifying the SnakePipes HiC pipeline to support the Arima kit. Before doing any changes to the pipeline, I would like to know if it is planned or not for HiCExplorer as it would solve the SnakePipes HiC issue of using multiple enzymes, as well as making hicFindRestSites easier to use for a kit that might become the norm for Hi-C in the future.

Thank you :)

**Comment by LeilyR** [comment]
I agree that it is going to be a good asset for hicexplorer. Shall we put it in todo list?

**Comment by joachimwolff** [comment]
We can add this, it is more or less one `for-loop` we have to add. However, it will be part of the next release which will be in maybe 2 - 4 weeks. I hope it is not too far in the future.

**Comment by LeilyR** [comment]
it may need downstream changes in QC too.

**Comment by joachimwolff** [comment]
Implemented with PR #732
