### ISSUE TITLE
Plot whole genome excluding intra-chromosomal (cis) contacts (i.e., show only trans contacts)?

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#664]
Hi HiCExplorer team,

Using HiCExplorer, is there a way to plot all of the chromosomes in a given genome while excluding all intra-chromosomal (cis) contacts? That is, show only inter-chromosomal (trans) interactions.

I was trying to think of a way to do it with `hicAdjustMatrix` and `hicPlotMatrix`, but nothing has come to my mind yet. If there's no way to currently do it, I wonder if I can submit this as a feature request?

Also, are `*.cool` files no longer usable with `hicCompareMatries`? In looking at the code and documentation, it seems not, unless I missed something.

Thanks,
Kris

**Comment by joachimwolff** [comment]
Plotting:
That is a feature we do not support, I will take it as a feature request/

Compare matrices:
It should work with h5 and cool, exactly like all other tools. The functionality to decide it is h5 or cool is a bit hidden in `HiCMatrix`: https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/HiCMatrix.py#L50

**Comment by joachimwolff** [comment]
I implemented a feature to remove intra or inter chromosomal contacts in develop, see issue #704. Will be available with the next release.
