### ISSUE TITLE
Difficulties installing HiCExplorer using conda

### ISSUE THREAD

**Issue by gabedolpten** [deeptools/HiCExplorer#667]
Hi, I am trying to install HiCExplorer with conda, python 3.8. However when I try to install it, running:

conda install hicexplorer=3.6 -c bioconda -c conda-forge --debug

I get the following error:
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5'] -> llvm-openmp[version='>=9.0.1'] -> openmp[version='11.0.1|11.0.1.*']
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5'] -> openmp_impl==9999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> pypy3.5==99999999999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> pypy3.7==99999999999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> python=3.6[build=*_73_pypy] -> python_abi==3.6[build=*_pypy36_pp73]
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> sqlite[version='>=3.34.0,<4.0a0']
  - hicexplorer=3.6 -> hic2cool[version='>=0.8.3']
  - hicexplorer=3.6 -> hicmatrix[version='>=15']
  - hicexplorer=3.6 -> pygenometracks[version='>=3.5']

Do you know what is going on and how I can fix it?

**Comment by joachimwolff** [comment]
Please use conda environments to make sure there is no interference with already installed software:

`conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
and activate the environment:
`conda activate hicexplorer`

**Comment by gabedolpten** [comment]
> Please use conda environments to make sure there is no interference with already installed software:
> 
> `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
> and activate the environment:
> `conda activate hicexplorer`

I still get the same error actually – 

UnsatisfiableError: The following specifications were found to be in conflict:
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5'] -> llvm-openmp[version='>=9.0.1'] -> openmp[version='11.0.1|11.0.1.*']
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> libgcc-ng[version='>=9.3.0'] -> _openmp_mutex[version='>=4.5'] -> openmp_impl==9999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> pypy3.5==99999999999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> pypy3.7==99999999999
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> python=3.6[build=*_73_pypy] -> python_abi==3.6[build=*_pypy36_pp73]
  - hicexplorer=3.6 -> cooler[version='>=0.8.10'] -> multiprocess -> pypy3.6[version='>=7.3.3'] -> sqlite[version='>=3.34.0,<4.0a0']
  - hicexplorer=3.6 -> hic2cool[version='>=0.8.3']
  - hicexplorer=3.6 -> hicmatrix[version='>=15']
  - hicexplorer=3.6 -> pygenometracks[version='>=3.5']

**Comment by gtrichard** [comment]
Is your base conda environment clean? You shouldn't install anything in your base conda, whatever you are installing should go to virtual envs.
