### ISSUE TITLE
HiC Matrix visualization

### ISSUE THREAD

**Issue by gabedolpten** [deeptools/HiCExplorer#668]
Is there a way to increase the resolution of the hicPlotMatrix function? It is a bit low. This is especially challenging when I am plotting the loops called from hicDetectLoops to visually inspect them, since the image is so low resolution I can only plot very short stretches of DNA at a time.

**Comment by joachimwolff** [comment]
You can change the resolution of an image by adding `—dpi value` (These should be two - , but it is always merged to one bigger —...) or you simply create a vector graphic by changing the file ending to svg, pdf, eps
