### ISSUE TITLE
downsample Hi-C contacts/equalisation of valid pairs between different samples 

### ISSUE THREAD

**Issue by Drosophilid** [deeptools/HiCExplorer#674]
Hi,
I want to compare the Hi-C data of different tissues but the number of valid Hi-C pairs differ between the samples. I have already created my matrix using Hi-Explorer. 
is there any option in Hi-Explorer or way to down pairs to equalize with others or vice versa?

Thank you

**Comment by joachimwolff** [comment]
hicNormalize with the option 'smallest': https://hicexplorer.readthedocs.io/en/latest/content/tools/hicNormalize.html#hicnormalize
