### ISSUE TITLE
Zero loops?

### ISSUE THREAD

**Issue by gabedolpten** [deeptools/HiCExplorer#676]
Hi, for some reason HiCExplorer returns zero loops. I am currently running the following code:
hicDetectLoops -m data_800.cool -o 400_loops.bedgraph -tpc 16 --windowSize 10 --peakWidth 6
Where the data is at 800bp resolution. 
Do you know what might be causing this issue?

**Comment by joachimwolff** [comment]
HI,

800 bp? That is really high. Are you sure your read coverage is high enough? I developed the loop detection with 10 kb data.

Can you plot a small region with hicPlotMatrix where there has to be a loop to validate there is any?

**Comment by joachimwolff** [comment]
No user response. Closing.
