### ISSUE TITLE
hicCompareMatrices without normalization

### ISSUE THREAD

**Issue by yxsee** [deeptools/HiCExplorer#677]
I have 2 matrices which are normalized by cell count instead of read count, in an attempt to view global increases or decreases in chromatin contacts. I would like to compare the matrices using hicCompareMatrices but I think the matrices are normalized by read count automatically before the log2ratio is performed. Is it possible to run hicCompareMatrices without the normalization step? Thanks!

**Comment by lldelisle** [comment]
Hi,
For the moment, it is not possible. I am working on it #645 ...
