### ISSUE TITLE
Varying bin size in *_tad_score.bm

### ISSUE THREAD

**Issue by yancychy** [deeptools/HiCExplorer#680]
Hi, I have confusion on the output of hicFindTADs. 
From the *_tad_score.bm file, I find that the binsize in each row is varying. The hic resolution is 2kb. Why the bin size in each row are not equal? Thanks. 

{"step":8000,"minDepth":6000,"maxDepth":50000,"binsize":2000}
chr3   0       7000    0.000000        0.000000        0.000000        0.000000
chr3   7000    49000   18.694121       18.694121       18.694121       10.794996
chr3   49000   88000   6.278219        5.230330        5.171986        5.666241
chr3   88000   93000   3.650062        3.599512        5.119487        5.838324
chr3   93000   98000   4.054495        4.174260        5.369658        4.513936
chr3  98000   100000  3.454103        3.872247        4.966880        3.276863
chr3   100000  102000  0.688500        3.096913        4.392023        2.644304
chr3   102000  105000  2.154638        4.389754        3.831286        2.576375

**Comment by joachimwolff** [comment]
Please consider my answer in: https://github.com/deeptools/HiCExplorer/issues/679
