### ISSUE TITLE
hicPlotTADs does not produce hic matrix in the plot

### ISSUE THREAD

**Issue by antarikshtyagi** [deeptools/HiCExplorer#682]
Hello,

I am trying to run hicPlotTADs. However, it does not produce the HiC matrix and plots only the boundaries, domains and bedgraph.

Attached here is tracks file and output image using this command:
hicPlotTADs --tracks run_01/TADs_run01_tracks_5.ini --region chr2:32856500-41739000 -t 'test_chr2' -out TADs_run01_pygenome_5.png

Could you please help me in getting the HiC matrix in the plot. 

Thanks
Ant
[TADs_run01_tracks_5.txt](https://github.com/deeptools/HiCExplorer/files/6073792/TADs_run01_tracks_5.txt)

[TADs_run01_pygenome_5.pdf](https://github.com/deeptools/HiCExplorer/files/6073897/TADs_run01_pygenome_5.pdf)

**Welcome to the HiCExplorer GitHub repository! Before opening the issue please check
 that the following requirements are met :**

- [ ] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [ ] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [ ] hicInfo 3.6, Python 3.8.8
- [ ] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [ ] yes
- [ ] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [ ] yes
- [ ] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [ ] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
WARNING:pygenometracks.tracksClass:title not set for section 3. [NlaIII_run01_UCSC_hg38.matrix]

INFO:pygenometracks.tracksClass:initialize 1. [x-axis]
INFO:pygenometracks.tracksClass:initialize 2. [spacer]
INFO:pygenometracks.tracksClass:initialize 3. [NlaIII_run01_UCSC_hg38.matrix]
INFO:pygenometracks.tracksClass:initialize 4. [TADs_run01_boundaries]
100%|██████████| 4/4 [00:00<00:00, 5326.10it/s]
INFO:pygenometracks.tracksClass:initialize 5. [TADs_run01_domains]
100%|██████████| 4/4 [00:00<00:00, 12748.64it/s]
INFO:pygenometracks.tracksClass:initialize 6. [TADs_run01_score]
100%|██████████| 8820/8820 [00:00<00:00, 28258.88it/s]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:2.7244105339050293
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 9.106529073905493. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [NlaIII_run01_UCSC_hg38.matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 3. [NlaIII_run01_UCSC_hg38.matrix] to: 1.0, 2.0

INFO:pygenometracks.tracksClass:plotting 4. [TADs_run01_boundaries]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 3.38,-0.08
INFO:pygenometracks.tracksClass:plotting 5. [TADs_run01_domains]
DEBUG:pygenometracks.tracks.GenomeTrack:ylim 5.68,-0.08
INFO:pygenometracks.tracksClass:plotting 6. [TADs_run01_score]

**Comment by LeilyR** [comment]
this looks strange. Isn't you matrix empty for that region? Maybe you can try to plot your matrix for the same region using hicPlotMatrix, just to check, or maybe try hicPlotTADs on an other region and see if it is the same. Please get back to us again if your problem is not solved.

**Comment by lldelisle** [comment]
Hi,
You set the depth to 100000 which is 100kb so I can see your matrix but it is very small as you can only see 1 bin probably. Please set the depth to 10000000 (10Mb) in your ini file:
`depth = 10000000`
This should solve your issue.

**Comment by antarikshtyagi** [comment]
Thanks,
The depth = 10000000 solution has apparently worked for me. However I just see a large blur block with very few red dots scattered. Is there a way to make it more informative and aesthetically pleasing?
[TADs_run01_pygenome_7.pdf](https://github.com/deeptools/HiCExplorer/files/6081014/TADs_run01_pygenome_7.pdf)

**Comment by lldelisle** [comment]
Can you try:
```
transform = no # Instead of log1p
min_value = 0
max_value = 5
```

**Comment by antarikshtyagi** [comment]
Thanks. I tried with these parameters and it only changed the red color dots to white. Do you think my matrix is too sparse? I have around 270 million contacts including 144 million cis contacts.
Attached is image output using the suggested parameters:
[TADs_run01_pygenome_14.pdf](https://github.com/deeptools/HiCExplorer/files/6088204/TADs_run01_pygenome_14.pdf)

Thanks for your continued support
Ant

**Comment by lldelisle** [comment]
Yes, clearly your matrix is too sparse. You should increase the bin size until you reach a good picture. Are you sure about your number of contacts?
Can you do a:
```
hicInfo -m cools/NlaIII_run01_UCSC_hg38.matrix.cool
```

**Comment by antarikshtyagi** [comment]
This is a Pore-C result and its metadata tells me the number of contacts. Attached is hicInfo report as well as pore C metadata
[slurm-81090.txt](https://github.com/deeptools/HiCExplorer/files/6088736/slurm-81090.txt)
[NlaIII_run01_UCSC_hg38.at.catalog.yaml.txt](https://github.com/deeptools/HiCExplorer/files/6088764/NlaIII_run01_UCSC_hg38.at.catalog.yaml.txt)

**Comment by lldelisle** [comment]
Hi,
I never saw Pore-C results before, so I cannot really say but I would try 100kb to check how it looks and I would run a [hicPlotDistVsCounts](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotDistVsCounts.html) to check...
