### ISSUE TITLE
sample downsizing of Hi-C data to equalize data set of variable sequencing depth 

### ISSUE THREAD

**Issue by mujahida87** [deeptools/HiCExplorer#683]
Hi, I have Hi-C data of multiple tissues of Drosophila, each of the tissue's data set has a different sequence depth (an amount of HiC-matrix data and valid HI-C pair differ accordingly).

I normalize this with hicNormalize "smallest ", but still I'm not sure if I can compare the data of different sequence depth or samples of different numbers of valid pairs to make a biological conclusion? 
my command:
hicNormalize -m a_matrix.corrected.h5 b_matrix.corrected.h5 c_matrix.corrected.h5 d_matrix.corrected.h5 --normalize smallest -o a_matrix.corrected.norm.h5 b_matrix.corrected.norm.h5 c_matrix.corrected.norm.h5 d_matrix.corrected.norm.h5

Is there any other method/function available in HiCexplorer to equalize the matrices of different sequencing depth/valid pairs?
Thank you

**Comment by LeilyR** [comment]
if you want to generate matrices of the same depth to begin with, you can also subample your deeper data to the depth of the shallowest in a way to get the same valid pairs for all of them.  However, HiCExplorer is not providing the sub-sampling of fastq files as a module.  Though you can easily use `seqtk` for that.

**Comment by mujahida87** [comment]
Than you @LeilyR, I ll try
