### ISSUE TITLE
Is there a recogmended protein profile for loops ?

### ISSUE THREAD

**Issue by gnilihzeux** [deeptools/HiCExplorer#684]
Dear author,
    It's a convenient tool for HiC analysis. But some tools lack detailed documentations including examples.
    I was detecting the loops using `hicDetectLoops`, but too many parameters. You'd mentioned that `hicHyperoptDetectLoops` could solve this but the protein profile makes me confused.
    What proteins are available for this job? Or How do I determine which proteins I need ?

**Comment by joachimwolff** [comment]
Hi,

may I recommend the following article to you? Bonev & Cavalli 2016 'Organization and function of the 3D genome': https://www.nature.com/articles/nrg.2016.112

As you will read, certain proteins like CTCF are present at loop boundaries, however, not in all cases, but on a majority. Moreover, you have to check if ChIP-Seq Data for the cell line and organism you use is available for example for CTCF. But be careful, not all organisms have CTCF at the boundaries, so please check this first.

Best,

Joachim

**Comment by gnilihzeux** [comment]
Thank you for your suggestions. Let me have a look.

Joachim Wolff <notifications@github.com> 于2021年3月4日周四 下午5:46写道：
