### ISSUE TITLE
variation in Boundary size after matrix correction

### ISSUE THREAD

**Issue by mujahida87** [deeptools/HiCExplorer#686]
Hi, I also have a similar issue as my colleague raises the question below. I found that boundary sizes differ (5 to 7% of boundaries) after matrix correction (--correctionMethod ICE). I'm using the 3.6 version of hicexplorer. is it usual after matrix correction?

Thank you

**Comment by joachimwolff** [comment]
- to what 'below' are you referring? If you refer to another issue, please specify the issue number.
- what boundaries are you speaking of? TAD boundaries?

In general: Please provide more information about what you are writing about; the template to open an issue is not for fun here.

**Comment by mujahida87** [comment]
Hi, I am referring to issue #679 
Yes, I am talking about TAD boundaries. My bin size was 5 kb and I expect that the boundary size will be 5kb but after correction, 5-7% of boundaries are larger than 5kb.

sorry for inconvenience
![Screenshot 2021-03-09 at 09 24 41](https://user-images.githubusercontent.com/30443593/110440778-53e8c180-80b9-11eb-8e0c-8bd643b8ca6c.png)

**Comment by joachimwolff** [comment]
See my comment on the other issue.

**Comment by joachimwolff** [comment]
Please consider my answer in https://github.com/deeptools/HiCExplorer/issues/679.
