### ISSUE TITLE
HiCExplorer with Micro-C data

### ISSUE THREAD

**Issue by StephenRicher** [deeptools/HiCExplorer#688]
Hi,

Thank you for developing this fantastic tool, I have been using it extensively for my Hi-C analysis. I have some Micro-C data and was wondering if I could use your tool to process this?

Since Micro-C is not restriction fragment based I imagine the key difference between Hi-C will be in the build matrix step. I would like to ignore the restriction sequence based arguments. Is there a way to do this as these argument are now required arguments for hicBuildMatrix.

Thanks very much,
Stephen

**Comment by joachimwolff** [comment]
Hi Stephen,

you can use the older 3.4 version where these arguments were not required. I would be interested to know if that works and if yes, we could discuss ways to integrate Micro-C into the current version.

Best,

Joachim

**Comment by StephenRicher** [comment]
Hi Joachim,

Thanks for your quick response. Brilliant thanks I will try that and let you know how it goes.

Thanks,
Stephen

**Comment by LeilyR** [comment]
Hi @StephenRicher , would you mind giving us an update about your experince in using hicexplorer on micro-c data?

**Comment by StephenRicher** [comment]
Hi @LeilyR, sorry I have not had a chance to get back to you on this. I have been a bit side tracked lately, but i still intend to try this and will let you know. If you did want to close the issue I would be happy to just re-raise it as a suggestion later, but I don't mind either way :)

**Comment by xl5525** [comment]
I tried my MicroC sample with 3.4.0 without providing enzyme data for QC purposes. And the result seems reasonable.

**Comment by tcege** [comment]
I am working with Micro-C data but want to use HiCExplorer for downstream analysis.
The HiCExplorer tutorial for hicBuildMatrix requires separate BAM files for R1 and R2, but Micro-C data is paired-end.

My main questions are:

Should I align R1 and R2 separately (like the Hi-C=hicexplorer website suggestion)?
Using local alignment settings:

bwa mem -A1 -B4  -E50 -L0 index_path \
mate_R1.fastq.gz 2>>mate_R1.log | samtools view -Shb - > mate_R1.bam

bwa mem -A1 -B4  -E50 -L0 index_path \
mate_R2.fastq.gz 2>>mate_R2.log | samtools view -Shb - > mate_R2.bam

Does this approach make sense for Micro-C, or will it cause issues?

2️. Or should I align R1 and R2 together as paired-end, then split the BAM file into separate R1 and R2 files later?

Options:
(A) Paired-end alignment (standard Micro-C website suggestion)

bwa mem -5SP -T0 -t<threads> <ref.fasta> <MicroC_R1.fastq> <MicroC_R2.fastq> -o <aligned.sam>


awk 'BEGIN {OFS="\t"} 
/^@/ {print > "aligned_ R1.sam"; print > "aligned _R2.sam"; next} 
NR % 2 == 1 {print > "aligned_R1.sam"} 
NR % 2 == 0 {print > "aligned_R2.sam"}' aligned.sam


(B) Align R1 and R2 separately using paired-end settings:

bwa mem -5SP -T0 -t20 "$fastafile" "$fastq1" -o aligned_R1.sam
bwa mem -5SP -T0 -t20 "$fastafile" "$fastq2" -o aligned_R2.sam

Is it better to align in paired-end mode and split the BAM into separate files later?

When I used the Paired-end alignment (standard Micro-C) website suggestion and split them in R1 and R2 sam files, I saw the error. I controlled my R1 and R2 files in different ways and sorted them, but my error was consistent. Later, I aligned separately using a paired-end setting, and I used hicBuildMatrixMicroC code, and I did not see any issue.

My question is: Which one is the correct way to do downstream analysis? 

3️. How should I precisely filter for chimeric interactions in Micro-C?

Unlike Hi-C, Micro-C captures all interactions, not just ligation-based contacts. What is the best way to filter chimeric interactions, specifically in Micro-C?

Any suggestions or best practices from those who have processed Micro-C with HiCExplorer would be appreciated!

**Comment by joachimwolff** [comment]
Mapping is, besides small details, no different in Micro-C compared to
Hi-C. Both are paired-end sequenced but need to be aligned independently as
single-end. For the correct mapping settings, I need to check what we used,
it is bwa mem2 with -5 setting and a local mode.

To create the interaction matrix, please use our latest release. I added
there hicBuildMatrixMicroC which drops the requirement of a restriction
sequence, restriction sequence location file and the dangling end sequence.

You don’t need to filter, hicBuildMatrixMicroC takes care that only
chimeric reads are accepted.

tcege ***@***.***> schrieb am Mi. 12. Feb. 2025 um 20:11:

**Comment by tcege** [comment]
I appreciate your helpful answer!
