### ISSUE TITLE
hicConvertFormat hic to h5 exits silently without output

### ISSUE THREAD

**Issue by mdozmorov** [deeptools/HiCExplorer#690]
Hi. I'm trying to convert a typical `.hic` file to `.h5`. The command:
````
hicConvertFormat -m /full/path/to/aligned/inter_30.hic -o outfile.h5 \ 
                 --inputFormat hic --outputFormat h5 --resolutions 1000000
````
It stops after a few seconds without any output or error messages. The same command with the `cool` outputFormat works. Why `.hic` to `.h5` doesn't work?
````
hicConvertFormat --version
hicConvertFormat 3.6
````
Thanks,
Mikhail

**Comment by joachimwolff** [comment]
Hi Mikhail,

As stated in our documentation, this is not possible: `It is only possible to convert from hic to cool format; no other formats are supported.`  https://hicexplorer.readthedocs.io/en/latest/content/tools/hicConvertFormat.html#hic2cool

We are using the library `hic2cool` to transform a hic into a cool file, therefore is a direct conversion not possible. However, you can apply first: 

```
hicConvertFormat -m /full/path/to/aligned/inter_30.hic -o outfile.cool \ 
                 --inputFormat hic --outputFormat cool --resolutions 1000000
```

and second:

```
hicConvertFormat -m outfile.cool -o outfile.h5 \ 
                 --inputFormat cool --outputFormat h5
```

Please note that `hic` files provide a different name scheme for the correction factors than cool files. To get the correct one for the cool file, the following is necessary: First, check which column names are available. 


```
hicInfo -m  outfile.cool
```

Next, apply the wanted column name to the cool file, in this example it is `KR`:

```
hicConvertFormat -m outfile.cool -o outfile_KR.cool --inputFormat cool --outputFormat cool --correction_name KR --enforce_integer
```

However, HiCExplorer does support cool files natively, and there is no need to transform our `h5` file format.

Best,

Joachim

**Comment by mdozmorov** [comment]
Thank you, Joachim, this is very informative. I should've read the fine manual more carefully :)

The original idea was to run `hicPCA`. The [documentation](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPCA.html#) says about the input matrix: `HiCExplorer matrix in h5 format.` I used `hicConvertFormat` to get the `.cool` file, and, as you mentioned, HiCExplorer's `hicPCA` supports it. I know both `.cool` and `.h5` are HDF5-based, but don't know the difference between them. Perhaps, clarifying in the documentation that the input format may be `.cool` will help avoid future confusions.

Thanks,
Mikhail
