### ISSUE TITLE
chicViewpoint --writeFileNamesToFile

### ISSUE THREAD

**Issue by Jssmith91** [deeptools/HiCExplorer#694]
When using chicViewpoint and the option --writeFileNamesToFile no file is actually generated so batch processing in a later stage wont work.

**Comment by joachimwolff** [comment]
Hi,

that should not happen, can you post the command you used?

Best,

Joachim

**Comment by Jssmith91** [comment]
chicViewpoint --matrices SW480_A_1000.cool SW480_B_1000.cool --referencePoints new_referencepoints.bed --threads 24 --backgroundModelFile SW480_BackGroundModel.bed --range 25000 25000 --writeFileNamesToFile FileNames.txt --allViewpointsList --outputFolder CHICVIEW

**Comment by joachimwolff** [comment]
Ok, I don't know; that looks correct. We have two options: Try to fix this bug, or, you could try out the upcoming version where I changed a lot with the file handling. There will be a reduced complexity, however, it might contain errors and you have to be familiar with how to install HiCExplorer from a branch.

**Comment by Jssmith91** [comment]
Which do you think is better? Happy to follow any command you can give maybe via email?

**Comment by joachimwolff** [comment]
Just drop me a message via mail.

**Comment by joachimwolff** [comment]
New file format comming in version 3.7. Won't fix.
