### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by e-lerat** [deeptools/HiCExplorer#695]
Hi,

I have installed the latest version of HicExplorer using conda. 
However, when I try to launch any of the tools, I get the following message 

ImportError: Unable to import required dependencies:numpy:

I have tried to reinstall numpy in my conda environment like that
conda install --name hicexplorer numpy

But it does not solve the problem.

I am working on an cluster on which I do not have root privileges.

Any help would be appreciated!

**Comment by gtrichard** [comment]
Hello.

Which command did you use to install HiCExplorer?

**Comment by e-lerat** [comment]
I used this command

conda create --name hicexplorer -c bioconda -c conda-forge hicexplorer

**Comment by joachimwolff** [comment]
Are you sure you activated the environment? What is the output of 'whereis hicInfo' `which hicInfo` and `hicInfo -v`? Do you have a clean root environment?

**Comment by e-lerat** [comment]
I removed everything and did another installation of the environment. Now it is working. I probably did something wrong the first time

Sorry for wasting you time and thank you very much for your answering.
