### ISSUE TITLE
Parameter combination issues about hicCorrectMatrix

### ISSUE THREAD

**Issue by biozzq** [deeptools/HiCExplorer#697]
Dear all,

I wonder that if the following command finished, which balancing method it used? Because I can use both default `--correctionMethod` (KR) and `--filterThreshold` in the following command. However, the option of `--filterThreshold` applied only for ICE. More, how can i check the balancing method deposited in the cool files? Thank you.

`hicCorrectMatrix correct --matrix LHP-1_normalized.cool --outFileName LHP-1_corrected_matrix.cool --filterThreshold -1.9300769306780177 4 --perchr`

Sincerely,
Zheng zhuqing

**Comment by joachimwolff** [comment]
Hi Zheng zhuqing,

The correction method overrules the other parameters e.g. if the correction method is set to KR but you set the filter threshold too, the latter one is ignored.

The correction factors are stored in cooler files in the 'weight' column, however, the name of the correction method is not stored. If it is somewhere stored, than in the metadata, but I need to check with the developers of the cooler format if something like this is implemented.

Best,

Joachim

**Comment by biozzq** [comment]
Dear @joachimwolff 

Thank you for explaining this.

Best,
Zheng zhuqing
