### ISSUE TITLE
hicAggregateContacts error

### ISSUE THREAD

**Issue by robeach78** [deeptools/HiCExplorer#698]
**Welcome to the HiCExplorer GitHub repository! Before opening the issue please check
 that the following requirements are met :**

- [x] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [x] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [x] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [x] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [x] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [ ] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [ ] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

**Comment by robeach78** [comment]
I have this error using HiExplorer 3.6.0 hicAggregateContacts funcion;

INFO:hicexplorer.hicAggregateContacts:Number of discarded empty submatrices  80 (0.02)
Traceback (most recent call last):
  File "/software/as/el7.2/EasyBuild/CRG/software/HiCExplorer/3.6/bin/hicAggregateContacts", line 7, in <module>
    main()
  File "/software/as/el7.2/EasyBuild/CRG/software/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/site-packages/hicexplorer/hicAggregateContacts.py", line 657, in main
    cluster_ids[chrom] = [range(len(chrom_matrix[chrom]))]
KeyError: 'chrM'

Thanks a lot

**Comment by LeilyR** [comment]
it complains that the chromosome name does not exist. but this is an odd issue. Are you arue you are using 3.6? I see a different content on the line [657](https://github.com/deeptools/HiCExplorer/blob/3.6/hicexplorer/hicAggregateContacts.py#L657) of this version.

**Comment by joachimwolff** [comment]
No more reply from user. Closing.
