### ISSUE TITLE
scaling P(s) request

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#699]
Hi,
First, thank you so much for the amazing tool. We recently put a paper on bioarchive, and it couldn't have been possible without this user-friendly tool.
I was wondering if you guys are developing a function for getting scaling P(s). source method section: https://www.nature.com/articles/s41556-019-0406-2
Is there much difference between plotDistvsCounts and scaling P(s)? For instance, in the paper the authors mention that the local min/max of derivative of P(s) implies certain properties of loop-extrusion... Is it okay to use DistvsCounts to make similar interpretation?
Thank you,
Jun

**Comment by joachimwolff** [comment]
Hi Jun,

We do not develop a method like this. However, in the paper they write their P(s) function is inspired by cooltools. I think this documentation can help you to get the P(s) plots you want to have: https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html?highlight=p(s)#Plot-the-P(s)-curve

You can simply take the cool file you used with HiCExplorer and use it with cooltools. 

Best,

Joachim
