### ISSUE TITLE
hicFindRestSite galaxy wrapper 3.6 complains about restriction enzyme sequence

### ISSUE THREAD

**Issue by cgirardot** [deeptools/HiCExplorer#701]
Hi @joachimwolff
I am now upgrading my galaxy WF to use the latest version and encountered this problem in hicFindRestSite. The ER sequence validation seems to have a bug and complaints even though the sequence is valid. 

<img width="990" alt="Screen Shot 2021-04-07 at 18 53 18" src="https://user-images.githubusercontent.com/10990795/113904610-85e16680-97d2-11eb-9b7e-aa36544d47e4.png">

**Comment by joachimwolff** [comment]
Hi,

There is a validator which checks if the characters entered are ascii. https://github.com/galaxyproject/tools-iuc/blob/master/tools/hicexplorer/hicFindRestrictionSites.xml#L22

Maybe @bgruening who added this validation can explain how to enter a sequence the correct way. For me your sequence looks alright.

Best,

Joachim

**Comment by cgirardot** [comment]
Thanks for looking into this. It is most likely JS related. I forgot to mention: I was using Chrome and switching to Firefox did not fix it.

**Comment by joachimwolff** [comment]
So it seems that we use a function that requires Python 3.7. Is it possible for you to upgrade to Python 3.7?

**Comment by joachimwolff** [comment]
For 3.6 we work on a fix, because our server runs with Python 3.6 too.

**Comment by cgirardot** [comment]
you mean the python version that runs galaxy I guess. I need to check with Jelle as we actually planned to update to the newer galaxy tonight.

**Comment by joachimwolff** [comment]
Yes, the Python version that Galaxy is using. 

However, Bjoern has a workaround:
`<validator type="expression" message="Only ASCII characters are allowed."><![CDATA[all(ord(c) < 128 for c in value)]]></validator>`

On our server it works now, I will create a PR at tools IUC with this fix.

**Comment by joachimwolff** [comment]
https://github.com/galaxyproject/tools-iuc/pull/3583

The fix should be available.

Best,

Joachim

**Comment by cgirardot** [comment]
thx a lot, we'll check this out
