### ISSUE TITLE
Version 2.2.1.1 working fine, except for hicDifferentialTAD and hicDetectLoops

### ISSUE THREAD

**Issue by ArielPaulson** [deeptools/HiCExplorer#702]
Using version 2.2.1.1 on CentOS7, Python 3.7.9

I installed everything two days ago, and have used six modules so far, four work fine: hicConvertFormat, hicPlotMatrix, hicCompareMatrices, and hicFindTADs.

But hicDifferentialTAD appears to have not installed into python:

$bin/hicDifferentialTAD
Traceback (most recent call last):
  File "./hicDifferentialTAD", line 4, in <module>
    from hicexplorer.hicDifferentialTAD import main
ModuleNotFoundError: No module named 'hicexplorer.hicDifferentialTAD'

Differently, hicDetectLoops also fails, looks like a bug:

$bin/hicDetectLoops --matrix strain1.h5 --outFileName strain1.h5.hicDetectLoops
Traceback (most recent call last):
  File "/n/core/Bioinformatics/Software/HiCExplorer/install/bin/hicDetectLoops", line 7, in <module>
    main()
  File "/n/core/Bioinformatics/Software/HiC_Python_3.7.9/python3/lib/python3.7/site-packages/hicexplorer/hicDetectLoops.py", line 678, in main
    hic_matrix.keepOnlyTheseChr([chromosome])
UnboundLocalError: local variable 'chromosome' referenced before assignment

I did not use conda and do not have root, this was my setup workflow, on a custom python installation:

git clone https://github.com/deeptools/HiCExplorer.git
export PYENV_VERSION=3.7.9
cd HiCExplorer
../HiC_Python_3.7.9/python3/bin/python3 setup.py install --prefix /n/core/Bioinformatics/Software/HiCExplorer/install
../HiC_Python_3.7.9/python3/bin/pip3 install hicexplorer

I attached the logs, which do not show any errors or warnings that I can see.  Likewise the python install did not have any significant issues.

[install.log.txt](https://github.com/deeptools/HiCExplorer/files/6280601/install.log.txt)

Thanks,
Ariel

**Comment by joachimwolff** [comment]
Hi Ariel,

version 2.2.1.1 is a completely outdated version, the current one is 3.6. Please use conda to install HiCExplorer, you do not need root privileges to install conda.

Best regards,

Joachim

**Comment by ArielPaulson** [comment]
That is odd about the version, thanks.  I had not noticed.

**Comment by joachimwolff** [comment]
Reading your log file a bit: the main issue is you install HiCExplorer first via python setup.py install which is correct and gives you the correct version from our master branch, however, after this you install HiCExplorer a second time using pip. We do not support pip anymore since a while and the 2.2.1 version was the last one we supported pip.

**Comment by ArielPaulson** [comment]
I tried the regular "git clone" install only, but when I do all commands fail with the same error:

$bin/hicConvertFormat
Traceback (most recent call last):
  File "./hicConvertFormat", line 4, in <module>
    from hicexplorer.hicConvertFormat import main
ModuleNotFoundError: No module named 'hicexplorer'

So I did the pip install on top of that, and then things ran.  So instead I am supposed to run only the conda install, and ignore the git approach?

**Comment by ArielPaulson** [comment]
Sorry not a python guy...

**Comment by joachimwolff** [comment]
Please remove first the current installation. If multiple versions are installed, strange errors can happen. 

ˋpip uninstall hicexplorerˋ and repeat the command until nothing is installed anymore. Than follow the installation instructions of conda: https://conda.io/projects/conda/en/latest/user-guide/install/linux.html

Next, install HiCExplorer to an environment and use it: https://github.com/deeptools/HiCExplorer#install-with-conda Please use the installation with the environment.

**Comment by joachimwolff** [comment]
We recommend for all users the installation with conda. Feel free to use the git approach but this one you usually need only if you want to contribute to the source code of HiCExplorer or you really know why git is the better way for you.

**Comment by ArielPaulson** [comment]
I got the conda approach working and everything seems to be running as expected now.

Thanks very much!!
Ariel
