### ISSUE TITLE
Control of hicPlotTads output image width?

### ISSUE THREAD

**Issue by ArielPaulson** [deeptools/HiCExplorer#705]
Hi,

It looks like there is no control for output image width or DPI in hicPlotTADs, everything is always 1133 pixels wide no matter the region or scale, am I missing something, or can these be added?  

It would be much more helpful if I could produce fewer, wider plots and zoom in, rather than have lots of files with plots at various scales.

Thanks,
Ariel

**Comment by joachimwolff** [comment]
There is the parameter ´—dpi xxx´ you can set to control the resolution. https://pygenometracks.readthedocs.io/en/latest/content/usage.html

**Comment by ArielPaulson** [comment]
I think this will work, thanks!
