### ISSUE TITLE
using corrected cool file instead of h5 file in the subcommand of hicexplorer

### ISSUE THREAD

**Issue by biozzq** [deeptools/HiCExplorer#708]
Dear all,

I have a minor question, could we use the corrected cool file in the downstream analysis but not the corrected h5 file, such as `hicPCA`, `hicFindTads` and so on? Thank you very much.

Best,
Zheng zhuqing

**Comment by joachimwolff** [comment]
In all tools of HiCExplorer you can use `cool` and `h5` files. Both are nativley supported.
