### ISSUE TITLE
--extraTrack only using the longest transcripts

### ISSUE THREAD

**Issue by biozzq** [deeptools/HiCExplorer#710]
Dear all,

We can use gene track (specified by option `--extraTrack`) to decide if the values of the eigenvector need a sign flip or not. When I prepare the bed file for my own species, I only converted the longest transcripts (as one gene may have many transcripts) to the bed format. Is this OK?

Best,
Zheng zhuqing

**Comment by joachimwolff** [comment]
Hi,

we think this approach is alright. Please validate the result in the end with pyGenomeTracks.

Best,

Joachim

**Comment by biozzq** [comment]
Dear @joachimwolff 

I think it is ok to use the longest transcripts, because I found most PC1 values have been flipped after involving this information, however, hicPCA sometimes reports an error and failed https://github.com/deeptools/HiCExplorer/issues/716. Would really appreciate if you can give your comments on this.

Sincerely,
Zheng zhuqing

**Comment by joachimwolff** [comment]
See #719. Are you sure for all chromosomes your sizes match the sizes of the reference genome?
