### ISSUE TITLE
hicCompartmentalization question

### ISSUE THREAD

**Issue by skytguuu** [deeptools/HiCExplorer#711]
Hi,

Thanks for your developed tools. I tried to use hicCompartmentalization to calculate the compartment strength. However, I am confused about the outputmatrix with '.npz' file. As I am understood, it should be saved the compartment strength in the array, but I don't know the meaning of the index. If I tried to calculate the compartment strength in each chromosomes, how could I do?

Thanks,
Garen

**Comment by LeilyR** [comment]
Hi Garen, 
It saves an array of matrices, one matrix per one obs/exp input, in the same order as has been given with -m.
npz file can be loaded using numpy.load
Keep in mind that our tool already generated figures corresponding to this matrix and you only need to sue it if your need it for further downstream analysis.
