### ISSUE TITLE
Is there a difference to hicBuildMatrix at 1K + hicMergeMatrixBins to 5K vs hicBuildMatrix at 5K directly ?

### ISSUE THREAD

**Issue by cgirardot** [deeptools/HiCExplorer#713]
I havent tried myself (sorry) and before doing so, I thought you might be able to comment quickly on a potential difference (also in the interest of other readers). 

My WF always hicBuildMatrix at 1K and then merge bins into different resolutions. Different analysis might then use different resolutions. 
I am wondering if there are obvious drawbacks to this? The only potential issue I could think of relates to reads being treated differentially at boundaries or reads that could be filtered out when the resolution is too high. Again this is just guessing.

Would you mind commenting?

Thank you

**Comment by biozzq** [comment]
Hi, I think you can refer to my previous issues. https://github.com/deeptools/HiCExplorer/issues/707

Good luck.

**Comment by joachimwolff** [comment]
Hi,

there should be no differences. However, there is always an exception :)

- As already mentioned, if a matrix was already corrected there might be issues with masked Nan areas
- The merge script has options on how to merge. These might lead to different results too.

Best,

Joachim
