### ISSUE TITLE
hicNormalize created empty matrix by normalizing to smallest

### ISSUE THREAD

**Issue by sckinta** [deeptools/HiCExplorer#714]
Based on my understanding,  `hicNormalize` can normalize multiplex matrix to the smallest matrix (kinda like subsampling at matrix format). Thus before using the `hicNormalize`, i counted my matrix read count

```
conditions=("celltype_A", "celltype_B", "celltype_C")
for condition in ${conditions[@]}; do
        count=$(cooler info $condition.4000.cool | grep "sum" | awk '{print $2}')
        echo -e "$condition\t$count"
done
```
it reports

```
# celltype_A	3202881486
# celltype_B	2975312234
# celltype_C	4364008271
```

Then i run `hicNormalize` on those three conditions, with expectation that celltype_A and celltype_C will be normalized to celltype_B. Here is command i run

```
files=("celltype_A.4000.cool" "celltype_B.4000.cool" "celltype_C.4000.cool")
out_files=("celltype_A.4000.norm.cool" "celltype_B.4000.norm.cool" "celltype_C.4000.norm.cool")
conda activate hicexplorer
hicNormalize --matrices ${files[@]} \
--normalize smallest \
--outFileName ${out_files[@]} \
--setToZeroThreshold 1.0
```

The run is successful without errors. But the result matrix are all empty.

```
for file in ${out_files[@]}; do
        count=$(cooler info $file| grep "sum" | awk '{print $2}')
        echo -e "$file\t$count"
done
```
it reports.
```
# celltype_A.4000.norm.cool	0.0
# celltype_B.4000.norm.cool	0.0
# celltype_C.4000.norm.cool	0.0
```

I have tested other hicexplorer functions with `.cool` file before, basically there is no difference in I/O using `.h5` and `.cool`, that is why I choose to use `.cool` here directly instead of convert format. I am not sure whether this is reason to cause problem.

my hicexplorer version is 3.6

**Comment by joachimwolff** [comment]
Hi,

what is the output of hicInfo for all three matrices before you run the normalization?

I assume the issue might be related to `--setToZeroThreshold 1.0`: i.e. are your values all `<=` 1.0 they will be removed.

Best,

Joachim

**Comment by sckinta** [comment]
The output of hic info is like below.

```
{
    "bin-size": 4000,
    "bin-type": "fixed",
    "creation-date": "2021-01-26T15:05:11.142901",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.10",
    "genome-assembly": "hg19",
    "nbins": 773935,
    "nchroms": 25,
    "nnz": 2362585656,
    "storage-mode": "symmetric-upper",
    "sum": 3202881486
}
{
    "bin-size": 4000,
    "bin-type": "fixed",
    "creation-date": "2021-01-26T14:52:28.970245",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.10",
    "genome-assembly": "hg19",
    "nbins": 773935,
    "nchroms": 25,
    "nnz": 2042445458,
    "storage-mode": "symmetric-upper",
    "sum": 2975312234
}
{
    "bin-size": 4000,
    "bin-type": "fixed",
    "creation-date": "2021-02-10T12:53:30.837785",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "cooler-0.8.10",
    "genome-assembly": "hg19",
    "nbins": 773935,
    "nchroms": 25,
    "nnz": 2606667958,
    "storage-mode": "symmetric-upper",
    "sum": 4364008271
}
```
All of them have a lot of values  > 1. I was able to use those matrix (before hicNormalize) to call loops earlier with minimum read count >= 5.

**Comment by sckinta** [comment]
I figured the problem. The input .cool file was previously balanced and contains weight. By using unbalanced .cool file solved the issue. Thanks!
