### ISSUE TITLE
hicPCA error when using gene track

### ISSUE THREAD

**Issue by biozzq** [deeptools/HiCExplorer#716]
Dear all,

In my mind, the following will be a common question when doing PCA analysis.
I resolved the following problem before (https://github.com/deeptools/HiCExplorer/issues/707, mainly because the intervals in the gene bed file exceed the chromosome ranges), but here it does not work when checking using the same methods. I have checked the gene bed file and the chromosome name, but cannot find any error. If the error occurred in the gene bed file, I hope you can give us more clear error message, such as which line of the bed file is wrong as you said before (https://github.com/deeptools/HiCExplorer/issues/621). Thank you very much.

The command I used is as following:

`hicPCA (Version3.6) -m KR_corrected.cool -o pca1.bw pca2.bw --format bigwig --extraTrack mm10_refGene.bed`

```
ERROR:hicmatrix.HiCMatrix:Index error
Traceback (most recent call last):
  File "/python3.8/site-packages/hicmatrix/HiCMatrix.py", line 270, in getRegionBinRange
    endbin = sorted(self.interval_trees[chrname][endpos:endpos + 1])[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/01.software/hicexplorer/bin/hicPCA", line 7, in <module>
    main()
  File "/python3.8/site-packages/hicexplorer/hicPCA.py", line 337, in main
    vecs_list = correlateEigenvectorWithGeneTrack(ma, vecs_list, args.extraTrack)
  File "/01.software/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicPCA.py", line 161, in correlateEigenvectorWithGeneTrack
    gene_occurrence[bin_id[1]] += 1
TypeError: 'NoneType' object is not subscriptable
```

Sincerely,
Zheng zhuqing

**Comment by joachimwolff** [comment]
See #719. Are you sure for all chromosomes your sizes match the sizes of the reference genome?
