### ISSUE TITLE
Error in hicBuildMatrix when multiple restriction enzymes have the same dangling sequence

### ISSUE THREAD

**Issue by StephenRicher** [deeptools/HiCExplorer#720]
Hi, 

I am currently re-processing a published [Mouse HiC dataset](https://genome.cshlp.org/content/30/8/1097.full) that uses a 3 enzyme protocol (CviQI, CviAII, and BfaI). CviQI and BfaI have the same dangling sequence (TA) and it looks like this causes an error when using hicBuildMatrix.

The error occurs on line 284 of hicPrepareQCreport.py, when the `params` dictionary is converted to a pandas dataframe. This raises `ValueError: arrays must all be same length` as the `dangling end TA` key now has 2 entries (`'dangling end TA': [3665, 0]`). 

The fact that the second entry has a count of 0 may be inevitable and simply redundant but I am not sure? Perhaps then it would be simple enough just to skip the second entry entirely - this is how I have solved this temporarily.

HiCExplorer (v3.6) Python (v3.8.8)

Thanks,
Stephen

**Comment by joachimwolff** [comment]
Hi Stephen,

thanks for reporting this, I will consider it in the next release of HiCExplorer.

Best,

Joachim
