### ISSUE TITLE
Low percentage of valid pairs and weird looking diagnostic plot

### ISSUE THREAD

**Issue by JohnsonStev** [deeptools/HiCExplorer#721]
Hello,

I am trying to call TAD in three libraries using the commands in the example usage.
However, only one of them yield acceptable results, the others has very low percentage of valid pairs.
So I ran a QC on the matrixes 
And here is what I get
![image](https://user-images.githubusercontent.com/38938938/122463545-0207df80-cfb6-11eb-9eb0-e65d7b97949c.png)

![image](https://user-images.githubusercontent.com/38938938/122462689-2b743b80-cfb5-11eb-90fe-086f3c5437e7.png)

The orange and the green samples are the ones I failed in TAD analysis.
Seems like they are having different problems. Also the diagnostic matrix plot looks pretty weird in the orange sample
![image](https://user-images.githubusercontent.com/38938938/122463730-42675d80-cfb6-11eb-9e81-048b1eff6632.png)

I assume that many duplicated reads is a result of wet lab procedure? But I can't figure out what's happening in the green sample.

Any suggestions? Should I try remapping with different parameter?
Thank you!!

**Comment by joachimwolff** [comment]
Hi,

- how are the FASTQC reports looking for the three datasets?
- orange sample: duplicated pairs means you have a lot of PCR duplicates. That is a wet-lab issue.
- green sample: many same fragments and self-ligations, also an issue of the wet-lab.
- remapping: first investigate the FASTQ files with FASTQC, apply eventually trimming. Remap only if there is no major issue in the raw reads, please use bwa-mem for this, we have made the best experience with the parameter setting we provide in the mouse Hi-C tutorial on our readthedocs documentation.

Best,

Joachim

**Comment by joachimwolff** [comment]
No reply from user. Closing.
