### ISSUE TITLE
hicHyperoptDetectLoops adds chromosome prefix by default

### ISSUE THREAD

**Issue by dawe** [deeptools/HiCExplorer#723]
Hello all, 
I just found out that `hicHyperoptDetectLoops` internally adds the flag `-cl` to `hicValidateLocations`. While this is not necessarily a bug, if protein file has the same chromosome naming convention than loop file, the entire process won't work as there won't be any overlaps between the two files.

**Comment by joachimwolff** [comment]
Hi,

Thanks for reporting it, I will consider it in the next HiCExplorer release.

Best,

Joachim
