### ISSUE TITLE
Add ranksums statistics to hicDifferentialTAD output [feature request]

### ISSUE THREAD

**Issue by dawe** [deeptools/HiCExplorer#726]
Hi again, sorry for the many issues opened in few days.
I was wondering if it was possible to output the ranksums statistic to the output of `hicDifferentialTAD`, in addition to p-values, or at least the sign of the statistic. As the test is two-sided, it would be interesting to know if there is an enrichment or a depletion of contacts.
Of course, one can calculate enrichments/depletions on the matrices themselves but since the statistic are already calculated, it should be easy to output them.

I guess I can write a PR for this, though...

**Comment by joachimwolff** [comment]
Merged to develop branch.
