### ISSUE TITLE
Help interpreting insulation scores

### ISSUE THREAD

**Issue by dawe** [deeptools/HiCExplorer#730]
Hi, I have successfully identified TADs in some samples of mine. Now I'm interested in understanding the insulation score on specific regions. I'm attaching an image that results from `computeMatrix` + `plotProfile` on a set of regions over all samples, using the `bedgraph` files from `hicFindTADs`. It's nice because I can see an effect on a specific sample. As my regions have a strand definition, the profiles may be asymmetrical (which is the case here). My question is: how should I interpret the fact insulation scores upstream are positive and scores downstream are negative? 
After all, what a positive (negative) insulation score means?
Thanks

![prof](https://user-images.githubusercontent.com/121868/123801206-5a11e080-d8ea-11eb-847c-65afb7d4a03e.png)

**Comment by LeilyR** [comment]
The way hicexplorer compute insulation scores, the more negative your values are the stronger is your tad separation. Those samples with positive score on your regions of interest may have a complete TAD depletion. The green sample however has a strong insulation score on the center of the regions (could be tad boundary or very close to them) and this insulation score increased (got worse) as it got further from the center (got further from the tad boundaries)

**Comment by dawe** [comment]
Thanks @LeilyR for the tip. So, if I understand it correctly, TADs should be between subsequent minima in the TAD score profile. Indeed a profilePlot over defined TAD boundaries gives me nice "V-shaped" plots. 
Now, given that the middle of the plot above is actually in proximity of sample-specific TAD boundaries, should I conclude that, on average, the bins downstream are "well" separated from points upstream, whereas in the other samples all points within the 100kb window are "equally" connected with each other? Forgive the adverbs, I'm just trying to get a general idea

**Comment by LeilyR** [comment]
Tad boundaries are where the minima are.

That could indeed be an interpration. At least they are better separated in the green one than the others.
