### ISSUE TITLE
h5 to cool usage in cooltools

### ISSUE THREAD

**Issue by kimj50** [deeptools/HiCExplorer#734]
Hi,
First, thank you very much for the helpful tools.
I am currently using hicexplorer version 3.6
I did the following two things:
1. hic output from juicer -> convertformat to cool (correction_method KR) -> cooltools pileup
2. hic output from juicer -> convertformat to h5 (correction_method none) -> normalize smallest -> ICE -> h5 to cool -> cooltools pileup

In the second case, I get 'streaks' on the pileup plot, which seems to be bins that are removed due to threshold set during ICE normalization.
I was wondering if you guys had any suggestions I could try to deal with the 'streaks'
Thank you,
Jun

![image](https://user-images.githubusercontent.com/47995646/125141655-a5df3980-e0e3-11eb-87cb-4a467daa5efa.png)

**Comment by joachimwolff** [comment]
Please check if the stripes are also present in the original corrected data. ICE correction, as you already wrote, masks certain regions if a threshold is passed. However, in cool we simply set these regions to 0 before exporting it to cool. In this case, I can only recommend to either accepted the stripes, use our KR, or ask the developers of cooltools how they handle these 0 regions.

**Comment by kimj50** [comment]
Thank you for the reply
1. a few of the layers of the stack did have 0 in them, removing them from average removes stripes
2. replacing 0 elements in those stack with nan solved the stripes issue, and ICE and KR pileup plots ended up looking pretty much the same
