### ISSUE TITLE
self ligation

### ISSUE THREAD

**Issue by descostesn** [deeptools/HiCExplorer#738]
Hi,

I am using `hicBuildmatrix Galaxy Version 3.6+galaxy0` and got the following error when using the `remove self ligation option`:

```
hicBuildMatrix: error: argument --removeSelfLigation: expected one argument
```

A post is on the galaxy forum [here](https://help.galaxyproject.org/t/hicexplorer-reference-genome-and-hicbuildmatrix/6266) but so far no answer was given. 

Any idea?

Thx

**Comment by joachimwolff** [comment]
Hi,

Thanks for reporting this error. I noticed we have a small bug here, the value is always set to true at the moment, so it does not make a difference if you actively set it or not, it is always active. To bypass this error, just uncheck it and it should be fine. Only in the case you want to keep self ligations, you need to wait for the upcoming 3.7 release of HiCExplorer.

Best,

Joachim
