### ISSUE TITLE
How to exclude trans interaction from ICE correction

### ISSUE THREAD

**Issue by cgirardot** [deeptools/HiCExplorer#739]
Hi @joachimwolff 

this is more of a question/check: in `hicCorrectMatrix correct`, I'd like to make sure the trans reads are ignored. It seems I can do this by setting  `--transCutoff 1`. Did I get this correctly?

PS: the background is that I am trying to normalize & correct with cis interactions only. I got the normalization already (https://github.com/deeptools/HiCExplorer/issues/715)

**Comment by joachimwolff** [comment]
Hi @cgirardot,

With the 3.7 release you can remove the trans contacts with hicAdjustMatrix. 

The `--transCutoff` parameter computes the highest value in the x percentile and set all higher values to this maximum value. 
In your case it would be 1 / 100 --> 0.01
https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicCorrectMatrix.py#L685
Leading to the 99.9 percentile:

```
high=0.01
max_inter = np.percentile(mat.data[dist_list == -1], (100 - high)) 

```
https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/HiCMatrix.py#L914

Your thought could work, however, only if the close to 0 percentile gives you 0.0 as a result. But to make a long story short: It does work. We expect as input for the threshold a value between 0 and 100, and divide this value by 100. In the next step, we compute the percentile by subtraction from 100. In all cases, the percentile value is always 100 - (x / 100) therefore 99 < x < 100.

Best,

Joachim

**Comment by cgirardot** [comment]
Hi @joachimwolff 
thank you for the answer. I am not so familiar with python code. Just to double-check I got your answer correctly, the setting `--transCutoff 1` **will** result in ignoring most trans contacts during ICE? 
Thx again

**Comment by joachimwolff** [comment]
No, I wrote the exact opposite. `--transCutoff 1` will lead to setting all values greater the value for the 99.9 percentile to exactly this value.

**Comment by cgirardot** [comment]
Ah. So I should set `--transCutoff 99` to get all trans contacts set to a value close to 0 (the value will be that of the 1 percentile).  Correct ?

**Comment by joachimwolff** [comment]
No, because a value of 99 will be converted to `percentile = 100 - (99/100)` equals `100 - 0.99` equals the percentile of `99.01` and not of 1 percentile.

**Comment by cgirardot** [comment]
ah ok so I can't do it this way

**Comment by cgirardot** [comment]
ah but I did not release the 3.7 was already out. I am gonna play with the new `hicAdjustMatrix` then!

**Comment by joachimwolff** [comment]
You need to list the names of chromosomes that should be either kept or removed in general. The `interIntraHandling` parameter is independent of this. For example if you want to remove the inter data and keep the first four chromosomes it command is as follows:
`hicAdjustMatrix -a keep --interIntraHandling inter -m in.h5 -o out.h5 --chromosomes chr1 chr2 chr3 chr4`  To keep all chromosomes, you have to list them all.

**Comment by cgirardot** [comment]
ok great !
