### ISSUE TITLE
issue with hicCovertFormat

### ISSUE THREAD

**Issue by Lattesnow** [deeptools/HiCExplorer#743]
Hey, I am always getting this error but don't know what does it mean. I processed the hic from juicerbox with a .hic file as the output. I tried to convert .hic to cool file with specific resolution. And then I got this:
hicConvertFormat --matrices dmsodeephg38new.hic -o dmsodeephg38new.cool --inputFormat cool --outputFormat cool -r 50000
Traceback (most recent call last):
  File "/mnt/c/Conda/yes/envs/py38/bin/hicConvertFormat", line 7, in <module>
    main()
  File "/mnt/c/Conda/yes/envs/py38/lib/python3.8/site-packages/hicexplorer/hicConvertFormat.py", line 166, in main
    _matrix, cut_intervals, nan_bins, \
ValueError: not enough values to unpack (expected 5, got 2)

**Comment by joachimwolff** [comment]
Hi,

You need to define hic and not cool as the input format.

Best,

Joachim
