### ISSUE TITLE
hicConvertFormat hicpro usage question

### ISSUE THREAD

**Issue by erbon7** [deeptools/HiCExplorer#752]
hicInfo --version
hicInfo 3.6
 python --version
Python 3.8.8

Hi,

I have a question related to the conversion from hicpro format to h5. The documentation indicates that an additional bed file should be provided, but what is the content of this bed file ?

Thanks,

Eric

**Comment by JSegueni** [comment]
The content of the bed file is the additional file produced by Hi-C Pro. If I have a file called file.matrix, then the Hi-C Pro bed file will be file_abs.bed, containing the bin identifier for each bin of each chromosome in your triple sparse Hi-C Pro matrix.

**Comment by erbon7** [comment]
Ok I see.
Thx Julie
