### ISSUE TITLE
Conversion issue to mcool format

### ISSUE THREAD

**Issue by JSegueni** [deeptools/HiCExplorer#753]
Hi all, 

I need help on a current conversion issue with the HiCExplorer hicConvertFormat command. I'm using HiGlass to visualize my Hi-C matrices and thus require an mcool matrix from my HiC-Pro matrix. 

Thus, I run the following command:
hicConvertFormat --matrices MCF7_10000.matrix --outFileName MCF7_10000.mcool --inputFormat hicpro --bedFileHicpro MCF7_10000_abs.bed --resolutions 10000 --outputFormat mcool

I used to have an Input/Output error coming from the HDF5 file format, that occured when trying to convert my matrix in a network-mounted folder. Copying the matrix to /tmp and then converting works, as proposed here: https://github.com/h5py/h5py/issues/1610.

However, I still have an issue, even after resolving the Input/Output error. The mcool output matrix does not work with HiGlass. I'm having a blank output when trying to display it.

I tried the hicpro2higlass util from Hi-C Pro with the same matrix and I get an mcool matrix with a different size and a nice HiGlass display.

Now, I'd like to use the hicConvertFormat to convert my normalized matrix from cool to mcool format, with the following command:

hicConvertFormat --matrices MCF7_10000_norm.cool --outFileName MCF7_1000_norm.mcool --inputFormat cool --resolutions 10000 --outputFormat mcool

and also without the resolutions part:

hicConvertFormat --matrices MCF7_10000_norm.cool --outFileName MCF7_1000_norm.mcool --inputFormat cool --outputFormat mcool

However, I still get this empty HiGlass window when using the mcool matrix output from hicConvertFormat, even when using a cool matrix as input.

How to output a correct version from hicConvertFormat ?

Best wishes.

---------------------------------------------------------
Version info:
- HiCExplorer version 3.6
- Python version 3.8.10
- Using conda environment

**Comment by joachimwolff** [comment]
The nature of a *m*cool file is to have *m*ultiple resolutions. Try it with by defining multiple of the resolutions:
`hicConvertFormat --matrices MCF7_10000_norm.cool --outFileName MCF7_1000_norm.mcool --inputFormat cool --resolutions 10000 20000 50000 100000 300000 500000 1000000 --outputFormat mcool`

**Comment by JSegueni** [comment]
Thank you for your kind comment :)
Indeed, I should have provided more resolutions for my file to be visualized with HiGlass !
Thus, I'm closing this issue.
