### ISSUE TITLE
hicHyperOptDetectLoops 

### ISSUE THREAD

**Issue by mtegtmey** [deeptools/HiCExplorer#756]
Hello, whenever im running hicHyperOptDetectLoops, i am getting weird usage errors. But the errors for missing requirements dont show up if you just look at the usage. So it seems like there are different usages for the same program. any thoughts?

usage: hicHyperoptDetectLoops --matrix MATRIX --proteinFile PROTEINFILE --maximumNumberOfLoops MAXIMUMNUMBEROFLOOPS [--outputFileName OUTPUTFILENAME] [--resolution RESOLUTION] [--chrPrefixLoops {None,add,remove}]
                              [--threads THREADS] [--runs RUNS] [--help] [--version]
hicHyperoptDetectLoops: error: the following arguments are required: --maximumNumberOfLoops/-ml
(hicexplorer) mtegtmey@wm44b-287 KR_files % hicHyperoptDetectLoops --matrix control_day0_10kb_10000normKR.cool --proteinFile /Users/mtegtmey/Desktop/CTCF.bed --maximumNumberOfLoops 1000 --outputFileName control_d0_hyperopt_loops.txt --chrPrefixLoops 'remove' 
  0%|                                                                                                                                                                                      | 0/100 [00:00<?, ?trial/s, best loss=?]INFO:hyperopt.tpe:build_posterior_wrapper took 0.003025 seconds
INFO:hyperopt.tpe:TPE using 0 trials
INFO:hyperopt.tpe:build_posterior_wrapper took 0.002434 seconds
INFO:hyperopt.tpe:TPE using 1/1 trials with best loss 1.000000
INFO:hicexplorer.hicDetectLoops:Computed loops for Y: 0
INFO:hicexplorer.hicDetectLoops:Number of detected loops for all regions: 1569
usage: hicHyperoptDetectLoops --data DATA --validationData VALIDATIONDATA [--validationType {bed,cool}] [--method {loops,tad}] --resolution RESOLUTION [--outFileName OUTFILENAME] [--chrPrefixLoops {None,add,remove}]
                              [--chrPrefixProtein {None,add,remove}] [--help] [--version]

hicHyperoptDetectLoops: error: the following arguments are required: --validationData/-vd

  1%|█▋                                                                                                                                                                      | 1/100 [02:07<3:30:16, 127.44s/trial, best loss: 1.0]
(hicexplorer) mtegtmey@wm44b-287 KR_files %

**Comment by mtegtmey** [comment]
It seems like running hicHyperoptDetectLoops is also calling arguments for the hicValidateLocations function.

**Comment by gunnarschulze** [comment]
Same here ⬆️   Would be great to have a fix for this!

**Comment by joachimwolff** [comment]
I will have a closer look maybe next week, this week I am really busy with
other things. Sorry for the delay in resolving this. You can use the
HiCExplorer version 3.6 in the meantime as a workaround.

Gunnar Schulze ***@***.***> schrieb am Mo. 20. Sept. 2021 um
21:09:

> Same here ⬆️ Would be great to have a fix for this!
>
-- 
Joachim Wolff
M.Sc. Computer Science
Chair for Bioinformatics
Department of Computer Science
Albert-Ludwigs-University Freiburg
Georges-Koehler-Allee 079
D-79110 Freiburg

http://www.bioinf.uni-freiburg.de

**Comment by gunnarschulze** [comment]
Thanks! v3.6 works well, except for  issue #723, affecting the validation part in that version.
Removing the "-cl" flag in hicHyperoptDetectLoops.py (line 79) worked for me as a quickfix.

**Comment by joachimwolff** [comment]
It should be fixed; you can try the development branch, and please provide me short feedback if it works for you. Thanks.
