### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by blessyantony9** [deeptools/HiCExplorer#767]
Unable to install using conda
conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.8
hicexplorer=3.6 -> python[version='>=3.6']
hicexplorer=3.6 -> biopython[version='<1.77'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|<3.7|>=3.9,<3.10.0a0|>=3.10,<3.11.0a0|3.4.*|>=3|>=3.7.1,<3.8.0a0|>=2.7|>=3.5|2.7|>=3.5']

**Comment by blessyantony9** [comment]
Issue using pip as well
ERROR: Cannot install hicexplorer==1.7, hicexplorer==1.7.1, hicexplorer==1.7.2, hicexplorer==1.8, hicexplorer==1.8.1, hicexplorer==2.1.1, hicexplorer==2.2.1, hicexplorer==2.2.1.1 and hicexplorer==3.7.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    hicexplorer 3.7.2 depends on pysam>=0.16
    hicexplorer 2.2.1.1 depends on pyBigWig>=0.3.*
    hicexplorer 2.2.1 depends on pysam>=0.14
    hicexplorer 2.1.1 depends on matplotlib==2.1.*
    hicexplorer 1.8.1 depends on pysam>=0.11.2
    hicexplorer 1.8 depends on pysam>=0.11.2
    hicexplorer 1.7.2 depends on pyBigWig>=0.2.8
    hicexplorer 1.7.1 depends on pyBigWig>=0.2.8
    hicexplorer 1.7 depends on pyBigWig>=0.2.8

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by adRn-s** [comment]
Please try running first `conda install mamba`, and then replace conda with mamba on your command: `create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`. This should work because mamba has better dependencies' resolution.

**Comment by joachimwolff** [comment]
We checked it and can recommend mamba in case the conda solver needs too much time. Concerning pip: Please read our documentation, we have made it very clear we do not support pip since version 3.0 anymore!
