### ISSUE TITLE
installation through bioconda not working

### ISSUE THREAD

**Issue by NuriaDiaz** [deeptools/HiCExplorer#779]
Hi, I'm trying to install hicexplorer with bioconda "conda install -c bioconda hicexplorer" and it isn't working. I get the following issue:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / failed with initial frozen solve. Retrying with flexible solve.

Other conda packages can be installed without problem.

Thanks :)

**Comment by joachimwolff** [comment]
Please try mamba instead of conda:
`conda install mamba -c conda-forge`
`mamba install hicexplorer -c condo-forge -c bioconda`

**Comment by NuriaDiaz** [comment]
Also not working:

`(hic) diaz@uwe:/media/data/nuria/hic/bams$ conda install mamba -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/diaz/anaconda3/envs/hic

  added / updated specs:
    - mamba


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    charset-normalizer-2.0.12  |     pyhd8ed1ab_0          35 KB  conda-forge
    conda-4.11.0               |  py310hff52083_0        16.9 MB  conda-forge
    conda-package-handling-1.7.3|  py310h6acc77f_1         1.0 MB  conda-forge
    icu-69.1                   |       h9c3ff4c_0        13.2 MB  conda-forge
    libarchive-3.5.2           |       hccf745f_1         1.6 MB  conda-forge
    libmamba-0.21.2            |       h3985d26_0         1.5 MB  conda-forge
    libmambapy-0.21.2          |  py310h69d3e99_0         320 KB  conda-forge
    libsolv-0.7.19             |       h780b84a_5         445 KB  conda-forge
    libxml2-2.9.12             |       h885dcf4_1         760 KB  conda-forge
    mamba-0.21.2               |  py310hf87f941_0          42 KB  conda-forge
    pybind11-abi-4             |       hd8ed1ab_3          10 KB  conda-forge
    pycosat-0.6.3              |py310h6acc77f_1009         236 KB  conda-forge
    pyopenssl-22.0.0           |     pyhd8ed1ab_0          49 KB  conda-forge
    reproc-14.2.3              |       h7f98852_0          28 KB  conda-forge
    reproc-cpp-14.2.3          |       h9c3ff4c_0          20 KB  conda-forge
    ruamel_yaml-0.15.80        |py310h6acc77f_1006         724 KB  conda-forge
    setuptools-60.9.2          |  py310hff52083_0         1.2 MB  conda-forge
    tqdm-4.62.3                |     pyhd8ed1ab_0          80 KB  conda-forge
    yaml-cpp-0.6.3             |       he1b5a44_4         208 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        38.3 MB

The following NEW packages will be INSTALLED:

  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py310h6acc77f_1003
  certifi            conda-forge/linux-64::certifi-2021.10.8-py310hff52083_1
  cffi               conda-forge/linux-64::cffi-1.15.0-py310h0fdd8cc_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  conda              conda-forge/linux-64::conda-4.11.0-py310hff52083_0
  conda-package-han~ conda-forge/linux-64::conda-package-handling-1.7.3-py310h6acc77f_1
  cryptography       conda-forge/linux-64::cryptography-36.0.1-py310h685ca39_0
  icu                conda-forge/linux-64::icu-69.1-h9c3ff4c_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libarchive         conda-forge/linux-64::libarchive-3.5.2-hccf745f_1
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libmamba           conda-forge/linux-64::libmamba-0.21.2-h3985d26_0
  libmambapy         conda-forge/linux-64::libmambapy-0.21.2-py310h69d3e99_0
  libsolv            conda-forge/linux-64::libsolv-0.7.19-h780b84a_5
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libxml2            conda-forge/linux-64::libxml2-2.9.12-h885dcf4_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_1
  lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000
  mamba              conda-forge/linux-64::mamba-0.21.2-py310hf87f941_0
  pip                conda-forge/noarch::pip-22.0.3-pyhd8ed1ab_0
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
  pycosat            conda-forge/linux-64::pycosat-0.6.3-py310h6acc77f_1009
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py310hff52083_4
  python             conda-forge/linux-64::python-3.10.2-h62f1059_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  reproc             conda-forge/linux-64::reproc-14.2.3-h7f98852_0
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.3-h9c3ff4c_0
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  ruamel_yaml        conda-forge/linux-64::ruamel_yaml-0.15.80-py310h6acc77f_1006
  setuptools         conda-forge/linux-64::setuptools-60.9.2-py310hff52083_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sqlite             conda-forge/linux-64::sqlite-3.37.0-h9cd32fc_0
  tqdm               conda-forge/noarch::tqdm-4.62.3-pyhd8ed1ab_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  urllib3            conda-forge/noarch::urllib3-1.26.8-pyhd8ed1ab_1
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.6.3-he1b5a44_4
  zstd               conda-forge/linux-64::zstd-1.5.2-ha95c52a_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
libxml2-2.9.12       | 760 KB    | ################################################################################################################## | 100%
pybind11-abi-4       | 10 KB     | ################################################################################################################## | 100%
pycosat-0.6.3        | 236 KB    | ################################################################################################################## | 100%
setuptools-60.9.2    | 1.2 MB    | ################################################################################################################## | 100%
conda-4.11.0         | 16.9 MB   | ################################################################################################################## | 100%
yaml-cpp-0.6.3       | 208 KB    | ################################################################################################################## | 100%
conda-package-handli | 1.0 MB    | ################################################################################################################## | 100%
pyopenssl-22.0.0     | 49 KB     | ################################################################################################################## | 100%
charset-normalizer-2 | 35 KB     | ################################################################################################################## | 100%
libsolv-0.7.19       | 445 KB    | ################################################################################################################## | 100%
libmamba-0.21.2      | 1.5 MB    | ################################################################################################################## | 100%
tqdm-4.62.3          | 80 KB     | ################################################################################################################## | 100%
libmambapy-0.21.2    | 320 KB    | ################################################################################################################## | 100%
libarchive-3.5.2     | 1.6 MB    | ################################################################################################################## | 100%
ruamel_yaml-0.15.80  | 724 KB    | ################################################################################################################## | 100%
mamba-0.21.2         | 42 KB     | ################################################################################################################## | 100%
reproc-14.2.3        | 28 KB     | ################################################################################################################## | 100%
reproc-cpp-14.2.3    | 20 KB     | ################################################################################################################## | 100%
icu-69.1             | 13.2 MB   | ################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(hic) diaz@uwe:/media/data/nuria/hic/bams$ mamba install hicexplorer -c condo-forge -c bioconda

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.21.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['hicexplorer']

condo-forge/linux-64                                12.6kB @  25.3kB/s 404 failed  0.5s
r/linux-64                                         595.8kB @ 861.3kB/s  0.2s
[+] 1.1s
condo-forge/noarch   ━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  1.1s
bioconda/linux-64    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 427.8kB /  ??.?MB @ 401.7kB/s  1.1s
bioconda/noarch      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   2.1MB /  ??.?MB @   1.9MB/s  1.1s
conda-forge/linux-64 ━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   3.3MB /  ??.?MB @   3.1MB/s  1.1s
pkgs/main/linux-64   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   1.3MB /  ??.?MB @   1.3MB/s  0.4s
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/mamba.py", line 940, in exception_converter
        raise e
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/mamba.py", line 890, in _wrapped_main
        result = do_call(args, p)
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/mamba.py", line 752, in do_call
        exit_code = install(args, parser, "install")
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/mamba.py", line 496, in install
        index = load_channels(pool, channels, repos)
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/utils.py", line 122, in load_channels
        index = get_index(
      File "/home/diaz/anaconda3/envs/hic/lib/python3.10/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Multi-download failed.

`$ /home/diaz/anaconda3/envs/hic/bin/mamba install hicexplorer -c condo-forge -c bioconda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=hic
                CONDA_EXE=/home/diaz/anaconda3/bin/conda
             CONDA_PREFIX=/home/diaz/anaconda3/envs/hic
           CONDA_PREFIX_1=/home/diaz/anaconda3
    CONDA_PROMPT_MODIFIER=(hic)
         CONDA_PYTHON_EXE=/home/diaz/anaconda3/bin/python
               CONDA_ROOT=/home/diaz/anaconda3/envs/hic
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/diaz/bin:/home/diaz/anaconda3/envs/hic/bin:/home/diaz/anaconda3/
                          condabin:/home/diaz/bin:/home/diaz:/home/diaz/cellranger-
                          arc/cellranger-arc-2.0.0:/media/data/nuria/single_cell/cellranger-
                          4.0.0:/media/data/nuria/nanopore/ont-guppy-cpu/bin:/usr/local/sbin:/us
                          r/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:
                          /snap/bin:/home/diaz/anaconda3/envs/homer/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
         UBUNTU_MENUPROXY=<set>

     active environment : base
    active env location : /home/diaz/anaconda3/envs/hic
            shell level : 2
       user config file : /home/diaz/.condarc
 populated config files : /home/diaz/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.10.2.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.34=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/diaz/anaconda3/envs/hic  (writable)
      conda av data dir : /home/diaz/anaconda3/envs/hic/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/condo-forge/linux-64
                          https://conda.anaconda.org/condo-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
          package cache : /home/diaz/anaconda3/envs/hic/pkgs
                          /home/diaz/.conda/pkgs
       envs directories : /home/diaz/anaconda3/envs/hic/envs
                          /home/diaz/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.10.2 Linux/5.13.0-23-generic ubuntu/21.10 glibc/2.34
                UID:GID : 1003:1003
             netrc file : None
condo-forge/noarch                                  12.6kB @  11.3kB/s 404 failed  1.1s
(hic) diaz@uwe:/media/data/nuria/hic/bams$
`

**Comment by ebioman** [comment]
Hi little note here, you used 

> Please try mamba instead of conda: `conda install mamba -c conda-forge` `mamba install hicexplorer -c condo-forge -c bioconda`

Hi little note, it should be:

`mamba install hicexplorer -c conda-forge -c bioconda` not condo.
Mamba is not catching that...

**Comment by NuriaDiaz** [comment]
Thanks for the note!

**Comment by ratheraarif** [comment]
I got the following error while installing

```Looking for: ['hicexplorer']

bioconda/osx-arm64 (check zst)                      Checked  0.5s
bioconda/noarch (check zst)                         Checked  0.1s
pkgs/main/osx-arm64 (check zst)                    Checked  0.1s
pkgs/main/noarch (check zst)                       Checked  0.0s
pkgs/r/osx-arm64 (check zst)                        Checked  0.0s
pkgs/r/noarch (check zst)                          Checked  0.0s
bioconda/osx-arm64                                 354.0 B @   2.1kB/s  0.2s
pkgs/main/noarch                                   714.2kB @ 461.6kB/s  1.4s
conda-forge/osx-arm64                               10.2MB @   3.3MB/s  3.1s
pkgs/r/osx-arm64                                   108.0 B @  33.0 B/s  0.1s
pkgs/r/noarch                                        2.1MB @ 518.0kB/s  2.4s
pkgs/main/osx-arm64                                  2.5MB @ 596.0kB/s  4.1s
bioconda/noarch                                      5.3MB @   1.0MB/s  5.1s
conda-forge/noarch                                  15.0MB @   2.1MB/s  7.1s

Pinned packages:
  - python 3.11.*


Could not solve for environment specs
The following packages are incompatible
└─ hicexplorer is not installable because there are no viable options
   ├─ hicexplorer [2.2|2.2.1|2.2.2|2.2.3] would require
   │  └─ pybigwig, which does not exist (perhaps a missing channel);
   ├─ hicexplorer 3.0.1 would require
   │  └─ krbalancing >=0.0.4 , which does not exist (perhaps a missing channel);
   ├─ hicexplorer 3.0.2 would require
   │  └─ krbalancing 0.0.4 , which does not exist (perhaps a missing channel);
   ├─ hicexplorer [3.1|3.2|...|3.7.4] would require
   │  └─ krbalancing >=0.0.5 , which does not exist (perhaps a missing channel);
   └─ hicexplorer [3.5.2|3.5.3|...|3.7.2] would require
      └─ biopython <1.77 , which does not exist (perhaps a missing channel).
```

**Comment by joachimwolff** [comment]
Please do not post in long closed issues.

The issue you have is macOS specific, we do not support arm-64 platform so far. Therefore you have to install hicexplorer to a x86 environment and run it via Apple Rosetta 2. To do so, you have to define the x86 folder to enforce the architecture change:

`CONDA_SUBDIR=osx-64 conda create -n hicexplorer_x86_environment python=3.10 hicexplorer=3.7.3`
