### ISSUE TITLE
hicConvertFormat hicpro to h5, warning and job killed

### ISSUE THREAD

**Issue by MzwaneleN** [deeptools/HiCExplorer#786]
Hi. I am trying to convert hicpro to h5 format and I am getting a warning and my job is killed. Here's my command:
hicConvertFormat --matrices name_1_5000.matrix --bedFileHicpro name_1_5000_abs.bed --inputFormat hicpro --outputFormat h5 --outFileName name_1_5000.h5 --resolutions 5000

The output:
INFO:numexpr.utils:Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Killed

hicInfo 2.2.1.1
python 3.7

I used pip install

Thanks.

**Comment by MzwaneleN** [comment]
Needed to change mem-per-cpu

**Comment by Zheng19w** [comment]
> Needed to change mem-per-cpu
How to   change mem-per-cpu  

(Hic) [zheng1996@hlogin12 Hic]$ /public/home/aczhzv5pmn/software/Anaconda/anaconda3-3d/envs/hicexplore/bin/hicPlotMatrix --matrix /public/home/zheng1996/Hic/hicpro2cool/scrofa-Hi-C-muscle.10000.cool -t 100  --outFileName hicexplore_plot.png --log --dpi 300
INFO:numexpr.utils:Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Killed

**Comment by MzwaneleN** [comment]
I increased mem-per-cpu from 32G to 64G from an interactive job in our HPC.

**Comment by Zheng19w** [comment]
thanks



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/04/2022 22:11 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [deeptools/HiCExplorer] hicConvertFormat hicpro to h5, warning and job killed (Issue #786) |

I increased mem-per-cpu from 32G to 64G from an interactive job in our HPC.
