### ISSUE TITLE
cannot import name 'LearningWithNoisyLabels' from 'cleanlab.classification'

### ISSUE THREAD

**Issue by phil622** [deeptools/HiCExplorer#806]
I install the hicexplorer through command: conda install hicexplorer -c bioconda -c conda-forge
then i use hicDetectLoop and it said:
     ImportError: cannot import name 'LearningWithNoisyLabels' from 'cleanlab.classification'
What it is happen
Thanks

**Comment by matteozoia4** [comment]
How did you solve the issue?

**Comment by yoeHuuui** [comment]
The version of my `HiCExplorer is 3.7.2`.
In the `requirements.txt` file, we require `cleanlab >= 0.1.*`. 
I believe the issue might be related to the version of the cleanlab package. You can attempt resolving this by using `pip install cleanlab==1.0`.
