### ISSUE TITLE
resolution hicPlotTADs

### ISSUE THREAD

**Issue by MarineBergot** [deeptools/HiCExplorer#815]
Hi!

I'm still working with hicexplorer and i have questions about plot. I can't succeed to plot nice and clean plot. I don't know if it's because i didn't produce nice matrix or if i'm not using proper parameters for plot. 
 I first aligned my reads with bwa on hg38 and then created matrix for differents bins ("10000" "50000" "100000" "500000") and --inputBufferSize 400000

after i corrected and normalized matrix (with "smallest"). I then search TAD on raw matrix (maybe it's not the best? i think i read on your doc this is the best way)

to finish i used mergeDomains

i tried to plot TAD for each bins but it's really not so good.my best attempt was with 50000.
i used : 
[x-axis]
where = top

[hic matrix]
file = C1829A_LR51_50000_norm_correct.h5
title = 50kb
# depth is the maximum distance plotted in bp. In Hi-C tracks
# the height of the track is calculated based on the depth such
# that the matrix does not look deformed
depth = 1000000
transform = log1p
file_type = hic_matrix

[tads]
file = C1829A_LR51_TADs_50000_domains.bed
file_type = domains
border_color = black
color = none
# the tads are overlay over the hic-matrix
# the share-y options sets the y-axis to be shared
# between the Hi-C matrix and the TADs.
overlay_previous = share-y

and used this command : 
hicPlotTADs --tracks hic_track3.ini -o test3.png --region chr7:156500000-160000000

i'm using last version of HiCExplorer (3.7) , with python 3.9 on server and i installed it with conda.

thanks a lot for your help !
50kb

![graph_5kb](https://user-images.githubusercontent.com/99812432/185116108-8bc9dc44-8f8d-4c50-8a6d-89011e6815d6.png)

100kb
![test](https://user-images.githubusercontent.com/99812432/185116173-5fff5ba6-fe3f-45f0-aae4-861a7a310ab1.png)

10kb
![test3](https://user-images.githubusercontent.com/99812432/185116177-64bf583c-68b5-4f39-8081-ac956d4c871b.png)

**Comment by MarineBergot** [comment]
Hi,

Thanks a lot for your answer! Unfortunatly yes i need to work on this area because right here i have a genomic recombination for a foetus, then i tried to follow your recommandation. Here's my "best" try, the first one is my control and the second is the foetus with genomic recombination. I didn't have same quality for both but i hope it's still good? i used depth = 1000000 for both. I tried other for the first but it's not really better.
I'm stil not expert with HiC data, can we say that, for the 1st one we can see clearly two TAD? one big and one smaller on the right? 
and for the second one, the big one was splited into and neo TAD was created? 
do you think we could imprive this file? 
thanks a lot for all your advices,
Marine
![TAD_CTRL_agenesis](https://user-images.githubusercontent.com/99812432/185859869-eb3001b4-7ebe-4de4-8ae5-ade15b1dcfa6.png)

**Comment by lldelisle** [comment]
Hi,
I think it is better to compare both at the same resolution. Your second is indeed less good than the first one but I think it is sufficient to see what you want. I would compute the same resolution for the first one so you can better compare. It looks like you have a deletion and that the contacts between the 2 part of the initial TAD disappear. I guess it is because you have a rearrangement and both parts are stuck to another part of the genome. Yes the big TAD is split into 2 creating 2 'neo-TADs' but you cannot say the limit of the neo-TADs as they can be in other parts of the genome.

**Comment by MarineBergot** [comment]
Hi,
thanks again for your answer ! ok i will change resolution :)
last question, if i have 4 replicate for one sample, what is the best way to agregate them ? i'm not sure hicMergeMatrixBinsis made for that ? or maybe it's better during mapping?
thanks again !

**Comment by lldelisle** [comment]
If you already computed the matrices (before correction), use [hicSumMatrices](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicSumMatrices.html) does it.
Else, you can merge all read1 bam files and all read2 bam files with [samtools merge](http://www.htslib.org/doc/samtools-merge.html)
And then compute matrices on the 2 merged bam.

**Comment by lldelisle** [comment]
Also what you can do to highlight the difference between your 2 matrices (control and rearranged) is to do a [hicCompareMatrices](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicCompareMatrices.html), I personally prefer the difference over the log2ratio. This should highlight that you loose contacts in the diamond above the deleted part where you have the rearrangment.

**Comment by MarineBergot** [comment]
thanks a lot for all your answers and advices it really helps me ! i will re run everything and try again with hicCompareMatrices
by any chance, do you know if it's possible to change the color of vlines? i saw it's possible for hlines, i tried to just set color = red in the paragraph but nothing changed, maybe it's not possible? thanks!

**Comment by lldelisle** [comment]
For the moment it is not possible, I can write a PR for that but this will wait for the next release.

**Comment by lldelisle** [comment]
I need more details ?
Error or you can't open it?

**Comment by MarineBergot** [comment]
no more like it looks like nothing ^^' 
i tried with : hicPlotTADs --tracks hic_track_all.ini -o TAD_CTRL_agenesis_fullchr7.svg --region chr7:0-158000000
the file .ini is the same 
![TAD_CTRL_agenesis_fullchr7](https://user-images.githubusercontent.com/99812432/185915477-809faac4-f3ab-433c-845d-cfc76d027eb5.svg)

**Comment by lldelisle** [comment]
I am not sure adding the vlines for each gene when you plot a whole chromosome is a good idea. You may also be interested in removing the labels for the genes at this scale.

**Comment by lldelisle** [comment]
Also you may be interested in increasing the depth of Hi-C. They look pretty small.

**Comment by lldelisle** [comment]
More parameters for vlines has been implemented in the last release of pyGenomeTracks which will be available on conda later today.
