### ISSUE TITLE
Plotting the TADs identified using TADCompare()

### ISSUE THREAD

**Issue by MurliNair** [deeptools/HiCExplorer#822]
Hi, 
I have analyzed my hi-c data using TADCompare(), it outputs a data frame with the following data

Boundary | Gap_Score |    TAD_Score1 | TAD_Score2 |    Differential |     Enriched_In | Type |  
3120000 | 0.987022471 | 6.217431419 | 5.840847457 | Non-Differential | Matrix 1 | Non-Differential
3130000 | 3.904120674 | 2.522456055 | 0.833019186 | Differential | Matrix 1 | Split |  
3200000 | -0.518321694 | 8.184606448 | 8.486056395 | Non-Differential | Matrix 2 | Non-Differential
3320000 | 1.922541055 | 1.959640889 | 1.134194198 | Non-Differential | Matrix 1 | Non-Differential
3330000 | 1.170574468 | 2.162714169 | 1.668906387 | Non-Differential | Matrix 1 | Non-Differential
3450000 | -0.164373857 | 1.852791729 | 1.941662888 | Non-Differential | Matrix 2 | Non-Differential
3460000 | -0.835761886 | 2.978231904 | 3.371754879 | Non-Differential | Matrix 2 | Non-Differential
3470000 | -0.422854833 | 2.254624827 | 2.460500511 | Non-Differential | Matrix 2 | Non-Differential
3620000 | 2.361046478 | 2.066327001 | 1.049525451 | Differential | Matrix 1 | Split |  

I am trying to use this to plot the TADs. Using the above data in the [tads] section of the ini file. Is there a way I can do this?  Trying to create a figure like figure 5 in reference for TADCompare. https://www.frontiersin.org/articles/10.3389/fgene.2020.00158/full  

I am using hicInfo 3.7.2 and my python version is 3.10.6

Thanks for your input. 
Cheers../Murli

**Comment by lldelisle** [comment]
This has been answered in https://github.com/deeptools/pyGenomeTracks/issues/420
