### ISSUE TITLE
hicAggregateContacts: FileContactPairs uncomplete

### ISSUE THREAD

**Issue by Lucas446** [deeptools/HiCExplorer#826]
Hi, 

I give as input to hicAggregateContacts function a .bed file containing 388 regions.

When looking at the output file generated  by "--outFileContactPairs" option I only find 26 regions being tested. 

Do you know why 108 regions has been filtered out ? (I can see that some pairs have 0 contacts, so it is not filtering out the regio that doesn't interact)

Thanks for your help, 
Best, 
Tanguy

**Comment by ralfgilsbach** [comment]
Hi,
was the bed file sorted? It has to be sorted by chromosome. Otherwise regions are skipped.
Best

Ralf
