### ISSUE TITLE
Abound hicexplorer tools

### ISSUE THREAD

**Issue by GleeenSIBS** [deeptools/HiCExplorer#857]
I can not use any command of hicexplorer. It always gave the following text:
Illegal instruction (core dumped)

hicxplorer version is 3.7.2
python version is 3.8.15

I tried to reinstall hicexplorer. but I failed. So, I want to know how to solve this problem. Thanks!

**Comment by bgruening** [comment]
Can you try the version 3.7.3. If this does not work, please reopen the issue and let us know how you installed the package.
