### ISSUE TITLE
hicPCA error

### ISSUE THREAD

**Issue by MurliNair** [deeptools/HiCExplorer#858]
Hi,
Thanks for developing HicExplorer and making it available to all. 
I am using 
hicInfo 3.7.2  and Python 3.10.6
I am following your protocol to analyze my HiCdata. 
Aligned using BWA and then created the matrix. Reviewed the plot before correcting the matrix. Plot is attached. 
![CON_corrected](https://github.com/deeptools/HiCExplorer/assets/12362166/28ade786-490a-4e73-9283-b6ac4a5ce2f5)
I used the following to correct the matrix 
hicCorrectMatrix correct -m CON.h5 --filterThreshold -1 4 -o CON_correctedMinu1And4.h5

I want to make sure that the threshold I have used is correct. 

When I run hicPCA 
hicPCA -m ../../hicBuildMatrix/CON/hiCmat1/CON_correctedMinu1And4.h5 \
	--method lieberman \
	--outputFileName CON_Minu1And4_pca1.bedgraph CON_Minu1And4_pca2.bedgraph CON_Minu1And4_pca3.bedgraph \
	--format bedgraph

I get the following error
Traceback (most recent call last):
  File "/work/mnair/anaconda3/envs/hiC/bin/hicPCA", line 7, in <module>
    main()
  File "/work/mnair/anaconda3/envs/hiC/lib/python3.10/site-packages/hicexplorer/hicPCA.py", line 318, in main
    eigenvectors_correlate = np.hstack((eigenvectors_correlate, eigs[:, int(id) - 1:int(id)]))
ValueError: invalid literal for int() with base 10: ' '

I have tried this several times and even changed the method and I keep getting the same error. 

Thanks and look forward to your comments. 

Cheers../Murli

**Comment by GiorgiaGiacomini** [comment]
I have the same issue. Did you solve it?

**Comment by MurliNair** [comment]
No I have not solved it yet.  If I find a solution I shall post it here.

**Comment by DavidWarrenKatz** [comment]
Can someone please link to where the actual code for hicPCA is? I am having trouble finding it. Also, the Pearson matrix will have many NaNs. What is done about those before eigenvalues are computed?

**Comment by LHXqwq** [comment]
hicPCA -m BBL-1.h5 --outputFileName BBL-1-pca1.bw BBL-1-pca2.bw --format bigwig --whichEigenvectors 1 2
This line of code can run smoothly.

**Comment by thomasmanke** [comment]
Indeed. The number of --outputFileName has to match the number specified in --whichEigenvectors (or -we).
