### ISSUE TITLE
'Styler' object has no attribute 'render'

### ISSUE THREAD

**Issue by pillailab** [deeptools/HiCExplorer#862]
Hello,
I am trying to run HicBuildMatrix on a conda install. 
Conda environent was installed was per version specifications given.
Thank you,
Manoj

The command is
module load miniconda
conda activate hicexplorer
cut=/home/mp758/project/Genomes/HiCExplorer/Mouse/GRCm38/GRCm38.MboI_positions.bed

FILE=/home/mp758/palmer_scratch/2023/July_2023/Hi-C/MPG25*
for f in $FILE
do
        cd $f
        v=$(basename "$f")
        bam1="$v"_1.bam
        bam2="$v"_2.bam
        mkdir hicMatrix
        hicBuildMatrix --samFiles $bam1 $bam2 --binSize 10000 --restrictionSequence GATC --danglingSequence GATC --restrictionCutFile $cut --outBam "$v"_ref.bam --outFileName hicMatrix/"$v"_10kb.h5 --QCfolder hicMatrix/"$v"_10kb_QC --threads 8 --inputBufferSize 400000

done

I am getting the following error:

INFO:hicexplorer.hicBuildMatrix:reading MPG254_1.bam and MPG254_2.bam to build hic_matrix

[E::idx_find_and_load] Could not retrieve index file for 'MPG254_1.bam'
[E::idx_find_and_load] Could not retrieve index file for 'MPG254_2.bam'
INFO:hicexplorer.hicBuildMatrix:dangling sequences to check are {'GATC': {'pat_forw': 'GATC', 'pat_rev': 'GATC'}}

INFO:hicexplorer.hicBuildMatrix:processing 16080403 lines took 80.44 secs (199895.5 lines per second)

INFO:hicexplorer.hicBuildMatrix:61991 (0.39%) valid pairs added to matrix

Traceback (most recent call last):
  File "/gpfs/gibbs/project/pillai/mp758/conda_envs/hicexplorer/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/gpfs/gibbs/project/pillai/mp758/conda_envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicBuildMatrix.py", line 1573, in main
    QC.main("-l {} -o {}".format(log_file_name, args.QCfolder).split())
  File "/gpfs/gibbs/project/pillai/mp758/conda_envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicPrepareQCreport.py", line 321, in main
    save_html(args.outputFolder + "/hicQC.html", unmap_table, discarded_table, distance_table,
  File "/gpfs/gibbs/project/pillai/mp758/conda_envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicPrepareQCreport.py", line 65, in save_html
    html_content = html_content.replace("%%TABLE_UNMAP%%", unmap_table.style
AttributeError: 'Styler' object has no attribute 'render'

**Comment by Ssmile333** [comment]
Hello, I am getting the same error, has the above problem been solved?

**Comment by lyy005** [comment]
I downgraded pandas version from 2.0.3 to 1.5.3. And it works now

**Comment by juliadouglasf** [comment]
Upgrading to version 3.7.3, which includes the mentioned commit, worked for me.
