### ISSUE TITLE
AttributeError: module 'cooler' has no attribute 'io'

### ISSUE THREAD

**Issue by vakh57** [deeptools/HiCExplorer#871]
**Welcome to the HiCExplorer GitHub repository! Before opening the issue please check
 that the following requirements are met :**

- [x] Search whether this issue (or a similar issue) has been solved before using the search tab above. Link the previous issue if appropriate below.

- [x] Paste your HiCExplorer version (`hicInfo --version`) and your python version (`python --version`) below. 
- [x] Have you checked our documentation on [hicexplorer.readthedocs.io](https://hicexplorer.readthedocs.io)?
- [x] Do you use [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) to install HiCExplorer? 
- [x] Do you use the latest HiCExplorer release? If not, please install it via a conda environment: 
       `conda create --name hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge`
       and activate the environment: `conda activate hicexplorer`.  Retry your command. You can exit a conda environment via `conda deactivate`. To learn more about conda and environments, please consider the following [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#).

Retry your command, is it solved now? If not please continue with the following:
- [x] Paste the full HiCExplorer command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

- [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

**Comment by vakh57** [comment]
Dear HiCExplorer team,

I have tried to install hicexplorer through conda on a linux-based cluster, the installation seems to have completed successfully, however when I try to run the hicInfo utility to obtain information on a cool file, I get the following error:

hicInfo -m my_matrix.mcool::/resolutions/10000
Traceback (most recent call last):
  File "/home/usr/miniforge-pypy3/envs/hicexplorer/bin/hicInfo", line 7, in <module>
    main()
  File "/home/usr/miniforge-pypy3/envs/hicexplorer/lib/python3.8/site-packages/hicexplorer/hicInfo.py", line 76, in main
    if check_cooler(matrix) and args.no_metadata:
  File "/home/usr/miniforge-pypy3/envs/hicexplorer/lib/python3.8/site-packages/hicmatrix/HiCMatrix.py", line 1034, in check_cooler
    if cooler.io.is_cooler(pFileName):
AttributeError: module 'cooler' has no attribute 'io'

I’ve tried installing hicexplorer (version 3.6) in a separate environment using both miniconda and mamba, however the error persists irrespective of how hicexplorer was installed.
I would be very grateful if you could suggest how to fix this error.

**Comment by joachimwolff** [comment]
I published today a maintenance update version 3.7.3 which should fix this issue.

**Comment by vakh57** [comment]
Dear Joachim,

Thanks a lot for the hicexplorer update and for getting back to me!
I’ve reinstalled hicexplorer through conda, and the hicInfo utility is now working properly.

I’m very grateful for your help with this issue!
