### ISSUE TITLE
HiCExplorer 3.5.2

### ISSUE THREAD

**Issue by robin-sto** [deeptools/HiCExplorer#884]
Hello,

Where can I get hiCExplorer version 3.5.2?

Thank you.

**Comment by joachimwolff** [comment]
Please use the requirements.txt file of the release (https://github.com/deeptools/HiCExplorer/blob/3.5.2/requirements.txt), and change first all dependencies from a `>=` to `=`. Next, install the dependencies in their own environment via `conda create -n hicexplorer3.5.2 --file requirements.txt hicexplorer=3.5.2`. Last, activate the environment `conda activate hicexplorer3.5.2`. The step to fixate the dependency version is necessary after three years to get the versions of this time and not newer ones with maybe changed APIs.

Alternatively, you can get the release here: https://github.com/deeptools/HiCExplorer/releases/tag/3.5.2
or https://github.com/deeptools/HiCExplorer/tree/3.5.2.

**Comment by robin-sto** [comment]
Thank you.
