### ISSUE TITLE
problem with chicViewpoint

### ISSUE THREAD

**Issue by robin-sto** [deeptools/HiCExplorer#887]
Hello,

In both HiCExplorer versions 3.7.2 and 3.5.2, chicViewpoint and chicViewpointBackgroundModel are throwing errors:

ERROR:hicexplorer.chicViewpoint:module 'numpy' has no attribute 'int'.

I have removed all the references to np.int that I can find but this error keeps appearing.  Do you know which py file needs to be modified?  

For 3.7.2. env:  
numpy                     1.26.2  
python                    3.9.18 

3.5.2:
numpy                     1.24.4
python                    3.8.15

Thanks

**Comment by joachimwolff** [comment]
The HiCExplorer version you use is outdated. Please use the current version 3.7.3.
