### ISSUE TITLE
Fastq polishing

### ISSUE THREAD

**Issue by DakeshiKitano** [deeptools/HiCExplorer#909]
Dear developers,

I am glad and thankful for your tool for Hi-C Data Analysis! I have a question regarding the beginning of the analyses.

Do I need to process my .fastq files to remove the reads of low quality (low q30), or to remove duplicates? Or can I align with .fa genome file (e.g. mm39.fa) straightforward to generate .bam file with "samtools"?

hicexplorer 3.7.2, Python 3.10.13, conda 4.12.0

**Comment by joachimwolff** [comment]
Low quality will be filtered out in the build process of the interaction matrix, parameter minMappingQuality is used to set the level.
